Feature/nex 519/add transactional
oat-sa/tao-core pull request #2323
Opened 2019-11-12 11:19 UTC by julien-sebire

TaskQueue brokers cleanup:
- removed useless transaction handling for single persistence query
- added exception message
- removed dead code

This is required by https://github.com/oat-sa/extension-tao-task-queue/pull/104

2019-11-18 09:00 UTC, mike-ionut-mihai-sandu-tao requested changes
please check the failing tests

2019-11-19 15:36 UTC, julien-sebire reviewed
ANswered your questions...

2019-11-19 15:36 UTC, julien-sebire commented on models/classes/taskQueue/TaskLog/Broker/RdsTaskLogBroker.php
> +use Google\Cloud\Spanner\Transaction;
As stated yesterday evening, we need a level of abstraction to be able to merge back to develop, but for the Spanner braznch, we can afford to keep it this way. The abstraction would just use a Google\Cloud\Spanner\Transaction for Spanner and a Doctrine\Dbal\Connection for other Rds, proxying the few methods we need (execute and commit).

2019-11-19 15:36 UTC, julien-sebire commented on models/classes/taskQueue/TaskLog/Broker/RdsTaskLogBroker.php
> +        $qb = $this->getQueryBuilder()
For the sake of clarity on what can actually throw an exception.

2019-11-19 15:36 UTC, julien-sebire commented on models/classes/taskQueue/TaskLog/Broker/RdsTaskLogBroker.php
> +        $qb = $this->getQueryBuilder()
Why would we? The idea is to limit the number of statements that can produce an exception. Exception have to be treated as a method to deal with things not going the supposed way, not a way to deal with a second king of result type.

2020-03-05 15:17 UTC, closed without merging