Fix/tao 9550/added not disabled
oat-sa/tao-core pull request #2326
Opened 2019-11-14 09:31 UTC by tikhanovichA

Depends on https://oat-sa.atlassian.net/browse/TAO-9550

For parsing elements from sub-classes in tree we need to the new callback for onopen event

2019-11-14 13:55 UTC, AndreyNegrov approved these changes

2019-11-15 09:37 UTC, ricproenca-tao requested changes
Need to bump version again...

2019-11-15 11:02 UTC, tikhanovichA commented
> Need to bump version again...

Done

2019-11-21 09:06 UTC, ricproenca-tao approved these changes

2019-11-21 09:13 UTC, merged