Feature/nex 780/env processor
oat-sa/tao-core pull request #2432
Opened 2020-03-12 09:53 UTC by boajer

2020-03-12 10:28 UTC, bartlomiejmarszal requested changes
Obvious missing tests. 
I also do not understand why you using this trick with ReflectionClass
getEnv is definitely too long. It should use additional validation methods and helpers.

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/EnvVarProcessor.php
> +    public function getEnv($prefix, $name, \Closure $getEnv)
It's difficult ti understand this method without unit tests

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/EnvVarProcessor.php
> +    public function getEnv($prefix, $name, \Closure $getEnv)
```suggestion
    public function getEnv($prefix, $name, Closure $getEnv)
```

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/EnvVarProcessor.php
> +            $array = $getEnv($next);
```suggestion
            $envVariables = $getEnv($next);
```

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/EnvVarProcessor.php
> +                    sprintf('Resolved value of "%s" did not result in an array value.', $next)
```suggestion
                    sprintf('Value of "%s" should be an array.', $next)
```

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/EnvVarProcessor.php
> +            if (!isset($array[$key]) && !\array_key_exists($key, $array)) {
Can we maybe move those methods to some kind of validator?

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/EnvVarProcessor.php
> +                $env = $getEnv($next);
try block should have only one line. Is it possible here?

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/EnvVarProcessor.php
> +                // no-op
What is no op?

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/EnvVarProcessor.php
> +        throw new RuntimeException(sprintf('Unsupported env var prefix "%s".', $prefix));
is this still `getEnv` method? Whoa!

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/EnvVarProcessorInterface.php
> +}
```suggestion
}

```

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/ParameterBug.php
> +    protected $parameters = [];
Missing phpdocs

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/ParameterBug.php
> +    private $getEnv;
Missing phpdocs

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/ParameterBug.php
> +    private $resolving;
Missing phpdocs

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/ParameterBug.php
> +    private $processor;
Missing phpdocs

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/ParameterBug.php
> +     * @param $name
can we type-hint it?

2020-03-12 10:28 UTC, bartlomiejmarszal commented on models/classes/envProcessor/ParameterBug.php
> +class ParameterBag
I think we shouldn't be so obvious when creating bugs in the code... (this is related to file name)

2020-03-12 10:31 UTC, boajer commented on models/classes/envProcessor/ParameterBug.php
> +class ParameterBag
Nice catch!

2020-03-12 12:52 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/envProcessor/EnvVarProcessor.php
> + */
i think the suggestion to run `phpcs --standard=PSR12 . ` on this development could be more suggestive instead of this type of comments , so let's provide as much as possible information to be able to learn from each other
;)

2020-03-12 12:54 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/envProcessor/EnvVarProcessor.php
> +                $env = $getEnv($next);
may i ask you to specify the rule about 1 line Try catch block (i do not know this rule :( )
is it part of PSR12?

2020-03-12 13:02 UTC, boajer commented on models/classes/envProcessor/EnvVarProcessor.php
> + */
I've run `phpcbf --standard=PSR-12 ` against new code directly and have no clue why phpstorm missed that.

2020-03-12 14:46 UTC, boajer commented
@bartlomiejmarszal I would prefer not to go too far away from the original symfony behavior, as believe at some moment we may reuse this classes venodorized ( that is impossible yet, as they are part of heavy DI component )

2020-03-13 08:28 UTC, mike-ionut-mihai-sandu-tao approved these changes
nice job

2020-03-13 08:29 UTC, mike-ionut-mihai-sandu-tao commented
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-03-13 09:11 UTC, bartlomiejmarszal commented on models/classes/envProcessor/EnvVarProcessor.php
> +                $env = $getEnv($next);
I meant that try block should be as short as possible and also it should contain only critical calls that can throw exceptions. Because of that, I would move those `if` statements outside of this block This is mostly good practise improving the readability of code.

2020-03-13 09:24 UTC, peetya requested changes

2020-03-13 09:24 UTC, peetya commented on models/classes/envProcessor/EnvVarProcessorInterface.php
> + * For the full copyright and license information, please view the LICENSE
Symfony is referencing to its own LICENSE file. Also I'm not sure we can copy-paste their logic from `symfony/symfony` under MIT license.

2020-03-13 09:31 UTC, boajer commented on models/classes/envProcessor/EnvVarProcessorInterface.php
> + * For the full copyright and license information, please view the LICENSE
They are using https://symfony.com/doc/current/contributing/code/license.html if it trustable, but yes, we need be careful.

2020-03-16 08:36 UTC, bartlomiejmarszal reviewed
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-03-16 08:36 UTC, bartlomiejmarszal commented on test/Asset/return_foo_string.php
> +<?php
What is this file for?

2020-03-17 08:55 UTC, closed without merging