Statement migration cli script and tasks added
oat-sa/tao-core pull request #2599
Opened 2020-07-15 12:59 UTC by boajer

https://oat-sa.atlassian.net/browse/NEX-1135

2020-07-16 07:15 UTC, gabrielfs7 commented on models/classes/task/helper/PositionTracker.php
> +    protected function getStorage(): common_persistence_KeyValuePersistence
```suggestion
    private function getStorage(): common_persistence_KeyValuePersistence
```

2020-07-16 07:15 UTC, gabrielfs7 commented on models/classes/task/helper/PositionTracker.php
> +    protected function getStorage(): common_persistence_KeyValuePersistence
Can you please keep public methods first?

2020-07-16 07:16 UTC, gabrielfs7 commented on models/classes/task/helper/StatementLastIdRetriever.php
> +
```suggestion
```

2020-07-16 07:16 UTC, gabrielfs7 commented on models/classes/task/helper/StatementLastIdRetriever.php
> +        return (int)$results;
```suggestion
        return (int)$query->execute()->fetchColumn();
```

2020-07-16 07:17 UTC, gabrielfs7 commented on models/classes/task/AbstractStatementMigrationTask.php
> +    protected $anomalies;
```suggestion
    private $affected;

    /** @var int */
    private $pickSize;

    /** @var common_report_Report */
    private $anomalies;
```

2020-07-16 07:20 UTC, gabrielfs7 commented on models/classes/task/helper/TaskIterator.php
> +class TaskIterator extends ConfigurableService
```suggestion
class StatementTaskIterator extends ConfigurableService
```

I know I put this name `TaskIterator` as example, but I agreed with you to use the statement as part of class name in this case.

2020-07-16 07:20 UTC, siwane requested changes
As it is for a core function, can I suggest you to add unit test
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-07-16 07:20 UTC, siwane commented on models/classes/task/AbstractStatementMigrationTask.php
> +        $queueDispatcher = $this->getServiceLocator()->get(QueueDispatcherInterface::SERVICE_ID);
I think, we should separate the task from the task factory

2020-07-16 07:20 UTC, siwane commented on models/classes/task/AbstractStatementMigrationTask.php
> +            $this->processUnit($unit);
Do you enivsage to add a success report foreach successfully processsed lines, or it is too verbose

2020-07-16 07:20 UTC, siwane commented on models/classes/task/helper/StatementLastIdRetriever.php
> +
Extra blank line

2020-07-16 07:20 UTC, siwane commented on models/classes/task/helper/StatementLastIdRetriever.php
> +            ->select('MAX(id)')
Be aware that spanner has alpha numeric format, and this part will require a new sql implementation

2020-07-16 07:20 UTC, siwane commented on models/classes/task/helper/TaskIterator.php
> +class TaskIterator extends ConfigurableService
I think this iterator should belongs to taskQueue domain

2020-07-16 07:20 UTC, siwane commented on scripts/tools/StatementsMigrationWrapper.php
> +                    '1. Please restart fpm to apply changes ' . PHP_EOL .
👍

2020-07-16 07:20 UTC, siwane commented on scripts/tools/StatementsMigrationWrapper.php
> +    private function spawnTask(
seems duplicate of https://github.com/oat-sa/tao-core/pull/2599/files#diff-d70c70a2a08dd00c95ef278c0b2e2e4fR127

2020-07-16 07:20 UTC, siwane commented on scripts/tools/StatementsMigrationWrapper.php
> +                    '1. Please restart fpm to apply changes ' . PHP_EOL .
I think we should distinguish action for queue management and enqueuing task, wdyt?

2020-07-16 07:20 UTC, siwane commented on scripts/tools/StatementsMigrationWrapper.php
> +    protected function returnJson($data, $httpStatus = 200)
Is it required?

2020-07-16 07:20 UTC, siwane commented on models/classes/task/helper/PositionTracker.php
> +        $persistence->set($id . self::CACHE_KEY, $position);
Seems dangerous to rely on cache, because cache can be deleted at any time

2020-07-16 07:24 UTC, gabrielfs7 commented on models/classes/task/helper/PositionTracker.php
> +namespace oat\tao\model\task\helper;
This means other classes do not help? :p

2020-07-16 07:26 UTC, boajer commented on models/classes/task/helper/PositionTracker.php
> +        $persistence->set($id . self::CACHE_KEY, $position);
That is not a cache but key value storage, the name of constant is misleading indeed. Would renaming help?

2020-07-16 07:28 UTC, boajer commented on scripts/tools/StatementsMigrationWrapper.php
> +    protected function returnJson($data, $httpStatus = 200)
Kinda, that comes as an abstract from `\oat\tao\model\taskQueue\TaskLogActionTrait::returnJson`

2020-07-16 07:49 UTC, gabrielfs7 commented on models/classes/task/helper/StatementLastIdRetriever.php
> +            ->select('MAX(id)')
I think Spanner is not covered here, right @boajer? So this class should probably implement an interface allowing switch clients to use Spanner implementation (when we will have it).

2020-07-16 07:54 UTC, gabrielfs7 commented on models/classes/task/helper/PositionTracker.php
> +namespace oat\tao\model\task\helper;
To elaborate a bit more. Every class has a responsibility and to segregate them we have plenty of design patterns. If you have a class with shared behavior, most probably you can fit it in an specific group (Service, Factory, Adapter, Strategy, Specification, etc) and in specific namespace. 

When we use `Helper` means we do not know how to call it, so probably a sign of bad domain. 

We could add this as a service to an specific namespace: `oat\tao\model\task\migration\service\PositionTracker`.

I would recommend to migrate new classes to this namespace too: `oat\tao\model\task\migration`

2020-07-16 08:00 UTC, gabrielfs7 commented on scripts/tools/StatementsMigrationWrapper.php
> +    private function spawnTask(
Yes, I would create a factory if possible.

2020-07-16 08:54 UTC, gabrielfs7 commented on models/classes/task/AbstractStatementMigrationTask.php
> +        $slideToTheStatementsEnd = (bool)array_shift($params);
We need to use proper array index to get param, cause if params size or order changes it will break.

- [ ] Use safer way to get params than `array_shift`

2020-07-16 08:58 UTC, gabrielfs7 commented on models/classes/task/AbstractStatementMigrationTask.php
> +        iterator_apply($iterator, [$this, 'applyProcessor'], [$iterator, $pickSize, $this->affected]);
```suggestion
        iterator_apply($iterator, [$this, 'applyProcessor'], [$iterator]);
```

`applyProcessor` is only using one parameter. Can the others be removed?

2020-07-16 09:03 UTC, gabrielfs7 commented on scripts/tools/StatementsMigrationWrapper.php
> +                    '2. Execute `php index.php "oat\taoTaskQueue\scripts\tools\RunWorker" --queue=%s`' . PHP_EOL .
```suggestion
                    '2. Execute `php index.php "' . RunWorker::class . '" --queue=%s`' . PHP_EOL .
```

So if class changes you can track usages here.

2020-07-16 09:38 UTC, boajer commented on models/classes/task/AbstractStatementMigrationTask.php
> +            $this->processUnit($unit);
Too verbose as for me

2020-07-16 09:42 UTC, boajer commented on models/classes/task/AbstractStatementMigrationTask.php
> +        $slideToTheStatementsEnd = (bool)array_shift($params);
What are you proposing? This is following existing practice for such scripts/Tasks inspired by interface signature.
This script also not intended (but still can be called) manually and have own wrapper with user friendly arguments checks/helps/casing etc

2020-07-16 10:19 UTC, boajer commented on models/classes/task/AbstractStatementMigrationTask.php
> +            $this->processUnit($unit);
And I can swap lines  `$this->processUnit($unit);` with `$this->logDebug(***)` so that would mean all entries in log has been successfully passed 😂

2020-07-16 10:27 UTC, boajer commented on scripts/tools/StatementsMigrationWrapper.php
> +                    '1. Please restart fpm to apply changes ' . PHP_EOL .
Yep, and then changes should go into `taoTaskQueue` extension directly to make it as generic as possible; WDYT ? Looks like  we are touching more and more components

2020-08-04 11:42 UTC, gabrielfs7 commented on models/classes/migrations/MigrationsService.php
> +         */
The other comment way is preferable IMO. This kind of multiline references too method, class description and kind of confuse eyes when reading the code.

2020-08-04 11:45 UTC, gabrielfs7 commented on models/classes/task/migration/MigrationConfig.php
> +
```suggestion
```
According to our CR standards, no double blank lines.

2020-08-04 11:46 UTC, gabrielfs7 commented on models/classes/task/migration/ResourceResultUnit.php
> +    public function __construct(core_kernel_classes_Resource $resource)
```suggestion
    public function __construct($resource)
```
Remove the type hint, so the class can be used to multiple types of resource.

2020-08-05 11:24 UTC, gabrielfs7 commented on models/classes/task/migration/service/QueueMigrationService.php
> +        SpawnMigrationConfigServiceInterface $configFactory,
```suggestion
        SpawnMigrationConfigServiceInterface $spawnService,
```

2020-08-05 11:25 UTC, gabrielfs7 commented on models/classes/task/migration/service/QueueMigrationService.php
> +                $this->affected++;
It seems we do not use this class attribute anymore.

2020-08-05 11:30 UTC, gabrielfs7 commented on scripts/tools/MigrationAction.php
> +                'description' => 'Amount of items proceed in chunk (for test purposes)'
Is it really for test purposes?

2020-08-05 11:31 UTC, gabrielfs7 commented on scripts/tools/MigrationAction.php
> +                'description' => 'Amount of `statements` rows provided into taskqueue to proceeded with'
"Amount of units", cause "statements" are DB/feature specific.

2020-08-05 11:35 UTC, gabrielfs7 commented on scripts/tools/MigrationAction.php
> +            ]),
```suggestion
            array_merge(
                $customParameters,
                [
                    'chunkSize' => $chunkSize,
                    'pickSize' => $pickSize,
                    'repeat' => $repeat,
                ]
            ),
```

https://www.php-fig.org/psr/psr-12/

```
Argument lists and variable lists MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one argument or variable per line.

When the ending list (whether of arguments or variables) is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.
```

I notice we do not do it in several places and we do this kind of thing like:

```
        return new ResultFilter([
            'start' => (int) $config->getCustomParameter('start'),
            'end' => $end,
            'max' => $max
        ]);
```

The `[` should come in the next line.

2020-08-05 11:39 UTC, gabrielfs7 commented on scripts/tools/MigrationAction.php
> +        throw new InvalidArgumentException(
```suggestion

        throw new InvalidArgumentException(
```

2020-08-05 11:40 UTC, gabrielfs7 commented on test/TaoPhpUnitTestRunner.php
> +        if (!extension_loaded('pdo_sqlite')) {
Was not this @jbout 's change? Why is it as new change in your branch?

2020-08-05 11:40 UTC, gabrielfs7 commented on test/unit/extension/UpdateExtensionsTest.php
> +        defined('TAO_VERSION') ?: define('TAO_VERSION', 'TAO_VERSION');
https://github.com/oat-sa/tao-core/pull/2599/files#r465665288

2020-08-05 11:41 UTC, bartlomiejmarszal commented on models/classes/task/migration/service/QueueMigrationService.php
> +                $this->affected++;
```suggestion
```

2020-08-05 11:42 UTC, gabrielfs7 commented on models/classes/task/migration/service/QueueMigrationService.php
> +        $report->add(common_report_Report::createSuccess('To repeat this process to other statements please provide -rp flag'));
We must remove the word statement from the common classes.

```suggestion
        $report->add(common_report_Report::createSuccess('To repeat this process to other units, please provide -rp flag'));
```

2020-08-05 11:42 UTC, gabrielfs7 commented on test/unit/models/classes/task/migration/PositionTrackerTest.php
> +
```suggestion
```

2020-08-05 11:44 UTC, gabrielfs7 commented on test/unit/models/classes/task/migration/PositionTrackerTest.php
> +        $this->persistenceMock->expects($this->once())->method('get')->with('id::_last_known')->willReturn(7);
Can you please break the lines to easier reading of code?

```
$this->persistenceMock
    ->expects($this->once())
    ->method('get')
    ->with('id::_last_known')
    ->willReturn(7);
```

2020-08-05 11:45 UTC, gabrielfs7 commented on test/unit/models/classes/task/migration/service/QueueMigrationServiceTest.php
> +
```suggestion
```

2020-08-05 11:45 UTC, gabrielfs7 commented on test/unit/models/classes/task/migration/service/QueueMigrationServiceTest.php
> +
```suggestion
```

2020-08-05 11:46 UTC, gabrielfs7 commented on test/unit/models/classes/task/migration/service/QueueMigrationServiceTest.php
> +        ]));
```suggestion
        $this->subject->setServiceLocator(
            $this->getServiceLocatorMock(
                [
                    StatementLastIdRetriever::class => $this->statementLastIdRetrieverMock,
                    ResultUnitProcessorInterface::class => $this->resultUnitProcessorMock,
                ]
            )
        );
```

PSR-12 as mentioned before: https://www.php-fig.org/psr/psr-12/

2020-08-05 11:46 UTC, gabrielfs7 commented on test/unit/models/classes/task/migration/service/StatementLastIdRetrieverTest.php
> +
```suggestion
```

2020-08-05 11:48 UTC, gabrielfs7 reviewed
Good job! Just a few comments about remove `statement` word from common classes that can mislead to make developers implement statement specific code for general classes.

Also some PSR-12 small fixes

2020-08-05 11:58 UTC, gabrielfs7 commented on models/classes/taskQueue/README.md
> +    -cp "start=0\&anotherOption=" \
- I would also add in the documentation that this Migration is agnostic of any kind of db and resource (and should remain like this). This is up to the 5 interfaces to be implemented and defined (If possible document the 5 interfaces or give an example).

- Also important to say the any additional parameter should be handled as `customParameter` for the specific task, but not extend the abstract one.

2020-08-05 11:59 UTC, gabrielfs7 commented on models/classes/taskQueue/README.md
> +We are obliged to provide array argument in `-cp` argument.
You mean a `queryString` argument?

2020-08-05 12:00 UTC, bartlomiejmarszal commented on scripts/tools/MigrationAction.php
> +        throw new InvalidArgumentException(
This doesn't seem right.

2020-08-05 13:26 UTC, gabrielfs7 commented on scripts/tools/MigrationAction.php
> +        throw new InvalidArgumentException(
A break like after if `}`. It is clear the exception does not belong to the if context.

2020-08-05 15:17 UTC, bartlomiejmarszal commented on test/TaoPhpUnitTestRunner.php
> +        if (!extension_loaded('pdo_sqlite')) {
<img width="898" alt="Screenshot 2020-08-05 at 17 16 59" src="https://user-images.githubusercontent.com/16231681/89430878-83a8a300-d73f-11ea-9440-9fe076964498.png">

2020-08-05 15:18 UTC, bartlomiejmarszal commented on test/unit/extension/UpdateExtensionsTest.php
> +        defined('TAO_VERSION') ?: define('TAO_VERSION', 'TAO_VERSION');
This test was broken without this.

2020-08-05 15:18 UTC, bartlomiejmarszal commented on test/TaoPhpUnitTestRunner.php
> +        if (!extension_loaded('pdo_sqlite')) {
I don't know what I have to do with this

2020-08-05 15:19 UTC, gabrielfs7 commented on test/unit/extension/UpdateExtensionsTest.php
> +        defined('TAO_VERSION') ?: define('TAO_VERSION', 'TAO_VERSION');
Yes. I know. I just wanted to know why it is appearing in your PR since it was already merged to develop last week.

2020-08-05 15:19 UTC, gabrielfs7 commented on test/TaoPhpUnitTestRunner.php
> +        if (!extension_loaded('pdo_sqlite')) {
Yes. I know. I just wanted to know why it is appearing in your PR since it was already merged to develop last week.

2020-08-05 15:19 UTC, bartlomiejmarszal commented on test/TaoPhpUnitTestRunner.php
> +        if (!extension_loaded('pdo_sqlite')) {
I would revert y commit with this change but I don't see any

2020-08-06 09:03 UTC, gabrielfs7 approved these changes
LGTM, just think README.md should be more clear.

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-08-06 09:06 UTC, mike-ionut-mihai-sandu-tao requested changes
manifest update

2020-08-06 12:48 UTC, gabrielfs7 approved these changes
LGTM

2020-08-06 12:58 UTC, merged