TAO-10423 added EventAggregatorService
oat-sa/tao-core pull request #2646
Opened 2020-08-20 08:44 UTC by andreluizmachado

Triggering the aggregated events after the action is dispatched.

2020-08-21 07:02 UTC, luisfn commented on migrations/Version202007231447592234_tao.php
> +        $this->getServiceManager()->register(IndexUpdaterInterface::SERVICE_ID, new GenerisIndexUpdater());
Don't we need to register these for install as well?

2020-08-24 10:56 UTC, Skyld requested changes

2020-08-24 10:56 UTC, Skyld commented on models/classes/search/strategy/GenerisIndexUpdater.php
> +        return false;
Shouldn't we add a test case to verify this behavior?

2020-08-24 11:26 UTC, andreluizmachado commented on models/classes/search/strategy/GenerisIndexUpdater.php
> +        return false;
Hi, unit tests were added.

2020-08-24 13:09 UTC, Skyld approved these changes
- [x] New code is covered by tests
- [ ] Tests are running successfully (old and new ones) on my local machine
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues
- [ ] Feature is working correctly on my local machine
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes
- [ ] Documentation is updated according to changes

2020-08-24 13:20 UTC, merged