Feature/tca 764/create new csrf token storage interface
oat-sa/tao-core pull request #2655
Opened 2020-08-25 13:17 UTC by SashaTAO

JIRA: https://oat-sa.atlassian.net/browse/TCA-764

There is a known issue in current BE token storage implementation. Because of this issue it may happen that two concurrent requests from client will rewrite CSRF token generated by another process. In this case there is a situation where there is `valid` token stored in client tokens pool, but it already doesn't exist in BE token storage.

Solution:
Instead of using pool of tokens on BE create a new interface which will allow to get/add/revoke one token atomically without rewriting all tokens in storage.

2020-08-31 10:32 UTC, wazelin commented
Wait, concurrent requests cannot invalidate the same token, can they?
I mean, client-side dequeues a token prior to sending a request, so when another request is being sent, a new token from the queue will be used.

2020-09-01 08:57 UTC, wazelin reviewed
Wait, concurrent requests cannot invalidate the same token, can they?
I mean, client-side dequeues a token prior to sending a request, so when another request is being sent, a new token from the queue will be used.

2020-09-14 09:28 UTC, SashaTAO commented
> Wait, concurrent requests cannot invalidate the same token, can they?
> I mean, client-side dequeues a token prior to sending a request, so when another request is being sent, a new token from the queue will be used.

@wazelin you are right, two concurrent requests will not invalidate the same token. But it may happen that two concurrent requests will read tokens pool, after that request A will generate a new token, store it and return to the client. After that request B will do the same and rewrite token pool without token generated by the first request. When it happens at some moment client will send request signed with token which doesn't exist in the pool on BE.

2020-09-14 09:31 UTC, wazelin commented
Right, very good point.

We should definitely consider getting rid of that pool, and using a single token for all the requests within a session.
Having a pool has no security benefits.

2020-09-15 16:00 UTC, wazelin requested changes

2020-09-15 16:00 UTC, wazelin commented on models/classes/security/xsrf/TokenService.php
> +        $savedToken = $savedToken = $this->getStore()->getToken(self::FORM_TOKEN_NAMESPACE);
```suggestion
        $savedToken = $this->getStore()->getToken(self::FORM_TOKEN_NAMESPACE);
```

2020-09-15 16:00 UTC, wazelin commented on models/classes/security/xsrf/TokenService.php
> +        if (($savedToken = $this->getStore()->getToken($token)) === null) {
It's weird to see `getToken` method being called with a `$token` argument.
Perhaps, it's better to rename `$token` into `$tokenId`, what do you think?

2020-09-15 16:00 UTC, wazelin commented on models/classes/security/xsrf/TokenStore.php
> -    public function getTokens();
Technically, that, among others, is a breaking change.

2020-09-24 10:57 UTC, augustas requested changes
Seems to work fine, but the bug was not reproduced neither by QA nor by devs, so it's hard to tell if it's definitely this problem that caused those errors.
The changes seem to be pretty clear, but security is a tricky topic and I would have liked to see a 3rd party library used for this.

2020-09-24 10:57 UTC, augustas commented on models/classes/security/xsrf/TokenStoreKeyValue.php
> +        }
I think you could just do `$this->getPersistence()->del($this->getKey());`, it will remove all hash fields/values, no need for iteration and multiple calls.

2020-09-24 10:57 UTC, augustas commented on models/classes/security/xsrf/TokenService.php
> +    protected function invalidate(array $tokens): array
The name of this function is a bit unclear for me. I expected all passed tokens will be invalidated, but it only invalidated the oldest one. Violates POLA principle :t-rex:

2020-10-07 12:28 UTC, SashaTAO commented on models/classes/security/xsrf/TokenService.php
> +        if (($savedToken = $this->getStore()->getToken($token)) === null) {
Agree, it looks a bit weir. At the moment there is no token ID,  therefore I use token string as key in KV storage.
It's called `$tokenId` in token storage implementation, but here in TokenService it's actually token string value. Do you think it will be better to rename it here to `$tokenId`

2020-10-07 12:32 UTC, SashaTAO commented on models/classes/security/xsrf/TokenStore.php
> -    public function getTokens();
Ideally TokenStorage  should be kind of `private` class, used only from TokenService. Therefore I didn't want to increase major version. 
Fixed.

2020-10-07 16:31 UTC, SashaTAO commented on models/classes/security/xsrf/TokenStoreKeyValue.php
> +        }
Done

2020-10-08 07:35 UTC, wazelin commented on models/classes/security/xsrf/TokenService.php
> +        if (($savedToken = $this->getStore()->getToken($token)) === null) {
Hmm, you're right. OK then.

2020-10-08 07:41 UTC, wazelin approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful ⚠️ it would've been better to describe the actual feature's impact there IMO
- [x] Pull request's target is not `master`

2020-10-08 09:45 UTC, augustas approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-10-08 09:46 UTC, merged