Fix UNO 444 - Broken layers in DEMO when background tasks menu opened
oat-sa/tao-core pull request #2656
Opened 2020-08-27 11:06 UTC by habemuscode

**Needs merge and publish this PR's first**

https://github.com/oat-sa/ckeditor-dev/pull/20

https://github.com/oat-sa/tao-core-shared-libs-fe/pull/9

**Related to**

https://oat-sa.atlassian.net/browse/UNO-444

**Description**

There're some issues with layers when the browser window resolution set to the smaller size e.g. 900x700 and the item has a property type set to Text - Long - HTML editor: the list of background tasks partially covered by edit item properties form. Reproduced only in `UDIR` demo environment.

**Preconditions**

Class property type is set to Text - Long - HTML editor.

**Steps to reproduce**

- Navigate to the Items tab
- Narrow the browser window 
- Open the Background tasks menu

**Actual result**

The opened Background tasks menu is partially covered by 'Kommentar' field in edit item properties filed.

**Expected result**

The opened Background tasks menu covers the edit item properties form.

![imagen](https://user-images.githubusercontent.com/34692207/91433018-e4209100-e862-11ea-9310-55fb6070c129.png)

2020-08-27 11:44 UTC, Alroniks approved these changes

2020-08-27 13:06 UTC, jsconan approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-08-28 06:50 UTC, andrey-ponamarev requested changes
Lock file is missing

2020-08-28 06:53 UTC, bziondik approved these changes
Add Lock file
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-08-28 07:10 UTC, habemuscode commented
@andrey-ponamarev Yes, that is why I put the list of PRs for merge before. For get approvals more fast while waiting other PRs merged :)

2020-08-28 07:13 UTC, merged