Feature/tao 10453/implement query builder
oat-sa/tao-core pull request #2660
Opened 2020-08-30 19:42 UTC by adriloma

**related to:** https://oat-sa.atlassian.net/browse/TAO-10454

This PR replaces the current `search` component by the new `searchModal` component, and is dependant of [this](https://github.com/oat-sa/tao-core-ui-fe/pull/172) PR on `tao-core-ui-fe`.

**How to test**
To be able to test this PR locally you need to setup your TAO instance to manage the new Advanced search feature. To do so you need to:

- On your root `composer.json` set the following dependencies:
```
    "oat-sa/generis": "dev-feature/TAO-10203-advanced-search as 12.33.2",
    "oat-sa/tao-core": "dev-feature/TAO-10203-advanced-search as 42.7.0",
    "oat-sa/extension-tao-dac-simple": "dev-feature/TAO-10203-advanced-search",
    "oat-sa/lib-tao-elasticsearch": "dev-feature/TAO-10203-advanced-search as 1.1.1"
```
- run `composer install`
- if you work with `taoDockerize` run `taoDockerize install`  (database will be reset)
- If you do not user `taoDockerize` run `php tao/scripts/taoUpdate.php`

Notice that because of its dependency, on `views/package.json` `@oat-sa/tao-core-ui` needs to be pointing to `feature/TAO-10454/implement-search-retention` following your usual way to do it (linking package to local repository, pointing `package.json` to origin branch...).

Now `searchModal` component should be used on search trigger instead of previous search component. Notice that advanced search syntax is not enabled if you do not set up an elastic search server, which is not required to test this feature.

Please let me know if you need more details about how to test the feature.

![search-retention](https://user-images.githubusercontent.com/14041944/91667796-6af59800-eb07-11ea-8fcd-ce2c3feccbe3.gif)

2020-09-01 07:51 UTC, andrey-ponamarev commented on views/js/layout/search.js
> +        query = query ? query : $('input', searchComponent.container).val();
```suggestion
    function createSearchModalInstance(query = $('input', searchComponent.container).val(), searchOnInit = true) {
```

2020-09-01 07:52 UTC, andrey-ponamarev commented on views/js/layout/search.js
> +        const url = $('.action-bar .search-area').data('url');
```suggestion
        const url = searchComponent.container.data('url');
```

2020-09-01 09:01 UTC, jsconan commented on views/js/layout/search.js
> +        query = query ? query : $('input', searchComponent.container).val();
The input may not exist when the function is loaded, especially as the `searchComponent` is not yet initialized.
Moreover, even if the input exists, the value may not be accurate as it is context dependant.

2020-09-02 08:22 UTC, jsconan requested changes
Quick code review.

Pay attention to how to use promises. They must be caught at least at a higher level. Nested promises should be caught as well or chained.

Regarding the CSS, please use classes instead of JS code. Please also use variables for colors.

2020-09-02 08:22 UTC, jsconan commented on views/js/layout/search.js
> +        });
Please catch the promise. Since there is a nested promise, it should be returned as well to catch it at one place.

2020-09-02 08:22 UTC, jsconan commented on views/js/layout/search.js
> +            $searchAreaButtonsContainer.css('right', '35px');
Is it not possible to use a CSS class instead??

2020-09-02 08:22 UTC, jsconan commented on views/js/layout/search.js
> +            $resultsCounter.css('display', 'none');
Same here, please use a CSS class instead.

2020-09-02 08:22 UTC, jsconan commented on views/scss/inc/_action-bars.scss
> +                    color: black;
even if the code was using a hardcoded color before, please use a variable instead. You have them listed in the [inc/_colors.scss](https://github.com/oat-sa/tao-core-ui-fe/blob/master/scss/inc/_colors.scss) file

2020-09-02 08:22 UTC, jsconan commented on views/scss/inc/_action-bars.scss
> +                border: 1px dashed black;
please use color variable

2020-09-02 08:22 UTC, jsconan commented on views/scss/inc/_action-bars.scss
> +                padding: 0px 0px 0px 5px;
unit must not be supplied for `0` value
```suggestion
                margin: 0;
                padding: 0 0 0 5px;
```

2020-09-02 08:22 UTC, jsconan commented on views/templates/blocks/search.tpl
> +        <button class="icon-ul" type="button" title="Open results"><div class="results-counter"></div></button>
semantically, a `span` should be used there instead of a `div`.

2020-09-02 14:48 UTC, bziondik approved these changes
Code review only
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-09-02 14:48 UTC, bziondik commented on views/js/layout/search.js
> +        $searchBtn.off('.searchComponent').on('click.searchComponent', () => createSearchModalInstance());
It is not readable when in one line

2020-09-02 14:48 UTC, bziondik commented on views/js/layout/search.js
> +            .on('keypress.searchComponent', e => (e.which === 13 ? createSearchModalInstance() : undefined));
Why you return `undefined` here?

2020-09-03 09:27 UTC, adriloma commented on views/js/layout/search.js
> +            .on('keypress.searchComponent', e => (e.which === 13 ? createSearchModalInstance() : undefined));
Hi @bziondik , I am a bit used to that structure. As far as I understand, this:

`.on('keypress.searchComponent', e => (e.which === 13 ? createSearchModalInstance() : undefined));`

Would be the same as:
```
.on('keypress.searchComponent', (e) =>  {
     if (e.which === 13) {
         createSearchModalInstance();
    }
});
```

For me it is more clear to read in one line and with ternary operator, but maybe because It's what I am used to.

2020-09-03 09:53 UTC, andrey-ponamarev commented on views/js/layout/search.js
> +        $searchBtn.off('.searchComponent').on('click.searchComponent', () => createSearchModalInstance());
Why do we call `off` method?
```suggestion
        $searchBtn.off('click.searchComponent').on('click.searchComponent', createSearchModalInstance);
```

2020-09-03 15:40 UTC, jsconan reviewed
Code review only.
Looks better 👍 .

2020-09-03 15:40 UTC, jsconan commented on views/js/layout/search.js
> +        });
```suggestion
        const searchModalInstance = searchModal({ query, url, searchOnInit });
```

2020-09-03 16:53 UTC, adriloma commented on views/js/layout/search.js
> +        $searchBtn.off('.searchComponent').on('click.searchComponent', () => createSearchModalInstance());
Yes, I had the same question as it was in the code I refactored. I assumed it is required to ensure that nothing else is attached to the given event. As don't fully know what other interactions could be involded there, decided to keep it in the code.

2020-09-04 06:11 UTC, andrey-ponamarev approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

2020-09-04 06:57 UTC, merged