[Feature] UNO 197 - Dropdown should show status
oat-sa/tao-core pull request #2666
Opened 2020-09-03 10:54 UTC by habemuscode

**Upgrade version of npm package**

**Related to**

https://github.com/oat-sa/tao-core-ui-fe/pull/173/files

2020-09-04 07:03 UTC, zagovorichev requested changes

2020-09-04 07:03 UTC, zagovorichev commented on manifest.php
> +    'version' => '45.8.0',
Don't you need to update version in the package.json as well?

2020-09-04 07:04 UTC, habemuscode commented on manifest.php
> +    'version' => '45.8.0',
Need this PR merge before :)

https://github.com/oat-sa/tao-core-ui-fe/pull/173

2020-09-07 13:43 UTC, jsconan approved these changes
code review only

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2020-09-07 13:50 UTC, adriloma approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2020-09-07 14:01 UTC, merged