Feature/NEX-689/Create previewer registry service
oat-sa/tao-core pull request #2669
Opened 2020-09-08 10:44 UTC by shpran

Relates to: [NEX-1689](https://oat-sa.atlassian.net/browse/NEX-1689)

**Changes:**
* Added abstract previewer registry service (from taoItems);
* Added unit test (from taoItems).

**Companion PRs:**
* [#352](https://github.com/oat-sa/extension-tao-test/pull/352)

2020-09-08 13:50 UTC, SergiiTao requested changes

2020-09-08 13:50 UTC, SergiiTao commented on models/classes/preview/PreviewerRegistryService.php
> +abstract class PreviewerRegistryService extends ConfigurableService
why it is an abstract if it doesn't contain any abstract methods?

2020-09-08 14:05 UTC, shpran commented on models/classes/preview/PreviewerRegistryService.php
> +abstract class PreviewerRegistryService extends ConfigurableService
It's abstract to avoid using this service directly

2020-09-08 14:18 UTC, SergiiTao commented on models/classes/preview/PreviewerRegistryService.php
> +abstract class PreviewerRegistryService extends ConfigurableService
is it possible to create a service that can be used directly?

2020-09-08 15:40 UTC, ktsirkou commented on models/classes/preview/PreviewerRegistryService.php
> +abstract class PreviewerRegistryService extends ConfigurableService
I guess what @shpran means here is that if this service is not declared as abstract then someone can initialize an object by that and then use, which will fail as the `registryEntryKey` property will never be set. 

I do agree that abstract class with no abstract methods doesn't really make much sense. 
What about defining an abstract method to get the `registryEntryKey`?

2020-09-08 16:26 UTC, SergiiTao commented on models/classes/preview/PreviewerRegistryService.php
> +abstract class PreviewerRegistryService extends ConfigurableService
to define an abstract method just to add a small sense to keep an abstract class? :)
PreviewerRegistryService is self-sufficient.
As I already offered. IMHO it would be better to create a common service an then use directly or initialize it with factory.
in such way we will have less coupling and `composition over inheritance`

2020-09-09 11:39 UTC, SergiiTao requested changes

2020-09-09 11:39 UTC, SergiiTao commented on models/classes/preview/PreviewerRegistryService.php
> +class PreviewerRegistryService extends ConfigurableService implements PreviewerRegistryServiceInterface
is it possible to use this service, not for previewer adapters only, but for any kind of adapters stored in `ClientLibConfigRegistry`?

2020-09-09 11:39 UTC, SergiiTao commented on models/classes/preview/PreviewerRegistryService.php
> +class PreviewerRegistryService extends ConfigurableService implements PreviewerRegistryServiceInterface
what do you think of using `InjectionAwareService` instead of `ConfigurableService`?

2020-09-11 07:17 UTC, SergiiTao approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-09-11 08:11 UTC, ktsirkou approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-09-16 11:54 UTC, merged