Specifies exact order for the form fields
oat-sa/tao-core pull request #2683
Opened 2020-09-17 21:14 UTC by boajer

2020-09-18 14:36 UTC, gabrielfs7 commented on models/ontology/oauth.rdf
> +    <tao:TAOGUIOrder><![CDATA[10]]></tao:TAOGUIOrder>
@boajer Why we have the definition here and taoLti? Would not be better to update just there if possible?

2020-09-18 14:36 UTC, gabrielfs7 commented on migrations/Version202009171036302234_tao.php
> +
```suggestion
```
Not required

2020-09-18 14:37 UTC, gabrielfs7 commented on manifest.php
> +    'version' => '45.11.2',
It is not a bug, shouldn't be `45.12.0`?

2020-09-18 14:46 UTC, boajer commented on models/ontology/oauth.rdf
> +    <tao:TAOGUIOrder><![CDATA[10]]></tao:TAOGUIOrder>
Here we have definitions of OAuth properties and I've added explicit ordering. 
Not sure if we have the same defined at taoLti

2020-09-21 06:28 UTC, gabrielfs7 commented on helpers/form/class.FormContainer.php
> +
```suggestion
        if (!empty($options[self::ADDITIONAL_VALIDATORS])) {
            $this->applyAdditionalValidationRules($options[self::ADDITIONAL_VALIDATORS]);
        }

```

Otherwise we would be looping the form unnecessarily every time.

2020-09-21 06:33 UTC, gabrielfs7 commented on models/ontology/oauth.rdf
> +    <tao:TAOGUIOrder><![CDATA[10]]></tao:TAOGUIOrder>
Aren't those fields related to LTIConsumer, not Provider? I am wondering why those fields are in the tao-core and will they change other undesired places? 

Maybe since the order you added to the other LTI fields are higher, you do not need to change this file. wdyt?

2020-09-22 06:23 UTC, bartlomiejmarszal requested changes
You should provide a short description in PR description what this PR is about

2020-09-22 06:23 UTC, bartlomiejmarszal commented on helpers/form/validators/class.OneOf.php
> + */
Strict type?

2020-09-22 06:23 UTC, bartlomiejmarszal commented on helpers/form/validators/class.Url.php
> +        if (empty($value) && $this->hasOption('allow_empty') && $this->getOption('allow_empty') == true) {
Why it is not const to get option name?

2020-09-22 06:33 UTC, gabrielfs7 commented on helpers/form/class.FormContainer.php
> -     * @access protected
I think this is from php 4 time when we did not have variables scopes. Otherwise I do not see the need to this.

2020-09-22 06:35 UTC, boajer commented on helpers/form/class.FormContainer.php
> +    private function propagate(iterable $validators, tao_helpers_form_Form $form): void
What would you suggest?

2020-09-22 06:37 UTC, gabrielfs7 commented on helpers/form/class.FormContainer.php
> +        if ($validationRules = $options[self::ADDITIONAL_VALIDATORS] ?? []) {
I know it works, but for me it is a bit misleading what you are checking. I would move the variable assign to outside of the if and check for `if (!empty($validationRules)) {`. For the developer is clear to understand. Just my opinion.

2020-09-22 06:40 UTC, gabrielfs7 commented on helpers/form/class.FormContainer.php
> +    private function propagate(iterable $validators, tao_helpers_form_Form $form): void
It is because this is `setting` validation rules for all the elements, but `propagate` is too magical for me. And it seems we are talking about events or threads. In this case I would use `configureFormValidators`.

2020-09-22 06:50 UTC, boajer commented on models/ontology/oauth.rdf
> +    <tao:TAOGUIOrder><![CDATA[10]]></tao:TAOGUIOrder>
I think that should be quite safe, as if no order attribute is provided sorting happens in the same order as it presented at RDF, unless we have mixed properties w and w/o that attributes. 
So in this case  I believe it either maintain the same order as it was before or will be fixed, if somewhere was combined with preorder elements before that change. 

As for relation to LTIConsumer, I think that is another topic, we may open another ticket for invistigation and fix ( if needed) as for now it for sure used for the providers form/rdf-instances/etc

![Screenshot 2020-09-22 at 09 49 02](https://user-images.githubusercontent.com/4569734/93851570-0ae2b380-fcb9-11ea-9c9e-1a7fa814a744.png)

2020-09-22 06:53 UTC, gabrielfs7 commented on helpers/form/validators/class.OneOf.php
> +            }
This should not be an error? Why would I have a reference that does not exist?

2020-09-22 06:55 UTC, gabrielfs7 commented on helpers/form/validators/InjectableElementsAware.php
> +}
This interface says that it is something `aware to inject elements`, but we are talking about `cross elements evaluation`. I am not sure if this is a good name for interface and method. Wdyt?

2020-09-22 06:56 UTC, gabrielfs7 commented on helpers/form/validators/class.OneOf.php
> +        return count(array_filter($isEmpty)) === 1;
In our cause, have both public key and JWKS should be also possible, IMO.

2020-09-22 06:58 UTC, gabrielfs7 requested changes
Good jog! Small things. Allow both JWKS and Public Key to be set, naming changes, etc.

2020-09-22 06:58 UTC, boajer commented on helpers/form/validators/class.OneOf.php
> +        return count(array_filter($isEmpty)) === 1;
But the ticket says the either key or JWKS, I've read it `exclusive or`

2020-09-22 06:58 UTC, boajer commented on helpers/form/validators/class.OneOf.php
> +            }
Good catch!

2020-09-23 06:12 UTC, gabrielfs7 commented on helpers/form/validators/class.AnyOf.php
> +class tao_helpers_form_validators_AnyOf extends tao_helpers_form_Validator implements CrossElementEvaluationAware
Do you plan to add tests for this?

2020-09-23 06:13 UTC, gabrielfs7 commented on helpers/form/validators/class.OneOf.php
> +class tao_helpers_form_validators_OneOf extends tao_helpers_form_Validator implements CrossElementEvaluationAware
Do you plan to add tests for this?

2020-09-23 06:15 UTC, gabrielfs7 commented on helpers/form/validators/class.Url.php
> +        if (empty($value) && $this->hasOption(self::OPTION_ALLOW_EMPTY) && $this->getOption(self::OPTION_ALLOW_EMPTY) == true) {
Just remember that `empty` will allow `'', 0, null, false, []`. Are you sure this is the desired behavior?

2020-09-23 06:15 UTC, gabrielfs7 requested changes
Missing tests and some misleading validation. Please address all the comments :)

2020-09-23 06:16 UTC, gabrielfs7 commented
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-09-23 07:37 UTC, bartlomiejmarszal requested changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-09-23 07:37 UTC, bartlomiejmarszal commented on helpers/form/class.FormContainer.php
> +        foreach ($this->getForm()->getElements() as $element) {
It is possible that `$this->getForm()` may be `null`

2020-09-23 07:37 UTC, bartlomiejmarszal commented on helpers/form/validators/class.AnyOf.php
> +        foreach ($this->getOption('reference', []) as $ref) {
Why do you need empty array in `getOption` method?

2020-09-23 07:44 UTC, boajer commented on helpers/form/validators/class.AnyOf.php
> +        foreach ($this->getOption('reference', []) as $ref) {
That is default value if option is not set, fallback to safer value rather then default `null`

2020-09-23 07:52 UTC, siwane approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-09-23 07:54 UTC, bartlomiejmarszal commented
I'm able to create a provider for LTI 1.3 without required fields. Only when I edit this form required fields are validated.

2020-09-23 14:29 UTC, siwane commented
Working locally, good job

2020-09-24 06:58 UTC, gabrielfs7 commented on test/unit/helpers/form/validators/AnyOfValidatorTest.php
> +
```suggestion

```
Single line to follow our PR guideline, please

2020-09-24 06:58 UTC, gabrielfs7 commented on test/unit/helpers/form/validators/AnyOfValidatorTest.php
> +
```suggestion
```
To follow our PR guideline, please

2020-09-24 06:58 UTC, gabrielfs7 commented on test/unit/helpers/form/validators/AnyOfValidatorTest.php
> +
```suggestion

```
Single line to follow our PR guideline, please

2020-09-24 06:58 UTC, gabrielfs7 commented on test/unit/helpers/form/validators/OneOfValidatorTest.php
> +
```suggestion

```
Single line to follow our PR guideline, please

2020-09-24 06:59 UTC, gabrielfs7 approved these changes
Approved.

2020-09-24 07:04 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-09-24 07:06 UTC, gabrielfs7 approved these changes

2020-09-24 07:09 UTC, merged