Feature/tao 10366 create event for changing resource privileges
oat-sa/tao-core pull request #2684
Opened 2020-09-18 08:49 UTC by andreluizmachado

This PR is intended to implement the issue https://oat-sa.atlassian.net/browse/TAO-10366
Please also take a look at the PRs:
- 
- 
**The issue:** 

- When the user updates Data Access Control on the resource, these changes are not reflected in the advanced search.

**The solution:** 
A new event was created (DataAccessControlChangedEvent) to be possible to have Advanced search up to date

**Extra fixes**
- 500 error on search action (actions/class.Search.php) when trying to filter permissions on empty results
- Fail during search resources that have access control by the user instead of by role. We need to include the user identifier on the query to get a proper result. Please look PR:  
- fixed wrong interface implementation IndexSinceLastRunService:runIndexing method

2020-09-18 09:38 UTC, luisfn requested changes

2020-09-18 09:38 UTC, luisfn commented on models/classes/event/DataAccessControlChangedEvent.php
> +    public function __construct(string $resourceId, array $addRemove, bool $isRecursive = false)
Can't we separate  $addRemove into 2 arrays? Or maybe call it "operations"  or "changes"?

2020-09-18 09:38 UTC, luisfn commented on migrations/Version202007231447592234_tao.php
> +        $eventManager->detach(DataAccessControlChangedEvent::class, [DataAccessControlChangedListener::SERVICE_ID, 'handleEvent']);
Can we rename the previous handlers as well (renameClassProperties and removeClassProperty) for better consistency?

2020-09-18 09:38 UTC, luisfn commented on models/classes/listener/DataAccessControlChangedListener.php
> +                array_keys($event->getAddRemove()['add'] ?? []),
Looking now, may you could do something like 

`$event->getOperations('add')` and get only the ones you want, but filter it there

2020-09-18 09:38 UTC, luisfn commented on models/classes/search/tasks/UpdateDataAccessControlInIndex.php
> +
Remove empty line

2020-09-18 09:38 UTC, luisfn commented on models/classes/search/tasks/UpdateDataAccessControlInIndex.php
> +        $logMessage = 'Data Access Control were being updated by ' . static::class;
maybe these should be inside the try block since we have the others on the catch section

2020-09-18 09:38 UTC, luisfn commented on migrations/Version202007231447592234_tao.php
> +        $eventManager->detach(DataAccessControlChangedEvent::class, [DataAccessControlChangedListener::SERVICE_ID, 'handleEvent']);
If you Agree, please change it on the register classes as well

2020-09-18 10:30 UTC, andreluizmachado commented on models/classes/event/DataAccessControlChangedEvent.php
> +    public function __construct(string $resourceId, array $addRemove, bool $isRecursive = false)
I'll follow your method suggestion: getOperations :)

2020-09-18 10:30 UTC, andreluizmachado commented on models/classes/search/tasks/UpdateDataAccessControlInIndex.php
> +        $logMessage = 'Data Access Control were being updated by ' . static::class;
I put it outside becase there is no way to this throw an exception.

2020-09-18 13:15 UTC, luisfn approved these changes
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2020-09-21 15:49 UTC, Skyld approved these changes
- [x] New code is covered by tests
- [ ] Tests are running successfully (old and new ones) on my local machine
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues
- [ ] Feature is working correctly on my local machine
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes
- [ ] Documentation is updated according to changes

2020-09-21 15:51 UTC, merged