Lti1p3FeatureFlag define disabled sections
oat-sa/tao-core pull request #2688
Opened 2020-09-22 14:15 UTC by bartlomiejmarszal

In order to hide specific LTI 1.3 functionality I introduce `Lti1p3FeatureFlag`. This service will keep information if an instance is using LTI 1.3 and display/hide jwks key generation or additional fields in LtiProvider.

https://oat-sa.atlassian.net/browse/NEX-1989

2020-09-22 16:00 UTC, siwane requested changes
I would recommend to not mix domain. I mean tao-core should not be aware of LTI concept.
Could u use the structure context to deal with that, I do not know if it is possible

2020-09-23 07:44 UTC, gabrielfs7 commented on models/classes/featureFlag/Lti1p3FeatureFlag.php
> +class Lti1p3FeatureFlag extends ConfigurableService
1) Feature flag is agnostic, does not know about LTI, Deliver, etc. The mapping comes from outside. Any occurence of Lti here must be removed.

2) Create a general interface `FeatureFlagCheckerInterface::isEnabled($featureFlag): bool`.

3) You could have a general interface like `SectionVisibilityFilterInterface::isVisible($sectionId): bool`. This can use a feature flag underneath. This class would receive a map **from external configuration** that maps section + feature flag and use the feature flag service to check.

2020-09-23 07:45 UTC, gabrielfs7 requested changes
Wrote a comment about it. We are mixing responsibilities and crossing boundaries here.

2020-09-23 08:00 UTC, bartlomiejmarszal commented on models/classes/featureFlag/Lti1p3FeatureFlag.php
> +        return in_array($section, $this->getOption(self::OPTION_DISABLED_SECTIONS), true);
I want to change this to extract sections from configurable options

```suggestion
        if (!$this->isLti1p3Enabled()) {
            return in_array($section, self::LTI_1P1_DISABLED_SECTIONS, true);
        }
        
        return false;
```

2020-09-23 08:00 UTC, bartlomiejmarszal commented on models/classes/featureFlag/Lti1p3FeatureFlag.php
> +        return in_array($section, $this->getOption(self::OPTION_DISABLED_SECTIONS), true);
WDYT?

2020-09-24 09:06 UTC, gabrielfs7 commented on models/classes/featureFlag/FeatureFlagChecker.php
> +    public const OPTION_MANUALLY_ENABLED_FEATURES = 'optionEnabledFeatures';
Can be removed.

2020-09-24 09:08 UTC, gabrielfs7 commented on models/classes/featureFlag/FeatureFlagChecker.php
> +        return in_array($feature, $this->getOption(self::OPTION_MANUALLY_ENABLED_FEATURES), true);
```suggestion
        return boolval($_ENV[$feature] ?? false);
```
As we discussed, this will be customized by env var at the beginning, we do not need to go beyond it as it might change.

2020-09-24 09:10 UTC, gabrielfs7 commented on models/classes/menu/SectionVisibilityFilter.php
> +    }
As we discussed, we should provide by external config the mapping instead of a hardcoded php class config, cause the plan is to have this feature flags totally outside of the platform using tools like: https://bullet-train.io/

In this way we cannot achieve this.

2020-09-24 09:11 UTC, gabrielfs7 commented on models/classes/menu/SectionVisibilityFilterInterface.php
> +}
```suggestion
}

```
Missing new line

2020-09-24 09:12 UTC, gabrielfs7 commented on models/classes/menu/SectionVisibilityFilterInterface.php
> +    public function isHidden(string $section): bool;
```suggestion
    public function isVisible(string $section): bool;
```
I wold use the same word `visible` to be consistent with the name `visibility`.

2020-09-24 11:06 UTC, bartlomiejmarszal commented on models/classes/menu/SectionVisibilityFilterInterface.php
> +    public function isHidden(string $section): bool;
Due to exclkuding strategy i would keep `isHidden` name. It's still in visibility domain (`isHidden`/`isVisible`)

2020-09-24 12:04 UTC, siwane requested changes
Missing manifest version

2020-09-24 12:04 UTC, siwane commented on migrations/Version202009221232112234_tao.php
> +        return 'Register Lti1p3FeatureFlag service';
No LTI things in TAO pls

2020-09-24 12:04 UTC, siwane commented on models/classes/menu/Perspective.php
> +     * @throws \common_exception_Error
FQN

2020-09-24 12:04 UTC, siwane commented on models/classes/menu/SectionVisibilityFilter.php
> +    }
Im not sure to get your point

2020-09-24 12:13 UTC, gabrielfs7 commented on models/classes/menu/SectionVisibilityFilter.php
> +    }
I think we need to have a meeting. I came with this idea to have feature flag also to have it extensible in the future by environment, not fixed config in the code. I had a call with @bartlomiejmarszal where I explained the concept. The way it was being designed was not following this. Lets have a call to align this. I think it is better :)

2020-09-24 12:13 UTC, siwane commented on models/classes/featureFlag/FeatureFlagChecker.php
> +        return filter_var(getenv($feature), FILTER_VALIDATE_BOOLEAN) ?? false;
As a suggestion, I would like to keep a fallback to TAO config. I agree this way is the most proper but we should wait/confirm that `.env` file is used in production and part of the pipeline. WDYT?

2020-09-24 12:15 UTC, gabrielfs7 commented on models/classes/featureFlag/FeatureFlagChecker.php
> +        return filter_var(getenv($feature), FILTER_VALIDATE_BOOLEAN) ?? false;
We will not configure it for now in other way, so it is just adding more code unnecessarily. We need to have a meeting everybody urgently. I think it is reaching a point that we are propagating different input from multiple team members without fully understand the purpose of this.

2020-09-24 13:57 UTC, gabrielfs7 commented on models/classes/menu/SectionVisibilityFilter.php
> +        foreach ($sections as $featureFlags) {
```suggestion
        foreach ($sections[$section] as $featureFlags) {
```
Needs to be fixed

2020-09-24 13:58 UTC, gabrielfs7 commented on models/classes/menu/SectionVisibilityFilter.php
> +        return false;
The logic here is not correct:

```suggestion
        return $this->getFeatureFlagChecker()->isEnabled($featureFlag);
```

Btw, this method is not necessary since it is just a `delegate`.

2020-09-24 13:59 UTC, gabrielfs7 commented on helpers/form/class.FormContainer.php
> +    public const EXCLUDED_PROPERTIES = 'excludedProperties';
Do you think `property` is a good name, since in the form we call them `elements`?

2020-09-24 14:49 UTC, bartlomiejmarszal commented on helpers/form/class.FormContainer.php
> +    public const EXCLUDED_PROPERTIES = 'excludedProperties';
This is name used in form helper. I want to stick to their name.

2020-09-24 15:08 UTC, gabrielfs7 commented on helpers/form/class.FormContainer.php
> +    public const EXCLUDED_PROPERTIES = 'excludedProperties';
But here, in this very form it is called element, since the constant is here and is about this, why use a different name?

2020-09-24 15:11 UTC, gabrielfs7 commented on test/unit/models/classes/menu/SectionVisibilityFilterTest.php
> +    public function testIsHidden(): void
```suggestion
    public function testIsVisible(): void
```

2020-09-24 15:15 UTC, gabrielfs7 commented on migrations/Version202009221232112234_tao.php
> +            new SectionVisibilityFilter([])
I think we will have to migrate this to `taoLti` extension in order to properly disable the sections, otherwise this will be available by default to everybody. wdyt? How would we handle the release otherwise?

2020-09-24 15:19 UTC, gabrielfs7 commented on actions/class.RdfController.php
> +    protected function getExcludedProperties(): array
I suggest `getExcludedFormElements`, cause properties are misleading. The class has properties for instance. wdyt?

2020-09-25 06:08 UTC, bartlomiejmarszal commented on actions/class.RdfController.php
> +    protected function getExcludedProperties(): array
I used this name in order to keep consistency with option name that allow us excluding fields. 
`tao_actions_form_CreateInstance::initElements`

2020-09-25 06:11 UTC, gabrielfs7 commented on actions/class.RdfController.php
> +    protected function getExcludedProperties(): array
And as you see the method is also using `elements`, cause it is `initElements`. I think this method will be very misleading if we call it property, but it is up to you to decide. I will close this, cause I already used all the arguments I had, so...

2020-09-25 06:17 UTC, bartlomiejmarszal commented on migrations/Version202009221232112234_tao.php
> +            new SectionVisibilityFilter([])
Done. I also filled migration with form fields with feature flag

2020-09-25 07:36 UTC, gabrielfs7 commented on migrations/Version202009221232112234_tao.php
> +            new SectionVisibilityFilter([])
Thanks! Do you think we need to register it here, since we will have it here? https://github.com/oat-sa/extension-tao-lti/pull/276/files#diff-cd73a30e156de316b5ab8bbf832150ffR69

I think we can remove this migration

2020-09-25 07:39 UTC, gabrielfs7 commented on helpers/form/AbstractFeatureFlagFormPropertyMapper.php
> +    private function getFeatureFlagChecker(): FeatureFlagChecker
```suggestion
    private function getFeatureFlagChecker(): FeatureFlagCheckerInterface
```
Open/closed

2020-09-25 07:39 UTC, gabrielfs7 commented on models/classes/menu/SectionVisibilityFilter.php
> +    private function getFeatureFlagChecker(): FeatureFlagChecker
```suggestion
    private function getFeatureFlagChecker(): FeatureFlagCheckerInterface
```
Open / closed

2020-09-25 07:39 UTC, gabrielfs7 commented on test/unit/models/classes/menu/SectionVisibilityFilterTest.php
> +        $this->featureFlagChecker = $this->createMock(FeatureFlagChecker::class);
```suggestion
        $this->featureFlagChecker = $this->createMock(FeatureFlagCheckerInterface::class);
```
Open closed

2020-09-25 07:40 UTC, gabrielfs7 commented on test/unit/models/classes/menu/SectionVisibilityFilterTest.php
> +    private $featureFlagChecker;
```suggestion
    /** @var FeatureFlagCheckerInterface|MockObject **/
    private $featureFlagChecker;
```
missing doc

2020-09-25 08:27 UTC, bartlomiejmarszal commented on migrations/Version202009221232112234_tao.php
> +            new SectionVisibilityFilter([])
What if we are not using taoLti. Wouldn't we likke to still create this service in a instance?

2020-09-25 09:46 UTC, gabrielfs7 commented on migrations/Version202009221232112234_tao.php
> +            new SectionVisibilityFilter([])
Yes, you are right. Since this will be release in tao-core separately it needs to be here. Thanks!

2020-09-25 09:50 UTC, gabrielfs7 approved these changes
LGTM

- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-09-25 09:51 UTC, gabrielfs7 commented on actions/class.Main.php
> +                if (!$this->getSectionVisibilityFilter()->isVisible($section->getId())) {
One thing we can do it to avoid call `$this->getSectionVisibilityFilter()` every time, so this cost more than the if inside the `isVisible` method.

- [ ] Please, extract `$this->getSectionVisibilityFilter()` to a variable to reuse.

2020-09-25 09:52 UTC, gabrielfs7 commented on actions/class.Main.php
> +                if (!$this->getSectionVisibilityFilter()->isVisible($section->getId())) {
Same as here: https://github.com/oat-sa/tao-core/pull/2688/files#r494878436

2020-09-25 09:52 UTC, gabrielfs7 commented on models/classes/menu/Perspective.php
> +    private function getSectionVisibilityFilter(): SectionVisibilityFilter
```suggestion
    private function getSectionVisibilityFilter(): SectionVisibilityFilterInterface
```
Open/closed

2020-09-25 09:53 UTC, boajer commented on actions/form/class.CreateInstance.php
> +    public const EXCLUDED_PROPERTIES = 'excludedProperties';
Should it be only `CreateInstance` specific?  Nothing about altering?

2020-09-25 10:03 UTC, gabrielfs7 commented on models/classes/menu/Perspective.php
> +use oat\oatbox\service\ServiceManager;
This changes are not required anymore, right?

2020-09-25 10:39 UTC, gabrielfs7 commented on actions/form/class.CreateInstance.php
> +    public const EXCLUDED_PROPERTIES = 'excludedProperties';
Shouldn't but the code was duplicated and it is better to have config for the class it belongs IMO. So for me it is OK like this.

2020-09-25 12:20 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-09-25 12:23 UTC, boajer approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-09-29 07:12 UTC, siwane approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-09-29 07:20 UTC, merged

2020-09-29 07:26 UTC, gabrielfs7 commented on models/classes/featureFlag/FeatureFlagChecker.php
> +        return filter_var($_ENV[$feature], FILTER_VALIDATE_BOOLEAN) ?? false;
```suggestion
        return filter_var($_ENV[$feature] ?? false, FILTER_VALIDATE_BOOLEAN) ?? false;
```
There is not verification here, you should check if variable exists.