Feature/tao 10473 metadata discovery endpoint
oat-sa/tao-core pull request #2692
Opened 2020-09-28 08:05 UTC by luisfn

The goal of this pull request is to cover the new endpoint need by the frontend to handle the advanced search metadata discovery.

We will be able to do requests like:

If lists have more than 5 items, we won't return the items but a URL to retrieve them instead 
`/tao/ClassMetadata/get?classUri={URLENCODED_CLASS_URI}`

If list have more items than the value specified, we won't return the items but a URL to retrieve them instead
`/tao/ClassMetadata/get?classUri={URLENCODED_CLASS_URI}&listMaxSize={INT_VALUE}`

2020-09-29 16:11 UTC, andreluizmachado reviewed
I haven't had time to check everything out yet. These are my notes so far. by the way, good work 👍.

2020-09-30 06:50 UTC, andreluizmachado requested changes
Hi, just a few more comments.

2020-09-30 06:50 UTC, andreluizmachado commented on models/classes/Lists/Business/Service/ClassMetadataService.php
> +    public function findAll(ClassMetadataSearchInput $input): ClassCollection
I think makes more sense to depend only of the searchRequest instead of the input

2020-09-30 06:50 UTC, andreluizmachado commented on models/classes/Lists/Business/Service/ClassMetadataService.php
> +            $values = $this->isListWidget($property) ? $this->getPropertyValues($property) : null;
I think it seems more readble:
```
if ($this->isListWidget($property) ) {
    $values = $this->getPropertyValues($property);
    $uri = $this->getListItemsUri($property);
}

2020-09-30 06:50 UTC, andreluizmachado commented on models/classes/Lists/Business/Service/ValueCollectionService.php
> +    public function count(ValueCollectionSearchInput $input): int
Maybe it makes more sense only be dependent of searchRequest

2020-09-30 06:50 UTC, andreluizmachado commented on models/classes/Lists/Business/Service/ValueCollectionService.php
> +    public function count(ValueCollectionSearchInput $input): int
or maybe remove the search request and stay only with input?

2020-09-30 06:50 UTC, andreluizmachado commented on scripts/install/RegisterClassMetadataServices.php
> +namespace oat\tao\scripts\install;
strict_types missing

2020-09-30 06:50 UTC, andreluizmachado commented on scripts/install/RegisterClassMetadataServices.php
> +namespace oat\tao\scripts\install;
Also, you should add this class on the manifest/migration files, no?

2020-09-30 07:52 UTC, Skyld commented on models/classes/Lists/Business/Domain/ClassCollection.php
> +        yield from array_values($this->items);
why do you have to call array_values here?

2020-09-30 07:58 UTC, Skyld approved these changes
- [x] New code is covered by tests
- [ ] Tests are running successfully (old and new ones) on my local machine
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues
- [ ] Feature is working correctly on my local machine
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes
- [ ] Documentation is updated according to changes

2020-10-02 07:20 UTC, luisfn commented on models/classes/Lists/Business/Service/ValueCollectionService.php
> +    public function count(ValueCollectionSearchInput $input): int
Will keep it as is for consistence with the other endpoint to get the list values of a property

2020-10-02 07:20 UTC, luisfn commented on models/classes/Lists/Business/Service/ClassMetadataService.php
> +    public function findAll(ClassMetadataSearchInput $input): ClassCollection
Will keep it as is for consistence with the other endpoint to get the list values of a property

2020-10-02 08:09 UTC, luisfn commented on models/classes/Lists/Business/Service/ClassMetadataService.php
> +            $values = $this->isListWidget($property) ? $this->getPropertyValues($property) : null;
Transfer this checking logic to the methods

2020-10-04 19:48 UTC, luisfn commented on models/classes/Lists/Business/Domain/ClassCollection.php
> +        yield from array_values($this->items);
We don't need, removed. Thanks!

2020-10-04 20:33 UTC, luisfn commented on scripts/install/RegisterClassMetadataServices.php
> +namespace oat\tao\scripts\install;
Thanks for catch, fixed

2020-10-05 07:20 UTC, andreluizmachado approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2020-10-05 10:59 UTC, merged