TAO-10473 Adjusted filename
oat-sa/tao-core pull request #2699
Opened 2020-10-07 08:45 UTC by luisfn

2020-10-09 08:40 UTC, Skyld requested changes
Could you please add tests?

2020-10-09 09:05 UTC, luisfn commented
> Could you please add tests?

There are tests already for these. For the "new" class, it is not new, it was just renamed, not sure it was not recognized as such

2020-10-09 09:13 UTC, andreluizmachado requested changes

2020-10-09 11:27 UTC, luisfn commented on models/classes/Lists/Business/Domain/MetadataCollection.php
> +        foreach ($items as $value) {
Thanks for the suggestion. Did the same for the other collection as well

2020-10-09 11:35 UTC, andreluizmachado approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2020-10-12 07:28 UTC, Skyld approved these changes

2020-10-12 07:41 UTC, merged