Backport/tao 10574/login template
oat-sa/tao-core pull request #2700
Opened 2020-10-07 13:14 UTC by SergiiTao

2020-10-07 15:27 UTC, ktsirkou requested changes

2020-10-07 15:27 UTC, ktsirkou commented on helpers/Template.php
> +        $absPath = Layout::getThemeTemplate(Theme::CONTEXT_BACKOFFICE, $path) ?? self::getTemplate($path, $extensionId);
What is the PHP version running on DEPP env?

2020-10-07 16:01 UTC, SergiiTao commented on helpers/Template.php
> +        $absPath = Layout::getThemeTemplate(Theme::CONTEXT_BACKOFFICE, $path) ?? self::getTemplate($path, $extensionId);
good question

2020-10-08 07:21 UTC, SergiiTao commented on helpers/Template.php
> +        $absPath = Layout::getThemeTemplate(Theme::CONTEXT_BACKOFFICE, $path) ?? self::getTemplate($path, $extensionId);
7.2 confirmed by Lionel

2020-10-08 07:24 UTC, ktsirkou commented on helpers/Template.php
> +        $absPath = Layout::getThemeTemplate(Theme::CONTEXT_BACKOFFICE, $path) ?? self::getTemplate($path, $extensionId);
nice

2020-10-08 07:24 UTC, ktsirkou approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-10-08 07:31 UTC, wazelin approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2020-10-08 07:33 UTC, merged