Fix/NSA-147/layout for small screen resolution
oat-sa/tao-core pull request #2701
Opened 2020-10-08 14:03 UTC by andrey-ponamarev

**Related to task:**  https://oat-sa.atlassian.net/browse/NSA-147
**Description:**  Change layout to use flexbox model for making content available on the itesm authoring page for a small screen resolutions.
<img width="1126" alt="Screenshot 2020-10-08 at 15 20 06" src="https://user-images.githubusercontent.com/6339002/95465634-ae9bb700-097b-11eb-83be-fd4edc54f3fe.png">

**Steps to reproduce:**
1. Login as admin
2. Change the browser size to have a few rows in the header 
2. Go to Items tab
3. Create a new item and go to Authoring
4. Add any interaction to the canvas (f.e. choice) and go to response mode
5. Click "Add an outcome" button until it reaches the bottom of the sidebar

Actual result: "Add an outcome" button is not accessible

2020-10-08 14:17 UTC, bziondik reviewed
Works for me. Only one comment

2020-10-08 14:17 UTC, bziondik commented on views/scss/inc/_header-footer.scss
> +    overflow-y: scroll;
Is `overflow-y: scroll;` needed?

2020-10-08 14:22 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-10-08 15:47 UTC, adriloma approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] bumping versions are applied (if applicable)

2020-10-08 16:57 UTC, jsconan requested changes
I only made a quick check. It seems to work.
However, I'm concerned about the possible regression it will add. Especially since a permanent vertical scroll bar is added.
If the purpose is to improve the experience on small screen size, can't you consider using media query instead? This would avoid impacting everyone.

2020-10-08 16:57 UTC, jsconan commented on views/scss/inc/_header-footer.scss
> +    overflow-y: scroll;
This is adding a permanent vertical scroll bar.

2020-10-13 07:03 UTC, andrey-ponamarev commented
The issue is fixed https://github.com/oat-sa/extension-tao-itemqti/pull/1562

2020-10-13 07:03 UTC, closed without merging