- add ref to custom branch of @oat-sa/tao-core-ui
oat-sa/tao-core pull request #2718
Opened 2020-10-28 16:21 UTC by meefox

Update a version for @oat-sa/tao-core-ui for https://oat-sa.atlassian.net/browse/TR-43

2020-10-29 08:47 UTC, jsconan requested changes
We need a verion bump in the `manifest.php` file as well.
There is also an issue with the package-lock which should not commited while the package file targets a GitHub repository. This should be done only once the related package has been published to NPM and has a proper version. Otherwise, this will introduce a lock issue.

2020-10-29 08:47 UTC, jsconan commented on views/package-lock.json
> +            "from": "github:oat-sa/tao-core-ui-fe#fix/TR-43-adaptieve-size-for-checkboxes"
**issue:** caution, this will introduce a lock to github instead of npm. Once the companion PR will be merged, we'll need to delete this file as well as the node_module, and regenerate them before merge.

2020-10-29 11:39 UTC, jsconan requested changes
Looks good on the code side.
Just one remark: the dependency add changes in the SCSS, this should be compiled and the changes added to the PR as well
    ```
    cd tao/views/build
    npm grunt taosass
    ```

2020-10-30 16:19 UTC, btamas approved these changes

2020-11-04 09:54 UTC, closed without merging