Feature/CON-21/Advanced Search flag mechanism
oat-sa/tao-core pull request #2719
Opened 2020-10-29 14:24 UTC by shpran

Relates to: [CON-21](https://oat-sa.atlassian.net/browse/CON-21)

**Changes:**
* Added service and endpoint to check if Advanced Search feature enabled or not;
* Base access granted to the Advanced Search controller (action);
* Added unit test.

**How to test:**
1. Log in;
2. Open `tao/AdvancedSearch/status` route.

Default status will be `false`. To change it you need to define a `FEATURE_FLAG_ADVANCED_SEARCH` global environment variable.

2020-10-29 14:48 UTC, gabrielfs7 commented on test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
> +    public function init(): void
Why no `setUp` method?

2020-10-29 14:49 UTC, gabrielfs7 commented on test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
> +     * @param bool $expected
This is new for you, but we have an internal CR guideline. https://oat-sa.atlassian.net/wiki/spaces/NEX/pages/311492833/CR+guidelines+for+Construct

We avoid PHPdoc already represented in the type hint or return type :)

2020-10-29 14:51 UTC, gabrielfs7 commented on test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
> + */
We also do not create class docs repeating things. This is part of the process to adapt to the CR guideline, so it is totally normal :)

2020-10-29 14:51 UTC, gabrielfs7 commented on test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
> + */
Can you please update the all the classes, methods to remove those docs?

2020-10-29 14:52 UTC, shpran commented on test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
> + */
Sure :)

2020-10-29 14:53 UTC, gabrielfs7 commented on models/classes/AdvancedSearch/AdvancedSearchChecker.php
> +        $featureFlagChecker = $this->getServiceLocator()->get(FeatureFlagChecker::class);
We generally create a private method for this with proper return type instead of annotations. It leverages for native PHP validation and we can use open/close more readable (while we do not have proper DI). Wdyt?

2020-10-29 14:56 UTC, gabrielfs7 commented on models/classes/AdvancedSearch/AdvancedSearchChecker.php
> +        return $featureFlagChecker->isEnabled(self::FEATURE_FLAG_ADVANCED_SEARCH);
You need to check also if the library is installed.

2020-10-29 14:58 UTC, gabrielfs7 requested changes
Thanks @shpran, god job!

Some small issues to manage:

- Need to check if library is installed.
- Please remove unnecessary PHPDocs.

2020-10-30 07:44 UTC, gabrielfs7 commented on migrations/Version202010291229382234_tao.php
> +            TaoRoles::BASE_USER,
It might be including test-taker too? I am not sure we want this available for them too. Should it not be `TaoRoles::BACK_OFFICE`?

2020-10-30 09:16 UTC, gabrielfs7 commented on test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
> +use oat\tao\elasticsearch\ElasticSearch;
You cannot use this class here, cause the library might no be installed and tests will break.

2020-10-30 09:17 UTC, gabrielfs7 commented on test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
> +        $this->search = $this->createMock(ElasticSearch::class);
https://github.com/oat-sa/tao-core/pull/2719/files#r514961978

2020-10-30 09:18 UTC, shpran commented on test/unit/AdvancedSearch/AdvancedSearchCheckerTest.php
> +use oat\tao\elasticsearch\ElasticSearch;
Oops, sorry, forgot to change

2020-11-02 10:52 UTC, boajer commented
@shpran could you add OpenAPI schema for new endpoint

2020-11-02 11:03 UTC, gabrielfs7 commented on models/classes/AdvancedSearch/AdvancedSearchChecker.php
> +        return $this->getFeatureFlagChecker()->isEnabled(self::FEATURE_FLAG_ADVANCED_SEARCH);
By default this will be false for customers ACT, NCCER, etc. Do not you think we could have a negative flag instead to backward compatibility? I.e `FEATURE_FLAG_ADVANCED_SEARCH_DISABLED`.

Then we do not need to involve ops in the deploy process.

2020-11-02 11:04 UTC, gabrielfs7 reviewed
Good job! I left final question about deployment/devops.

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-11-03 07:18 UTC, boajer approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-11-03 13:32 UTC, bartlomiejmarszal commented on models/classes/AdvancedSearch/AdvancedSearchChecker.php
> +        return $this->getFeatureFlagChecker()->isEnabled(self::FEATURE_FLAG_ADVANCED_SEARCH);
This will lead us to double negation. I would prefer to keep as It was on a beginning so: `FEATURE_FLAG_ADVANCED_SEARCH`

2020-11-03 13:38 UTC, bartlomiejmarszal requested changes
I do not like the negative flag here. It will be confusing and will lead us to double negation in order to enable feature.

I'm missing default config here. I want to know what you would set under `OPTION_ALLOWED_SEARCH_CLASSES`.

2020-11-03 13:39 UTC, shpran commented
> I do not like the negative flag here. It will be confusing and will lead us to double negation in order to enable feature.
> 
> I'm missing default config here. I want to know what you would set under `OPTION_ALLOWED_SEARCH_CLASSES`.

We used `OPTION_ALLOWED_SEARCH_CLASSES` for unit test 😄

2020-11-03 14:19 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/AdvancedSearch/AdvancedSearchChecker.php
> +        return $this->getFeatureFlagChecker()->isEnabled(self::FEATURE_FLAG_ADVANCED_SEARCH);
my suggestion :
 - ask OPS because they will need to populate this
 - i do not think this should be a blocker for the merging of the PR
i would go for 
```
ADVANCED_SEARCH_FLAG_STATUS
```

2020-11-03 14:23 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-11-03 14:24 UTC, mike-ionut-mihai-sandu-tao commented
please don't merge to develop
the target should be the integration branch

2020-11-03 14:32 UTC, gabrielfs7 commented on models/classes/AdvancedSearch/AdvancedSearchChecker.php
> +        return $this->getFeatureFlagChecker()->isEnabled(self::FEATURE_FLAG_ADVANCED_SEARCH);
The purpose is to avoid devops cost and be compatible with current production behavior. Lets have a call later. :)

2020-11-03 14:40 UTC, shpran commented on models/classes/AdvancedSearch/AdvancedSearchChecker.php
> +        return $this->getFeatureFlagChecker()->isEnabled(self::FEATURE_FLAG_ADVANCED_SEARCH);
@gabrielfs7 @mike-ionut-mihai-sandu-tao @boajer 

As for me - both solutions are good:
* if we will use a positive flag - it will be clear for everyone how this feature works (enabled flag - enable feature, it's usual behavior for the new feature);
* if we will use a negative flag - it may confuse a little, because it looks like "This feature enabled because it's not disabled". But this flag will help us not to involve ops in the deployment process (because there is no need to define this flag for all customers).

What do you think?

2020-11-03 15:07 UTC, gabrielfs7 commented on models/classes/AdvancedSearch/AdvancedSearchChecker.php
> +        return $this->getFeatureFlagChecker()->isEnabled(self::FEATURE_FLAG_ADVANCED_SEARCH);
I would not add pipeline changes for something that was not required. Also, the double negation is common used on many application to disable default features (which is our case when elasticsearch library is installed). 

Example: Google chrome "Disable cache
![Screenshot 2020-11-03 at 16 03 14](https://user-images.githubusercontent.com/1467589/98003074-98eca680-1dee-11eb-86de-557530ced6ca.png)
"

2020-11-04 09:37 UTC, bartlomiejmarszal approved these changes
LGTM

2020-11-04 14:39 UTC, gabrielfs7 approved these changes
Code LGTM. Good job! :) 

Could we have a quick demo?

2020-11-05 08:20 UTC, merged