create resource relations proxy
oat-sa/tao-core pull request #2721
Opened 2020-10-30 10:39 UTC by gabrielfs7

- Return resources relation through an endpoint
- Create base classes to be used on specific extensions to deliver this feature.

https://oat-sa.atlassian.net/browse/CON-12

2020-11-02 08:41 UTC, shpran requested changes
Minor changes.

2020-11-02 08:41 UTC, shpran commented on models/classes/resources/relation/service/ResourceRelationServiceProxy.php
> +    use OntologyAwareTrait;
[PSR-12](https://www.php-fig.org/psr/psr-12/#42-using-traits): `The use keyword used inside the classes to implement traits MUST be declared on the next line after the opening brace.`
```suggestion
    use OntologyAwareTrait;

    public const SERVICE_ID = 'tao/ResourceRelationServiceProxy';
    public const OPTION_SERVICES = 'services';
```

2020-11-02 08:41 UTC, shpran commented on models/classes/resources/relation/service/ResourceRelationServiceProxy.php
> +        if (!in_array($serviceId, $services[$type])) {
Can we use here strict comparison?
```suggestion
        if (!in_array($serviceId, $services[$type], true)) {
```

2020-11-02 08:41 UTC, shpran commented on models/classes/resources/relation/service/ResourceRelationServiceProxy.php
> +        }
Can we store `$query->getType()` in a separate variable?
And as I see, we can call `if` statement in the first level `foreach`, WDYT?

```suggestion
        $queryType = $query->getType();

        foreach ($this->getOption(self::OPTION_SERVICES, []) as $type => $services) {
            if ($queryType === $type) {
                foreach ($services as $serviceId) {
                    /** @var ResourceRelationServiceInterface $service */
                    $service = $this->getServiceLocator()->get($serviceId);

                    $relations = array_merge(
                        $relations,
                        $service->relations($query)->getIterator()->getArrayCopy()
                    );
                }
            }
        }
```

2020-11-02 08:41 UTC, shpran commented on models/classes/resources/relation/service/ResourceRelationServiceProxy.php
> +        }
Can we store `$query->getType()` is a separate variable?
And we can move the `if` statement to the first level `foreach`, wdyt?

```suggestion
        $queryType = $query->getType();

        foreach ($this->getOption(self::OPTION_SERVICES, []) as $type => $services) {
            if ($queryType === $type) {
                foreach ($services as $serviceId) {
                    $relations = array_merge(
                        $relations,
                        $this->getResourceRelationService($serviceId)
                            ->relations($query)
                            ->getIterator()
                            ->getArrayCopy()
                    );
                }
            }
        }
```

2020-11-02 10:38 UTC, gabrielfs7 commented on models/classes/resources/relation/service/ResourceRelationServiceProxy.php
> +    use OntologyAwareTrait;
Thanks. The trait is not used anymore :)

2020-11-02 10:38 UTC, gabrielfs7 commented on models/classes/resources/relation/service/ResourceRelationServiceProxy.php
> +        if (!in_array($serviceId, $services[$type])) {
Applied, thanks!

2020-11-02 10:39 UTC, gabrielfs7 commented on models/classes/resources/relation/service/ResourceRelationServiceProxy.php
> +        }
Agree. I did a bit different! Thanks!

2020-11-02 15:19 UTC, gabrielfs7 commented on views/package.json
> +        "@oat-sa/tao-core-ui": "oat-sa/tao-core-ui-fe#feature/CON-12/confim-delete-dialog",
@bziondik Just a reminder we need to revert before merge :)

2020-11-03 07:25 UTC, boajer commented on test/unit/model/resources/relation/FindAllQueryTest.php
> +        $resourceRelation = (new FindAllQuery('sourceId', 'classId', 'item'));
```suggestion
        $resourceRelation = new FindAllQuery('sourceId', 'classId', 'item');
```

2020-11-03 07:27 UTC, bziondik reviewed
**Depends on https://github.com/oat-sa/tao-core-ui-fe/pull/204
package.json and package-lock.json should be updated**

2020-11-03 08:51 UTC, shpran approved these changes
Good job!

- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-11-03 12:29 UTC, bartlomiejmarszal approved these changes
LGTM

Please remember about changing FE version in `views/package.json`

2020-11-03 12:33 UTC, bartlomiejmarszal reviewed
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-11-03 12:44 UTC, mike-ionut-mihai-sandu-tao commented on actions/class.ResourceRelations.php
> +class tao_actions_ResourceRelations extends Controller implements ServiceLocatorAwareInterface
are you sure this name format is still mandatory ?

2020-11-03 12:44 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/resources/relation/ResourceRelation.php
> +            'label' => $this->label ?? '',
why the default is empty string but the object construct has null ?

2020-11-03 12:44 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/resources/relation/ResourceRelationCollection.php
> +        $this->relations[] = $relation;
does it worth to index this for a quicker retrieval ?

2020-11-03 12:44 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/resources/relation/exception/NestedClassLimitExceededException.php
> +    private const ERROR_CODE = 999;
why 999 , can you add some description to that :)

2020-11-03 12:44 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/resources/relation/service/ResourceRelationServiceInterface.php
> +    public function relations(FindAllQuery $query): ResourceRelationCollection;
don't fully like the name , but i can live with this generic approach

2020-11-03 12:44 UTC, mike-ionut-mihai-sandu-tao commented on views/package.json
> +        "@oat-sa/tao-core-ui": "github:oat-sa/tao-core-ui-fe#feature/CON-12/confim-delete-dialog",
this will go to develop, are you sure we should use a branch ?

2020-11-03 12:53 UTC, gabrielfs7 commented on models/classes/resources/relation/ResourceRelation.php
> +            'label' => $this->label ?? '',
To keep compatibility with previous code. It was like this on media manager before. I did not want to change it in the PR.

2020-11-03 12:54 UTC, bartlomiejmarszal commented on models/classes/resources/relation/exception/NestedClassLimitExceededException.php
> +    private const ERROR_CODE = 999;
It was accepted in my PR back then when we commit it in Media Manager

2020-11-03 12:55 UTC, gabrielfs7 commented on models/classes/resources/relation/ResourceRelationCollection.php
> +        $this->relations[] = $relation;
I am not sure I understood. What do you mean by index? 

This code was moved from media manager to here, I did not want to change behavior on this PR, but if it will not break compatibility I can add an improvement. Just need to understand. :) 

This is basically used to aggregate the results today how could it increase performance now?

2020-11-03 12:56 UTC, gabrielfs7 commented on models/classes/resources/relation/exception/NestedClassLimitExceededException.php
> +    private const ERROR_CODE = 999;
Also moved from media manager to here. There, there was no comment. I can add here.

2020-11-03 12:58 UTC, gabrielfs7 commented on models/classes/resources/relation/service/ResourceRelationServiceInterface.php
> +    public function relations(FindAllQuery $query): ResourceRelationCollection;
You can suggest a name and I can change. Not a problem :) 

`getRelations`?

2020-11-03 12:58 UTC, gabrielfs7 commented on views/package.json
> +        "@oat-sa/tao-core-ui": "github:oat-sa/tao-core-ui-fe#feature/CON-12/confim-delete-dialog",
Yes. I put a comment to not forget about this too: https://github.com/oat-sa/tao-core/pull/2721#discussion_r516044402 :)

2020-11-03 13:24 UTC, gabrielfs7 commented on actions/class.ResourceRelations.php
> +class tao_actions_ResourceRelations extends Controller implements ServiceLocatorAwareInterface
All the controllers on `tao` are using these names. As far as I know, if I want to change name I need to map in the `structure.xml`, otherwise is not possible to set the ACL with new controller. Should we do this change now? This will be the first controller?

2020-11-03 14:05 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/resources/relation/service/ResourceRelationServiceInterface.php
> +    public function relations(FindAllQuery $query): ResourceRelationCollection;
yes

2020-11-03 14:06 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-11-03 14:33 UTC, gabrielfs7 commented on models/classes/resources/relation/ResourceRelationCollection.php
> +        $this->relations[] = $relation;
As discussed. Now we do not need information indexed, so I will keep as it was before.

2020-11-03 14:34 UTC, gabrielfs7 commented on actions/class.ResourceRelations.php
> +class tao_actions_ResourceRelations extends Controller implements ServiceLocatorAwareInterface
As we discussed, all controllers are like this on tao-core and I used to be consistent and support current ACL.

2020-11-04 08:53 UTC, gabrielfs7 commented on views/package.json
> +        "@oat-sa/tao-core-ui": "github:oat-sa/tao-core-ui-fe#feature/CON-12/confim-delete-dialog",
@bziondik did :)

2020-11-04 08:53 UTC, merged