Feature/cgf 23/improve error reporting during tao update
oat-sa/tao-core pull request #2727
Opened 2020-11-05 10:10 UTC by AndreyNegrov

**Related to task:**  https://oat-sa.atlassian.net/browse/CGF-23
**Description:** Improve error reporting during taoUpdate
**How to test:**

2020-11-30 09:48 UTC, Alroniks requested changes
The first round of review is finished, some issues should be addressed.

2020-11-30 09:48 UTC, Alroniks commented on models/classes/notifiers/Notifier.php
> +interface Notifier
```suggestion
interface NotifierInterface
```
According to https://www.php-fig.org/bylaws/psr-naming-conventions/
Also, file should be renamed due to PSR-4.

2020-11-30 09:48 UTC, Alroniks commented on models/classes/notifiers/OpsGenieNotifier.php
> +    const OPTION_BASE_URI = 'https://api.opsgenie.com/v2/';
Access modifier missed. Also, in other places too.

2020-11-30 09:48 UTC, Alroniks commented on models/classes/notifiers/OpsGenieNotifier.php
> +    public function notify(string $title, string $description, array $parameters = []): array
I am not sure that we have to have the ability to configure the behavior of the driver in such straightway. It should encapsulate how it dealing with a provider, the client (like service) shouldn't know about driver internal things.

2020-11-30 09:48 UTC, Alroniks commented on config/default/updatingNotificationService.conf.php
> +    'notifiers' => []
As we provide it without any drivers configured, need to provide examples in comments. In TAO we use headers in config folders for such things. Please, check examples in the code.

2020-11-30 09:48 UTC, Alroniks commented on models/classes/extension/UpdatingNotificationService.php
> +class UpdatingNotificationService extends ConfigurableService
I think that we have to provide abstract Service and inherit it because seems that code will be similar for all.

2020-12-30 13:47 UTC, hutnikau requested changes

2020-12-30 13:47 UTC, hutnikau commented on models/classes/extension/AbstractNotificationService.php
> + * Class TaoUpdateNotifier
please fix the phpdoc

2020-12-30 13:47 UTC, hutnikau commented on models/classes/extension/UpdatingNotificationService.php
> +class UpdatingNotificationService extends AbstractNotificationService
May we rename this class to `AlarmNotificationService`?

2021-01-06 12:16 UTC, hutnikau requested changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-01-06 13:26 UTC, hutnikau approved these changes

2021-01-11 10:53 UTC, merged