Feature/con 134/search modal universal query
oat-sa/tao-core pull request #2735
Opened 2020-11-16 10:16 UTC by bartlomiejmarszal

# searchAction enpoint modyfication 
 
Introducing proxies and bridges in order to properly pass search requests. 

## Ticket related
https://oat-sa.atlassian.net/browse/CON-134

2020-11-16 12:52 UTC, shpran requested changes
There are some CS comments.
Everything else looks fine 👍🏻

2020-11-16 12:52 UTC, shpran commented on models/classes/search/GenerisSearchBridge.php
> +}
```suggestion
}

```

2020-11-16 12:52 UTC, shpran commented on models/classes/search/SearchBridgeInterface.php
> +}
```suggestion
declare(strict_types=1);

namespace oat\tao\model\search;

interface SearchBridgeInterface
{
    public function search(SearchQuery $query): ResultSet;
}

```

2020-11-16 12:52 UTC, shpran commented on models/classes/search/SearchProxy.php
> +        if (!$this->getElasticSearchChecker()->isEnabled()) {
```suggestion
        } else {
```

2020-11-16 12:52 UTC, shpran commented on models/classes/search/SearchProxy.php
> +        $page = isset($request->getQueryParams()['page']) ? (int)$request->getQueryParams()['page'] : 1;
Should we keep space after type cast or not?
Wdyt?

2020-11-16 12:52 UTC, shpran commented on models/classes/search/SearchProxy.php
> +        $totalPages = is_null($rows) ? 1 : ceil($results->getTotalCount() / $rows);
There will be an error if `$rows = 0` (Division by zero).

2020-11-16 12:52 UTC, shpran commented on models/classes/search/SearchProxy.php
> +}
```suggestion
    private function getElasticSearchChecker(): AdvancedSearchChecker
    {
        return $this->getServiceLocator()->get(AdvancedSearchChecker::class);
    }

    private function getElasticSearchBridge(): ElasticSearchBridge
    {
        return $this->getServiceLocator()->get(ElasticSearchBridge::class);
    }

    private function getGenerisSearchBridge(): GenerisSearchBridge
    {
        return $this->getServiceLocator()->get(GenerisSearchBridge::class);
    }

    private function getQueryFactory(): SearchQueryFactory
    {
        return $this->getServiceLocator()->get(SearchQueryFactory::class);
    }
}

```

2020-11-16 12:52 UTC, shpran commented on models/classes/search/SearchQuery.php
> + */
```suggestion
 */
 
declare(strict_types=1);
```

2020-11-16 12:52 UTC, shpran commented on models/classes/search/SearchQuery.php
> +    {
```suggestion
    public function __construct(
        string $term,
        string $rootClass,
        string $parentClass,
        int $startRow,
        int $rows = null,
        int $page = null
    ) {
```

2020-11-16 12:52 UTC, shpran commented on models/classes/search/SearchQuery.php
> +}
```suggestion
}

```

2020-11-16 12:52 UTC, shpran commented on models/classes/search/SearchQueryFactory.php
> +}
```suggestion
}

```

2020-11-16 12:52 UTC, shpran commented on test/unit/models/classes/search/ElasticSearchBridgeTest.php
> +            1);
```suggestion
        $query = new SearchQuery(
            'user input',
            'rootClass',
            'parentClass',
            1,
            10,
            1
        );
```

2020-11-16 12:52 UTC, shpran commented on test/unit/models/classes/search/GenerisSearchBridgeTest.php
> +
```suggestion

```

2020-11-16 12:52 UTC, shpran commented on test/unit/models/classes/search/GenerisSearchBridgeTest.php
> +            1);
```suggestion
        $query = new SearchQuery(
            'user input',
            'rootClass',
            'parentClass',
            1,
            10,
            1
        );
```

2020-11-16 12:52 UTC, shpran commented on test/unit/models/classes/search/SearchQueryTest.php
> +}
```suggestion
    }
}
```

2020-11-16 13:41 UTC, bartlomiejmarszal commented on models/classes/search/SearchProxy.php
> +        if (!$this->getElasticSearchChecker()->isEnabled()) {
I' not a fan of using `else` in this case.

2020-11-16 13:46 UTC, shpran commented on models/classes/search/SearchProxy.php
> +        if (!$this->getElasticSearchChecker()->isEnabled()) {
So you can store `$this->getElasticSearchChecker()->isEnabled()` in a separate variable and use it to avoid second call.
Is it make sense?

2020-11-16 14:20 UTC, gabrielfs7 commented on models/classes/search/SearchProxy.php
> +        if (!$this->getElasticSearchChecker()->isEnabled()) {
You can always avoid else and make your code cleaner and simpler: https://williamdurand.fr/2013/06/03/object-calisthenics/#2-dont-use-the-else-keyword

I agree with @shpran that we can store it in a $var to avoid double call :) But I strongly suggest a separated method instead:


```
private function executeSearch()
{
    if ($this->getElasticSearchChecker()->isEnabled()) {
        return $this->getElasticSearchBridge()->search($query);
    }

    return $this->getGenerisSearchBridge()->search($query);
}
```

So you not even need the variable anymore :)

2020-11-16 14:22 UTC, gabrielfs7 commented on models/classes/search/SearchProxy.php
> +        $page = isset($request->getQueryParams()['page']) ? (int)$request->getQueryParams()['page'] : 1;
@bartlomiejmarszal  You already have this on the SearchQuery object `$query`.  No need to do it again :)

2020-11-16 14:23 UTC, gabrielfs7 commented on models/classes/search/SearchProxy.php
> +    public function search(ServerRequestInterface $request): array
Can we return a proper Psr7 response instead? Wdyt?

2020-11-16 14:26 UTC, gabrielfs7 commented on models/classes/search/SearchProxy.php
> +        $resultsRaw = $results->getArrayCopy();
I think convert the `ResultSet` to an normalized array should be responsibility of another class. Example:

```
class ResultSetNormalizer
{
    public function normalize(ResultSet $resuls, SearchQuery $query): array
    {
        // all the content from line 57 to 107 here
    }
}
```

@bartlomiejmarszal Do not you think it is better?

2020-11-16 14:27 UTC, gabrielfs7 commented on models/classes/search/SearchProxy.php
> +}
@shpran what is the change here?

2020-11-16 14:28 UTC, gabrielfs7 commented on models/classes/search/SearchQueryFactory.php
> +    public function createSearchQuery(ServerRequestInterface $request): SearchQuery
```suggestion
    public function create(ServerRequestInterface $request): SearchQuery
```

It is already a `SearchQuery` factory :)

2020-11-16 14:29 UTC, gabrielfs7 reviewed
Good job! Some comments about code improvement :) 

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-11-16 14:50 UTC, bartlomiejmarszal commented on models/classes/search/SearchProxy.php
> +        $resultsRaw = $results->getArrayCopy();
I would like to redefine how we using this endpoint in order to provide a JSON result set. This code that you intent to separate requires some work.

2020-11-16 14:52 UTC, bartlomiejmarszal commented on models/classes/search/SearchProxy.php
> +    public function search(ServerRequestInterface $request): array
Yes, I would like to do that but unfortunately, it is strictly coupled with deprecated `returnJson`. We should tackle this in the new ticket.

2020-11-19 08:47 UTC, shpran approved these changes
Please, don't forget about unnecessary empty lines and newline at end of file 😄 
Good job 👍🏻 

- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-11-19 08:47 UTC, shpran commented on models/classes/search/ResultSetResponseNormalizer.php
> +use oat\generis\model\data\permission\PermissionHelper;
```suggestion
<?php

/**
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; under version 2
 * of the License (non-upgradable).
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 *
 * Copyright (c) 2020 (original work) Open Assessment Technologies SA;
 */

declare(strict_types=1);

namespace oat\tao\model\search;

use oat\generis\model\data\permission\PermissionHelper;
```

2020-11-19 08:47 UTC, shpran commented on models/classes/search/ResultSetResponseNormalizer.php
> +}
```suggestion
}

```

2020-11-19 10:41 UTC, boajer commented on models/classes/search/ResultSetResponseNormalizer.php
> +            : ceil($resultSet->getTotalCount() / $searchQuery->getRows());
Could you move value of `$searchQuery->getRows()` into the separate variable, it's called 3 times in a row

2020-11-19 10:45 UTC, boajer commented on models/classes/search/ResultSetResponseNormalizer.php
> +        $response['records'] = $resultAmount;
Just a flavor, but WDYT instead of composing response field by field directly into the `$response` across all the method, to change this into something like

```
$response = [
         'data' => $data,
         'readonly' =>$readonly, 
         ...
         'total'=> $totalPages,
         'totalCount' => $resultSet->getTotalCount(),
         ...
];
```
To give immediate overview on what we are actually returning

2020-11-19 10:51 UTC, boajer reviewed
Great Job! A few minor comments, from me, in addition, could you verify all the phpdoc\copyright section is in place and run PSR formatter against new code

- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-11-19 16:14 UTC, bartlomiejmarszal commented on models/classes/search/ResultSetResponseNormalizer.php
> +        $response['records'] = $resultAmount;
I expect this part of this class to be refactored so we will not need this normalizer anymore. I copy paste all code related to this and replace stdClass with associated array.

2020-11-19 16:15 UTC, bartlomiejmarszal commented on models/classes/search/ResultSetResponseNormalizer.php
> +            : ceil($resultSet->getTotalCount() / $searchQuery->getRows());
https://github.com/oat-sa/tao-core/pull/2735#discussion_r527013389

2020-11-19 20:21 UTC, gabrielfs7 commented on models/classes/search/ResultSetResponseNormalizer.php
> +
```suggestion
```

2020-11-19 20:22 UTC, gabrielfs7 commented on models/classes/search/ResultSetResponseNormalizer.php
> +
```suggestion
```

2020-11-19 20:23 UTC, gabrielfs7 commented on test/unit/models/classes/search/SearchProxyTest.php
> +
```suggestion

```

2020-11-19 20:27 UTC, gabrielfs7 commented on test/unit/models/classes/search/SearchQueryFactoryTest.php
> +        $this->expectException(CreateSearchQueryException::class);
You actually have two validations here, but only one test. I also recommend to add the message pattern to distinguish. Wdyt?

2020-11-19 20:29 UTC, gabrielfs7 approved these changes
Good job! Can you do a demo tomorrow?

2020-11-20 12:49 UTC, merged