Feature/CON-76/advance search in result page
oat-sa/tao-core pull request #2743
Opened 2020-11-26 13:38 UTC by bziondik

2020-11-27 15:30 UTC, bziondik commented on views/js/layout/search.js
> +                    data.result ||
@bartlomiejmarszal I assumed that I will have in response `result` filed with delivery result id

2020-11-30 13:17 UTC, habemuscode approved these changes
Code review only

2020-12-02 10:34 UTC, bziondik commented on config/default/ResultSetMapper.conf.php
> +                'results' => [
@bartlomiejmarszal please, update `label` for all `'label' => __('Delivery'),`, add `Delivery URI` as we discussed, and `Start Time`
```'delivery' => array(
                'id' => 'delivery',
                'label' => 'Delivery Uri',
                'sortable' => false,
                'visible' => false)
```
and change order according mockup - first will be `Test Taker Name`

2020-12-02 10:35 UTC, bziondik commented on migrations/Version202011301939462234_tao.php
> +                ResultSetMapper::OPTION_STRUCTURE_MAP =>
Can we use here `config/default/ResultSetMapper.conf.php`?

2020-12-02 12:18 UTC, adriloma approved these changes
FE review only. Notice my comment on `package.json`

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] bumping versions are applied (if applicable)

2020-12-02 15:31 UTC, habemuscode approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] bumping versions are applied (if applicable)

2020-12-03 08:36 UTC, shpran reviewed
Looks good. 👍🏻 
Minor cs comments :)

2020-12-03 08:36 UTC, shpran commented on config/default/ResultSetMapper.conf.php
> +        ResultSetMapper::OPTION_STRUCTURE_MAP =>
I think it's better to not move the open parenthesis to the next line.
So, instead of:
```
ResultSetMapper::OPTION_STRUCTURE_MAP =>
    [
        ... code ...
    ]
```
use this one:
```
ResultSetMapper::OPTION_STRUCTURE_MAP => [
    ... code ...
]

2020-12-03 08:36 UTC, shpran commented on migrations/Version202011301939462234_tao.php
> +                ResultSetMapper::OPTION_STRUCTURE_MAP =>
Same

2020-12-03 08:36 UTC, shpran commented on models/classes/search/ResultSetMapper.php
> +        return $map['default'];
```suggestion
        return $map[$structure] ?? $map['default'];
```

2020-12-03 08:36 UTC, shpran commented on models/classes/search/ResultSetResponseNormalizer.php
> +                $response['data'] = $instanceProperties;
This block looks a bit strange for me.
WDYT about this?
```
$response['data'][] = $this->getResultSetMapper()->getResultSetModel($content, $structure);
```

2020-12-03 08:39 UTC, gabrielfs7 commented on config/default/ResultSetMapper.conf.php
> +        ResultSetMapper::OPTION_STRUCTURE_MAP =>
This is also PSR recommendation. I agree with @shpran

2020-12-03 08:41 UTC, gabrielfs7 commented on config/default/ResultSetMapper.conf.php
> +return new ResultSetMapper(
I am wondering why this needs to be configurable? If I change this, most probably a custom extesion / layout would have to be applied. I would not open this to be configurable outside right now.

2020-12-03 08:46 UTC, gabrielfs7 commented on models/classes/search/ResultSetMapper.php
> +    public function getPromiseModel(string $structure)
Do you think a `mapper`, that should only `map` should have methods like `getPromiseModel` or `getResultSetModel`? 

Should it not have the method `map` instead?

2020-12-03 08:47 UTC, gabrielfs7 requested changes
SRP violated on `ResultSetMapper`

2020-12-03 13:31 UTC, bartlomiejmarszal commented on config/default/ResultSetMapper.conf.php
> +return new ResultSetMapper(
I can move configuration to internal const variables. 
Yes. 

I think base on multiple extensions we may want to introduce additional indexation also over non-resource content 
(I mean other then Groups, Tests, Items etc). 

At this moment we are indexing this way `delivery-results` only but I expect that we will extend this in the future. 

If we keep our result set configurable we will have control over what we want to display in `searchModal` result data table. 

Having configurable service allow us to quickly extend our search result set to our needs.

2020-12-03 14:15 UTC, shpran commented on models/classes/search/ResultSetMapper.php
> +        $allowedKeys = $map[$structure] ?? $map['default'];
To avoid code duplication we can replace this with `getPromiseModel` method call:
```
$allowedKeys = $this->getPromiseModel($structure);
```
Wdyt?

2020-12-03 14:17 UTC, bartlomiejmarszal commented on migrations/Version202011301939462234_tao.php
> +                ResultSetMapper::OPTION_STRUCTURE_MAP =>
I don't think I can use this file here. @boajer @mike-ionut-mihai-sandu-tao ?

2020-12-03 14:24 UTC, bartlomiejmarszal commented on config/default/ResultSetMapper.conf.php
> +                'results' => [
I think I fix all this changes. Can you have a look?

2020-12-03 14:39 UTC, gabrielfs7 commented on config/default/ResultSetMapper.conf.php
> +return new ResultSetMapper(
I agree, but it seems this configuration is not enough. We have to do several changes in the FE to add new indexes and search criteria. I am more concerned about this https://github.com/oat-sa/tao-core/pull/2743#discussion_r534939705 to be honest.

2020-12-03 15:30 UTC, bartlomiejmarszal commented on models/classes/search/ResultSetMapper.php
> +    public function getPromiseModel(string $structure)
`ResultSetModelBuilder`?

2020-12-04 15:51 UTC, mike-ionut-mihai-sandu-tao commented on migrations/Version202011301939462234_tao.php
> +                ResultSetMapper::OPTION_STRUCTURE_MAP =>
if you want to have this inside a specific place you could technically doing but i don't see the benefits of that

2020-12-04 15:51 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/Lists/Business/Service/ClassMetadataService.php
> +            if (!$this->isWidget($property)) {
are you sure we need this extra check ? 
we are checking 
```
if (!$this->isTextWidget($property) && !$this->isListWidget($property)) {
```

2020-12-04 15:51 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/Lists/Business/Service/ClassMetadataService.php
> +    private function isWidget(core_kernel_classes_Property $property): bool
i am not sure that we need this and that this is not available anyware

2020-12-04 15:51 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/search/ResultSetFilter.php
> +            return $key === 'id' || in_array($key, array_keys($allowedKeys));
maybe add 3rd element to 
```
in_array
```

2020-12-04 15:53 UTC, bartlomiejmarszal commented on models/classes/Lists/Business/Service/ClassMetadataService.php
> +            if (!$this->isWidget($property)) {
This was causing an error when Item property did not have `getWidget` set. I fix this error in our PR.

2020-12-04 15:54 UTC, bartlomiejmarszal commented on models/classes/Lists/Business/Service/ClassMetadataService.php
> +    private function isWidget(core_kernel_classes_Property $property): bool
This is solution of an error when Item property did not have getWidget set. I fix this error in our PR.

2020-12-07 07:20 UTC, gabrielfs7 commented on models/classes/search/ResultSetMapper.php
> +        }
Do you think we should return a map for an undesired structure because advanced search is not active? I saw the default one contains label, but what if we add another field or the result you are mapping does not have label?

Should not we have a `default` map per each type of structure instead? This is not extensible and will cause issues if fields change. I recommend change the mapping to something like:


```
                'results' => 
                    'default' => [
                        'label' => [
                            'id' => 'label',
                            'label' => __('Label'),
                            'sortable' => false
                        ],
                    ],
                    'advanced' => [
                        'label' => [
                            'id' => 'label',
                            'label' => __('Label'),
                            'sortable' => false
                        ],
                        'test_taker_name' => [
                            'id' => 'test_taker_name',
                            'label' => __('Test Taker'),
                            'sortable' => false
                        ],
                        'test_taker' => [
                            'id' => 'test_taker',
                            'label' => __('Test Taker'),
                            'sortable' => false
                        ],
                    ]
```

And then you can do something like this to get the results:

```
if (!$this->getAdvancedSearchChecker()->isEnabled()) {
    return $map[$structure]['default'] ?? [];
}

return $map[$structure]['advanced'] ?? [];
```

2020-12-07 07:21 UTC, gabrielfs7 commented on migrations/Version202011301939462234_tao.php
> +                ResultSetMapper::OPTION_STRUCTURE_MAP => [
I left a comment here. The result mapping default should be done by subject to avoid coupling among all different result types we will have:

https://github.com/oat-sa/tao-core/pull/2743/files#r537280131

2020-12-07 07:27 UTC, gabrielfs7 commented on models/classes/search/ResultSetResponseNormalizer.php
> +                    continue;
Now the results with `Access Denied` will never be added for the result and it will cause broken lists. Does business agree with that? It is changing the behavior and interface.

If they agree, we also do not need then to have this line:

```
$content['label'][] = __('Access Denied');
```

...cause is never used. But I am afraid we should have same amount of results per page.

2020-12-07 07:28 UTC, gabrielfs7 requested changes
Inconsistence in the results as it was before and also coupled result mapping should change

2020-12-07 07:33 UTC, gabrielfs7 commented on models/classes/search/ResultSetResponseNormalizer.php
> +    public function normalize(SearchQuery $searchQuery, ResultSet $resultSet, string $structure): array
$structure should be identified by the `ResultSet` object IMO. They are interdependent therefore should contain this info.

2020-12-07 07:35 UTC, gabrielfs7 commented on test/unit/models/classes/search/ResultSetFilterTest.php
> +}
```suggestion
}

```

2020-12-07 07:37 UTC, gabrielfs7 commented on models/classes/search/ResultSetFilter.php
> +        }, ARRAY_FILTER_USE_KEY);
```suggestion
        return array_filter(
            $content, 
            function ($key) use ($allowedKeys) {
                return $key === 'id' || in_array($key, array_keys($allowedKeys), true);
            }, 
            ARRAY_FILTER_USE_KEY
        );
```

Please, apply PSR-12.

When breaking lines to pass parameters to a function, every parameter should be in a new line.

2020-12-07 08:05 UTC, shpran commented on models/classes/search/ResultSetFilter.php
> +        }, ARRAY_FILTER_USE_KEY);
This part is OK in my opinion. :)
You can find the same "breaking lines" in [PSR-12](https://www.php-fig.org/psr/psr-12/#47-method-and-function-calls):
```
somefunction($foo, $bar, [
  // ...
], $baz);

$app->get('/hello/{name}', function ($name) use ($app) {
    return 'Hello ' . $app->escape($name);
});
```

2020-12-07 08:32 UTC, bartlomiejmarszal commented on models/classes/search/ResultSetMapper.php
> +        }
When elastic search is not enabled we are using GenerisSearch to search over the labels. This means that we always have labels and we can assume that it is default model when elastic search is not enabled.

2020-12-07 08:50 UTC, gabrielfs7 commented on models/classes/search/ResultSetFilter.php
> +        }, ARRAY_FILTER_USE_KEY);
It is not ok, there are 2 arguments here. read it: 

```
Argument lists MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one argument per line
```

2020-12-07 08:53 UTC, gabrielfs7 commented on models/classes/search/ResultSetMapper.php
> +        }
You can assume, but if you search over generis URI or other fields we have issues. It is for the sake of extensibility and maintainability.

2020-12-07 08:56 UTC, shpran commented on models/classes/search/ResultSetFilter.php
> +        }, ARRAY_FILTER_USE_KEY);
Take a look on this example:
![image](https://user-images.githubusercontent.com/59471572/101330002-29515780-3883-11eb-9d0d-d8081a91cc23.png)

2020-12-07 09:47 UTC, bartlomiejmarszal commented on models/classes/search/ResultSetResponseNormalizer.php
> +    public function normalize(SearchQuery $searchQuery, ResultSet $resultSet, string $structure): array
We can set  structure string as a type of `ResultSet`

2020-12-07 10:03 UTC, gabrielfs7 commented on models/classes/search/ResultSetFilter.php
> +        }, ARRAY_FILTER_USE_KEY);
@shpran Yes, this is "optional" for anonymous functions and arrays, but honestly do you think it makes sense to have such different approaches?  This contradicts the first sentence.

```
When doing so, the first item in the list MUST be on the next line, and there MUST be only one argument per line
```

For me is worse to read like this. It takes time to understand what is parameter for the anonymous function and what is not.

2020-12-07 11:49 UTC, bartlomiejmarszal commented on models/classes/search/ResultSetMapper.php
> +        }
https://github.com/oat-sa/tao-core/pull/2743/commits/4e60e857c029e27543e379224371c4279964b058
Is this solving your comment?

2020-12-07 11:49 UTC, bartlomiejmarszal commented on migrations/Version202011301939462234_tao.php
> +                ResultSetMapper::OPTION_STRUCTURE_MAP => [
https://github.com/oat-sa/tao-core/pull/2743/commits/4e60e857c029e27543e379224371c4279964b058

2020-12-08 12:23 UTC, gabrielfs7 commented on actions/class.Search.php
> +                'structure' => $parsedBody['structure'],
Why structure of result response is part of the query provided by enduser?

2020-12-08 12:24 UTC, gabrielfs7 commented on migrations/Version202011301939462234_tao.php
> +                    'results' => [
This needs to be fixed as here: https://github.com/oat-sa/tao-core/pull/2743/files#diff-5de033e84d58407715598c1bd76c5d4051a24e962bbf891dcdb47785110cc2bbR15

2020-12-08 12:26 UTC, gabrielfs7 commented on models/classes/search/SearchQueryFactory.php
> +            $params['params']['structure'],
Will it work as it was before? You used the root node for generis query, no?

2020-12-08 12:26 UTC, gabrielfs7 commented on test/unit/models/classes/search/ResultSetFilterTest.php
> +    public function testGetResultSetModel(array $resultDataSet, string $structure, array $filteredResults, array $map): void
Inconsistent test name

2020-12-08 12:27 UTC, gabrielfs7 commented on test/unit/models/classes/search/ResultSetFilterTest.php
> +    public function getResultSetData()
```suggestion
    public function getResultSetData(): array
```

2020-12-08 12:28 UTC, gabrielfs7 commented on test/unit/models/classes/search/ResultSetFilterTest.php
> +                'results',
SHould not this be compatible with new format (with `default` and `advanced` indexes)?

2020-12-09 15:38 UTC, bartlomiejmarszal commented on test/unit/models/classes/search/ResultSetFilterTest.php
> +                'results',
In this test its is not relevant. It's relevant only in `ResultSetMapperTest`

2020-12-09 15:41 UTC, bartlomiejmarszal commented on models/classes/search/SearchQueryFactory.php
> +            $params['params']['structure'],
this attribute is relevant only for elastic search query. Gerneris search is taking parent node as a type:
`\oat\tao\model\search\GenerisSearchBridge::search` root node is not involved here.

2020-12-09 15:48 UTC, bartlomiejmarszal commented on actions/class.Search.php
> +                'structure' => $parsedBody['structure'],
This is not provided by enduser. This string is generated by FE. It's referring to tab that we want to perform search query.

2020-12-09 15:49 UTC, bartlomiejmarszal commented on models/classes/search/ResultSetFilter.php
> +        }, ARRAY_FILTER_USE_KEY);
Can I resolve this comment or you suggest to apply some changes here?

2020-12-09 15:54 UTC, gabrielfs7 commented on actions/class.Search.php
> +                'structure' => $parsedBody['structure'],
FE in this case is the user, cause enduser uses FE to reach us. But, is a `structure` of mapping representing the `tab` a good reference? 

Do not you think a more generic/agnostic name i.e `searchType` would fit better? When you read structure what do you think this is about?

2020-12-09 15:55 UTC, gabrielfs7 commented on models/classes/search/SearchQueryFactory.php
> +            $params['params']['structure'],
So how will this query still work for elastic search? Are you providing this in another way? The `SearchQuery` should be agnostic of search engine. Could you help me understand how it is working now?

2020-12-09 16:00 UTC, gabrielfs7 approved these changes
I think there are other things that could be done, but only my opinion. 

Approved! Good job! :)

2020-12-09 16:01 UTC, gabrielfs7 commented on models/classes/search/ResultSetFilter.php
> +        }, ARRAY_FILTER_USE_KEY);
I think nobody has issues with this format of coding except me, so I am closing :)

2020-12-10 09:24 UTC, merged