Interface reflects support of pagination for media resources loading
oat-sa/tao-core pull request #2747
Opened 2020-12-09 20:21 UTC by boajer

2020-12-10 13:25 UTC, gabrielfs7 commented on models/classes/media/MediaBrowser.php
> +        int $offset = 0
Could we have a more explanatory name for these parameters? Cause we return a single directory here and now we have `limit` and `offset`. What is the limit and offset for response of a `single` directory? It is `childrenLimit` and `childrenOffset`? 

Do you think this belongs to this interface?

2020-12-10 13:27 UTC, gabrielfs7 commented on manifest.php
> +    'version' => '46.9.0',
This is a breaking change and we should avoid it. I suggest create a new method in another interface and receiving proper parameters and object as response.

2020-12-10 13:28 UTC, gabrielfs7 requested changes
We should avoid breaking changes and use deprecation instead. Also some comments about the approach used to solve the problem.

2020-12-10 13:52 UTC, shpran approved these changes
1 minor cs comment
Well done 👍🏻 

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-12-10 13:52 UTC, shpran commented on models/classes/media/sourceStrategy/HttpSource.php
>      {
[PSR-12](https://www.php-fig.org/psr/psr-2/#44-method-arguments): `When the argument list is split across multiple lines, the closing parenthesis and opening brace MUST be placed together on their own line with one space between them.`
```suggestion
    ): array {
```

2020-12-15 08:42 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-12-15 09:43 UTC, bartlomiejmarszal requested changes
What happen in HttpSource?

2020-12-15 09:43 UTC, bartlomiejmarszal commented on models/classes/media/sourceStrategy/HttpSource.php
> + * Copyright (c) 2015-2020 (original work) Open Assessment Technologies SA;
There is no functional changes here. Why you included this in the PR?

2020-12-15 09:43 UTC, bartlomiejmarszal commented on models/classes/media/sourceStrategy/HttpSource.php
> +        throw new common_Exception('Unable to browse the internet');
Wait, what?

2020-12-15 09:43 UTC, bartlomiejmarszal commented on models/classes/media/sourceStrategy/HttpSource.php
> +        throw new common_Exception('Unable to browse the internet');
Not following, can you explain me this?

2020-12-15 09:43 UTC, bartlomiejmarszal commented on models/classes/media/mediaSource/QueryObject.php
> +     * @var string
Didn't we agree to use one liner annotations?

2020-12-15 11:10 UTC, boajer commented on models/classes/media/sourceStrategy/HttpSource.php
> + * Copyright (c) 2015-2020 (original work) Open Assessment Technologies SA;
This class implements changed interface, so was changed to comply with it

https://github.com/oat-sa/tao-core/pull/2747/files#diff-05ca634d455288c38e2cb9556c48f6f89f6e23c4619ee6f3e668fae082530599R32

2020-12-15 11:12 UTC, boajer commented on models/classes/media/sourceStrategy/HttpSource.php
> +        throw new common_Exception('Unable to browse the internet');
Could you elaborate, what do you mean? 

New method mimics behavior of the old one, if you have better suggestion about exception text, please  make it, I've kept it same to have same behavior

2020-12-15 11:12 UTC, boajer commented on models/classes/media/sourceStrategy/HttpSource.php
> +        throw new common_Exception('Unable to browse the internet');
Could you elaborate, what do you mean?

2020-12-15 14:14 UTC, bartlomiejmarszal commented on models/classes/media/sourceStrategy/HttpSource.php
> +        throw new common_Exception('Unable to browse the internet');
Why `getDirectories` method can only throw an error? 
Also a message in this errors seems odd. Am I missing smoothing obvious?

2020-12-16 14:37 UTC, gabrielfs7 commented on models/classes/media/mediaSource/DirectorySearchQuery.php
> +    private $itemUri;
According to our standards:

```suggestion
    /** @var string */
    private $parentLink;
    
    /** @var array */
    private $filter;
    
    /** @var int */
    private $depth;
    
    /** @var int */
    private $childrenLimit;
    
    /** @var int */
    private $childrenOffset;
    
    /** @var MediaAsset */
    private $asset;
    
    /** @var string */
    private $itemLang;
    
    /** @var string */
    private $itemUri;
```

2020-12-16 14:41 UTC, gabrielfs7 commented on test/unit/models/classes/media/mediaSource/QueryObjectTest.php
> +class QueryObjectTest extends TestCase
Rename file too, please :) 

```suggestion
class DirectorySearchQueryTest extends TestCase
```

2020-12-16 14:41 UTC, gabrielfs7 commented on test/unit/models/classes/media/mediaSource/QueryObjectTest.php
> +
```suggestion
```

2020-12-16 14:51 UTC, gabrielfs7 commented on models/classes/media/sourceStrategy/HttpSource.php
> +        return $this->getDirectory($params->getParentLink());
Not really required the parameter.

```suggestion
        return $this->getDirectory();
```

2020-12-16 14:51 UTC, gabrielfs7 commented on views/package.json
> +        "@oat-sa/tao-core-ui": "git://github.com/oat-sa/tao-core-ui-fe#feature/CON-185/chunk-loading-resource-manager",
Please, do not forget to change before merge :)

2020-12-16 14:54 UTC, mike-ionut-mihai-sandu-tao reviewed
a few things :
  - the QueryObjectTest need to be called as per the class your testing DirectorySearchQuery
  -  @oat-sa/tao-core-ui need to be updated to version
  - apply psr-12 please
  otherwise good job

2020-12-16 15:03 UTC, bartlomiejmarszal requested changes
Just remember about `views/package.json`

2020-12-16 15:05 UTC, gabrielfs7 commented on manifest.php
> +    'version' => '46.9.0',
manifest version is outdate/conflicting. Just a reminder to update when all comments are solved :)

2020-12-17 07:43 UTC, gabrielfs7 approved these changes
Lets have a demo! Good job! :)

2020-12-17 13:21 UTC, bziondik approved these changes
Tested. Works for me.

2020-12-18 08:41 UTC, merged