Fix/CON-144/Booklet preview fails due to timeout
oat-sa/tao-core pull request #2760
Opened 2020-12-21 01:24 UTC by shpran

Relates to: [CON-144](https://oat-sa.atlassian.net/browse/CON-144)

**Changes:** default KV storage will be used to store DOM validation result for items. This will allow us to avoid unnecessary validations.

**How to test:**
1. Create or import a large test (15+ items);
2. Generate a booklet;
3. Open this booklet and preview it.

**Previous result:** _the preview takes a long time (1 - 1.5 seconds per item)._
**Current result:** _the preview takes a short time (1-3 seconds for the whole test)._

_**Note: if a booklet was generated before this fix was applied - you need to preview it or regenerate to store validation results in storage.**_

**Require PR:** [#1603](https://github.com/oat-sa/extension-tao-itemqti/pull/1603)

2020-12-21 06:38 UTC, gabrielfs7 commented on models/classes/class.Parser.php
> +                        if (!$this->source->exists()) {
The PSR-2 exception is for closures and arrays, in this case is one parameter per line. Can you please format/ident it?

2020-12-21 06:38 UTC, gabrielfs7 commented on models/classes/class.Parser.php
> +                            throw new Exception(sprintf(
The PSR-2 exception is for closures and arrays, in this case is one parameter per line. Can you please format/ident it?

2020-12-21 06:42 UTC, gabrielfs7 commented on models/classes/class.Parser.php
> +    protected function getKvStorage(): KeyValuePersistence
- This should be private. Least privilege principle.
- You are forcing the `default_kv` always now, this means that it wont take by configuration. Are you sure this is a good idea?

2020-12-21 06:45 UTC, gabrielfs7 commented on models/classes/class.Parser.php
> +                $hashedContent = md5(preg_replace('/\s+<responseProcessing\/>/', '', $content));
Can you explain why this is needed? If this is important, I recommend to extract the new methods added + this part to a new class with proper name and self-explanatory methods.

2020-12-21 06:47 UTC, gabrielfs7 requested changes
Good job! I will need come explanation on how this solution fixed the issue. :) 

Please, consider moving all new code to a proper place where this new requirements understandable for next developers. Also always provide storage by option.

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-12-21 14:29 UTC, shpran commented on models/classes/class.Parser.php
> +                $hashedContent = md5(preg_replace('/\s+<responseProcessing\/>/', '', $content));
Moved to a new class with explanation 😄

2020-12-22 11:06 UTC, gabrielfs7 commented on models/classes/ItemDomValidation.php
> +    public function __construct(
As much as I prefer dependencies through constructor, if we want to extend this with new options provided by the user, this might be done only using configurable service inheritance.
- Also if seems you will have ton instantiate this service directly on the client class, so not good for testing (cause we do not have the DI).

I wold consider make this a ConfigurableService.

2020-12-23 07:29 UTC, gabrielfs7 commented on models/classes/class.Parser.php
> +    public const SOURCE_FLYFILE = 4;
```suggestion
    public const SOURCE_FILE = 1;
    public const SOURCE_URL = 2;
    public const SOURCE_STRING = 3;
    
    /**
     * Current file is \oat\oatbox\filesystem\File object
     */
    public const SOURCE_FLYFILE = 4;
```

Thanks for adding constant visibility. No line break is required unless there is a comment

2020-12-23 07:55 UTC, gabrielfs7 commented on models/classes/class.Parser.php
> +                $itemDomValidation = new ItemDomValidation($dom, $schema, $content);
I sent to you a message explaining details about this, but you can replace from line 134 to line 154 to rely only on the validator to do everything. The outcome will be something like this:

```
$errors = $this->getItemDomValidator()->validateSchema($schema, $content);
$this->valid = count($errors) === 0;

if (!$this->valid) {
    $this->addErrors($errors);
}
```

This way the validation is entirely done outside of this class and the other classes do not need to load DOMElement by themselves just to use it. Also you return a collection of errors instead of true/false, which will help us understand the exact error.

2020-12-24 07:13 UTC, gabrielfs7 commented on models/classes/DomValidator.php
> +        return $this->keyValuePersistence;
It is safer to inject the persistence id instead of the object, cause on seed files it will not work :/ 

```suggestion
        if (!isset($this->keyValuePersistence)) {
            $this->keyValuePersistence = $this->getPersistenceManager()
                ->getPersistenceById($this->getOption(self::OPTION_KV_PERSISTENCE) ?? 'default_kv');
        }

        return $this->keyValuePersistence;
```

2020-12-24 07:15 UTC, gabrielfs7 commented on models/classes/DomValidator.php
> +            $this->getKeyValuePersistence()->set($this->validationKey . '.result', $isValid, $ttl);
Does it work for SQL or just for Redis?

2020-12-24 07:20 UTC, gabrielfs7 reviewed
Good job @shpran! This is a tough topic.

I think it is better to have a chat about this, cause on the first test preview we would still have 504 cause test could be too big. Even using cache, I might have a huge booklet and timeout will arrive. 

Suggestion: Maybe we should allow paginated preview for booklets? So we reduce the amount of computation required? Maybe combine the 2 solutions?

I am not sure the TTL will work as expected to others KV storage and if we use Redis, what would be the impact by adding all item content and validation inside of it?

2020-12-29 22:40 UTC, closed without merging