Fix/tr 260 261 266 fix strings for cognia
oat-sa/tao-core pull request #2762
Opened 2020-12-27 13:50 UTC by lecosson

Related to:
- https://oat-sa.atlassian.net/browse/TR-260
- https://oat-sa.atlassian.net/browse/TR-261
- https://oat-sa.atlassian.net/browse/TR-266

Replace some strings for Cognia 

Related PR's:

2020-12-30 09:33 UTC, meefox commented
is it still draft?

2020-12-30 18:48 UTC, meefox approved these changes

2021-01-04 13:15 UTC, wazelin requested changes

2021-01-04 13:15 UTC, wazelin commented on models/translation/ManualTranslations.php
> +            __('SUBMIT THE TEST'),
Wait what?
Why do you need manual translations for those, especially on the core extension?

They should **already** be in the QTI test extension or a test runner extension.
https://github.com/oat-sa/extension-tao-testqti/blob/master/locales/en-US/messages.po#L1212

2021-01-04 13:16 UTC, wazelin commented
Consider closing the PR, I don't think it's needed.

2021-01-06 08:42 UTC, btamas commented on models/translation/ManualTranslations.php
> +            __('SUBMIT THE TEST'),
I totally agree. I do not understand the aim of this PR.

2021-01-06 09:24 UTC, closed without merging