[Fix] CON-122 - advanced search modal match mockup
oat-sa/tao-core pull request #2772
Opened 2021-01-02 16:01 UTC by 404passionFruit

**JIRA issue**
[CON-122 (comment after testing)](https://oat-sa.atlassian.net/browse/CON-122?focusedCommentId=114171)

**Related PR**
https://github.com/oat-sa/tao-core-ui-fe/pull/242

**Fixies**
- [x] Change version in package.json `"@oat-sa/tao-core-ui": "1.20.5"`
- [ ] Change version in package-lock.json
- [ ] `cd ./views/build && npm run build`

Currently is in draft, finish updating after releasing and publishing @oat-sa/tao-core-ui v1.20.5

2021-01-11 08:54 UTC, mike-ionut-mihai-sandu-tao requested changes

2021-01-11 08:54 UTC, mike-ionut-mihai-sandu-tao commented on views/package.json
> +        "@oat-sa/tao-core-ui": "1.20.5",
when you change a piece of code inside any extension you need to update the version also , 
so please go to manifest and increase the version :) according to the semver,
also i see this is done a while ago (x days ) so please contact your peers to review it

2021-01-12 09:16 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-01-12 10:02 UTC, habemuscode approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-01-12 10:37 UTC, 404passionFruit commented
As Hanna suggested to find existing logic for keycodes in codebase, moving this back to Draft.

2021-01-21 12:58 UTC, merged