Add events
oat-sa/tao-core pull request #2783
Opened 2021-01-21 08:56 UTC by bartlomiejmarszal

https://oat-sa.atlassian.net/browse/CON-495

Created new events, 
- `models/classes/event/ClassPropertyCreatedEvent.php`
- `models/classes/event/ClassPropertyDeletedEvent.php`

I triggered events in existing property actions that will cover adding/removing/modifying property

2021-01-21 10:18 UTC, gabrielfs7 commented on models/classes/event/ClassPropertyCreatedEvent.php
> +class ClassPropertyCreatedEvent implements Event
Is there a `ClassPropertyUpdatedEvent` needed?

2021-01-21 10:19 UTC, gabrielfs7 commented on models/classes/event/ClassPropertyDeletedEvent.php
> +class ClassPropertyDeletedEvent implements Event
We are missing the trigger of those events and the listener, according to the class AC, will it be done in separate PR?

2021-01-21 10:23 UTC, bartlomiejmarszal commented on models/classes/event/ClassPropertyCreatedEvent.php
> +class ClassPropertyCreatedEvent implements Event
Yes. We already have it:
`\oat\tao\model\event\ClassPropertiesChangedEvent`

2021-01-21 10:24 UTC, bartlomiejmarszal commented on models/classes/event/ClassPropertyDeletedEvent.php
> +class ClassPropertyDeletedEvent implements Event
This will be done in genesis PR. 
https://github.com/oat-sa/generis/pull/865

2021-01-22 15:59 UTC, gabrielfs7 commented on models/classes/event/ClassPropertyCreatedEvent.php
> +class ClassPropertyCreatedEvent implements Event
It seems the event `ClassPropertiesChangedEvent` is only existing on the advanced search branches. Since this belongs to generis, what about move it there? 

As an addition to comment https://github.com/oat-sa/generis/pull/865/files#r562729807

2021-01-25 09:40 UTC, bartlomiejmarszal commented on models/classes/event/ClassPropertyCreatedEvent.php
> +class ClassPropertyCreatedEvent implements Event
I had to move back all events from genesis. We should not used it there.

2021-01-26 08:59 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +                'propertyUri' => $newProperty->getUri()
Small indentation issue:

```suggestion
                    'label' => $newProperty->getLabel(),
                    'propertyUri' => $newProperty->getUri()
```

2021-01-26 09:00 UTC, gabrielfs7 commented on models/classes/event/ClassPropertyCreatedEvent.php
> +    public function __construct(core_kernel_classes_Class $class, array $properties)
Will we add unit tests for those?

2021-01-26 09:00 UTC, gabrielfs7 commented on models/classes/event/ClassPropertyDeletedEvent.php
> +    public function __construct(string $propertyUri)
Will we add unit tests for those?

2021-01-26 09:24 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +                    $this->getEventManager()->trigger(new ClassPropertyDeletedEvent($property->getUri()));
@bartlomiejmarszal Why for one event we use URI and for the other we have label and class too? Could maybe we do those events consistent with each other?

2021-01-26 09:37 UTC, gabrielfs7 reviewed
Good job! Left some comments :) 

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-01-26 12:22 UTC, bartlomiejmarszal commented on actions/class.PropertiesAuthoring.php
> +                    $this->getEventManager()->trigger(new ClassPropertyDeletedEvent($property->getUri()));
https://github.com/oat-sa/tao-core/pull/2783/commits/8f19bd79bdafc20febc9b6f1c66501a920d04b75

2021-01-28 16:13 UTC, boajer commented on actions/class.PropertiesAuthoring.php
> +                    'class' => $this->getCurrentClass()
I feel like something wrong with formatting here

2021-02-01 08:24 UTC, gabrielfs7 reviewed
I am not sure the controller is the only place we change the property, so maybe this event should be trigger in the persistence level. Wdyt?

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-02-01 08:33 UTC, boajer approved these changes
I agree with @gabrielfs7, ideally event triggering should go into persistance level, but afraid that would be more tricky afaik with a current RDF approach 
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-02-01 08:56 UTC, shpran approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-02-01 11:14 UTC, bartlomiejmarszal commented
> I am not sure the controller is the only place we change the property, so maybe this event should be trigger in the persistence level. Wdyt?

This event is requiring to have access to class where property belongs. It's more readable to keep it in `class.PropertiesAuthoring` IMO.

2021-02-01 12:09 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +            $this->getEventManager()->trigger(
This and this https://github.com/oat-sa/tao-core/pull/2783/files#diff-20695273e40e9913e486042b5e0438c58ef8609a048347f9ced970e92e0cd87cR149 only exist in the advanced search feature branches. So I think we could add those event in generis, where they belong instead of tao-core controller. For example:

The remove property is called in multiple places, like:

- \oat\tao\model\ClassServiceTrait (and this is used in multiple places)
- tao_actions_PropertiesAuthoring

2021-02-01 12:12 UTC, gabrielfs7 commented on models/classes/event/ClassPropertiesChangedEvent.php
> +     *          'class' => (\core_kernel_classes_Class), current class where changes were made
IMO we should remove this class and replace with proper generis event (already created). It only exists on our integration branch and was created on tao-core instead of generis (where the others are).

2021-02-04 09:19 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/GetClassMetadataValuesService.php
> +        return $this->getClassMetadata($class, $maxListSize, true);
@bartlomiejmarszal  Why both `getByClassExplicitly` and `getByClass` have same internal behavior?

2021-02-04 09:22 UTC, gabrielfs7 requested changes
Recursively method missing

2021-02-04 09:26 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/GetClassMetadataValuesService.php
> +    public function getByClass(
I think this is more clear what is going on:

```suggestion
    public function getRecursivelyByClass(
```

2021-02-04 09:26 UTC, bartlomiejmarszal commented on models/classes/Lists/Business/Service/GetClassMetadataValuesService.php
> +        return $this->getClassMetadata($class, $maxListSize, true);
`getByClass` behaviour is in default recursive. I'm not going to change this method as it was previously used. This is why I introduced getByClassExplicitly which serve purpose of non-recursive search

2021-02-04 09:27 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/GetClassMetadataValuesService.php
> +    public function getByClassExplicitly(
IMO this means the scope is only the class. (if rename previous https://github.com/oat-sa/tao-core/pull/2783/files#r570068373) 

```suggestion
    public function getByClass(
```

2021-02-04 10:22 UTC, gabrielfs7 approved these changes

2021-02-04 10:23 UTC, merged