fix: instance can change class when current and target parent metadat…
oat-sa/tao-core pull request #2811
Opened 2021-03-05 13:07 UTC by boajer

https://oat-sa.atlassian.net/browse/ADF-92

2021-03-05 15:54 UTC, gabrielfs7 commented on actions/class.RdfController.php
> +            $status = $this->getClassService()->changeClass($instance, $destinationClass);
We are moving the instance even if confirmed is false if there is no difference

2021-03-05 15:54 UTC, gabrielfs7 requested changes
Check the move instance behavior

2021-03-08 09:01 UTC, gabrielfs7 commented
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-06-09 08:07 UTC, gabrielfs7 commented on actions/class.RdfController.php
> + *
why?

2021-06-09 14:04 UTC, gabrielfs7 approved these changes

2021-06-10 12:49 UTC, chinnu-focaloid approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2021-06-15 06:06 UTC, AntonNeviarouski commented
QA verified on http://test-move_resource.playground.kitchen.it.taocloud.org:49021/

2021-06-16 09:38 UTC, merged