Feature/aut 122/e2e
oat-sa/tao-core pull request #2814
Opened 2021-03-11 08:59 UTC by AnastasiaArcadia

**Related to:**
https://oat-sa.atlassian.net/browse/AUT-122

**Description of changes**:
Sample E2E tests were added using the cypress core system prototype: https://github.com/oat-sa/e2e-runner/pull/1.
Tests for items creation, edition, deletion will be run (may be refactored in the next sprints).

**How to run locally:**
- `npm install`
- update the admin's credentials in `env-local.json`
- set local TAO address in cypress.json file (`baseUrl` option)
- `npm run cy:open` - to run in browser
- or `npm run cy:run` -  for headless execution

2021-03-11 14:30 UTC, bziondik requested changes

2021-03-11 14:30 UTC, bziondik commented on views/cypress.json
> +  "baseUrl": "https://bosa.docker.localhost",
`"baseUrl": "https://bosa.docker.localhost"` should be in `cypress.env.json`

2021-03-11 14:30 UTC, bziondik commented on views/cypress/envs/env-local.json
> +  "adminUser": "admin",
also should be in `cypress.env.json`

2021-03-11 14:30 UTC, bziondik commented on views/cypress/support/commands.js
> +Cypress.Commands.add('setupServer', () => {
I think these 3 commands will be common for all extension. Can we move them to tao-core or some shared npm package?

2021-03-11 14:41 UTC, bziondik commented on views/cypress/support/commands.js
> +Cypress.Commands.add('setupServer', () => {
Sorry, it is `tao-core `
But in this case why we have tests for taoQtiItem here?

2021-03-11 14:41 UTC, ampaveliev commented on views/cypress.json
> +  "baseUrl": "https://bosa.docker.localhost",
`baseUrl` doesn't work from the `cypress.env.json`. Maybe better to pass it through the command line :thinking:

2021-03-11 15:39 UTC, AnastasiaArcadia commented on views/cypress.json
> +  "baseUrl": "https://bosa.docker.localhost",
Yes, seems like there's no other oprions
https://docs.cypress.io/guides/references/configuration.html#See-also

2021-03-11 16:11 UTC, AnastasiaArcadia commented on views/cypress/envs/env-local.json
> +  "adminUser": "admin",
This is an alternative way to set env via file, in cypress.json we have:
```
  "env": {
    "configFile": "cypress/envs/env-local.json"
  }
```
https://github.com/oat-sa/tao-deliver-testrunner-nui-fe/pull/161/files#r591512804

2021-03-11 16:13 UTC, AnastasiaArcadia commented on views/cypress/support/commands.js
> +Cypress.Commands.add('setupServer', () => {
If I'm if not mistaken it's part of taoItems?
Yes, I think tests can be moved there

2021-03-12 08:51 UTC, mike-ionut-mihai-sandu-tao requested changes

2021-03-12 08:51 UTC, mike-ionut-mihai-sandu-tao commented on views/cypress.json
> +  "baseUrl": "https://bosa.docker.localhost",
hard-coding something that has a client name inside of it is a big NO NO
please change the change and if there is no other way, 
we will leave a fake string inside the readme file and not commit this file

2021-03-12 08:51 UTC, mike-ionut-mihai-sandu-tao commented on views/cypress/README.md
> +Example:
missing dummy configuration

2021-03-12 08:51 UTC, mike-ionut-mihai-sandu-tao commented on views/cypress/envs/env-local.json
> +  "adminUser": "admin",
i agree just add this to the readme and not commit this json file

2021-03-15 13:18 UTC, oatymart reviewed
Code review first, I'm currently setting up to run this.

2021-03-15 13:18 UTC, oatymart commented on views/cypress/fixtures/locators.json
> +    "gotToAuthoring": "a[href$=\"Items/authoring\"]"
```suggestion
    "goToAuthoring": "a[href$=\"Items/authoring\"]"
```

2021-03-15 13:18 UTC, oatymart commented on views/cypress/plugins/index.js
> +}
I didn't include this file in my project. I think you can delete it, unless you have plans for a way to run the 2 plugin init functions.

2021-03-15 13:18 UTC, oatymart commented on views/cypress/support/commands.js
> +import '@oat-sa-private/e2e-runner/support/auth';
```suggestion
import '@oat-sa/e2e-runner/support/auth';
```

2021-03-15 13:18 UTC, oatymart commented on views/package.json
> +        "cy:run": "cypress run --headless"
I don't think `--headless` will do anything unless you configured a non-Electron browser (`--browser chrome`). Running Electron in CI seems to be a standard practice (it comes installed with Cypress, other browsers don't).

2021-03-15 13:18 UTC, oatymart commented on views/package.json
> +        "@oat-sa-private/e2e-runner": "github:oat-sa/e2e-runner#feature/TRN-605/e2e-core-setup",
```suggestion
        "@oat-sa/e2e-runner": "^0.1.0",
```

2021-03-15 13:18 UTC, oatymart commented on views/cypress.json.sample
> +  "integrationFolder": "../..",
We didn't use a sample file for this in [deliver PR](https://github.com/oat-sa/tao-deliver-testrunner-nui-fe/pull/161), we just committed the good config (since it doesn't contain sensitive information).

2021-03-15 15:47 UTC, ampaveliev commented on views/cypress.json.sample
> +  "integrationFolder": "../..",
In our case, we should provide `baseUrl`, which may differ in different environments. So I don't see a way to commit a good config

2021-03-17 08:17 UTC, bziondik commented on views/cypress/support/resourceTree.js
> +    cy.route('POST', '**/createItem').as('createItem');
Can you move this Commands to taoQtiItem?

2021-03-17 14:06 UTC, oatymart commented on views/cypress.json.sample
> +  "integrationFolder": "../..",
Then it's up to you. The baseUrl can easily be overridden on the command line and [in other ways](https://docs.cypress.io/guides/guides/environment-variables.html#Setting), but if the default settings are useful to have, you can keep it here.

2021-03-17 14:12 UTC, AnastasiaArcadia commented on views/cypress/support/resourceTree.js
> +    cy.route('POST', '**/createItem').as('createItem');
In cypress we have [support file](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#Support-file) to place/import such commands. It can be just one file, but not a template like for specs, so I don't know the way to keep commands in extensions

2021-03-22 10:50 UTC, bziondik commented on views/cypress/support/resourceTree.js
> +    cy.route('POST', '**/createItem').as('createItem');
Ok, I see. But this command very specific to taoItems, can they be overwritten to general command with params, because we have the same tree on Items, Tests, Test-takers... pages
Or maybe no need to put them in command, if it is not shared parts of tests.

2021-06-21 13:21 UTC, jsconan reviewed
Sorry to come to the review times later. I'm working on the PoC for the test runner, and I was trying to use this PR as a basis. While the basis looks good and will allow me to move forward a bit, I think there are several thinks that are not correct:
- the core implementation should be agnostic, it should not include knowledge from consumer extensions
- I wonder if the fixture is the right place to put selectors and config. Usually this is were we place the test data, but not the constants. I would rather put such info in helpers.
- the way to manage the base config looks a bit odd. I'd prefer to see it managed the same way as for other project within the company to avoid discrepancy and keep a common way of using  it
- I didn't review in detail the commands, but I think some of them could either be moved to specific extensions, or should be refactored to be generic enough to lie in this repo

2021-06-21 13:21 UTC, jsconan commented on views/cypress/support/resourceTree.js
> +Cypress.Commands.add('addItem', cssSelector => {
**thought:** Is this related to taoItems? If so, I don't think it should be present in this repo.

2021-07-02 07:48 UTC, habemuscode approved these changes
LGTM, just some non-critical comments

2021-07-02 07:48 UTC, habemuscode commented on .gitignore
> +views/cypress/videos
What about to put only `views/cypress` and ignore all?

2021-07-02 07:48 UTC, habemuscode commented on views/cypress/utils/urls.js
> +};
End line

2021-07-02 07:52 UTC, AnastasiaArcadia commented on .gitignore
> +views/cypress/videos
We have all the tests and cypress configuration in it, so it's needed
Just env files, photo and video output is ignored

2021-07-02 08:10 UTC, bziondik approved these changes
- [x]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2021-07-02 12:54 UTC, jsconan approved these changes
A few comments below, but no show stopper.

Very nice job!

2021-07-02 12:54 UTC, jsconan commented on views/cypress/fixtures/example.json
> +}
**chore:** not sure this file needs to be added

2021-07-02 12:54 UTC, jsconan commented on views/cypress/plugins/index.js
> +   return extendConfig(config);
**question:** Is it enough? I mean the snapshot plugin may also be needed. Anyway this is not a showstopper, and it can be added later if needed.

2021-07-02 12:54 UTC, jsconan commented on views/package.json
> +        "@oat-sa/e2e-runner": "git://github.com/oat-sa/e2e-runner#feature/TR-1080/allow-setting-the-baseurl-from-env",
**nitpick:** Would be better to have this PR merged before letting this one to move forward.

2021-07-02 13:00 UTC, AnastasiaArcadia commented on views/cypress/plugins/index.js
> +   return extendConfig(config);
Yes, maybe later we'll add it

2021-07-02 13:39 UTC, jsconan commented
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-07-05 07:59 UTC, merged