feat: create atomic roles for item class
oat-sa/tao-core pull request #2852
Opened 2021-03-31 16:00 UTC by voknil

https://oat-sa.atlassian.net/browse/ADF-154

Created first atomic roles.
Needed to disable edit functionality for divided methods by checking access to action.

2021-03-31 16:26 UTC, shpran approved these changes
Good job! 👍🏻 

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-04-01 09:41 UTC, shpran requested changes
Please, add installation script for atomic roles

2021-04-01 11:42 UTC, gabrielfs7 commented
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-04-01 11:45 UTC, gabrielfs7 commented on migrations/Version202103301905282234_tao.php
> +        $this->throwIrreversibleMigrationException();
You can do a `foreach AclProxy::revokeRule()`

2021-04-01 11:55 UTC, gabrielfs7 commented on scripts/install/AddAtomicRoles.php
> +class AddAtomicRoles extends InstallAction
A few comments about this approach. 

- The "AtomicRole" is some language using while negotiation with NMC, but now what we have are `Role` and `Rule`, so I would not add this new nomenclature, cause it may cause more confusion as if they are different from what we have.

- The action, should work as a delegate / intermediary (Like a controller) for other specialized services. In this cause, all the logic is inside this class and it is hard to test and extend. Should not we have a specialized service that apply rules based on a role/rule mapping? It would be easier to test and extend or use on different parts. What do you think?

- Based on the previous suggestion. The same service should be able to revoke (remove) rules based on rule/role mappings.

- To you think a raw array is the best way to store these mapping? Or should we have some well defined contract for this that would avoid discrepancy while extending / using the service.

2021-04-01 11:57 UTC, gabrielfs7 commented on models/classes/user/TaoRoles.php
> +    /** Atomic roles */
Lets stop using "Atomic" roles, cause they are just new roles.

2021-04-01 11:58 UTC, gabrielfs7 commented on migrations/Version202103301905282234_tao.php
> +        return 'Create atomic roles for items and assign permissions to them';
Lets stop using "Atomic" roles, cause they are just new roles.

2021-04-01 11:58 UTC, gabrielfs7 commented on models/ontology/tao.rdf
> +  <!-- Atomic Roles -->
Lets stop using "Atomic" roles, cause they are just new roles.

2021-04-01 12:18 UTC, shpran commented on migrations/Version202103301905282234_tao.php
> +        $this->throwIrreversibleMigrationException();
Do you think it's a good idea to revoke rules?
In this case we will have a lot of new roles without any permissions (because they are declared in `tao.rdf`)

2021-04-01 13:09 UTC, gabrielfs7 commented on migrations/Version202103301905282234_tao.php
> +        $this->throwIrreversibleMigrationException();
We can add them using `models/classes/class.RoleService.php`. I am not sure using the RDF was required, but I am supposing if we are reverting, the schema will also be reverted (application version). So the database holing invalid roles is not a good idea. Do you agree?

2021-04-01 13:19 UTC, shpran commented on migrations/Version202103301905282234_tao.php
> +        $this->throwIrreversibleMigrationException();
Didn't know about this service 🙂 
Yeah, I think we should try to use it.
@voknil, please, check it 🧑‍🔬

2021-04-01 13:59 UTC, gabrielfs7 commented on migrations/Version202103301905282234_tao.php
> +        $this->throwIrreversibleMigrationException();
Even if we use RDF, still we should revert, cause it is possible to revert.

2021-04-12 14:08 UTC, boajer commented on migrations/Version202103301905282234_tao.php
> + */
```suggestion

```

2021-04-12 14:09 UTC, boajer commented on migrations/Version202103301905282234_tao.php
> +                ['ext' => 'taoItems', 'mod' => 'Items', 'act' => 'viewClassLabel'],
Why `taoItem` logic is defined at the `core`?

2021-04-12 23:50 UTC, shpran commented on migrations/Version202103301905282234_tao.php
> +            TaoRoles::ITEM_CLASS_EDITOR => [
```suggestion
            TaoRoles::ITEM_CLASS_CREATOR => [
```

2021-04-13 05:54 UTC, gabrielfs7 commented on migrations/Version202103301905282234_tao.php
> +                ['ext' => 'taoItems', 'mod' => 'Items', 'act' => 'viewClassLabel'],
That was one of the points to have this on external config.

2021-04-13 06:18 UTC, gabrielfs7 commented on scripts/install/AddAtomicRoles.php
> +                ['ext' => 'taoItems', 'mod' => 'Items', 'act' => 'viewClassLabel'],
https://github.com/oat-sa/tao-core/pull/2852/files/41bb84648102859e68cf6004dd654f8ae06c7172#r611663031

2021-04-13 06:26 UTC, bartlomiejmarszal reviewed
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-04-13 06:34 UTC, bartlomiejmarszal commented on models/classes/user/TaoRoles.php
> +    /** Atomic roles */
Agree with @gabrielfs7, I see this solved, yet this name is still everywhere here. I unresolved it.

2021-04-13 06:40 UTC, gabrielfs7 commented on actions/class.RdfController.php
> +    public function editClassLabel(bool $checkAccessToMethod = false)
This is a code smell https://martinfowler.com/bliki/FlagArgument.html

Is it possible to:

- Use can use already existent `@requiresRight` annotation here instead with the `classUri`?
- Create a `common protected method` that receives form configuration.
- Delegate the new method for the `editClassLabel` method and `viewClassLabel`. https://github.com/oat-sa/extension-tao-item/pull/462/files#diff-78ab91df1465a696b293091206facc84f9df2d6c55539136448974996ac10db9R160 (This would become unnecessary.

```
/**
 * @requiresRight classUri READ
 */
public function viewClassLabel()
{
        $this->renderEditClassLabelForm(
             [
                  FormContainer::CSRF_PROTECTION_OPTION => true, 
                  FormContainer::IS_DISABLED => true
             ]
        );
}

/**
 * @requiresRight classUri WRITE
 */
public function editClassLabel()
{
        $this->renderEditClassLabelForm(
             [
                  FormContainer::CSRF_PROTECTION_OPTION => true, 
                  FormContainer::IS_DISABLED => false
             ]
        );
}

protected method renderEditClassLabelForm(array $formConfig): void
{
        $class     = $this->getCurrentClass();
        $signature = $this->createFormSignature();

        $classUri       = $class->getUri();
        $hasWriteAccess = $this->hasWriteAccess($classUri);

        $editClassLabelForm = new tao_actions_form_EditClassLabel(
            $class,
            $this->getRequestParameters(),
            $signature,
            $formConfig
        );

        $myForm = $editClassLabelForm->getForm();

        if ($myForm->isSubmited() && $myForm->isValid()) {
            if ($hasWriteAccess) {
                $class->setLabel($myForm->getValue(tao_helpers_Uri::encode(OntologyRdfs::RDFS_LABEL)));
                $this->setData('message', __('%s Class saved', $class->getLabel()));
            } else {
                $this->setData('errorMessage', __('You do not have the required rights to edit this resource.'));
            }

            $this->setData('selectNode', tao_helpers_Uri::encode($classUri));
            $this->setData('reload', true);
        }

        $this->setData('formTitle', __('Edit class %s', \tao_helpers_Display::htmlize($class->getLabel())));
        $this->setData('myForm', $myForm->render());
        $this->setView('form.tpl', 'tao');
} 
```

2021-04-21 06:47 UTC, closed without merging