[Fix - ADF 193] UDIR Pre-Prod: Console errors after removing all 'Grant' permissions from the object in Access Control panel.
oat-sa/tao-core pull request #2865
Opened 2021-04-07 14:43 UTC by habemuscode

**Issue**

https://oat-sa.atlassian.net/browse/ADF-193

**Description**

When user with Global Manager role (f. e. Administrator) removes all the 'Grant' permissions from any object in Back Office, there are 2 errors in Browser console appear right after removing the last 'Grant' permission. Also there's an uninformative error message randomly appears after the saving attempt (please see attached images).

**Steps to reproduce**

- Log in as admin and go to Items tab.
- Choose any class or item and click 'Access Control' button.
- Remove checkboxes from 'Grant' permissions and try to click 'Save'.

**Actual result**

2 errors appear in Browser console right after removing the last 'Grant' permission. Also, there's an uninformative error message pops up after clicking 'Save' button (occurs randomly).

**Expected result**

No errors appear in browser console, clicking 'Save' button causes the report to appear in Background tasks with the explanation that saving demands at least one role or user to have 'Grant' permission.

**Bonus**

-- Pending --

- Fix non-meaningful message when try to save ignoring warning popup

2021-04-08 10:23 UTC, habemuscode commented
Deployed temporarily here: http://test-bosa.playground.kitchen.it.taocloud.org:49151 Ping me if not solved, maybe overwrited deployment

2021-04-09 07:22 UTC, andrey-ponamarev requested changes

2021-04-09 07:22 UTC, andrey-ponamarev commented on views/js/lib/popper/tooltip.js
>          }
I can be mistaken, but it doesn't look like a library issue, I feel the issue could be on our side, and it smells like a memory leak.
Please try to avoid modifications of external libraries sources instead check if the issue exist and fixed there, then update the whole [library source](https://github.com/popperjs/popper-core/blob/v1.16.1/packages/tooltip/src/index.js#L351).

2021-04-09 08:19 UTC, habemuscode commented on views/js/lib/popper/tooltip.js
>          }
Thanks!

Change all popper library will require a more extensive QA test that we don't have planned. Also, we need to check if all methods continue to exist or not or have modifications in params.

I can create another issue for this and go forward with this small workaround for now

https://oat-sa.atlassian.net/browse/ADF-262

2021-04-09 09:29 UTC, 404passionFruit commented on views/js/lib/popper/tooltip.js
>          }
Maybe leave a comment with a hint to the issue and the way this should be handled when we have more time?

2021-04-09 10:09 UTC, habemuscode commented on views/js/lib/popper/tooltip.js
>          }
I already comment the new issue link: https://oat-sa.atlassian.net/browse/ADF-262

2021-04-09 10:14 UTC, 404passionFruit approved these changes
Approved as temp fix

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-04-12 12:29 UTC, bziondik requested changes
The root of issue in our code
taoDacSimple/views/js/controller/admin/index.js
we don't have `$submitter` , maybe markup was changed
![image](https://user-images.githubusercontent.com/25976342/114394345-c3b00780-9ba3-11eb-96ea-0025b178b69a.png)
Please, fix `$submitter`

2021-04-13 10:07 UTC, habemuscode commented
To avoid modifying the external library I will follow @bziondik suggestion in this other PR: https://github.com/oat-sa/extension-tao-dac-simple/pull/164

2021-04-13 10:07 UTC, closed without merging