feat: Enable right to left text direction by script action
oat-sa/tao-core pull request #2912
Opened 2021-05-11 13:38 UTC by bartlomiejmarszal

[AUT-337](https://oat-sa.atlassian.net/browse/AUT-337)

Created a command that allow us to add rtf language locales

2021-05-11 15:26 UTC, jsconan approved these changes
It works well. But it would have been great to have more feedback when executing the script:
![image](https://user-images.githubusercontent.com/1500098/117841461-6039f800-b27d-11eb-8be9-33bce4b4a510.png)

Once added, we can retrieve the languages list in the config request:
![image](https://user-images.githubusercontent.com/1500098/117841776-99726800-b27d-11eb-929b-d4f3aa6184db.png)

Maybe could it be great to also have a way to unregister a language, in case of mistake (typo in the name, wrong language, ...). But this is not a blocker.

Beware, there is one unconventional commit:
![image](https://user-images.githubusercontent.com/1500098/117842110-e9e9c580-b27d-11eb-8552-2131a70af400.png)

There is no unit test, but I wonder if this is unit testable.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-12 08:29 UTC, shpran commented on models/classes/textDirection/RightToLeftTextDirectionRegistry.php
> +                'rtl' => $allLocales
```suggestion
                self::RTL => $allLocales
```

2021-05-12 08:29 UTC, shpran commented on scripts/tools/AddRtlLocales.php
> +                'longPrefix' => 'rtlLocales',
```suggestion
                'longPrefix' => self::RTL_LOCALES,
```

2021-05-12 08:29 UTC, shpran commented on scripts/tools/AddRtlLocales.php
> +     */
```suggestion
```

2021-05-12 08:29 UTC, shpran commented on models/classes/textDirection/RightToLeftTextDirectionRegistry.php
> +    public function addRtlLocales(string $locales): void
Will we provide here a string-list of RTL locales? Or we will provide only one locale?
`$locales` confusing me a bit 😅

2021-05-12 08:29 UTC, shpran commented on scripts/tools/AddRtlLocales.php
> +    public const RTL_LOCALES = 'rtlLocales';
Same here - in accordance with script name, argument (constant) name and script description we can assume, that we can provide a string-list of locales and this will work as expected. Is it true? Or this script is ready to handle only one locale?

2021-05-12 09:15 UTC, bartlomiejmarszal commented on scripts/tools/AddRtlLocales.php
> +    public const RTL_LOCALES = 'rtlLocales';
Script is able to insert only one locale. I'm fixing this

2021-05-12 09:20 UTC, bartlomiejmarszal commented on scripts/tools/AddRtlLocales.php
> +                'longPrefix' => 'rtlLocales',
This is long prefix and it has nothing to do with const variable. I prefer to keep it as it is.

2021-05-12 09:21 UTC, shpran approved these changes
Good job!
One more comment: we can rename script to `AddRtlLocale`, constant to `RTL_LOCALE` and option description to `add locale code to enable rtl handling`. But it's not critical, up to you 🙂 

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-05-12 14:51 UTC, wazelin requested changes

2021-05-12 14:51 UTC, wazelin commented on scripts/tools/AddRtlLocales.php
> +class AddRtlLocales extends ScriptAction
Consider adding a migration, registering all _known_ locales with RTL direction.
We don't really want to end up with half-configured instances here and there.

2021-05-14 08:21 UTC, mike-ionut-mihai-sandu-tao commented on scripts/tools/AddRtlLocales.php
> +class AddRtlLocales extends ScriptAction
i think we need strategy confirmation on where this migration should be 
customer extension or main product , 
but for sure having a migration is a plus

2021-05-14 08:22 UTC, mike-ionut-mihai-sandu-tao commented on scripts/tools/AddRtlLocales.php
> +class AddRtlLocales extends ScriptAction
also i see that FE is done after this , 
so maybe the migration should be at the end as this allows you to register but does not do it for you 
@wazelin wdyt ?

2021-05-17 08:25 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/textDirection/RightToLeftTextDirectionRegistry.php
> +                self::RTL => $allLocales
do we want also to have this while installing a fresh TAO platform or just to update customers ? 
as i see it we might need install script also

2021-05-17 08:25 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/textDirection/RightToLeftTextDirectionRegistry.php
> +                self::RTL => $allLocales
wdyt guys ?

2021-05-17 08:28 UTC, wazelin commented on scripts/tools/AddRtlLocales.php
> +class AddRtlLocales extends ScriptAction
I think it should at least provide all the _expected_ locale mapping out-of-the-box. That's just convenient, isn't it?

2021-05-17 08:31 UTC, wazelin commented on models/classes/textDirection/RightToLeftTextDirectionRegistry.php
> +                self::RTL => $allLocales
That's right. No need to add a dedicated script, though. The very same `AddRtlLocale` should be sufficient.

If you add something like `[AddRtlLocale::class, ['--rtlLocale', 'ar-arb']]` into the `manifest`'s `install => php`.

2021-05-17 08:33 UTC, wazelin requested changes

2021-05-17 08:33 UTC, wazelin commented on migrations/Version202105140945122237_tao.php
> +            new TextDirectionRegistry(),
Fellas, have you verified the migration?

I don't think the registry should be invoked here directly, it's not an action.
I'm pretty sure it should be replaced with `AddRtlLocales`.

2021-05-17 09:23 UTC, bartlomiejmarszal commented on models/classes/textDirection/RightToLeftTextDirectionRegistry.php
> +                self::RTL => $allLocales
I'm not aware of that way @wazelin. Created dedicated script to register on install process.

2021-05-17 09:24 UTC, bartlomiejmarszal commented on migrations/Version202105140945122237_tao.php
> +            new TextDirectionRegistry(),
Right,  this was some solution from renaming. It's fixed now.

2021-05-17 11:30 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-05-17 11:37 UTC, merged