Fix: TR-981/scrollbar-between-item-pages
oat-sa/tao-core pull request #2925
Opened 2021-05-25 06:13 UTC by marpesia

Related to: [TR-981](https://oat-sa.atlassian.net/browse/TR-981)

It happens when the page's height has decimals. 
Loader set a full height without decimals and overflow the page.
I can reproduce it in any browser.

2021-05-25 10:01 UTC, jsconan reviewed
While the fix won't hurt (at worst it will make the loading bar smaller), I don't see the benefit of it.
Actually, I was not able to reproduce the issue, but even, I don't see how this PR can fix it since the loading bar has an absolute positioning and doesn't count in the page height.

2021-05-25 11:35 UTC, marpesia commented
To reproduce, on chrome. It's very fast and not happens every time, so create a breakpoint helps to see.

![image](https://user-images.githubusercontent.com/11692751/119491180-ea925980-bd5d-11eb-8ca7-28e54e0482a0.png)

2021-05-25 11:41 UTC, marpesia commented on views/js/layout/loading-bar.js
> +                $loadingBar.height($doc.height() - 1);
I've tried with floor and ceil but it seems that $doc.height() is returning already rounded.
In the screenshot, you can see the actual height of the body on the left down corner and on the js console the number that is returning the $doc.height()

![image](https://user-images.githubusercontent.com/11692751/119492017-e4e94380-bd5e-11eb-8bf9-3f9e91c85e4a.png)

2021-05-26 05:56 UTC, marpesia commented on views/js/layout/loading-bar.js
> +                $loadingBar.height($doc.height() - 1);
Great solution. Thanks for the suggestion!

2021-05-26 06:06 UTC, btamas approved these changes
Code looks good and I cannot see scrollbar in my browser.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-26 12:00 UTC, lecosson approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-26 13:56 UTC, jsconan reviewed
Looks good. Just one remark about code style.

2021-05-26 13:56 UTC, jsconan commented on views/js/layout/loading-bar.js
> +                var loadingBarHeight = $doc.height();
**nitpick:** Please use ES6 whenever possible. Or please declare the variable on top to reflect [hoisting](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting).

**suggestion:** Use `let`
```suggestion
                let loadingBarHeight = $doc.height();
```

2021-05-27 07:07 UTC, jsconan requested changes
The code looks ok, but I was unable to bundled it:
```
Start transform
>> Error: Unexpected token: name «loadingBarHeight», expected: punc «;»
Fatal error: Unable transform your code
```

2021-05-27 11:22 UTC, jsconan requested changes
The bundle works, but the implementation looks climsy

2021-05-27 11:22 UTC, jsconan commented on views/js/layout/loading-bar.js
> +                    loadingBarHeight--;
**nitpick:** Caution, as the same top scope variable is used, it will decrease on each call, and at the end the value will be totally inaccurate. Moreover, this variable is assigned at a very early stage and may never be accurate.

**suggestion:** Declare a local variable, and assign the valu on time.

2021-05-27 11:39 UTC, jsconan approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-05-31 05:24 UTC, merged