[FIX] ADF-3: child items of the class should show file property
oat-sa/tao-core pull request #2979
Opened 2021-06-24 09:56 UTC by chinnu-focaloid

Related task - https://oat-sa.atlassian.net/browse/ADF-3

Description: User has the possibility to add additional property for a given folder/class, using the "Manage Schema" option. All the items that are contained by this class will inherit the parent-folder's properties.
It works for all the properties BUT the File one.
Upon adding of this property, even though set for the parent-folder, the items won't inherit this only property.

Expected Result: all the child elements of the class are inheriting and are being shown all its properties.

2021-06-25 09:34 UTC, shpran commented on helpers/form/class.Form.php
> +        return $returnValue;
```suggestion
        foreach ($this->elements as $element) {
            if ($element instanceof tao_helpers_form_elements_xhtml_AsyncFile) {
                return true;
            }
        }

        return false;
```

2021-06-25 09:34 UTC, shpran commented on helpers/form/ElementMapFactory.php
If we don't need this part - just remove it

2021-06-25 11:15 UTC, gabrielfs7 commented on helpers/form/ElementMapFactory.php
> -        if ($widgetUri === AsyncFile::WIDGET_ID) {
Why do not we apply the fix here? https://github.com/oat-sa/extension-tao-item/pull/477/files#r658687083

2021-06-25 11:17 UTC, gabrielfs7 reviewed
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-06-30 11:06 UTC, gabrielfs7 commented on helpers/form/xhtml/class.Form.php
> +            $returnValue .= "<input type='hidden' name='check-file' id='check-file' data-id='schema' value='1' />\n";
The "name", "id" and "data-id" attribute needs to be dynamic. In case we have multiple file fields they will be repeated.

2021-06-30 11:07 UTC, gabrielfs7 commented on helpers/form/xhtml/class.Form.php
> +            $returnValue .= "<input type='hidden' name='check-file' id='check-file' data-id='schema' value='1' />\n";
Ping @habemuscode @chinnu-focaloid

2021-06-30 11:07 UTC, gabrielfs7 requested changes
ids, names are not unique with this solution

2021-06-30 13:29 UTC, habemuscode approved these changes
This must be merged after merge PR of `tao-core-ui` and release it, then change here the related files (Ping me)

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-06-30 13:32 UTC, habemuscode commented on helpers/form/xhtml/class.Form.php
> +            $returnValue .= "<input type='hidden' name='check-file' id='check-file' data-id='schema' value='1' />\n";
The behavior is that all uploaders are non-mandatory, so you can save without upload anything. In that context, we want that all aren't required, so this solution is done with that purpose

2021-06-30 13:52 UTC, gabrielfs7 commented on helpers/form/xhtml/class.Form.php
> +            $returnValue .= "<input type='hidden' name='check-file' id='check-file' data-id='schema' value='1' />\n";
Do you mean I can have multiple inputs with same name and id? Is it good for you to manipulate in this way? Would not be better a `class` in this case?

2021-07-01 05:00 UTC, chinnu-focaloid commented on helpers/form/ElementMapFactory.php
> -        if ($widgetUri === AsyncFile::WIDGET_ID) {
This is a AsyncFile upload. We don't want to change the widget definition of it. Hence removed.

2021-07-01 05:02 UTC, chinnu-focaloid commented on helpers/form/xhtml/class.Form.php
> +            $returnValue .= "<input type='hidden' name='check-file' id='check-file' data-id='schema' value='1' />\n";
No. The id will not repeat. The idea behind adding a hidden field is just to identify the front end team that the  form has a file upload. If the hidden field is there, FE enable the save button

2021-07-01 05:42 UTC, gabrielfs7 commented on helpers/form/class.Form.php
> +            if ($element->getName() == "tao.forms.instance" ) {
What do you think of having a constant added at `tao_actions_form_Instance` for `tao.forms.instance`?

2021-07-01 05:43 UTC, gabrielfs7 commented on helpers/form/class.Form.php
> +    public function checkFormInstance(): bool
IMO check seems you are validating something, which is not the case. You just need to know if this is a form instance.

```suggestion
    public function isFormInstance(): bool
```

2021-07-01 05:43 UTC, gabrielfs7 approved these changes
Good job!

2021-07-01 05:44 UTC, gabrielfs7 commented on helpers/form/class.Form.php
> +    public function hasAsyncFileUpload(): bool
Is is possible to add tests?

2021-07-01 11:18 UTC, chinnu-focaloid commented on helpers/form/class.Form.php
> +    public function hasAsyncFileUpload(): bool
Added

2021-07-02 05:56 UTC, gabrielfs7 commented on test/unit/helpers/form/TaoHelpersXhtmlFormTest.php
> +        $this->tao_helpers_form_xhtml_Form_obj = $this->createMock(tao_helpers_form_xhtml_Form::class);
Do not you think this name is too big? Also we do not use `_` or complete namespace in the variables.

```suggestion
        $this->form = $this->createMock(tao_helpers_form_xhtml_Form::class);
```

2021-07-02 05:57 UTC, gabrielfs7 commented on test/unit/helpers/form/TaoHelpersXhtmlFormTest.php
> +        $this->assertIsBool($response);
Unnecessary variable.

```suggestion
        $this->assertIsBool($this->subject->hasAsyncFileUpload($this->tao_helpers_form_xhtml_Form_obj));
```

2021-07-02 05:57 UTC, gabrielfs7 commented on test/unit/helpers/form/TaoHelpersXhtmlFormTest.php
> +    public function testHasAsyncFileUpload(): void
Can we test both cases?

2021-07-02 05:57 UTC, gabrielfs7 commented on test/unit/helpers/form/TaoHelpersXhtmlFormTest.php
> +    public function testIsFormInstance(): void
Can we test both cases?

2021-07-02 05:57 UTC, gabrielfs7 commented on test/unit/helpers/form/TaoHelpersXhtmlFormTest.php
> +        $this->assertIsBool($response);
```suggestion
        $this->assertIsBool($this->subject->isFormInstance($this->tao_helpers_form_xhtml_Form_obj));
```

2021-07-02 06:18 UTC, chinnu-focaloid commented on helpers/form/class.Form.php
> +            if ($element->getName() == "tao.forms.instance" ) {
tao.forms.instance is the name of the object of class tao_helpers_form_elements_xhtml_Hidden

2021-07-02 06:22 UTC, chinnu-focaloid commented on test/unit/helpers/form/TaoHelpersXhtmlFormTest.php
> +        $this->assertIsBool($response);
Done

2021-07-02 06:22 UTC, chinnu-focaloid commented on test/unit/helpers/form/TaoHelpersXhtmlFormTest.php
> +        $this->assertIsBool($response);
Removed

2021-07-02 06:22 UTC, chinnu-focaloid commented on test/unit/helpers/form/TaoHelpersXhtmlFormTest.php
> +        $this->tao_helpers_form_xhtml_Form_obj = $this->createMock(tao_helpers_form_xhtml_Form::class);
Done

2021-07-02 06:22 UTC, chinnu-focaloid commented on helpers/form/class.Form.php
> +    public function checkFormInstance(): bool
Done

2021-07-02 07:47 UTC, gabrielfs7 commented on helpers/form/class.Form.php
> +            if ($element->getName() == "tao.forms.instance" ) {
I know, but it is repeating now, so I suggested to create a constant instead of repeat.

2021-07-02 07:48 UTC, gabrielfs7 commented on helpers/form/class.Form.php
> +    public function hasAsyncFileUpload(): bool
thanks!

2025-10-03 11:29 UTC, closed without merging