Feat: add Arabic language
oat-sa/tao-core pull request #3021
Opened 2021-07-22 06:47 UTC by alexeyvy

Ticket: https://oat-sa.atlassian.net/browse/TR-1323

Add lang.rdf for Arabic to expose it to UI

2021-07-22 09:00 UTC, alexeyvy commented on locales/ar-arb/lang.rdf
> +    <tao:LanguageOrientation rdf:resource="http://www.tao.lu/Ontologies/TAO.rdf#OrientationLeftToRight"/>
```suggestion
    <tao:LanguageOrientation rdf:resource="http://www.tao.lu/Ontologies/TAO.rdf#OrientationRightToLeft"/>

```

2021-07-23 13:53 UTC, marpesia commented
It's working perfect if I add a Test taker with the Arabic language.

But I have got this issue if I try to save the item on Arabic
![image](https://user-images.githubusercontent.com/11692751/126791525-0d9e0c38-0fd4-4680-93d2-e2b6ce33c795.png)

2021-07-25 18:54 UTC, Abrahim111s approved these changes

2021-07-25 18:56 UTC, Abrahim111s requested changes
locales/ar-arb/lang.rdf

2021-07-25 18:56 UTC, Abrahim111s commented
@

2021-07-26 13:16 UTC, wazelin requested changes
Please update the commit message to have a lowercase feat prefix?
The uppercase one is not a conventional one, and won't be taken into account when generating the extension's version.

2021-07-27 13:59 UTC, alexeyvy commented
@wazelin fixed, thanks

2021-07-27 14:19 UTC, alexeyvy commented
Sorry, @Abrahim111s I didn't get your comment, can you explain it, please?

2021-07-28 06:42 UTC, wazelin approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-07-30 11:43 UTC, emgolubev approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2021-07-30 11:43 UTC, merged