chore: add function to get User role
oat-sa/tao-core pull request #3024
Opened 2021-07-23 13:06 UTC by chinnu-focaloid

Relates to https://oat-sa.atlassian.net/browse/ADF-208

2021-07-26 05:54 UTC, gabrielfs7 commented on helpers/form/class.FormContainer.php
> +    public const IS_REPLACE_ASSET_DISABLED = 'is_replace_asset_disabled';
This is too generic to be here, the asset is the only thing related to replace action, so it should not be in tao-core. Please keep in mind the domain language and feature boundaries while changing the code or it will become a mess.

Better place to put is here.

https://github.com/oat-sa/extension-tao-mediamanager/pull/298/files#diff-fc799a03009e11cb7d588783d2f4bf2efe716588a4290e1e77b7ef087e7a01faR53

2021-07-26 05:54 UTC, gabrielfs7 commented on actions/class.CommonModule.php
> +        return ($user ?? $this->getSession()->getUser())->getRoles();
What is this condition? The variable `$user` does not come from anywhere.

2021-07-26 05:55 UTC, gabrielfs7 requested changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-07-26 11:17 UTC, chinnu-focaloid commented on helpers/form/class.FormContainer.php
> +    public const IS_REPLACE_ASSET_DISABLED = 'is_replace_asset_disabled';
Done

2021-07-26 11:17 UTC, chinnu-focaloid commented on actions/class.CommonModule.php
> +        return ($user ?? $this->getSession()->getUser())->getRoles();
Done

2021-07-29 12:44 UTC, gabrielfs7 approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-07-29 12:49 UTC, shpran approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-07-30 06:33 UTC, AntonNeviarouski commented
QA verified on http://test-chinnufrancis.playground.kitchen.it.taocloud.org:48831/tao/Main/login

2021-07-30 08:56 UTC, AntonNeviarouski commented
QA re-verified on http://test-chinnufrancis.playground.kitchen.it.taocloud.org:48831/tao/Main/login

2021-07-30 09:17 UTC, merged