Feature/ADF-421/Extend remote list with extra optional parameter to define dependency field
oat-sa/tao-core pull request #3045
Opened 2021-08-07 01:38 UTC by shpran

**Relates to:** _[ADF-421](https://oat-sa.atlassian.net/browse/ADF-421)_

- [x] Extend remote list with extra optional parameter to define dependency field
- [ ] Add and configure feature flag for this feature

2021-08-08 09:16 UTC, gabrielfs7 commented on models/classes/Context/AbstractContext.php
> +abstract class AbstractContext
```suggestion
abstract class AbstractContext implements ContextInterface
```

2021-08-08 09:16 UTC, gabrielfs7 commented on models/classes/Context/AbstractContext.php
> +    public function setParameter(string $parameter, $parameterValue): void
Shouldn't it also be part of the interface?

2021-08-08 09:17 UTC, gabrielfs7 commented on models/classes/Lists/Business/Domain/RemoteSourceContext.php
> +class RemoteSourceContext extends AbstractContext implements ContextInterface
Make the abstraction implement it, please :) 

```suggestion
class RemoteSourceContext extends AbstractContext
```

2021-08-08 09:18 UTC, gabrielfs7 commented on models/classes/Lists/Business/Domain/RemoteSourceContext.php
> +    protected function validateParameter(string $parameter, $parameterValue): void
It is missing validate the other parameters, like: PARAM_URI_PATH, PARAM_PARSER, etc...

2021-08-08 09:18 UTC, gabrielfs7 commented on models/classes/Lists/Business/Domain/RemoteSourceContext.php
> +            self::PARAM_PARSER,
Will it be a parser service as reference? Should it be here?

2021-08-08 09:19 UTC, gabrielfs7 commented on models/classes/Lists/Business/Domain/Value.php
> +
Why separate line?

```suggestion
```

2021-08-08 09:20 UTC, gabrielfs7 commented on models/classes/Lists/Business/Domain/Value.php
> +    public function setDependencyUri(?string $dependencyUri): self
Why allow to set it to null back again? Does it make sense to happen? This is a VO, so in theory is should not even change the state.

2021-08-08 09:22 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/RemoteSource.php
> +    public function fetchContext(RemoteSourceContext $context): Traversable
👏 👏 👏  🚀

2021-08-08 09:23 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/RemoteSourceParserInterface.php
> +    public function iterateContext(ContextInterface $context): iterable;
You are not actually iterating the context, but based on it. Wdyt?

```suggestion
    public function iterateByContext(ContextInterface $context): iterable;
```

2021-08-08 09:24 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/RemoteSource.php
> +    public function fetchContext(RemoteSourceContext $context): Traversable
Cause you are fetching the resources by context, not fetching the context. Wdyt?

```suggestion
    public function fetchByContext(RemoteSourceContext $context): Traversable
```

2021-08-08 09:25 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/RemoteSourceJsonPathParser.php
> +    public function iterateContext(ContextInterface $context): iterable
https://github.com/oat-sa/tao-core/pull/3045/files#r684744084

```suggestion
    public function iterateByContext(ContextInterface $context): iterable
```

2021-08-08 09:26 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
> +            $value->setDependencyUri($rawValue[self::FIELD_DEPENDENCY_ITEM_URI]);
I would add this as a construct parameter, seems we will alway set it for now on. Wdyt?

2021-08-08 09:28 UTC, gabrielfs7 commented on models/classes/accessControl/AbstractContext.php
>  abstract class AbstractContext
You can erase all the content and extend the proper abstraction, so you do not keep the same logic in 2 places.

```suggestion
abstract class AbstractContext extends \oat\tao\model\Context\AbstractContext
```

2021-08-08 09:29 UTC, gabrielfs7 commented on models/classes/accessControl/ContextInterface.php
>  interface ContextInterface
You can make this interface extends the proper one and to not keep the same methods in 2 places.

```suggestion
interface ContextInterface extends \oat\tao\model\Context\ContextInterface
```

2021-08-08 09:31 UTC, gabrielfs7 commented on models/classes/accessControl/ContextInterface.php
>  interface ContextInterface
You can extends the proper interface and remove the methods from here, so it is easier/safer to migrate to eliminate deprecated implementations.

```suggestion
interface ContextInterface extends \oat\tao\model\Context\ContextInterface
```

2021-08-08 09:32 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
> +                self::FIELD_DEPENDENCY_ITEM_URI => ':dependencyUri',
Did not we agree to use a separate table to keep the dependencies?

2021-08-08 09:33 UTC, gabrielfs7 commented on scripts/install/CreateRdsListStore.php
> +            RdsValueCollectionRepository::FIELD_DEPENDENCY_ITEM_URI,
Did not we agree to use a separate table to keep the dependencies?

2021-08-08 09:37 UTC, gabrielfs7 requested changes
Good job @shpran! 🥇 

I think should use a separate table to store the dependencies relation as we agreed before, so we can be prepared to more complex relations in the future.

There are some other comments about deprecation and OO, etc

2021-08-08 19:33 UTC, shpran commented on models/classes/Lists/Business/Domain/RemoteSourceContext.php
> +    protected function validateParameter(string $parameter, $parameterValue): void
They are all covered by this validation:
```php
if ($parameter !== self::PARAM_JSON && is_string($parameterValue)) {
    return;
}
```

The only check we need - just to check that they are string-values

2021-08-08 19:35 UTC, shpran commented on models/classes/Lists/Business/Domain/RemoteSourceContext.php
> +            self::PARAM_PARSER,
Nope, it's just a parser key (string value)

2021-08-08 19:47 UTC, shpran commented on models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
> +                self::FIELD_DEPENDENCY_ITEM_URI => ':dependencyUri',
Yes, we need to discuss this one more time 🙂

2021-08-11 05:48 UTC, boajer commented on migrations/Version202007151446482234_tao.php
> +        $fromSchema = clone $schema;
Why are you modifying existing migrations?

2021-08-11 05:51 UTC, boajer commented on models/classes/Lists/Business/Domain/Value.php
> +            'dependencyUri' => $this->dependencyUri,
Why while we have two different types of urls in serialized object one is encoded, but another - not?

2021-08-11 06:03 UTC, boajer commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_ADVANCED_SEARCH_DISABLED = 'FEATURE_FLAG_ADVANCED_SEARCH_DISABLED';
What is the purpose of introducing such constants?  IMO despite it may be helpful to have all feature flags in the centric location it may introduce even more code coupling

2021-08-11 06:32 UTC, gabrielfs7 commented on actions/form/class.RemoteList.php
> +                __('Dependency URI Path'),
Will it be required to update translations files for UDIR with this?

2021-08-11 06:35 UTC, gabrielfs7 commented on migrations/Version202007151446482234_tao.php
> +        $fromSchema = clone $schema;
Yes, indeed, we need a new migration for the new table

2021-08-11 06:36 UTC, gabrielfs7 commented on migrations/Version202007151446482234_tao.php
> +                    'Table "%s" successfully dropped',
This is already existing table, we should not drop it.

2021-08-11 06:37 UTC, gabrielfs7 commented on migrations/Version202007151446482234_tao.php
> +        $listItemsTable = $schema->createTable(RdsValueCollectionRepository::TABLE_LIST_ITEMS);
Probably it should be the new table

2021-08-11 06:38 UTC, gabrielfs7 commented on migrations/Version202108101839442234_tao.php
> +            [RdsValueCollectionRepository::FIELD_ITEM_ID]
Is `FIELD_ITEM_ID` a key on `TABLE_LIST_ITEMS`?

2021-08-11 06:43 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/RemoteSource.php
> +    public function fetchByContext(RemoteSourceContext $context): Traversable
Should we use ContextInterface instead?

2021-08-11 06:45 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/RemoteSource.php
> +            $this->getFeatureFlagChecker()->isEnabled(
Why parser does not check itself the feature flag, but instead we provide it here, so if another place call the parses needs to remember to do the same?

2021-08-11 06:47 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/RemoteSourceJsonPathParser.php
> +        $isListsDependencyEnabled = $context->getParameter(
I suggest to use feature flag checker directly here to avoid clients of this parser to have to do it everytime. 

https://github.com/oat-sa/tao-core/pull/3045/files#r686543834

2021-08-11 06:49 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
> +                    'list_item_id' => $qb->getConnection()->lastInsertId('list_items_id_seq'),
We need to check if it will work with postgres and myqsl/mariadb

2021-08-11 06:51 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
> +    private function deleteListItemsDependencies(QueryBuilder $query, string $valueCollectionUri): void
Our CR guidelines reinforce private methods should be always after public, protected.

2021-08-11 06:52 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
> +        } catch (\Throwable $e) {
FQN

```suggestion
        } catch (Throwable $e) {
```

2021-08-11 06:56 UTC, gabrielfs7 commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_ADVANCED_SEARCH_DISABLED = 'FEATURE_FLAG_ADVANCED_SEARCH_DISABLED';
Where would we document map all the FF we have? I do agree it is coupling, but at the same time we do not have a place to track what can be "activated" in the platform.

2021-08-11 07:23 UTC, boajer commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_ADVANCED_SEARCH_DISABLED = 'FEATURE_FLAG_ADVANCED_SEARCH_DISABLED';
What if we can have such FF mapping not in the code itself, but in documentation stored within the codebase?  
If not plain format, but annotations to the classes which can be parsed and aggregated, might be even with help of GitHub actions to be a bit more automatic

2021-08-11 07:27 UTC, gabrielfs7 commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_ADVANCED_SEARCH_DISABLED = 'FEATURE_FLAG_ADVANCED_SEARCH_DISABLED';
It could also be, but it wont avoid us to create constants and forget to update this new doc.

2021-08-11 07:28 UTC, shpran commented on migrations/Version202007151446482234_tao.php
> +        $fromSchema = clone $schema;
@gabrielfs7 we talked about this yesterday - I'm extracting logic from Installation Script into this migration + I created new migration for new table

2021-08-11 07:30 UTC, gabrielfs7 commented on migrations/Version202007151446482234_tao.php
> +        $fromSchema = clone $schema;
So this change here will be reverted?

2021-08-11 07:37 UTC, shpran commented on actions/form/class.RemoteList.php
> +                __('Dependency URI Path'),
Translation files can be updated, but this is not necessary - `Dependency URI path` will be used by default if there are no translations.

2021-08-11 07:42 UTC, shpran commented on migrations/Version202007151446482234_tao.php
> +        $listItemsTable = $schema->createTable(RdsValueCollectionRepository::TABLE_LIST_ITEMS);
I do not fully understand you. I extracted this table creation from Installation script.
Previously, we called installation script directly, and it was not so good.

2021-08-11 07:44 UTC, shpran commented on migrations/Version202108101839442234_tao.php
> +            [RdsValueCollectionRepository::FIELD_ITEM_ID]
Yes

2021-08-11 07:51 UTC, shpran commented on models/classes/Lists/Business/Service/RemoteSource.php
> +            $this->getFeatureFlagChecker()->isEnabled(
We cannot use `serviceLocator` inside the parser (I tried 😅).
If we want this - we need to propagate it before. So we will need to remember to propagate it in all other places.
In my case, if we forgot to provide feature flag in the context - it will be `false` by default

2021-08-11 07:53 UTC, shpran commented on models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
> +    private function deleteListItemsDependencies(QueryBuilder $query, string $valueCollectionUri): void
Thanks - I forgot about this

2021-08-11 07:56 UTC, shpran commented on models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
> +                    'list_item_id' => $qb->getConnection()->lastInsertId('list_items_id_seq'),
With postgres - yes (locally I worked with it).
I will configure playground to use `mysql`

2021-08-11 07:57 UTC, shpran commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_ADVANCED_SEARCH_DISABLED = 'FEATURE_FLAG_ADVANCED_SEARCH_DISABLED';
So, what should I do?

I will update the README.md file. Something else?

2021-08-11 08:02 UTC, shpran commented on migrations/Version202007151446482234_tao.php
> +        $fromSchema = clone $schema;
Nope.
Previously, we executed the installation script here.
In this case, if I will add something to the installation scrip - this may affect on this migration (or on the new ones). Because this migration will contain changes from installation scrip.
That's why I extracted old logic (list_items table creation) from installation script into this migration + I created a new migration for the new table.
And now I can safely update Installation script with my new table and I can be sure, that this will not affect on something except fresh installation.

2021-08-11 08:15 UTC, gabrielfs7 commented on models/classes/Lists/Business/Service/RemoteSource.php
> +            $this->getFeatureFlagChecker()->isEnabled(
Is it possible to make parser extend ConfigurableService?

2021-08-11 09:37 UTC, shpran commented on models/classes/Lists/DataAccess/Repository/RdsValueCollectionRepository.php
> +                    'list_item_id' => $qb->getConnection()->lastInsertId('list_items_id_seq'),
Checked with `postgres` and `mysql` - both work

2021-08-11 09:41 UTC, shpran commented on models/classes/Lists/Business/Service/RemoteSource.php
> +            $this->getFeatureFlagChecker()->isEnabled(
This may confuse you, but this parser already extend this ConfigurableService 😅

2021-08-11 09:43 UTC, gabrielfs7 commented on migrations/Version202007151446482234_tao.php
> +        $fromSchema = clone $schema;
Yes, I see your point and it might already have been happened. If you tested the migration it is ok then

2021-08-11 09:43 UTC, gabrielfs7 commented on migrations/Version202007151446482234_tao.php
> +                    'Table "%s" successfully dropped',
got it from previous comments, thanks!

2021-08-11 09:44 UTC, gabrielfs7 commented on migrations/Version202007151446482234_tao.php
> +        $listItemsTable = $schema->createTable(RdsValueCollectionRepository::TABLE_LIST_ITEMS);
Yes, not it is clear why you did this. :)

2021-08-11 10:08 UTC, shpran commented on models/classes/Lists/Business/Service/RemoteSource.php
> +            $this->getFeatureFlagChecker()->isEnabled(
Done. Will propagate parser during `getParser` method execution 🙂

2021-08-11 11:13 UTC, gabrielfs7 commented on models/classes/Lists/Business/Domain/Value.php
> +use JsonSerializable;
Why change the alphabetical order?

2021-08-11 11:16 UTC, gabrielfs7 commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_ADVANCED_SEARCH_DISABLED = 'FEATURE_FLAG_ADVANCED_SEARCH_DISABLED';
It is ok for me to keep it here, since core is used in all extensions and this is only about a feature flag mapping, we do not have the features logic here

2021-08-11 11:18 UTC, gabrielfs7 commented on scripts/install/CreateRdsListStore.php
> -    public function create(Schema $schema): void
Is it a breaking change?

2021-08-11 11:22 UTC, shpran commented on scripts/install/CreateRdsListStore.php
> -    public function create(Schema $schema): void
Nope - this method used only in this installation script.
Plus, as we know, installation scrip should be executed by `__invoke` method, that it's a bit strange that this method was public 😅 I will roll back to the previous name (to be sure that we will not break anything)

2021-08-11 11:56 UTC, gabrielfs7 approved these changes

2021-08-11 11:58 UTC, boajer commented on migrations/Version202007151446482234_tao.php
> +            ['autoincrement' => true]
Any change to avoid auto increments by design? That will not work with NewRDS

2021-08-11 12:00 UTC, boajer commented on models/classes/Context/AbstractContext.php
> +     * @param $parameterValue
```suggestion
     * @param mixed $parameterValue
```

2021-08-11 12:01 UTC, boajer commented on models/classes/Context/AbstractContext.php
> +     * @param $parameterValue
```suggestion
     * @param mixed $parameterValue
```

2021-08-11 12:04 UTC, boajer commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_ADVANCED_SEARCH_DISABLED = 'FEATURE_FLAG_ADVANCED_SEARCH_DISABLED';
Yes, lets keep readme updated, I've realized that plenty of people in the company not aware yet we have feature flags at all, not even speaking about which exactly we have. So Readme would be the first place to read about it

2021-08-11 12:05 UTC, boajer commented on scripts/install/CreateRdsListStore.php
> +            ['autoincrement' => true]
same as https://github.com/oat-sa/tao-core/pull/3045/files#r686760292

2021-08-11 12:06 UTC, boajer approved these changes
I would strongly encourage  to deal with https://github.com/oat-sa/tao-core/pull/3045/files#r686760292 before merging, meanwhile it's not a blocker 

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-08-11 12:07 UTC, gabrielfs7 commented on migrations/Version202007151446482234_tao.php
> +            ['autoincrement' => true]
@boajer this was previous existing logic that only supports RDS by default, so Andrei cannot remove it here, but I do agree with you :) 

We could add a techdebt for this (which was not created by our squad)

2021-08-11 12:40 UTC, shpran commented on models/classes/Lists/Business/Domain/Value.php
> +use JsonSerializable;
`JsonSerializable` (16 characters) is longer word, than `tao_helpers_Uri` (15 characters) 🙂
First I order by length, then - by alphabet

2021-08-11 12:43 UTC, gabrielfs7 commented on models/classes/Lists/Business/Domain/Value.php
> +use JsonSerializable;
PHPStorm orders by alphabet always, I am not sure we should create another type of ordering, but it is ok :)

2021-08-12 10:48 UTC, merged