Clicking 'Save' in Manage schema removes the chosen List from the added property
oat-sa/tao-core pull request #3049
Opened 2021-08-10 08:35 UTC by chinnu-focaloid

**Relates to** https://oat-sa.atlassian.net/browse/ADF-550
**Description**
Whenever user adds a property in manage schema, choose it's type then sets the list for it and clicks 'Save' first time, list set for this property is removed and user has to set it up again in order to save added property. Second click on 'Save' button saves the list.

2021-08-10 09:17 UTC, shpran requested changes

2021-08-10 09:17 UTC, shpran commented on actions/class.PropertiesAuthoring.php
> +                                $elementRangeArray[$index . "_range_list"] = $prop["range"];
1. Don't use double quotes if you don't need them
2. Are you sure, that `$prop['uri']['elements'][0]` exists every time?

```suggestion
                            if (!empty($prop['range'])) {
                                $index = strstr($groups['property_' . $prop['uri']]['elements'][0], '_', true);
                                $elementRangeArray[$index . '_range_list'] = $prop['range'];
```

2021-08-10 09:17 UTC, shpran commented on actions/class.PropertiesAuthoring.php
> +                            array_key_exists($element->getName(), $elementRangeArray)
Just a suggestion. Not necessary to fix it 🙂 
```suggestion
                            $element instanceof tao_helpers_form_elements_xhtml_Combobox
                            && array_key_exists($element->getName(), $elementRangeArray)
```

2021-08-10 12:07 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +                                $elementRangeArray[$index . "_range_list"] = $prop["range"];
Done. It seems that it exists every time. :-)

2021-08-11 06:08 UTC, boajer commented on actions/class.PropertiesAuthoring.php
> +                                $index = strstr($groups['property_' . $prop['uri']]['elements'][0], '_', true);
Suggestion, can we somehow modify code to have this logic which responsible for such index "unpacking" somewhere nearby to place where "packing" is being held? Otherwise it may be tricky to keep it always consistent or understand assumptions made to have this code working.

2021-08-11 06:10 UTC, boajer commented on actions/class.PropertiesAuthoring.php
> +                    foreach ($myForm->getElements() as $element) {
```suggestion
                    $elements = [];
                    foreach ($myForm->getElements() as $element) {
```

2021-08-11 11:44 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +                    if (isset($data['properties'])) {
You do not need this change. The issue is just an object state problem. I created a PR to fix it, take a look, please :) 

https://github.com/oat-sa/extension-tao-item/pull/503/files

2021-08-11 13:08 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +                    $myForm->setElements($elements);
Can we move the new logic to a separate method, like `private function populateSubmittedProperties($myForm, $data)`?

2021-08-11 13:59 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +                    if (isset($data['properties'])) {
After talking to @chinnu-focaloid we can stick to her solution, but moving to another method and making sure it also supports trees.

The reason is that, in case of errors, if we generate a new form, the errors will be lost.

2021-08-12 06:53 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +                    foreach ($myForm->getElements() as $element) {
Done

2021-08-12 06:53 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +                    $myForm->setElements($elements);
Done

2021-08-12 06:55 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +                                $index = strstr($groups['property_' . $prop['uri']]['elements'][0], '_', true);
Done this. Please check it has done correctly in the way you suggested?

2021-08-12 08:34 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +        foreach ($myForm->getElements() as $element) {
If there is not `$data['properties']` do we need to do this second loop?

2021-08-12 08:35 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +        }
You can avoid processment

```suggestion
        if (empty($data['properties'])) {
            return;
        }
        
        foreach ($data['properties'] as $prop) {
            if (!empty($prop['range'])) {
                $elementUri = $groups['property_' . $prop['uri']]['elements'][0];
                if (isset($elementUri)) {
                    $index = strstr($elementUri, '_', true);
                    $elementRangeArray[$index . '_range_list'] = $prop['range'];
                }
            }
         }
```

2021-08-12 08:37 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +        }
You are correct. I will change this

2021-08-12 08:39 UTC, shpran commented on actions/class.PropertiesAuthoring.php
> +        }
1. We can move `$grops` inside if-statement;
2. We should check that `$prop['range']` and `$prop['uri']` were provided;
3. If `$groups['property_' . $prop['uri']]['elements'][0]` not exists - we should use `?? null` for the next if-statement.

All these changes are not required, but WHAT IF...? 🙂😅 

Wdyt, @chinnu-focaloid @gabrielfs7 @boajer ?

```suggestion
        $elementRangeArray = [];

        if (isset($data['properties'])) {
            $groups = $myForm->getGroups();

            foreach ($data['properties'] as $prop) {
                if (isset($prop['range'], $prop['uri']) && !empty($prop['range'])) {
                    $elementUri = $groups['property_' . $prop['uri']]['elements'][0] ?? null;

                    if (isset($elementUri)) {
                        $index = strstr($elementUri, '_', true);
                        $elementRangeArray[$index . '_range_list'] = $prop['range'];
                    }
                }
            }
        }
```

2021-08-12 10:05 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +        }
Done

2021-08-12 10:05 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +        }
Done

2021-08-12 10:08 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +        foreach ($myForm->getElements() as $element) {
No

2021-08-12 11:30 UTC, gabrielfs7 approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-08-12 11:32 UTC, shpran commented on actions/class.PropertiesAuthoring.php
> +            }
@gabrielfs7 @chinnu-focaloid @boajer wdyt?
```suggestion
            if (empty($prop['range']) || empty($prop['uri'])) {
                continue;
            }
```

2021-08-12 11:37 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +            }
I resolved this.  Please check

2021-08-12 11:44 UTC, shpran approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2021-08-12 14:15 UTC, Natallia-Radkevich commented
QA verified on http://test-chinnufrancis.playground.kitchen.it.taocloud.org:48831/tao/Main

2021-08-13 04:54 UTC, merged