Task/aut 875/data testid attrs
oat-sa/tao-core pull request #3067
Opened 2021-08-18 12:00 UTC by AnastasiaArcadia

**Ticket:** https://oat-sa.atlassian.net/browse/AUT-949

**How to test:**
- Create item (test, asset) class
- Add properties
- Check that properties controls (inputs, textareas, etc.) have data-testid attrs
- Check that e2e tests run successfully

Export button was not affected as it's associated with changes in ui libs (like [here](https://github.com/oat-sa/tao-core-ui-fe/blob/master/src/loadingButton/tpl/button.tpl))

2021-08-18 13:13 UTC, bartlomiejmarszal commented on helpers/form/elements/xhtml/class.Button.php
> +    // Is the game worth the candle?
Yes it is. 
```suggestion
```

2021-08-18 13:13 UTC, bartlomiejmarszal approved these changes
BE changes approved

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-08-19 07:41 UTC, Silvia-loza reviewed
Confirmed that have data-testid attrs, however some of the tests don't pass when I run them locally,
 Perhaps something to do with  the environment I am testing with?

2021-08-19 14:46 UTC, Silvia-loza approved these changes
ALL looks good and all new Tests pass. Great job!
- [ ] New code is covered by tests (if applicable)
- [X] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2021-08-19 15:21 UTC, mike-ionut-mihai-sandu-tao requested changes
please change the target of your branch 
also please remove the debug information

2021-08-19 15:25 UTC, mike-ionut-mihai-sandu-tao commented on helpers/form/elements/xhtml/class.Button.php
> +        $this->setAttribute('data-testid', $testId);
please apply formating

2021-08-19 15:25 UTC, mike-ionut-mihai-sandu-tao commented on helpers/form/elements/xhtml/class.Readonly.php
> +        $returnValue .= "<input type='text' readonly='readonly' disabled='disabled' name='{$this->name}' id='{$this->name}' data-testid='{$this->getDescription()}' ";
are you sure that you can still access $this->getDescription() here?

2021-08-19 15:26 UTC, AnastasiaArcadia commented on helpers/form/elements/xhtml/class.Readonly.php
> +        $returnValue .= "<input type='text' readonly='readonly' disabled='disabled' name='{$this->name}' id='{$this->name}' data-testid='{$this->getDescription()}' ";
For me works
@pnal?

2021-08-19 15:26 UTC, mike-ionut-mihai-sandu-tao commented
please add inside the ticket where we can test this (as you did changes to prod code we need to validate that tao GUI is not breaking) so QA needs to check that before closing the ticket

2021-08-19 15:27 UTC, mike-ionut-mihai-sandu-tao commented
please also fix the tests as your change was broken them 
see here : http://qa.kitchen.it.taocloud.org/blue/organizations/jenkins/ci-pipeline-cg-extension-pr%2Ftao-core/detail/PR-3067/5/pipeline

2021-08-23 13:45 UTC, mike-ionut-mihai-sandu-tao approved these changes
lgtm

2021-08-23 13:45 UTC, mike-ionut-mihai-sandu-tao commented
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-08-23 14:57 UTC, merged