Counter service
oat-sa/tao-core pull request #3101
Opened 2021-09-06 12:19 UTC by alroniks

Counter service allows counting amount of calls of the event configured in the service.

For example, it used to count every delivery executions creation as well as delivery executions state changes to provide information for another system, for analyzing daily activity.

https://oat-sa.atlassian.net/browse/CGF-445

2021-09-07 16:26 UTC, SashaTAO approved these changes

2021-09-07 20:21 UTC, siwane reviewed
lgtm, some comments

2021-09-07 20:21 UTC, siwane commented on migrations/Version202108081928492234_tao.php
> +        $this->propagate(new RegisterCounterService)();
Should you register the service here?

2021-09-07 20:21 UTC, siwane commented on models/classes/counter/CounterService.php
> +    protected function getPersistence(): KeyValuePersistence
wdyt about putting visibility to private? it eases the maintenance and there is no value to inherit this method (as it is configurable)

2021-09-07 20:21 UTC, siwane commented on models/classes/counter/CounterService.php
> +    public function attach(string $eventFqcn, string $shortName, ?string $keyCallbackMethod = null): void
Attach and detach method should be part of the install and not part of the runtime. I think it is better to create another service to alter config folder

2021-09-07 20:26 UTC, siwane commented
Im wondering about the purpose of this PR.

2021-09-08 06:17 UTC, gabrielfs7 commented on scripts/install/RegisterCounterService.php
> +    protected function discoverPersistenceId(): ?string
As @siwane pointed, lets focus on least privilege principle and try to avoid protected/public unless they are required and are used.

It makes eayser to maintain code. Imagine that if you have a protected method/attribute/constant and have to change the signature it is already a **breaking change** and hard to track where is it used, since this is an open-source code.

2021-09-08 06:17 UTC, gabrielfs7 commented on scripts/install/RegisterCounterService.php
> +     */
No need for redundant annotations.

```suggestion
    /**
     * @throws ServiceNotFoundException
     * @throws InvalidServiceManagerException
     */
```

2021-09-08 06:19 UTC, gabrielfs7 commented on scripts/install/RegisterCounterService.php
> +         */
Why do you think this comment is necessary?

2021-09-08 06:21 UTC, gabrielfs7 commented on scripts/install/RegisterCounterService.php
> +         */
Why do you think this comment is necessary? It is implicit in TAO that a configurable service can be override by other extensions. We do not need to advertise it in everyplace we use :)

2021-09-08 06:22 UTC, gabrielfs7 commented on scripts/install/RegisterCounterService.php
> +        $this->logInfo($logMsg);
Unnecessary variable:

```suggestion
        $this->logInfo(
            sprintf(
                "Counter Service registered with persistence '${persistence}' and key prefix '%s'",
                CounterService::DEFAULT_PREFIX
            )
        );
```

2021-09-08 06:23 UTC, alroniks commented on scripts/install/RegisterCounterService.php
> +         */
Not my, it was Jerome's explanation, but I fully agree that it has to be there with an explanation of how it works. Code should be self-explanatory, but the logic behind not always clear. I prefer to leave it here.

2021-09-08 06:24 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +    protected const OPTION_SHORT_NAME = 'shortName';
https://github.com/oat-sa/tao-core/pull/3101/files#r704079172

```suggestion
    private const OPTION_CALLBACK = 'keyCallbackMethod';
    private const OPTION_SHORT_NAME = 'shortName';
```

2021-09-08 06:26 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +    protected function buildKey(string $eventFqcn, ?string $keySuffix = null): string
Keep least privilege in mind. It is very important to avoid extra maintenance costs.

https://github.com/oat-sa/tao-core/pull/3101/files#r704079172

Unnecessary annotation, we already have typehint and return types

```suggestion
    private function buildKey(string $eventFqcn, ?string $keySuffix = null): string
```

2021-09-08 06:26 UTC, alroniks commented on scripts/install/RegisterCounterService.php
> +         */
It is tao-core, root extension. I assume it is the best place to advertise such things. :) Even if we all know that it is possible, but newbies don't know it.

2021-09-08 06:27 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +class CounterService extends ConfigurableService
Unit tests?

2021-09-08 06:27 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +    protected function getPersistence(): KeyValuePersistence
https://github.com/oat-sa/tao-core/pull/3101/files#r704079172

2021-09-08 06:29 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +    protected function getPersistence(): KeyValuePersistence
Also, we can avoid redundant annotation when we have type hint/return type. Less code to read /maintain is always better :)

2021-09-08 06:30 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +        $persistence = KeyValuePersistence::getPersistence($persistenceId);
Is a static call the best way?

2021-09-08 06:32 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +    public function attach(string $eventFqcn, string $shortName, ?string $keyCallbackMethod = null): void
Suggestion: I would create an object (or array) to pass as parameter (This is a Command from CQRS). This list of params can grow/shrink and then we will have troubles extending it.

2021-09-08 06:33 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +    public function detach(string $eventFqcn): void
Suggestion: I would avoid redundant annotations and also import FGN

```suggestion
    /**
     * @throws InvalidServiceManagerException|CounterServiceException
     * @throws ServiceNotFoundException
     * @throws common_Exception
     */
    public function detach(string $eventFqcn): void
```

2021-09-08 06:35 UTC, gabrielfs7 commented
Code sniffing is breaking: http://qa.kitchen.it.taocloud.org/blue/organizations/jenkins/ci-pipeline-cg-extension-pr%2Ftao-core/detail/PR-3101/4/pipeline

2021-09-08 06:36 UTC, gabrielfs7 requested changes
Good job! 

Some required changes required:

- Least privilege
- Code sniffing is breaking http://qa.kitchen.it.taocloud.org/blue/organizations/jenkins/ci-pipeline-cg-extension-pr%2Ftao-core/detail/PR-3101/4/pipeline
- Missing unit tests

2021-09-08 06:36 UTC, gabrielfs7 commented on migrations/Version202108081928492234_tao.php
> + */
Not needed

```suggestion
```

2021-09-08 06:37 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +class CounterService extends ConfigurableService
Suggestion: I would create an interface for this service, since it seems it can be implemented in the feature with different approach

2021-09-08 06:39 UTC, alroniks commented on migrations/Version202108081928492234_tao.php
> +        $this->propagate(new RegisterCounterService)();
But it registers the service here. It uses a script, which is used for both cases, installation and updating. `RegisterCounterService` is an invokable script.

2021-09-08 06:43 UTC, alroniks commented on models/classes/counter/CounterService.php
> +        $persistence = KeyValuePersistence::getPersistence($persistenceId);
To change it need to refactor too deep things https://github.com/oat-sa/generis/blob/master/common/persistence/class.Persistence.php#L46, so I would say yes, no way.

2021-09-08 06:46 UTC, gabrielfs7 commented on scripts/install/RegisterCounterService.php
> +         */
I think it pollutes the codebase. I got many times outdated code, cause implementation changed and I never rely on comments, specially in TAO. 

Also this is describing how ConfigurableService works. The best place to advertise is in the README.md or user guide, not in the places that use it :) 

I think less is more, so less to read is always better

2021-09-08 06:49 UTC, gabrielfs7 commented on scripts/install/RegisterCounterService.php
> +         */
The code iterates an array and when find the key, returns it. Not sure we need an explanation for that. If KV is recommended, this might be the case now, but for other purposes, other infra, it could be different. This is a decision taken outside of the application, not to be documented here IMO, but this is my suggestion :)

2021-09-08 06:53 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +        $persistence = KeyValuePersistence::getPersistence($persistenceId);
You can use PersistenceManager

```
/** @var PersistenceManager $persistenceManager */
$persistenceManager = $this->getServiceManager()->get(PersistenceManager::SERVICE_ID);

$persistenceManager->getPersistenceById($persistenceId);
```

2021-09-08 07:44 UTC, SashaTAO commented on models/classes/counter/CounterService.php
> +    public function attach(string $eventFqcn, string $shortName, ?string $keyCallbackMethod = null): void
This service is quite simple and does exactly what it has to do - count registered events. Maybe it would be better to make it final and avoid customization? In this case we will have less issues, WDYT?

2021-09-08 08:00 UTC, gabrielfs7 commented on models/classes/counter/CounterService.php
> +    public function attach(string $eventFqcn, string $shortName, ?string $keyCallbackMethod = null): void
It is reasonable to say that in the future we might need to attach event timestamp, payload, userId or other data to provide to more granular counting metrics.

We cannot predict the future, but having a list of parameters like this (including one optional parameter) already gives a hint that this can change.

I would work with a context parameter https://github.com/oat-sa/tao-core/blob/master/models/classes/Context/ContextInterface.php

2021-09-10 09:49 UTC, alroniks commented on scripts/install/RegisterCounterService.php
> +         */
I moved this description from the method body to the method description, it should help with code readability itself, but I still want to save somewhere explanation. Sometimes it helps a lot especially you want to get a quick answer during support instead of digging the code.

2023-02-05 18:57 UTC, closed without merging