Task/aut 968/import item test
oat-sa/tao-core pull request #3123
Opened 2021-09-17 08:00 UTC by AnastasiaArcadia

**Related to:** https://oat-sa.atlassian.net/browse/AUT-968

Added import items tests

**How to test:**
- Run items test

2021-09-20 07:52 UTC, bziondik requested changes

2021-09-20 07:52 UTC, bziondik commented on views/cypress/support/commands.js
> +        }).then((el) => {
how we get here `el` if from previous Promise we receive boolean `true` or `false`?

2021-09-20 13:03 UTC, Silvia-loza approved these changes
All looks good and tests pass consistently.
- [ ] New code is covered by tests (if applicable)
- [X] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2021-09-23 10:36 UTC, bziondik approved these changes
- [x]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2021-09-23 14:11 UTC, merged