feat: add cache layer
oat-sa/tao-core pull request #3128
Opened 2021-09-23 07:07 UTC by chinnu-focaloid

Related to https://oat-sa.atlassian.net/browse/ADF-692

Description
Add cache layer to avoid searching for parent properties multiple times.

2021-09-23 07:14 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +        $this->getParentPropertyListCachedRepository()->deleteCache(
Why are we deleting cache every time now?

2021-09-23 07:15 UTC, gabrielfs7 commented on models/classes/Lists/Business/Contract/DependencyRepositoryInterface.php
> +    public function findAllChildListUris(): array;
This change does not belong to your PR. Maybe change the target branch here?

2021-09-23 07:15 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/DependencyRepository.php
> +    public function findAllChildListUris(): array
This change does not belong to your PR. Maybe change the target branch here?

2021-09-23 07:19 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +        $this->getParentPropertyListCachedRepository()->deleteCache(
Unless , the newly added property will not reflect in already existing list. When a new property add, We need to delete all existing cache to fetch from DB on next call

2021-09-23 07:20 UTC, chinnu-focaloid commented on models/classes/Lists/Business/Contract/DependencyRepositoryInterface.php
> +    public function findAllChildListUris(): array;
Here I am fetching all child lists in the table

2021-09-23 07:27 UTC, gabrielfs7 commented on models/classes/Lists/Business/Contract/DependencyRepositoryInterface.php
> +    public function findAllChildListUris(): array;
I am doing this in my PR https://github.com/oat-sa/tao-core/pull/3115/files#diff-7a8ee945aadcc4b40c9d6dac1f64e37ee47bd705c0874ba67977db73cb4bae89R38

2021-09-23 08:09 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +        $childListUris = $this->getDependencyRepository()->findAllChildListUris();
So if you DO pass a `propertyUri` as a filter you remove all the cache? what is the point of this parameter? DO you think it is easy to understand this?

2021-09-23 09:38 UTC, shpran commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +        if ($currentValues != $listCacheValues) {
Please, use strict comparison.

2021-09-23 09:38 UTC, shpran commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +                $string = explode('-', $value);
Can we rename `$string` to a more corresponding name?
We should be able to understand the variable value.

WDYT?

2021-09-23 09:38 UTC, shpran commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +                $this->getCache()->delete(sprintf(self::CACHE_MASK, $string[1], $string[2]));
1. Why we are using elements 1 and 2 instead of 0 and 1 ? (Just to understand 😅)
2. Are you sure, that we will have these elements every time?
3. If you are sure, you can replace `$string = explode('-', $value);` with `[$bla1, bla2, bla3] = explode('-', $value);` and use these variables 🙂 (But not required)

2021-09-23 13:31 UTC, chinnu-focaloid commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +        if ($currentValues != $listCacheValues) {
Done

2021-09-23 13:31 UTC, chinnu-focaloid commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +                $string = explode('-', $value);
Done

2021-09-24 07:03 UTC, gabrielfs7 commented on test/unit/models/classes/Lists/DataAccess/Repository/DependencyRepositoryTest.php
> +    public function findAllChildListUris(): void
This test is never execute if you do not put the prefix `test`. I already fixed, but this test was broken. We need to pay more attention on this @chinnu-focaloid

2021-09-24 07:03 UTC, gabrielfs7 commented on test/unit/models/classes/Lists/DataAccess/Repository/DependencyRepositoryTest.php
> +                    'parentListUris' => ['uri1']
This parameter does not exists and its value is a string, not an array. I already fixed, but we need to pay more attention on this @chinnu-focaloid

2021-09-24 07:05 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/DependencyRepository.php
> +                        ->andWhere($expressionBuilder->eq('items.list_uri', "'" . $options['parentListUri'] . "'"))
We should use prepared statement with biding for security reasons. I will fix, but we need to pay more attention on this @chinnu-focaloid

2021-09-24 10:36 UTC, shpran commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +                        ]);
Fix indentation

2021-09-27 06:33 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +                'listUri' => $listUri ?? $currentProperty->getRange()->getUri()
Will `$currentProperty->getRange()` always exist?

2021-09-27 06:35 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +        $this->getParentPropertyListCachedRepository()->deleteCache(
So we cache based on `range` (list uri), but even if the range was not changed we clear the cache? I am not sure I got the point.

2021-09-27 06:36 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +                        ]);
@chinnu-focaloid please fix indentation and add blank lines to separate blocks.

2021-09-27 06:36 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +        }
Please add blank line to help people read the code easily.

```suggestion
        $listCacheKey = sprintf(self::LIST_CACHE_MASK, $uri);
        
        if ($this->getCache()->has($listCacheKey)) {
            $listCacheValues = $this->getCache()->get($listCacheKey);
            
            foreach ($listCacheValues as $value) {
                [$key, $propertyUri, $listUri]  = explode('-', $value);
                $this->getCache()->delete(sprintf(self::CACHE_MASK, $propertyUri, $listUri));
            }
            
            $this->getCache()->delete($listCacheKey);
        }
```

2021-09-27 06:39 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +            $this->removeUsingListUri($options['listUri']);
We no longer need `$options['propertyUri']` as I saw. Why we're still receiving it? Why is this if required?

2021-09-27 06:40 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +        if ($this->getCache()->has($listCacheKey)) {
Small performance improvement. We need to store `$this->getCache()` in a variable instead of call it many times.

2021-09-27 06:41 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +        $listUri = $options['listUri'] ?? $property->getRange()->getUri();
Are we sure `$property->getRange()` will be present every time?

2021-09-27 06:50 UTC, gabrielfs7 requested changes
Some changes need to be done:

- $property->getRange() needs to be validated or we will have fatal error.
- Formatting/indentation needs to be fixed 
- Review cache removal logic, cause we require `propertyUri` which is not used.
- Optimize by avoiding calling `getCache` multiple times.

2021-09-27 06:51 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +                'listUri' => $listUri ?? $currentProperty->getRange()->getUri()
This triggers a fatal error in case I change the list from `-- select --` to `-- select --` and change property label.

2021-09-27 06:56 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +            return $this->getParentPropertyListRepository()->findAllUris($options);
The main class uses only `'listUri'` as filter, why would we pass property in the proxy? It is breaking he integrity.

2021-09-27 11:57 UTC, chinnu-focaloid commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +                        ]);
Done

2021-09-27 11:57 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +                'listUri' => $listUri ?? $currentProperty->getRange()->getUri()
Done

2021-09-27 11:57 UTC, chinnu-focaloid commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +        }
Done

2021-09-27 11:58 UTC, chinnu-focaloid commented on models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepository.php
> +        if ($this->getCache()->has($listCacheKey)) {
Done

2021-09-27 12:00 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +        if ($listUri === null || $currentProperty->getRange() === null) {
Are you sure this validation is correct?

2021-09-27 12:20 UTC, chinnu-focaloid commented on actions/class.PropertiesAuthoring.php
> +        if ($listUri === null || $currentProperty->getRange() === null) {
Done

2021-09-27 15:15 UTC, gabrielfs7 commented on actions/class.PropertiesAuthoring.php
> +        if (empty($listUri) && $currentProperty->getRange() === null) {
Remember this blank lines, please :D 

```suggestion
        }
        
        if (empty($listUri) && $currentProperty->getRange() === null) {
```

2021-09-28 06:25 UTC, gabrielfs7 commented on models/classes/Lists/DataAccess/Repository/DependencyRepository.php
> +                        ->andWhere($expressionBuilder->eq('items.list_uri', "'" . $options['parentListUri'] . "'"))
ping @chinnu-focaloid

2021-09-28 06:27 UTC, gabrielfs7 commented on test/unit/models/classes/Lists/DataAccess/Repository/ParentPropertyListCachedRepositoryTest.php
> +
No double lines, please

```suggestion
```

2021-09-28 06:42 UTC, chinnu-focaloid commented on models/classes/Lists/DataAccess/Repository/DependencyRepository.php
> +                        ->andWhere($expressionBuilder->eq('items.list_uri', "'" . $options['parentListUri'] . "'"))
Done

2021-09-28 08:01 UTC, gabrielfs7 approved these changes

2021-09-28 10:11 UTC, shpran approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-09-29 14:50 UTC, gabrielfs7 requested changes
@chinnu-focaloid Test is broken

2021-09-30 06:24 UTC, gabrielfs7 approved these changes

2021-09-30 07:03 UTC, merged

2021-09-30 10:26 UTC, AntonNeviarouski commented
QA verified