fix: float of slider handle for RTL support
oat-sa/tao-core pull request #3234
Opened 2021-11-16 17:04 UTC by shaveko

related to https://oat-sa.atlassian.net/browse/TR-2757

### Description

This PR fixes the styling for noUI slider used with SliderInteraction

To test you need to apply changes to `taoQtiItem/views/node_modules/@oat-sa/tao-item-runner-qti` from this brach `feat/TR-2757/slider-interaction-rtl`

🚩**NOTE** : publish and. update dependency for `tao-item-runner-qti-fe`

2021-11-17 07:56 UTC, marpesia requested changes

2021-11-17 07:56 UTC, marpesia commented on views/scss/inc/_jquery.nouislider.scss
> +  float: left;
Hi, I can't see any effect adding this style. I suggest removing it if it is not necessary.

2021-11-17 08:30 UTC, shaveko commented on views/scss/inc/_jquery.nouislider.scss
> +  float: left;
Sorry, may be I'm asking something very stupid: did you rebuild css after you remove this style from this scss?

2021-11-17 09:18 UTC, marpesia approved these changes
LGTM

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ]  Commits messages are meaningful
- [ ]  Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-11-17 21:04 UTC, meefox requested changes

2021-11-17 21:04 UTC, meefox commented on views/scss/inc/_jquery.nouislider.scss
> +  float: left;
I also didn't get the point for float here, 
it is a relative element that is surrounded by nothing. 
Or may I miss the point?

2021-11-18 08:49 UTC, meefox commented on views/scss/inc/_jquery.nouislider.scss
> +    &:before {
does it make any sense?

2021-11-18 13:44 UTC, shaveko commented on views/scss/inc/_jquery.nouislider.scss
> +  float: left;
> I also didn't get the point for float here, it is a relative element that is surrounded by nothing. Or may I miss the point?

here the main purpose of `float` is to specify the positioning inside the container, which is wrong for slider's logic if `rtl` direction is applied

2021-11-18 14:12 UTC, shaveko commented on views/scss/inc/_jquery.nouislider.scss
> +  -webkit-touch-callout: none;
done

2021-11-19 10:17 UTC, meefox approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-11-19 10:43 UTC, merged