fix: Skip call ElementMapFactory::withInstance() if the instance is not set
oat-sa/tao-core pull request #3244
Opened 2021-11-24 09:24 UTC by hectoras

**Associated Jira ticket:** [ADF-841](https://oat-sa.atlassian.net/browse/ADF-841)

This fixes calls being made when creating new instances from the remote publishing admin panel, as there is no instance then (and `null` is passed instead). `ElementMapFactory::withInstance()` will fail in such cases, as it expects a not-allow parameter.

2021-11-24 09:32 UTC, gabrielfs7 commented on actions/form/class.Instance.php
> +            }
PSR and strict check :) 

```suggestion
            $elementFactory = $this->getElementFactory();
            
            if ($instance instanceof core_kernel_classes_Resource) {
                $elementFactory->withInstance($instance);
            }
```

2021-11-24 09:42 UTC, hectoras commented on actions/form/class.Instance.php
> +            }
Realized that after pushing :sweat: Fixed in a4d454316c584f602b3b5e65f5e4200112a59a7f

As you suggested, I'm  changing the `null` comparison with `instanceof` as well in d410e8f624d05ff2740c191857a4c033af6e2783

2021-11-24 23:17 UTC, shpran approved these changes

2021-11-24 23:17 UTC, shpran commented on actions/form/class.Instance.php
> +            if ($instance instanceof core_kernel_classes_Resource) {
```suggestion
            $elementFactory = $this->getElementFactory();

            if ($instance instanceof core_kernel_classes_Resource) {
```

2021-11-25 07:57 UTC, gabrielfs7 commented on actions/form/class.Instance.php
> +            $elementFactory = $this->getElementFactory();
Please do not forget you also need to fix it here https://github.com/oat-sa/tao-core/blob/develop/helpers/form/ElementMapFactory.php#L222

2021-11-25 07:58 UTC, gabrielfs7 requested changes
Needs to fix here too https://github.com/oat-sa/tao-core/blob/develop/helpers/form/ElementMapFactory.php#L222

EDIT: Fixed in a918ca61be521f9c9f4ebd300de99cf6d29f0ec9

2021-11-25 09:44 UTC, hectoras commented on actions/form/class.Instance.php
> +            $elementFactory = $this->getElementFactory();
Fixed in a918ca61be521f9c9f4ebd300de99cf6d29f0ec9 & b4458c0fcc774117f919d1128089cf0784d75843

2021-11-25 09:50 UTC, hectoras commented on actions/form/class.Instance.php
> +            if ($instance instanceof core_kernel_classes_Resource) {
Added separation between blocks in 8854ea2be826e7e1ec71c4917c8047727ad10f2f  :+1:

2021-11-25 10:19 UTC, hectoras commented on actions/form/class.Instance.php
> +        // Add a hidden element for the class uri
Reverted 46afb28f82948efc58fb7d05307f5e52729bae28 :+1:

2021-11-25 10:35 UTC, gabrielfs7 approved these changes
Good job! 

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-11-26 14:21 UTC, hectoras commented
QA has verified this fix works as expected. Therefore, merging this fix back to the `develop` branch.

2021-11-26 14:25 UTC, merged