Feature/ADF-759/Efficient loading of lists with huge amount of elements
oat-sa/tao-core pull request #3270
Opened 2021-12-07 23:43 UTC by shpran

2021-12-09 10:09 UTC, hectoras commented on views/js/uiForm.js
> +                        type: 'GET',
_For reference: This matches [this change in the controller](https://github.com/oat-sa/extension-tao-backoffice/blob/8df36234c7e2ee6013bd834e206b27f535b745b1/controller/Lists.php#L234) to explicitly expect this to be passed as a GET parameter._

2021-12-13 18:57 UTC, gabrielfs7 commented on models/classes/Lists/Business/Specification/LocalListClassSpecification.php
> +        return $this->isBoolean($class) || !$this->remoteListClassSpecification->isSatisfiedBy($class);
- [ ] We need to revert this, this will bring a false positive in case of any class that is not a remote list (including Item class, Test class, etc)

2021-12-13 18:58 UTC, gabrielfs7 requested changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-12-13 19:44 UTC, shpran commented on models/classes/Lists/Business/Specification/LocalListClassSpecification.php
> +        return $this->isBoolean($class) || !$this->remoteListClassSpecification->isSatisfiedBy($class);
Are you sure?
We don't have remote Boolean lists. In this case you f class is Boolean - it's local list.
Or I'm wrong?

2021-12-14 07:26 UTC, gabrielfs7 commented on models/classes/Lists/Business/Specification/LocalListClassSpecification.php
> +        return $this->isBoolean($class) || !$this->remoteListClassSpecification->isSatisfiedBy($class);
Try to call this specification passing an object of class `http://www.tao.lu/Ontologies/TAOItem.rdf#Item` and you will see it returns true when should not, cause anything will be different of `$this->remoteListClassSpecification->isSatisfiedBy($class)`

2021-12-14 15:55 UTC, hectoras approved these changes

2021-12-15 09:06 UTC, hectoras commented on views/js/uiForm.js
>                                  }
Suggestion: Maybe it would be slightly better to use `Object.prototype.hasOwnProperty.call()` instead of calling the method directly on the object instance (ESLint would probbaly complain about this). See https://dev.to/aman_singh/what-s-the-deal-with-object-prototype-hasownproperty-call-4mbj,  https://stackoverflow.com/questions/12017693 & https://eslint.org/docs/rules/no-prototype-builtins

```suggestion
                                if (!Object.prototype.hasOwnProperty.call(response.data.elements, property)) {
                                    continue;
                                }
```

2021-12-17 05:39 UTC, gabrielfs7 commented on models/classes/Lists/Business/Domain/ValueCollectionSearchRequest.php
> +        return $this->offset > 0;
0 is a valid offset, I did not get your validation. Suggestion: 

```suggestion
        return $this->offset >= 0;
```

An you can make the default null

2021-12-17 05:40 UTC, gabrielfs7 commented on models/classes/Lists/Business/Domain/ValueCollectionSearchRequest.php
> +    private $offset = 0;
According to this comment https://github.com/oat-sa/tao-core/pull/3270/files#r771116688

```suggestion
    private $offset = null;
```

2021-12-17 07:47 UTC, gabrielfs7 approved these changes

2021-12-17 08:22 UTC, shpran commented on views/js/uiForm.js
>                                  }
Thanks for your suggestion 🙂
@bziondik @adriloma , can you please check this?

2021-12-17 08:34 UTC, shpran commented on models/classes/Lists/Business/Domain/ValueCollectionSearchRequest.php
> +        return $this->offset > 0;
Thanks, added. A bit modified your solution by additional check for null:
```php
return $this->offset !== null && $this->offset >= 0;
```
Because `null >= 0` is `true` - just to avoid this 🙂

2021-12-17 09:14 UTC, bziondik commented on views/js/uiForm.js
>                                  }
yes, it is correct

2021-12-17 12:15 UTC, AntonNeviarouski commented
QA Verified

2021-12-17 14:05 UTC, merged