Fix/ADF-865/Return empty dependencies list if feature flag is disabled
oat-sa/tao-core pull request #3271
Opened 2021-12-08 15:49 UTC by shpran

# [ADF-865](https://oat-sa.atlassian.net/browse/ADF-865)

## Changes
* Method `checkForDependency` will return an empty array if feature flag is disabled.
* If there's no `depends on property` value - use `' '` as a default value.

## How to test
1. Disable FEATURE_FLAG_LISTS_DEPENDENCY_ENABLED feature flag;
2. Create a new class or select an existing one;
3. Open schema managements;
4. Create new property;
5. Try to delete it.

**Previous behavior:** _nothing happens, property is not deleted, no errors, no calls on Network tab of Devtools._
**Current behavior:** _the confirmation pop-up message opens, property is removed after clicking `OK`._

2021-12-08 16:01 UTC, gabrielfs7 commented on views/js/uiForm.js
> +                const dependsOnValue = $($groupNode).find('select[id$="_depends-on-property"]').val() || ' ';
Does it need to be a 'space'?

2021-12-08 16:05 UTC, gabrielfs7 approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-12-08 16:08 UTC, shpran commented on views/js/uiForm.js
> +                const dependsOnValue = $($groupNode).find('select[id$="_depends-on-property"]').val() || ' ';
I don't know why, but we have a default value for select elements - `space`.
As you can see, we also check for this `space` in the `if-statement` - that's why I decided to use `space` also if this select is `undefined` - to avoid additional checks. (Code: https://github.com/oat-sa/tao-core/blob/de76ff82245aef0c4314b8172bb9515d8275e3c8/views/js/uiForm.js#L519)
```javascript
                const dependencies = await checkForDependency(uri, $groupNode);
                const dependsOnValue = $($groupNode).find('select[id$="_depends-on-property"]').val() || ' ';

                return new Promise((resolve, reject) => {
                    if (!dependencies.length && dependsOnValue === ' ') {
                        return regularConfirmantion() ? resolve() : reject();
                    }
```

But if you want, I can do differently:
```javascript
                const dependencies = await checkForDependency(uri, $groupNode);
                const dependsOnValue = $($groupNode).find('select[id$="_depends-on-property"]').val();

                return new Promise((resolve, reject) => {
                    if (!dependencies.length && (!dependsOnValue || dependsOnValue === ' ')) {
                        return regularConfirmantion() ? resolve() : reject();
                    }
```

2021-12-08 16:29 UTC, gabrielfs7 commented on views/js/uiForm.js
> +                const dependsOnValue = $($groupNode).find('select[id$="_depends-on-property"]').val() || ' ';
It is ok, I just wanted to understand. Thanks

2021-12-09 07:58 UTC, bziondik requested changes
need refactor to remove async/await

2021-12-09 07:58 UTC, bziondik commented on views/js/uiForm.js
>              async function checkForDependency(propertyUri, $groupNode) {
We can't use async/await, because we support IE11

2021-12-09 10:00 UTC, bziondik approved these changes
refactor will be in separate task
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ]  New code is respecting code style rules
- [ ]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2021-12-09 10:02 UTC, shpran commented on views/js/uiForm.js
>              async function checkForDependency(propertyUri, $groupNode) {
Will be covered in a [separate ticket](https://oat-sa.atlassian.net/browse/ADF-866)

2021-12-09 13:51 UTC, AntonNeviarouski commented
QA verified

2021-12-09 15:28 UTC, merged