fix/TR-3280/header-logo-support-rtl
oat-sa/tao-core pull request #3311
Opened 2022-01-03 16:02 UTC by marpesia

**Related to:** [TR-3280](https://oat-sa.atlassian.net/browse/TR-3280)

**Description:**
On RTL mode the logo on the Header keeps on the left. There is a CSS class that forces a `float: left`.
I've tracked the CSS class but I don't know the reason to have it. In order to avoid regression, I just disable the floating effect on RTL mode.

**Companion PR:**

- [Add CSS rule to disable `float: left` effect on RTL mode.](https://github.com/oat-sa/tao-core-ui-fe/pull/408)

**How to check:**

- It is failing only when any user is logged but Tao is on an RTL language. To change Tao language, go to `config/generis.conf.php` and change to `define('DEFAULT_ANONYMOUS_INTERFACE_LANG','ar-arb');` on line 47

**TAE Environment:**

- In progress

**Local test:**

- Link to Composer in the ticket https://oat-sa.atlassian.net/browse/TR-3280?focusedCommentId=167192

2022-01-04 08:57 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on playground (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-01-04 08:57 UTC, bziondik commented on views/package.json
> +        "@oat-sa/tao-core-ui": "github:oat-sa/tao-core-ui-fe#fix/TR-3280/header-logo-support-rtl",
Just reminder, to update after lib will be released

2022-01-04 09:14 UTC, krampstudio requested changes
I'd suggest you to reset the `clear` property either in [views/scss/layout.scss](https://github.com/oat-sa/tao-core/blob/master/views/scss/layout.scss) or maybe in the [views/scss/inc/_header-footer.scss](https://github.com/oat-sa/tao-core/blob/master/views/scss/inc/_header-footer.scss#L284)

2022-01-04 15:31 UTC, krampstudio commented
ok so the companion PR is not needed anymore, can you please close it and update the description.

2022-01-04 15:37 UTC, krampstudio reviewed
We can see quickly the logo on the left and then moving to the right, but I guess it's because the rtl dir is added after the page has loaded? 
 But after the logo is correctly positionned.

- [ ] New code is covered by tests (not applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] <s>New code is not subject to concurrency issues (if applicable)</s>
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2022-01-04 15:37 UTC, krampstudio approved these changes

2022-01-06 08:43 UTC, bziondik approved these changes

2022-01-07 16:07 UTC, krampstudio approved these changes
The update looks good to me.

2022-01-10 10:19 UTC, merged