Draft: feat: Do not ksort list items if they are from types that are already sorted
oat-sa/tao-core pull request #3312
Opened 2022-01-04 15:53 UTC by hectoras

Associated Jira task: [ADF-870](https://oat-sa.atlassian.net/browse/ADF-870)

2022-01-11 09:23 UTC, mike-ionut-mihai-sandu-tao requested changes
it looks like a nice coded solution but we need to think about performance also , 
so please reconsider and do not replace ksort with a functionality that has very expensive calls

2022-01-11 09:23 UTC, mike-ionut-mihai-sandu-tao commented on helpers/form/ElementMapFactory.php
> +use oat\tao\model\Lists\Business\Specification\PresortedListSpecification;
can you optimize the imports please ,  as i assume the addon was just done on top

2022-01-11 09:23 UTC, mike-ionut-mihai-sandu-tao commented on helpers/form/ElementMapFactory.php
> +        $parentProperty = null;
why ?

2022-01-11 09:23 UTC, mike-ionut-mihai-sandu-tao commented on helpers/form/ElementMapFactory.php
> +                        ksort($options);
why do we need the ksort at all ?

2022-01-11 09:23 UTC, mike-ionut-mihai-sandu-tao commented on models/classes/Lists/Business/Specification/PresortedListSpecification.php
> +class PresortedListSpecification implements PropertySpecificationInterface
so instead of a ksort we are creating a new service that will setup a new core_kernel_classes_Class inside the constructor
and that does a very expensive get `getRange()` and some other logic 

i think this is a bit too much and will cost and decrease the performance

2022-01-11 09:23 UTC, andreluizmachado commented on helpers/form/ElementMapFactory.php
> +        $parentProperty = null;
I believe that you do not need to initiate this variable here as you already do in line 105. Could you check it, please?

2022-01-11 09:39 UTC, andreluizmachado commented on models/classes/Lists/Business/Specification/PresortedListSpecification.php
> +
is it possible to add strict_types declaration?

2022-01-11 09:39 UTC, andreluizmachado commented on test/unit/models/classes/Lists/Business/Specification/PresortedListSpecificationTest.php
> + * Copyright (c) 2021 (original work) Open Assessment Technologies SA;
2022

2022-01-11 09:39 UTC, andreluizmachado commented on test/Asset/CustomRootClassFixture.php
> +class CustomRootClassFixture extends core_kernel_classes_Class
Do we really need to create this stub class? Can't it be done by using mockBuilder? maybe an anonymous class?

2022-01-13 08:52 UTC, shpran commented on helpers/form/ElementMapFactory.php
> +        $parentProperty = null;
I think he added this to avoid a possible issue at [line 144](https://github.com/oat-sa/tao-core/blob/d61675218da1ff0a9cfb58562817bbf86d791caa/helpers/form/ElementMapFactory.php#L144)

As you can see there, we use this `$parentProperty`, but previously we initialized this one inside if-statement, so sometimes our property was not exists and might fail at this line.

2022-01-13 08:52 UTC, shpran commented on models/classes/Lists/Business/Specification/PresortedListSpecification.php
> +class PresortedListSpecification implements PropertySpecificationInterface
https://github.com/oat-sa/tao-core/pull/3312#discussion_r783749039

2022-01-13 08:52 UTC, shpran commented on helpers/form/ElementMapFactory.php
> +        $parentProperty = null;
https://github.com/oat-sa/tao-core/pull/3312#discussion_r783749039

2022-01-13 10:23 UTC, shpran commented on helpers/form/ElementMapFactory.php
> +                        ksort($options);
I'm not sure, that we need this one, but I decided to keep this one to avoid any unexpected issues.

At the moment, I removed specification and moved `ksort` inside the if statement.
So, we will not use `ksort` for lists (local or remote), but we will keep this one for other properties, like `Item Model`, `Roles`, etc.
(In accordance with the task ACs)

Pint @mike-ionut-mihai-sandu-tao

2022-01-13 10:38 UTC, andreluizmachado commented on helpers/form/ElementMapFactory.php
> + * Copyright (c) 2020-2022 (original work) Open Assessment Technologies SA;
Do we already have automated tests covering these changes?

2022-01-13 10:38 UTC, andreluizmachado commented on helpers/form/ElementMapFactory.php
>                          $sortedOptions[$values[0]] = $values[1];
What is value[0] and value[1]? shouldn't we validate if they are set or not?

2022-01-13 10:43 UTC, shpran commented on helpers/form/ElementMapFactory.php
> + * Copyright (c) 2020-2022 (original work) Open Assessment Technologies SA;
Nope, we didn't have any tests covering sorting

2022-01-13 11:06 UTC, shpran commented on helpers/form/ElementMapFactory.php
>                          $sortedOptions[$values[0]] = $values[1];
Updated - now these variables are named.
About validation - there's no need, because we are filling this `$options` a bit upper 🙂

2022-01-13 13:25 UTC, andreluizmachado approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-01-13 15:56 UTC, bartlomiejmarszal requested changes
Why there is no unit tests?

2022-01-13 16:59 UTC, shpran commented
> Why there is no unit tests?

Will be covered by unit tests in a separate task to avoid blocking the task, as this one is a sprint goal.
https://oat-sa.atlassian.net/browse/ADF-922

2022-01-14 08:03 UTC, bartlomiejmarszal approved these changes
LGTM

2022-01-14 08:47 UTC, hectoras commented on helpers/form/ElementMapFactory.php
> +                        ksort($options);
`ksort` is the former behavior.

Here I was keeping the call to `ksort()` for widget types that are not listed in the acceptance criteria from the ticket: For what I remember, the change to keep the former order should be applied only to:

-  _Single choice lists with Radio buttons_ ("list", `tao_helpers_form_elements_Radiobox::WIDGET_ID`)
-  _Single choice lists with Drop downs_ ("longlist", `tao_helpers_form_elements_Combobox::WIDGET_ID`) 
- `Multiple choice lists with Check box` ("multilist", `tao_helpers_form_elements_Checkbox::WIDGET_ID`)

My idea was to use `PresortedListSpecification` to check if the list was for one of those types and, only in that case, skip the `ksort` call.

2022-01-14 09:42 UTC, hectoras commented on models/classes/Lists/Business/Specification/PresortedListSpecification.php
> +class PresortedListSpecification implements PropertySpecificationInterface
Please note `getRange()` call was already being called by the former code, here I was just moving that call along with the logic for what should and what should not be sorted to a separate class.

2022-01-14 10:59 UTC, AntonNeviarouski commented
QA verified

2022-01-14 11:26 UTC, merged

2022-01-14 13:52 UTC, hectoras commented on helpers/form/ElementMapFactory.php
> + * Copyright (c) 2020-2022 (original work) Open Assessment Technologies SA;
My former idea was to move the logic that checks if a list has to be sorted to a specification class (`PresortedListSpecification`) and test that part independently.