Fix/tr 3287/update raphael and eve
oat-sa/tao-core pull request #3320
Opened 2022-01-12 10:23 UTC by krampstudio

Related to https://oat-sa.atlassian.net/browse/TR-3287

 - update rahpael to 2.3.0 in order to get rid of the subdependency to `eve` using `git://`
 - remove the local copy of raphael :exploding_head: 
 - link the node_modules copy in requires mapping

**How to test**
 - test graphic interaction in debug mode
 - rebundle locally (`cd tao/views/build && npm i && npx grunt bundleall`) and test again the graphic interactions

2022-01-12 10:33 UTC, wazelin requested changes

2022-01-12 10:33 UTC, wazelin commented on views/build/config/requirejs.build.json
> +    "raphael": "../../../tao/views/node_modules/raphael/raphael",
```suggestion
    "raphael": "../node_modules/raphael/raphael",
```

2022-01-12 10:43 UTC, wazelin commented
Not sure why we have [this version here](https://github.com/oat-sa/tao-core/blob/8f7a6465b7d5691120ce289f7fc44960044deede/views/package.json#L3) in the first place, but should we also update it?

2022-01-12 15:38 UTC, krampstudio commented
> Not sure why we have [this version here](https://github.com/oat-sa/tao-core/blob/8f7a6465b7d5691120ce289f7fc44960044deede/views/package.json#L3) in the first place, but should we also update it?
npm requires a version but for publishing, we should rather investigate if we mark the package as [private](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#private) we can remove it. 
I guess for another PR...

2022-01-12 16:30 UTC, wazelin approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2022-01-13 09:39 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

**Lines became thicker**
![image](https://user-images.githubusercontent.com/25976342/149304818-2e23ee1c-b88f-4f6f-8bdf-252360f9c3c1.png)

2022-01-13 15:09 UTC, merged