Feature/ADF-894/Bulk Import of item/test statistical metadata
oat-sa/tao-core pull request #3325
Opened 2022-01-13 01:27 UTC by shpran

# [ADF-894](https://oat-sa.atlassian.net/browse/ADF-894)

## How to test
1. Create any item/test properties
2. Create aliases for them
3. Create items/tests
4. Create CSV file in the following format:
    | itemId | testId | metadata_{alias1} | metadata_{alias2} | ... | metadata_{aliasN} |
    | --- | --- | --- | --- | --- | --- |
    | item 1 URI | OR Test 1 URI | Value 1 (can be empty) | Value 2 (can be empty) | ... | Value N (can be empty) |
    | item 2 URI | OR Test 2 URI | Value 1 (can be empty) | Value 2 (can be empty) | ... | Value N (can be empty) |

    Notes:
    * `itemId` - required if `testId` not provided
    * `testId` - required if `itemId` not provided
    * `alias1`, `alias2`, `aliasN` - necessary property aliases
    * delimiter - `;`
5. Open `Import statistical analysis metadata` page
6. Import CSV file
7. Check items/tests property values.

2022-01-13 13:14 UTC, pnal approved these changes
Good job!
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2022-01-13 14:26 UTC, bartlomiejmarszal requested changes
Missing unit test

2022-01-13 14:26 UTC, bartlomiejmarszal commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +    public function process(File $file): Report
There is no way to approve this without unit tests.

2022-01-13 14:27 UTC, andreluizmachado commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +    public function process(File $file): Report
According to what i saw, they plan to fix this technical debit on ticket https://oat-sa.atlassian.net/browse/ADF-922

2022-01-13 14:28 UTC, shpran commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +    public function process(File $file): Report
I already created a separate ticket to add unit tests (so as not to block this task as this one is a sprint goal): https://oat-sa.atlassian.net/browse/ADF-922

2022-01-13 14:32 UTC, andreluizmachado requested changes

2022-01-13 14:32 UTC, andreluizmachado commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +        $metadataUris = $this->extractMetadataUris(fgetcsv($stream, 0, ';'));
What happens if we have a big file? we can explode PHP memory here, no?

2022-01-13 14:41 UTC, andreluizmachado requested changes

2022-01-13 14:41 UTC, andreluizmachado commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +        while ($line = fgetcsv($stream, 0, ';')) {
duplication of `fgetcsv($stream, 0, ';')`

2022-01-13 14:41 UTC, andreluizmachado commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +        while ($line = fgetcsv($stream, 0, ';')) {
Don't we have something better to read csv? EX: League\Csv\Reader

2022-01-13 14:41 UTC, andreluizmachado commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +            if ($line[0] === null) {
What is line[0]. Can we validate it (isset)?

2022-01-13 14:41 UTC, andreluizmachado commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +    private function replaceMetadataWithUris(array &$metadata): void
I'd avoid pointer and return the replaced metadata instead.

2022-01-13 14:41 UTC, andreluizmachado commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +     * @return string[]
I believe you can remove this comment

2022-01-13 14:45 UTC, bartlomiejmarszal reviewed
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2022-01-13 14:45 UTC, bartlomiejmarszal commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +                continue;
Shouldn't we log warning if resource was not found?

2022-01-13 14:45 UTC, bartlomiejmarszal commented on models/classes/import/service/AgnosticImportHandler.php
> +    public const STATISTICAL_METADATA_SERVICE_ID = self::class . '::STATISTICAL_METADATA';
What is that constant for?

2022-01-13 14:51 UTC, shpran commented on models/classes/import/service/AgnosticImportHandler.php
> +    public const STATISTICAL_METADATA_SERVICE_ID = self::class . '::STATISTICAL_METADATA';
By default, we use class name as ID to register it in DI container.
But sometimes we need to use different configuration for the same class.
As this class is agnostic and might be used with different processors for different purposes, I created this constant to register this class with a specific processor.

https://github.com/oat-sa/tao-core/pull/3325/files#diff-805ecd3fd323d354f3b22c266437d92bc2e449004cf776227adf1121f0474ee9R48-R67

Right now, I can receive this agnostic handler with setted processor and label by this ID.

2022-01-13 14:53 UTC, shpran commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +                continue;
We can, but I thought, that I will do this during next task: https://oat-sa.atlassian.net/browse/ADF-905

As you can see, during this task we will improve reporting, so at the same time we can improve logging here.
But if you want, I can easily add some logs right now 🙂

2022-01-13 16:50 UTC, shpran commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +        while ($line = fgetcsv($stream, 0, ';')) {
> Don't we have something better to read csv? EX: League\Csv\Reader

At the moment, we are not using `League\Csv\Reader` or something like this.
As I see, we use simple PHP functions `fgetcsv` and `str_getcsv`.

I can add `League\Csv\Reader` in future task.

> duplication of fgetcsv($stream, 0, ';')

During first call we are receiving header (metadata URIs). 
Then inside `while` we use this call to go through the content.
This was done to avoid `if`-statement inside `while` to receive header. Imagine, that during each iteration we will check if `$header` isset or that this is first line (header) - a lot of unnecessary checks.

2022-01-13 16:55 UTC, shpran commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +            if ($line[0] === null) {
> What is line[0]?

`$line[0]` - if file contains empty line - array will use a single `null` element.
E.g.
```csv
val0_1;val0_2;val0_3
val1_1;val1_2;val1_3
// empty line
```
Lines will be:
```php
[
    ['val0_1', 'val0_2', 'val0_3'],
    ['val1_1', 'val1_2', 'val1_3'],
    [null],
]
```

> Can we validate it (isset)?

Yes, I will use `isset($line[0])` instead;

2022-01-13 16:57 UTC, shpran commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +        $metadataUris = $this->extractMetadataUris(fgetcsv($stream, 0, ';'));
During the HLE we decided, that `file size won't be bigger than 1MB or 100 items.`
So, I think, that we will not have any issues with this. 🙂

2022-01-14 12:43 UTC, bartlomiejmarszal commented on models/classes/StatisticalMetadata/Import/Processor/ImportStatisticalMetadataProcessor.php
> +    public function process(File $file): Report
Why create separate ticket for unit tests. In this case where we have a new class it's pointless to review code that has no unit test cause it's more difficult to understand what a code actually doing.

2022-01-17 09:39 UTC, hectoras approved these changes
LGTM

Checked with a demo the functionality works as expected. Unit tests will be added as part of [ADF-922](https://oat-sa.atlassian.net/browse/ADF-922).

2022-01-17 10:00 UTC, merged