Draft: feature/ADF-869: Delete previous statements for a property when edited with an empty value
oat-sa/tao-core pull request #3339
Opened 2022-01-17 17:56 UTC by hectoras

**Associated Jira issue:** [ADF-869](https://oat-sa.atlassian.net/browse/ADF-869)

2022-01-19 12:19 UTC, shpran requested changes
Great job!
Left some comments and suggestions 🙂

I didn't comment the whole test (only first test method), as it contain the same issues - please, fix them in accordance with the comments 👨🏻‍💻

2022-01-19 12:19 UTC, shpran commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        return (('' == $value) || (' ' == $value) || strlen(trim($value)) == 0);
1. Please, use strict comparison
2. There's no need to wrap these comparisons with brackets
3. Maybe we can use `empty(trim($value))` instead?
```php
return empty(trim($value));
```

2022-01-19 12:19 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            );
```suggestion
        $this->sut = new tao_models_classes_dataBinding_GenerisInstanceDataBinder(
            $this->resource,
            $this->eventManagerMock
        );
```

2022-01-19 12:19 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->with($this->callback(function (MetadataModified $e): bool {
Please use a better variable name.

2022-01-19 12:19 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    && ($e->getMetadataValue() == 'Value 1'));
1. Please, use strict comparison
2. There's no need to wrap these comparisons with brackets

2022-01-19 12:19 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->with($this->callback(function (core_kernel_classes_Class $c) {
Please use a better name for the property.

2022-01-19 12:19 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                return ($c->getUri() == self::URI_TYPE_1);
1. Please, use strict comparison
2. There's no need to wrap these comparisons with brackets

2022-01-19 12:19 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                new core_kernel_classes_Class(self::URI_TYPE_1)
Please, return configured mock object

2022-01-19 12:19 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    if ($property->getUri() == self::URI_PROPERTY_1) {
Please, use strict comparison

2022-01-19 12:19 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    $this->fail("Unexpected property: {$property->getUri()}");
```suggestion
                    $this->fail('Unexpected property: ' . $property->getUri());
```

2022-01-19 12:19 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                function (core_kernel_classes_Property $property, $_ = null) {
Please use a better variable name (`$_`).

2022-01-19 12:19 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    return ($property->getUri() == self::URI_PROPERTY_1);
Please, use strict comparison.

2022-01-19 12:19 UTC, shpran commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        EventManager $eventManager = null
I'm not sure about providing here a second parameter, as this class is initializable and fully relates to work with `instance`. So, this one will not be automatically configured by DI container.

As I understood, you added this one for testing.
Maybe using a method `withEventManager` would be better?

It's just a suggestion 🙂 
WDYT?

2022-01-19 13:05 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +                if (($propUri == OntologyRdf::RDF_TYPE) && (null != $value)) {
Whoops, missed that one. Changed here :point_right:  3cc111e1933bf4656807826bdae50570174a949d, thanks! :+1:

2022-01-19 13:05 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +                    "Error binding property values to instance '%s': %s",
You're right , it is better that way. Changed here :point_right: 3cc111e1933bf4656807826bdae50570174a949d, thanks! :+1:

2022-01-19 13:15 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        EventManager $eventManager = null
Yes, this was just for testing, since right now this class is used by instantiating it directly instead of using the DI container nor `ServiceManager`.

Changed in 55b97cd74ac968e3e79a0e98879fc3072fc92637 to inject the `EventManager` in tests with a new setter method (used only from tests).

2022-01-19 14:01 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        return (('' == $value) || (' ' == $value) || strlen(trim($value)) == 0);
Changed to strict comparison (since a type coercion to string has already been done because of the type hint of `$value`), as well as unwrapped the expressions (removed the parenthesis) in 6c1d423b2096038d8351f1ada89d421523cfce60 :+1: Thanks!

Regarding the third point, I think we cannot use `empty()` in this method, since that would handle a literal zero (`"0"`) as an empty value, and we only want to handle as such strings containing only whitespaces. I've just checked just in case:

```
hector@hector-oat:~/snippets$ cat empty-with-zero-str.php 
<?php
$value = '0';

if (empty(trim($value))) {
	echo "Oh no :(" . PHP_EOL;
}
hector@hector-oat:~/snippets$ php empty-with-zero-str.php 
Oh no :(
hector@hector-oat:~/snippets$ 
```

2022-01-19 16:21 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        $prop = new core_kernel_classes_Property($propertyUri);
Done! 5acd1b9a189ea65bcef831f5e6f898f55069cceb :+1:

2022-01-19 16:21 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +            $instance->setType(new core_kernel_classes_Class($type));
Done! 5acd1b9a189ea65bcef831f5e6f898f55069cceb :+1:

2022-01-20 09:52 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->with($this->callback(function (MetadataModified $e): bool {
Changed in 28de603eecea5195605434e6dfc091abb57fc57b :ok_hand:

2022-01-20 09:52 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            );
Changed in 28de603eecea5195605434e6dfc091abb57fc57b, but I'm not completely sure about this one. [PSR-12](https://www.php-fig.org/psr/psr-12/) states that "Lines SHOULD NOT be longer than 80 characters; lines longer than that SHOULD be split into multiple subsequent lines of no more than 80 characters each". 

The class name alone is already 56 chars long, so I think putting it in the next line is the only way to keep the lines short. By the way, putting it as a single line will make it 83 chars, so I'll do it that way as you suggested as it is still not too long.

2022-01-20 09:52 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    && ($e->getMetadataValue() == 'Value 1'));
Changed in 28de603eecea5195605434e6dfc091abb57fc57b :ok_hand:

2022-01-20 09:52 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->with($this->callback(function (core_kernel_classes_Class $c) {
Changed in 28de603eecea5195605434e6dfc091abb57fc57b :ok_hand:

2022-01-20 09:52 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                return ($c->getUri() == self::URI_TYPE_1);
Changed in 28de603eecea5195605434e6dfc091abb57fc57b :ok_hand:

2022-01-20 09:54 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        return (('' == $value) || (' ' == $value) || strlen(trim($value)) == 0);
TODO
- [ ] Add a unit test for checking "0" is not handled as an empty value

2022-01-20 10:04 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    $this->fail("Unexpected property: {$property->getUri()}");
Changed in 5b06cbb3c967251292b1811c866280f51a2c8306 :+1:

2022-01-20 10:04 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    if ($property->getUri() == self::URI_PROPERTY_1) {
Changed in 5b06cbb3c967251292b1811c866280f51a2c8306 :+1:

2022-01-20 10:06 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    return ($property->getUri() == self::URI_PROPERTY_1);
Changed in 5b06cbb3c967251292b1811c866280f51a2c8306 :+1:

2022-01-20 10:16 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                function (core_kernel_classes_Property $property, $_ = null) {
Changed: c8385d39e8a9cd846f26f0898e07f7ad93d9c77b :ok_hand:

2022-01-20 10:25 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                new core_kernel_classes_Class(self::URI_TYPE_1)
Missed that one, changed in 55bef0e7ea387769500e5a420b626e2a178e7a8f. Thanks!

2022-01-20 10:40 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        return (('' == $value) || (' ' == $value) || strlen(trim($value)) == 0);
Added a unit test in 0e59c66a3cd9f8d7cd447867fc32d8c7663c63c9 that checks if setting a property value to zero works as expected (i.e. calls `$target->setPropertyValue($property, '0')`).

As expected, changing the implementation for `isEmptyValue()` to use `empty(trim($value))` makes the test fail.

2022-01-24 08:46 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        return (('' == $value) || (' ' == $value) || strlen(trim($value)) == 0);
I think things raised in this thread regarding coding standards and using strict comparison have been already addressed, and we've checked if we can use `empty()` instead of `strlen()` here (as well as added a unit test to ensure a literal zero is not handled as an empty value).

Therefore, I'm marking this thread as solved, but please feel free to reopen it if you think I'm missing something :smile:

2022-01-24 08:58 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +                $instance->removePropertyValues($property);
Note this is the primary change introduced by this pull request (initially committed in 7c43473e4eb7d976e4861f02f2ada6d54415dd14).

If the value is considered empty (an empty string, or a string containing only whitespaces) and we are editing a scalar field, we unconditionally remove the values for this property under this instance (previously we were doing so with `$instance->removePropertyValues($property, ['pattern' => ''])`, which doesn't work in Postgres as expected).

Other things should work as they did, this pull request just refactor them to be easier to follow.

2022-01-24 09:17 UTC, shpran requested changes

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            }));
```suggestion
            ->with($this->callback(function (core_kernel_classes_Property $property) {
                return $property->getUri() === self::URI_PROPERTY_1;
            }));
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            }));
I saw, that you repeat this one multiple times. Maybe you can extract this into a separate method and use it instead?
WDYT?

1. There's no need to wrap such condition with brackets
2. Use strict comparison
```suggestion
            ->with(
                $this->callback(
                    function (MetadataModified $event): bool {
                        return $event->getResource()->getUri() === $this->target->getUri()
                            && $event->getMetadataUri() === self::URI_PROPERTY_1
                            && $event->getMetadataValue() === 'Value 1';
                    }
                )
            );
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    }
```suggestion
                    if (in_array($property->getUri(), [self::URI_PROPERTY_1, self::URI_PROPERTY_2], true)) {
                        return $this->nonEmptyCollectionMock;
                    }
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                }
```suggestion
                function (core_kernel_classes_Property $property, $opts = []) {
                    $this->assertEquals(self::URI_PROPERTY_1, $property->getUri());
                }
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->expects(self::never())
```suggestion
            ->expects($this->never())
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->expects(self::exactly(1))
```suggestion
            ->expects($this->exactly(1))
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->expects(self::exactly(1))
```suggestion
            ->expects($this->exactly(1))
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->expects(self::never())
```suggestion
            ->expects($this->never())
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    }
```suggestion
                    if (in_array($property->getUri(), [self::URI_PROPERTY_1, self::URI_PROPERTY_2], true)) {
                        return $this->emptyCollectionMock;
                    }
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                        return ($property->getUri() === self::URI_PROPERTY_1);
```suggestion
                        return $property->getUri() === self::URI_PROPERTY_1;
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    function (core_kernel_classes_Property $property, $_value = null) {
```suggestion
                    function (core_kernel_classes_Property $property, $value = null) {
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->willThrowException(new Exception("error", 123));
```suggestion
            ->willThrowException(new Exception('error', 123));
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +        );
```suggestion
        $this->expectExceptionMessage('Error binding property values to instance');
```

2022-01-24 09:17 UTC, shpran commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +    }
Do we really need this method?
Not critical, you can keep this one if you want 🙂

2022-01-24 10:19 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +            foreach ($data as $propUri => $value) {
I agree. I think this was shortened to keep the lines short (as we had more than 3 levels of indentation), but it is now unneeded since most of the logic like that has been moved to separate methods.

Changed in 0b71577f5446ddb457cc71cd8d70c3b003065872 :+1:

2022-01-24 10:20 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        core_kernel_classes_Resource &$instance,
Removed pass-by-reference declaration in 0b71577f5446ddb457cc71cd8d70c3b003065872 :+1:

2022-01-24 10:20 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        foreach ($types as $type) {
Changed in 0b71577f5446ddb457cc71cd8d70c3b003065872 :+1:

2022-01-24 10:21 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +    private static function isEmptyValue(string $value): bool
Changed in 0b71577f5446ddb457cc71cd8d70c3b003065872 :+1:

2022-01-24 10:21 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        if ($this->eventManager == null) {
Changed in 0b71577f5446ddb457cc71cd8d70c3b003065872 :+1:

2022-01-24 10:41 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    function (core_kernel_classes_Property $property, $_value = null) {
Changed: 4ce6e76e6ee334de1160502f796c2e59187e35c5 :+1:

2022-01-24 10:42 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    function (core_kernel_classes_Property $property, $_value = null) {
Changed: 4ce6e76e6ee334de1160502f796c2e59187e35c5 :+1:

2022-01-24 10:50 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +        );
This was put this way to conform to [PSR-12](https://www.php-fig.org/psr/psr-12/) soft limit on line length.

BTW I'm changing it in 47e54e9a5c0d33c8198b547bfad98cf9807cbb11.

2022-01-24 10:59 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                        return ($property->getUri() === self::URI_PROPERTY_1);
Missed that one, changed on d9d2097b62f2e37fadea731930defb60dd728246.

BTW I generally prefer being explicit when I'm using the result of a condition as a (boolean) value, or when combining multiple boolean expressions on conditional ("`if`") statements), for the reasons stated on this SO comment: https://softwareengineering.stackexchange.com/a/201187

2022-01-24 11:07 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                        return ($property->getUri() === self::URI_PROPERTY_1);
Changed in ac23cd5cb705abff473deca0cc3a43b5ac8a3868 (see https://github.com/oat-sa/tao-core/pull/3339#discussion_r790629100 for the rationale for wrapping it with parenthesis).

2022-01-24 11:07 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                return ($class->getUri() === self::URI_TYPE_1);
Changed in ac23cd5cb705abff473deca0cc3a43b5ac8a3868 (see https://github.com/oat-sa/tao-core/pull/3339#discussion_r790629100 for the rationale for wrapping it with parenthesis).

2022-01-24 11:07 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    return ($property->getUri() === self::URI_PROPERTY_1);
Changed in ac23cd5cb705abff473deca0cc3a43b5ac8a3868 (see https://github.com/oat-sa/tao-core/pull/3339#discussion_r790629100 for the rationale for wrapping it with parenthesis).

2022-01-24 11:16 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->expects(self::exactly(1))
Changed here: 754c338c79f0b4299aa11c33ce0b42cf8f03482f

2022-01-24 11:16 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->expects(self::exactly(1))
Changed here: 754c338c79f0b4299aa11c33ce0b42cf8f03482f

2022-01-24 11:17 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            ->expects(self::never())
Changed here: 754c338c79f0b4299aa11c33ce0b42cf8f03482f

2022-01-24 11:25 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +    }
I thought having it this way made a more clear the intent of that check.

BTW I'm inlining the check and removing the additional method and comment in 376dfcb02dd7c2b2ed5592e768429fa3d52db128 since it is clear that way too.

2022-01-24 11:34 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            }));
Changed: 24948dcdf4ff8ec460c2606746e78fc9fc97dbb2 :+1:

2022-01-24 12:15 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    }
Putting it as a single line (`if (in_array($property->getUri(), [self::URI_PROPERTY_1, self::URI_PROPERTY_2], true)) {`) would make the line 109 chars width (exceeding [PSR-12](https://www.php-fig.org/psr/psr-12/) max line lenght), so if we want to still use `in_array` for this one and conform to the linter rules, this should be put this way instead to make the linter happy :) :

```
                    if (
                        in_array(
                            $property->getUri(),
                            [self::URI_PROPERTY_1, self::URI_PROPERTY_2],
                            true
                        )
                    ) {
                        return $this->nonEmptyCollectionMock;
                    }
```
 (Because of PSR-12 §4.7 rules _The first expression of a multi-line control structure must be on the line after the opening parenthesis_ and _Argument lists MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line._)
 
I personally find it more readable the former, explicit way with two `if`s (and will avoid the reader to know (or check in the documentation, as I did :sweat_smile: ) that the 3rd parameter for `in_array` is to do strict checking  (i.e. to make `in_array` behave as `===` on individual items)).

We may also use this one, but still feels a bit weird ([I put it like that initially](https://github.com/oat-sa/tao-core/blob/46462ce747455a4f3fca73898f2d40726700728f/test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php#L383)):

```
                    if (
                        $property->getUri() === self::URI_PROPERTY_1
                        || $property->getUri() === self::URI_PROPERTY_2
                    ) {
                        return $this->nonEmptyCollectionMock;
                    }
```

I'd prefer to keep it as it is right now unless you have a strong preference for merging the two conditionals using either one of the previous formulas (`in_array` or the multi-line `if`) :)

2022-01-24 12:30 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +                    }
See https://github.com/oat-sa/tao-core/pull/3339#discussion_r790538135

2022-01-24 12:54 UTC, hectoras commented on test/unit/models/classes/dataBinding/GenerisInstanceDataBinderTest.php
> +            }));
Good idea! I'm moving the setup for method expectations to a helper method in dd3faa491d1984a9fb7d729d62148922bd362d2f. Thank you :slightly_smiling_face:

2022-01-24 13:53 UTC, andreluizmachado requested changes

2022-01-24 13:53 UTC, andreluizmachado commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
>      protected function getTargetInstance()
is it possible to add return type hint here?

2022-01-24 13:53 UTC, andreluizmachado commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
>  class tao_models_classes_dataBinding_GenerisInstanceDataBinder extends tao_models_classes_dataBinding_AbstractDataBinder
How hard would be to change to namespace instead of FQN on the class name for this class? is it possible?

2022-01-24 14:21 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
>      protected function getTargetInstance()
Yes, it is :) Added such return type hint in a4f5bd618f34029bf2bc82e282620e0aa8fc1faa Thanks!

2022-01-24 15:32 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
>  class tao_models_classes_dataBinding_GenerisInstanceDataBinder extends tao_models_classes_dataBinding_AbstractDataBinder
I'm afraid it would be a little risky, since that would be a breaking change and it seems this class was created in 2013.

But maybe we can leave this one as:

```
/**
 * @deprecated Use oat\tao\model\dataBinding\GenerisInstanceDataBinder instead.
 */
class tao_models_classes_dataBinding_GenerisInstanceDataBinder extends GenerisInstanceDataBinder
{
    // void
}
```

and then have the real class as `GenerisInstanceDataBinder` under `namespace oat\tao\model\dataBinding;` and with the proper file name (and rename the usages under tao-core to use the new name). That would ensure prior usages for this class still work while allowing using the namespaced name for new usages (btw I'd rename usages in tao-core itself (such as those from Lists), and other classes under the "dataBinder" directory to keep them consistent with this change).

Would that work for you? :)

2022-01-24 16:14 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
>  class tao_models_classes_dataBinding_GenerisInstanceDataBinder extends tao_models_classes_dataBinding_AbstractDataBinder
(Hmm.. by the way I think creating a new file while keeping the former one for each class would mean we'd loose the git history for the class the moment we remove the file with the legacy name)

2022-01-25 08:31 UTC, andreluizmachado requested changes

2022-01-25 08:31 UTC, andreluizmachado commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
>  class tao_models_classes_dataBinding_GenerisInstanceDataBinder extends tao_models_classes_dataBinding_AbstractDataBinder
I like your proposal to keep backward compatibility and at the same time, we can start to use namespace for such kinds of classes. Regarding the history. did you try to only rename the file first, commit it and then rename the class and recreate the tao_models_classes_dataBinding_GenerisInstanceDataBinder class? I think like this way will keep the history, no?

2022-01-25 08:34 UTC, andreluizmachado commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
>  class tao_models_classes_dataBinding_GenerisInstanceDataBinder extends tao_models_classes_dataBinding_AbstractDataBinder
or maybe just a comment on the commit explaining that the content of the class was moved would work.

2022-01-25 11:12 UTC, hectoras commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
>  class tao_models_classes_dataBinding_GenerisInstanceDataBinder extends tao_models_classes_dataBinding_AbstractDataBinder
That worked like a charm! Renamed file 8a7e3c56fcd64f554e37739e126927e3ec4221c6 and then pushed a new one with the former name 9f495ee25a3698180b4f9dd45c1c84a4e1d1754e et voila! The former git log is correctly tracked under the new name DataBindingException.php. I'll repeat the procedure with the other files.

2022-01-26 13:26 UTC, gabrielfs7 commented on models/classes/dataBinding/GenerisFormDataBindingException.php
> +  *              2022 (update and modification) Open Assessment Technologies SA;
No need to all dates

2022-01-26 13:26 UTC, gabrielfs7 commented on models/classes/dataBinding/GenerisInstanceDataBindingException.php
> + *               2009-2012 (update and modification) Public Research Centre Henri Tudor (under the project TAO-SUSTAIN & TAO-DEV);
No need to all dates

2022-01-26 13:27 UTC, gabrielfs7 commented on models/classes/dataBinding/GenerisInstanceDataBindingException.php
> + */
Not required 

```suggestion
```

2022-01-26 13:27 UTC, gabrielfs7 commented on models/classes/dataBinding/GenerisFormDataBindingException.php
> + */
Not required

```suggestion
```

2022-01-26 13:28 UTC, gabrielfs7 commented on models/classes/dataBinding/DataBindingException.php
> + */
Not required
```suggestion
```

2022-01-26 13:28 UTC, gabrielfs7 commented on models/classes/dataBinding/DataBindingException.php
> + *
Please, use latest annotation on all your new classes and provide only the creation year, not all dates

2022-01-26 13:32 UTC, gabrielfs7 commented on models/classes/dataBinding/GenerisFormDataBindingException.php
> +class GenerisFormDataBindingException extends DataBindingException
I safe way to deprecate the previous one is make this one extend `tao_models_classes_dataBinding_GenerisFormDataBindingException`

I am afraid this code can cause a breaking change and unpredictable errors.

2022-01-26 13:35 UTC, gabrielfs7 commented on models/classes/dataBinding/AbstractDataBinder.php
> +<?php
Please, review annotations as other classes

2022-01-26 13:39 UTC, gabrielfs7 commented on actions/class.Users.php
> +     * @throws GenerisFormDataBindingException
This is a breaking change now. More details in the other comments I left.

2022-01-26 13:39 UTC, gabrielfs7 commented on actions/class.Users.php
> +     * @throws GenerisFormDataBindingException
This is a breaking change now. More details in the other comments I left.

2022-01-26 13:40 UTC, gabrielfs7 commented on models/classes/GenerisServiceTrait.php
> +     * @throws GenerisInstanceDataBindingException
This is a breaking change now. More details in the other comments I left.

2022-01-26 13:40 UTC, gabrielfs7 commented on models/classes/class.UserService.php
> +     * @throws GenerisFormDataBindingException
This is a breaking change now. More details in the other comments I left.

2022-01-26 16:15 UTC, hectoras commented
This pull request has been superseded by #3361 (which commits fewer changes).

2022-01-31 09:07 UTC, AntonNeviarouski commented
QA verified

2022-01-31 09:22 UTC, hectoras commented
A newer pull request that fix the same issue as this one has been merged tot he `develop` branch: https://github.com/oat-sa/tao-core/pull/3361

2022-02-25 12:01 UTC, closed without merging