Feature/aut 1249/apply language ordering
oat-sa/tao-core pull request #3348
Opened 2022-01-21 08:44 UTC by pnal

2022-01-25 09:48 UTC, andreluizmachado requested changes

2022-01-25 09:48 UTC, andreluizmachado commented on helpers/class.I18n.php
>      public static function getLangResourceByCode($code)
is it possible to add return type hint here?

2022-01-25 09:48 UTC, andreluizmachado commented on helpers/class.I18n.php
>      public static function init(common_ext_Extension $extension, $langCode)
is it possible to add return type hint here?

2022-01-25 09:48 UTC, andreluizmachado commented on helpers/form/ElementMapFactory.php
>                          $values = $this->getListValues($property, $range, $parentProperty);
is it doing some expensive operation (going to db, cache, ...)? in case of yes I'd suggest:
```
                        if ($this->getLanguageClassSpecification()->isSatisfiedBy($range))
                        {
                            $values = $this->getLanguageListElementSortService()->getSortedListCollectionValues($values);
                        } else {
                            $values = $this->getListValues($property, $range, $parentProperty);
                       }
```
or isolate it in a private method (I prefer this one :)).

2022-01-25 09:48 UTC, andreluizmachado commented on models/classes/Lists/Business/Contract/ListElementSorterInterface.php
> +     * @return Value[]
I believe that you can remove this phpdoc

2022-01-25 09:48 UTC, andreluizmachado commented on models/classes/Lists/Business/Contract/ListElementSorterComparatorInterface.php
> +     * @return int -1|0|1
what is -1 0 and 1?

2022-01-25 09:48 UTC, andreluizmachado commented on models/classes/Lists/Business/Specification/EditableListClassSpecification.php
> +        LanguageClassSpecification $languageClassSpecification
ClassSpecificationInterface $languageClassSpecification

2022-01-25 09:48 UTC, andreluizmachado commented on test/unit/models/classes/Language/Business/Service/LanguageListElementSortServiceTest.php
> +<?php
could add/extend tests for EditableListClassSpecification, LanguageClassSpecification?

2022-01-25 16:28 UTC, bartlomiejmarszal requested changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2022-01-26 09:06 UTC, pnal commented on helpers/form/ElementMapFactory.php
>                          $values = $this->getListValues($property, $range, $parentProperty);
No it's not doing

2022-01-26 09:26 UTC, pnal commented on helpers/class.I18n.php
> +                usort(self::$availableLangs, function ($item1, $item2) {
I do not see much sense to test PHP standard functions used here. But I have another question related to this, why item authoring page using this as a source for language selector in UI instead of lists as in other places. Probably because here the data is cached?
Moreover:
![image](https://user-images.githubusercontent.com/18700632/151136754-b968e42d-c2a4-4d3d-bf81-da9d4f6d4fca.png)
![image](https://user-images.githubusercontent.com/18700632/151136830-e4cc686b-f72d-4635-9087-0205113d1c59.png)
@bziondik do you know why we requesting the same data twice and do not take it from `getItemData`?

2022-01-26 09:36 UTC, bziondik commented on helpers/class.I18n.php
> +                usort(self::$availableLangs, function ($item1, $item2) {
Check this https://github.com/oat-sa/extension-tao-itemqti/pull/1622

2022-01-26 10:05 UTC, pnal commented on models/classes/Lists/Business/Contract/ListElementSorterInterface.php
> +     * @return Value[]
as soon as we are able to set Value[] as a return type hint

2022-01-26 10:13 UTC, pnal commented on models/classes/Language/Service/LanguageListElementSortService.php
> +     * @return Value[]
Sure it's already defined in the interface

2022-01-26 10:19 UTC, pnal commented on models/classes/Lists/Business/Contract/ListElementSorterComparatorInterface.php
> +     * @return int -1|0|1
prompt that value relative to zero matters

2022-01-26 16:33 UTC, andreluizmachado requested changes

2022-01-26 16:34 UTC, andreluizmachado commented on helpers/class.I18n.php
>      public static function getLangResourceByCode($code)
?

2022-01-26 16:34 UTC, andreluizmachado commented on helpers/class.I18n.php
>      public static function init(common_ext_Extension $extension, $langCode)
?

2022-01-26 16:35 UTC, andreluizmachado commented on models/classes/Lists/Business/Specification/EditableListClassSpecification.php
> +        LanguageClassSpecification $languageClassSpecification
?

2022-01-26 16:58 UTC, pnal commented on helpers/class.I18n.php
>      public static function getLangResourceByCode($code)
outdated!
![image](https://user-images.githubusercontent.com/18700632/151210033-c97be1cc-1118-44c7-98a6-1d9c87574cec.png)

2022-01-26 17:06 UTC, pnal commented on models/classes/Lists/Business/Contract/ListElementSorterInterface.php
> +     * @return Value[]
Never seen that we do one line phpDoc annotations for class methods

2022-01-28 08:57 UTC, bartlomiejmarszal approved these changes
LGTM

2022-01-28 10:25 UTC, andreluizmachado approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-01-31 08:57 UTC, merged