fix: include oauth parameters in only one place, either query or header
oat-sa/tao-core pull request #3368
Opened 2022-01-28 10:06 UTC by augustas

Oauth 1.0 parameters must be included either in request query parameters, `Authorization` header, or body. According to [protocol specification](https://datatracker.ietf.org/doc/html/rfc5849#section-3.5). Currently it was either query params, or query params + `Authorization` header.
 
Related to: https://oat-sa.atlassian.net/browse/TR-2754
  
#### How to test
 
- launch delivery via LTI 1.1 with specified additional parameter `lis_outcome_service_url`, sending a url where result should be submitted. For testing you could use a webhook testing tool like https://webhook.site
- complete the test
- verify that generated request had oauth parameters only in the `Authorization` header, and not in query parameters

2022-01-28 15:26 UTC, wazelin requested changes

2022-01-28 15:26 UTC, wazelin commented on models/classes/oauth/OauthService.php
> +        return mb_substr($signedRequest->to_header(), 15);
I didn't debug the code to figure out what's happening here.
Could you please add a comment, explaining the goal we're trying to achieve here, and the means of achieving it.

In other words, WTF is 15? :)

2022-01-28 15:42 UTC, augustas commented on models/classes/oauth/OauthService.php
> +        return mb_substr($signedRequest->to_header(), 15);
You're questioning my magic! :D You are right it's not clear, will update, `OauthRequest::to_header()` returns a generated auhorization header string with `Authorization: ` already prefixed.

2022-01-31 09:46 UTC, wazelin approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2022-01-31 14:08 UTC, merged