ADF-835 Add assign value to calendar cypress command
oat-sa/tao-core pull request #3421
Opened 2022-02-18 20:04 UTC by meefox

Related to https://oat-sa.atlassian.net/browse/ADF-835

2022-02-22 07:20 UTC, gabrielfs7 commented on views/cypress/support/resourceProperties.js
> +Cypress.Commands.add('assignValueToCalendarProperty', (property, value) => {
What about the password property (and the other properties)?

2022-02-22 07:37 UTC, gabrielfs7 commented on views/cypress/support/resourceProperties.js
> +Cypress.Commands.add('assignValueToCalendarProperty', (property, value) => {
https://github.com/oat-sa/extension-tao-item/pull/571/files#r811649620

2022-02-22 10:09 UTC, Silvia-loza approved these changes
It LGTM. 
- [X] New code is covered by tests (if applicable)
- [X] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2022-02-22 12:02 UTC, meefox commented on views/cypress/support/resourceProperties.js
> +Cypress.Commands.add('assignValueToCalendarProperty', (property, value) => {
it is not necessary for now, the password is the same in terms of adding value

2022-02-22 12:29 UTC, gabrielfs7 commented on views/cypress/support/resourceProperties.js
> +Cypress.Commands.add('assignValueToCalendarProperty', (property, value) => {
But why creating the calendar here and not the password? What if someone wants to validate password property in other test, should they repeat the code you wrote the in the tao-item extension?

2022-02-23 09:20 UTC, bziondik requested changes
Failed because of expired token issue, after  tests `Main Item Class creation and editing`
![image](https://user-images.githubusercontent.com/25976342/155290775-d91dfb3d-9906-4802-aa00-9c1b90a4238b.png)

2022-02-25 10:53 UTC, gabrielfs7 approved these changes

2022-02-25 15:52 UTC, merged