feat: add Assessment Project id property on test
oat-sa/tao-core pull request #3441
Opened 2022-03-03 08:53 UTC by pnal

2022-03-04 08:34 UTC, pnal commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_REMOTE_PUBLISHING_FROM_TEST = 'FEATURE_FLAG_REMOTE_PUBLISHING_FROM_TEST';
The fact that public constant is defined does not commit core to be depended of anything, even if we do not have extension tao-publishing installed nothing happen.
I thought about and decided that it might be good if all possible .env feature flags will be collected in one place.

2022-03-04 09:01 UTC, andreluizmachado commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_REMOTE_PUBLISHING_FROM_TEST = 'FEATURE_FLAG_REMOTE_PUBLISHING_FROM_TEST';
From My point of view, this ENV var is polluting the code because is not used here. If you install only tao-core without the remote publishing extension this env will not have any usage. This is not part of Tao Core this should be part of remote publishing. As you can see you are introducing a variable that has FEATURE_FLAG_**REMOTE_PUBLISHING**_FROM_TEST on the name and what is the meaning of this on tao core? this is not part of this context for me this is a dirt code, sorry.
What is the point to create a code in a repo which is not being used? There is no point to do it here.

2022-03-07 09:56 UTC, pnal commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_REMOTE_PUBLISHING_FROM_TEST = 'FEATURE_FLAG_REMOTE_PUBLISHING_FROM_TEST';
It is used in taoTests in order to check the feature flag and disable some functionality, so if I define it not in the core but in any other extension this will mean that we will have a dependency for taoTests on that extension https://github.com/oat-sa/extension-tao-test/pull/424/files#diff-0eac1785cd2532bf8ece8a05713ef49a8cf9c4c4de858890339ed843728c35d8R116

2022-03-08 14:43 UTC, bartlomiejmarszal requested changes
IMO we should keep feature flag const in taoTests

2022-03-08 14:43 UTC, bartlomiejmarszal commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_REMOTE_PUBLISHING_FROM_TEST = 'FEATURE_FLAG_REMOTE_PUBLISHING_FROM_TEST';
I support choosing taoTests to keep this feature flag.

2022-03-09 08:30 UTC, pnal commented
Moved out feature flag definition const, PR is not needed anymore

2022-03-09 08:30 UTC, closed without merging