feat: add isVisibility feature helper
oat-sa/tao-core pull request #3464
Opened 2022-03-31 07:04 UTC by meefox

2022-04-04 12:19 UTC, jsconan requested changes
Nice addition!

Regarding the implementation, there are a few things to look at, as you can see in the coment below.

Globally speaking, I wonder if we ever need to support the wildcard from the consumer API. For the definition, yes we need to wildcard the namespace. But not sure it is needed for the reading. Anyway, this is not a problem in the end.

Unfortunately, the unit tests don't pass in CLI.

2022-04-04 12:19 UTC, jsconan commented on views/js/services/features.js
> +            for (let i in featuresKeys) {
**nitpick:** `for..in` loops over the keys, and therefore it is not suitable to be used on an array as it would also cover entries that are not array items. Please consider using `.forEach()` instead, or a look that respects the array structure. If you want an early return inside a `forEach()` you could also use `every()` or `some()`.

2022-04-04 12:27 UTC, meefox commented on views/js/services/features.js
> +        lookupPath = lookupPath.replaceAll('*', '\\S*');
S+ better indeed.
Actually, if we want to support only one wild card. 
Just one simple .replace() may be sufficient enough in this case.

2022-04-04 15:17 UTC, jsconan requested changes
It looks better, and the unit tests don't fail in CLI 👍 

However, I found a possible issue with the fallback RegEx.
Plus some other comments

2022-04-04 15:17 UTC, jsconan commented on views/js/test/services/features/test.html
> +        <script type="text/javascript" src="js/lib/blanket/blanket.min.js" data-cover-only="i18n.js"></script>
**core:** This can be removed. `Blanket` is not compatible with ES6+. Beside this, the target is not accurate :) (`ata-cover-only="i18n.js` while the test module is `services/features`)

2022-04-04 15:17 UTC, jsconan commented on views/js/services/features.js
> +            const logger = loggerFactory('services/features');
**nitpick:** The logger needs to be created only once, at the module level.

2022-04-04 15:45 UTC, meefox commented on views/js/services/features.js
> +            const logger = loggerFactory('services/features');
Error here considering as corner-case my intention not waste resource on something that not supposed to happen :)

2022-04-05 08:36 UTC, jsconan commented on views/js/services/features.js
> +        isVisible: (featurePath = '') => {
in this particular context yes, it behaves the same. However, an arrow function does not have the same lexical scope than a pure method.

2022-04-05 09:04 UTC, meefox commented on views/js/test/services/features/test.js
> +    ];
Added module test. 
About JSON not sure, this data is tightened to this test case I would keep it at least until the test grew or data be needed anywhere else.

2022-04-05 09:44 UTC, jsconan requested changes
Very close to being approved :)

I have a few comments.

And a wondering: with this implementation we are considering a whitelist of features. This means if a feature is not registered yet, it will be considered hidden.

Looking at the ACs, it looks like it should rather be a blacklist:
>  `Show` is used as default value when a feature is not listed in the response

2022-04-05 09:44 UTC, jsconan commented on views/js/test/services/features/test.js
> +        {lookup: 'items/category/subcategory/anyFeature', visible: true},
**chore:** duplicated test case.

**thought:** I see tests to validate the lookup from a filled-up config. But I don't see test for incorrect entry nor for empty config

2022-04-05 09:44 UTC, jsconan commented on views/js/services/features.js
> +        }
**nitpick:** Something I didn't notice yet, the RegExp needs to be instantiated

**suggestion:**
```suggestion
        try {
            return new RegExp(`^${lookupPath}$`);
        } catch (e) {
            logger.warn(`Lookup feature path ${lookupPath} was not found`);
            return new RegExp('^\0$');
        }
```

2022-04-05 12:13 UTC, krampstudio commented on views/js/services/features.js
> +         * based on client_lib_config_registry.conf.php
```suggestion
         * Check if the feature is configured to be visible
         * based on the module configuration
```

2022-04-05 12:17 UTC, krampstudio approved these changes
I just have an optional suggestion.

Everything else looks good. 

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] <s>New code is not subject to concurrency issues (if applicable)</s>
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2022-04-05 12:33 UTC, jsconan approved these changes
LGTM. Nice work!

**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- ~~[ ] New code is not subject to concurrency issues (if applicable)~~
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

2022-04-05 14:07 UTC, merged