feat: Add FeatureVisibilityService
oat-sa/tao-core pull request #3473
Opened 2022-04-07 07:19 UTC by yaraslau-kavaliou

2022-04-07 08:34 UTC, quintanilhar commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +        $existingConfig = call_user_func([__CLASS__, $configUpdaterCallableName], $existingConfig, $configUpdaterArg);
If you provide the current object instance ($this) you don't need to use a static method which is usually better to avoid for regular execution flows like this.

2022-04-07 08:35 UTC, quintanilhar commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +        $existingConfig = call_user_func([__CLASS__, $configUpdaterCallableName], $existingConfig, $configUpdaterArg);
```suggestion
        $updatedConfig = call_user_func([__CLASS__, $configUpdaterCallableName], $existingConfig, $configUpdaterArg);
```

2022-04-07 08:39 UTC, quintanilhar commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +    private const GLOBAL_UI_CONFIG_NAME = 'globalUIConfig';
As I see the [FE expects a different config](https://github.com/oat-sa/tao-core/pull/3464#issue-1187611883) structure, we should probably follow the same.

2022-04-07 08:40 UTC, quintanilhar commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +class FeatureVisibilityService
Considering the logic in this service, what do you think about creating a unit test for it?

2022-04-07 08:41 UTC, quintanilhar commented on models/classes/featureVisibility/FeatureVisibilityServiceProvider.php
> +class FeatureVisibilityServiceProvider implements ContainerServiceProviderInterface
nice! 👍🏻

2022-04-07 08:45 UTC, quintanilhar requested changes
We need to align the config structure with the FE.

2022-04-07 14:35 UTC, shpran commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +    private common_ext_ExtensionsManager $extManager;
I'm not sure, that we can use such syntax, since not all of our customers are on PHP 7.4 (most of them still on PHP 7.2)

2022-04-07 14:35 UTC, shpran commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +    }
[Optional]
```suggestion
    public function __construct(common_ext_ExtensionsManager $extensionsManager)
    {
        $this->extensionsManager = $extensionsManager;
    }
```

2022-04-07 14:35 UTC, shpran commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +        }
[Optional]
```suggestion
        $taoExtension = $this->extManager->getExtensionById(self::EXTENSION_NAME);

        if ($taoExtension === null) {
            throw new Exception(sprintf('Cannot find %s extension', self::EXTENSION_NAME));
        }

        $existingConfig = $taoExtension->getConfig(self::CONFIG_FILE_NAME);

        if ($existingConfig === false) {
            throw new Exception(sprintf('Cannot read %s config', self::CONFIG_FILE_NAME));
        }
```

2022-04-07 14:35 UTC, shpran commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +            if (!in_array($featureValue, [self::HIDE_PARAM, self::SHOW_PARAM])) {
```suggestion
            if (!in_array($featureValue, [self::HIDE_PARAM, self::SHOW_PARAM], true)) {
```

2022-04-07 21:45 UTC, yaraslau-kavaliou commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +        $existingConfig = call_user_func([__CLASS__, $configUpdaterCallableName], $existingConfig, $configUpdaterArg);
Those methods don't use $this and do not have any side effects, and I beleive it is better to make such methods static to emphasise they do not mutate the state of the object.

2022-04-07 21:51 UTC, yaraslau-kavaliou commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +    private const GLOBAL_UI_CONFIG_NAME = 'globalUIConfig';
fixed

2022-04-07 21:51 UTC, yaraslau-kavaliou commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +class FeatureVisibilityService
Added unit tests

2022-04-07 21:52 UTC, yaraslau-kavaliou commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +    private common_ext_ExtensionsManager $extManager;
I'm not sure that we support only PHP 7.2
@quintanilhar maybe you know what PHP version should we use?

2022-04-07 21:53 UTC, yaraslau-kavaliou commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +    }
fixed

2022-04-07 21:53 UTC, yaraslau-kavaliou commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +        }
I don't like those empty lines, to be honest :)

2022-04-07 21:54 UTC, yaraslau-kavaliou commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +            if (!in_array($featureValue, [self::HIDE_PARAM, self::SHOW_PARAM])) {
fixed

2022-04-07 22:02 UTC, yaraslau-kavaliou commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +        $existingConfig = call_user_func([__CLASS__, $configUpdaterCallableName], $existingConfig, $configUpdaterArg);
@quintanilhar fixed
@shpran - fixed - good point - I think it will improve code's readability

2022-04-08 07:54 UTC, quintanilhar commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +        $taoExtension->setConfig(self::CONFIG_FILE_NAME, $updatedConfig);
I just realized you're not using the service `ClientLibConfigRegistry` to manipulate the config, any reasons why?

2022-04-08 08:04 UTC, quintanilhar commented on test/unit/featureVisibility/FeatureVisibilityServiceTest.php
> +        $this->fv = new FeatureVisibilityService($this->extManager);
We should use abbreviations for a very limited number of words like "id", "config", "param", "sut" and a few more. For any other case, it's important to use a meaningful and complete name.
```suggestion
        $this->featureVisibilityService = new FeatureVisibilityService($this->extManager);
```

2022-04-08 08:45 UTC, quintanilhar commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +    private common_ext_ExtensionsManager $extManager;
As I see the min supported version is still PHP 7.2.

2022-04-08 12:22 UTC, yaraslau-kavaliou commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +    private common_ext_ExtensionsManager $extManager;
Update code to support php 7.2

2022-04-08 12:23 UTC, yaraslau-kavaliou commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +        $taoExtension->setConfig(self::CONFIG_FILE_NAME, $updatedConfig);
Updated - but it not so obvious from testing point of view :)

2022-04-08 12:23 UTC, yaraslau-kavaliou commented on test/unit/featureVisibility/FeatureVisibilityServiceTest.php
> +    public function testShowFeature_SetsFeatureToTheShowStatus()
fixed

2022-04-08 12:23 UTC, yaraslau-kavaliou commented on test/unit/featureVisibility/FeatureVisibilityServiceTest.php
> +        $this->fv = new FeatureVisibilityService($this->extManager);
fixed

2022-04-08 13:11 UTC, quintanilhar commented on test/unit/featureVisibility/FeatureVisibilityServiceTest.php
> +        }
We can use `phpunit` API to assert the exception:

```suggestion
        $this->expectException(Exception::class);
        
        $this->featureVisibilityService->setFeaturesVisibility(['featureName' => $wrongFeatureStatus]);
```

2022-04-08 13:13 UTC, quintanilhar commented on models/classes/featureVisibility/FeatureVisibilityService.php
> +                throw new Exception(sprintf(
What do you think about using a more specific exception type here? Perhaps `InvalidArgumentException` could be a good fit.

2022-04-08 13:30 UTC, yaraslau-kavaliou commented on test/unit/featureVisibility/FeatureVisibilityServiceTest.php
> +        }
fixed

2022-04-08 13:41 UTC, quintanilhar approved these changes
- [X] New code is covered by tests
- [X] Tests are running successfully on my local machine
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X] Feature is working correctly on my local machine
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful
- [X] Pull request's target is not `master`
- [X] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] Commits messages are meaningful
- [X] Commits are atomic

2022-04-08 13:47 UTC, merged