Backport/oatsd 1881/collapsing sub lines
oat-sa/tao-core pull request #3542
Opened 2022-05-30 12:44 UTC by yukipastelcat

# Pull request summary

Related to [OATSD-1881](https://oat-sa.atlassian.net/browse/OATSD-1881).

This is a backport of https://github.com/oat-sa/tao-core/pull/3541

2022-05-30 14:14 UTC, btamas requested changes

2022-05-30 14:14 UTC, btamas commented on views/package.json
> +        "@oat-sa/tao-core-ui": "1.22.18",
I think it is still too much. It should be 1.22.11, if it is not taken. If it is, then 1.22.10-1

2022-05-31 06:06 UTC, btamas commented
It looks good.
- Can you please create the `1.22.10-1` tag in `tao-core-ui-fe` on that branch?
- When comparede 1.22.10 and 1.22.10-1, I've seen an extra modification, that was not in the original PR. You changed the 0.75 rem to 0.75em. Was it intended?

2022-05-31 06:07 UTC, btamas approved these changes

2022-05-31 07:03 UTC, yukipastelcat commented
@btamas tag is already created (https://github.com/oat-sa/tao-core-ui-fe/releases/tag/v1.22.10-1), and changing `rem` to `em` was intended while resolving conflicts during cherry-pick, since `<sub>` and `<sup>` font-size should follow it's corresponding element font-size

2022-05-31 07:09 UTC, merged