fix: restore removed getTokenName method
oat-sa/tao-core pull request #3555
Opened 2022-06-17 07:11 UTC by pnal

Related ticket: https://oat-sa.atlassian.net/browse/TR-4321
The method was removed in this PR: https://github.com/oat-sa/tao-core/pull/2655/files#diff-755eff4da554fe5ca1678fdd0bce56daff2827518c160ba87f347a56051f9c47L230
Was found that it is used by taoSync: https://github.com/oat-sa/extension-tao-sync/blob/master/controller/Synchronizer.php#L170

2022-06-17 07:56 UTC, bziondik approved these changes
LGTM

2022-06-17 08:48 UTC, andreluizmachado approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-06-17 08:49 UTC, andreluizmachado requested changes
could u include unit tests, please?

2022-06-28 07:49 UTC, pnal commented
fixed by another approach https://github.com/oat-sa/extension-tao-sync/pull/204

2022-06-28 07:49 UTC, closed without merging