feat: grafana on call notifier implementation
oat-sa/tao-core pull request #3557
Opened 2022-06-21 16:26 UTC by poyuki

# [SI-570](https://oat-sa.atlassian.net/browse/SI-570)

## Summary 
new notifier for alerts

2022-06-21 19:29 UTC, kilatib approved these changes

2022-06-21 20:51 UTC, wazelin requested changes

2022-06-21 20:51 UTC, wazelin commented on models/classes/notifiers/GrafanaNotifier.php
> +            "message" => $description,
I hate to leave a comment like that, but "mixed single/double quotes usage" :)

```suggestion
            'alert_uuid' => Uuid::uuid4()->toString(),
            'title' => $title,
            'message' => $description,
```

2022-06-22 07:43 UTC, poyuki commented on models/classes/notifiers/GrafanaNotifier.php
> +            "message" => $description,
fair enough

2022-06-22 07:58 UTC, tikhanovichA approved these changes
Tested. All good

2022-06-22 08:41 UTC, merged