Feature/adf 1145/fix integer form validator on php8
oat-sa/tao-core pull request #3599
Opened 2022-08-22 10:12 UTC by pnal

2022-08-22 11:01 UTC, pnal commented on test/unit/helpers/form/validators/IntegerValidatorTest.php
> +        $this->assertEquals($isValid, $this->subject->evaluate($value));
![image](https://user-images.githubusercontent.com/18700632/185905733-93a66b83-f913-4b2b-afec-6b6440286531.png)
![image](https://user-images.githubusercontent.com/18700632/185905982-617313af-5fdc-4bee-ad3a-4b11ba293e47.png)

2022-08-22 11:58 UTC, bartlomiejmarszal commented on test/integration/ValidatorTest.php
> +            //'valid_object'     => [$validObject, true], //todo check why it is failing
Should we fix it first?

2022-08-22 12:38 UTC, bartlomiejmarszal approved these changes
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-08-22 12:58 UTC, pnal commented on test/integration/ValidatorTest.php
> +            //'valid_object'     => [$validObject, true], //todo check why it is failing
Good question:
in one hand the test has a case where object should be consider as non empty value;
in other hand this was [broken by this PR](https://github.com/oat-sa/tao-core/pull/2591/files#diff-0ae76075b47cc2560d07d2c70953d0fdfbdaad7d4f384c0d802f55718e9457baR41) almost 2 years ago, and no one cares so most probably it does not affect anything. I decided to left it commented to make the test passing.

2022-08-23 09:20 UTC, gabrielfs7 commented on test/integration/ValidatorTest.php
> +        $validator = new tao_helpers_form_validators_Integer();
Should not we have a test for this validator instead a new method here?

2022-08-23 09:23 UTC, gabrielfs7 commented on test/integration/ValidatorTest.php
> +            //'valid_object'     => [$validObject, true], //todo check why it is failing
We should either fix or let it broken, but not comment. It will not help in anything IMO.

2022-08-23 13:33 UTC, pnal commented on test/integration/ValidatorTest.php
> +        $validator = new tao_helpers_form_validators_Integer();
I already created it

2022-08-23 13:34 UTC, pnal commented on test/integration/ValidatorTest.php
> +            //'valid_object'     => [$validObject, true], //todo check why it is failing
Left it broken, cause I do not know is it safe to fix it

2022-08-23 13:43 UTC, gabrielfs7 commented on test/integration/ValidatorTest.php
> +            'valid_object'     => [$validObject, true], //todo check why it is failing
I think it is redundant since the test it failing. I would remove this comment and fix it, cause according to the original implementation, we do not support length for objects.

```suggestion
            'valid_object'     => [$validObject, false],
```

2022-08-23 13:45 UTC, gabrielfs7 commented on test/integration/ValidatorTest.php
> +        $validator = new tao_helpers_form_validators_Integer();
Nice, but then, why we need it here?

2022-09-01 08:53 UTC, gabrielfs7 commented on composer.json
> +        "phpspec/prophecy": "*"
We do not include test libraries in the extensions composer, cause it is not useful since all of them depend on a full tao installation to work. 

Additional point: we are trying to get rid of `prophecy`, cause it is completely useless if you have PHP unit already.

2022-09-01 08:54 UTC, gabrielfs7 commented on composer.json
> +        "phpspec/prophecy": "*"
The CI issue is not related to that

2022-09-01 08:57 UTC, gabrielfs7 commented on composer.json
> +        "phpspec/prophecy": "*"
PHP 8 pipeline will fail until we finish the PHP 8 migration epic. The error you are getting is due the php version in your composer, already fixed here: https://github.com/oat-sa/tao-core/pull/3573/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L59

We will not attach PHP versions to the extensions anymore.

2022-09-01 08:57 UTC, gabrielfs7 requested changes
Check https://github.com/oat-sa/tao-core/pull/3599/files#r960393106

2022-11-15 13:00 UTC, bartlomiejmarszal commented on test/integration/ValidatorTest.php
> +        //this data provider valid according default config tao/config/default/passwordConstraints.conf.php
SHouldn't we consider actual config option?

2022-11-15 13:17 UTC, bartlomiejmarszal approved these changes

2022-11-15 13:24 UTC, merged