Fix/aut 2349/translate rdf properties
oat-sa/tao-core pull request #3681
Opened 2022-11-23 17:11 UTC by andreluizmachado

2022-11-24 14:37 UTC, bartlomiejmarszal approved these changes

2022-11-25 08:25 UTC, pnal approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on playground (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-11-28 13:25 UTC, alroniks requested changes

2022-11-28 13:25 UTC, alroniks commented on scripts/class.TaoTranslate.php
> +            if ($translationFile->getBySource($oldTu) === null) {
I am not against such approach, but need to make possible to clear translations files. So, I suggest make a parameter and probably set it as default, but still be able to turn off such behavior.

In case using any kind of translations system, keeping everything in PO files will confuse translators and other involved people. And of course it may increase amount of work, when we pass the files for translation which has not used in the code lines.

2022-11-28 19:00 UTC, bartlomiejmarszal commented on scripts/class.TaoTranslate.php
> +            if ($translationFile->getBySource($oldTu) === null) {
Added a new flag that will allow clearing translation when not existing in PO files

2022-11-29 09:33 UTC, Silvia-loza commented on scripts/class.TaoTranslate.php
> +            if ($translationFile->getBySource($oldTu) === null) {
I have tested the flag and it works perfect,  clearing  translations when options set to `true` :white_check_mark:

2022-11-30 10:25 UTC, alroniks approved these changes
Let's try such an approach. lgtm

2022-11-30 14:38 UTC, bartlomiejmarszal approved these changes

2022-12-12 15:07 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-12-16 08:51 UTC, merged