fix/TR-4934/cookiePHP7.4
oat-sa/tao-core pull request #3698
Opened 2022-12-15 09:13 UTC by africz

Not tested yet properly, not sure about this fix solve the issue or not

2022-12-15 09:38 UTC, wazelin requested changes

2022-12-15 09:38 UTC, wazelin commented on models/classes/session/Business/Service/SessionCookieService.php
> +                'path' => (string)$sessionCookieAttributes,
Unfortunately, that's not gonna do.
`SessionCookieAttributeCollection` has a collection of attributes, not a single value.

What you might want to do instead is to transform the collection into an array (`iterator_to_array()` may come in handy here), and simply merge the results with the rest of the session cookie parameters. Same applies to the `setcookie()` call down below.

2022-12-15 09:38 UTC, wazelin commented on models/classes/session/Business/Service/SessionCookieService.php
> +        if (PHP_VERSION_ID > 70300) {
In fact, we can drop support for PHP <7.4 completely. No need to worry about that condition at all.

2022-12-15 10:01 UTC, kilatib requested changes

2022-12-16 08:03 UTC, wazelin requested changes

2022-12-16 08:03 UTC, wazelin commented on test/unit/session/Business/Service/SessionCookieServiceTest.php
> +        return $retVal;
![but why?](https://media2.giphy.com/media/s239QJIh56sRW/giphy.gif?cid=ecf05e47dmuvoc5szdy0rjoc97gif4v8scuu344jsozemope&rid=giphy.gif&ct=g)

2022-12-16 08:03 UTC, wazelin commented on test/unit/session/Business/Service/SessionCookieServiceTest.php
> +                // var_dump($globalFunctionExpectation['actualArguments']);
If you need help setting up a debugger, let me know ;)
```suggestion
```

2022-12-16 09:20 UTC, africz commented on test/unit/session/Business/Service/SessionCookieServiceTest.php
> +        return $retVal;
Easier to debug just move mouse cursor above the $retval , don't need to mark copy etc , Visual Studio Code is my IDE. 
certainly removable once project is done.

2022-12-16 09:21 UTC, africz commented on test/unit/session/Business/Service/SessionCookieServiceTest.php
> +                // var_dump($globalFunctionExpectation['actualArguments']);
Thank you, my PHPStorm license was expired at beginning of December

2022-12-16 09:22 UTC, africz commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +     * getCookieParams
Gotcha

2022-12-16 09:26 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams = $this->sessionCookieAttributesFactory->create()->getCookieParams($params, false);
I would like to discuss this in a short call sometimes.

2022-12-16 09:26 UTC, africz commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +        return $retVal;
I would like to discuss this in a short call sometimes.

2022-12-16 09:26 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
>  {
Okay I will do

2022-12-16 10:02 UTC, wazelin commented on test/unit/session/Business/Service/SessionCookieServiceTest.php
> +                // var_dump($globalFunctionExpectation['actualArguments']);
Oh boy 🤦 

Working on fixing that.

2022-12-16 10:31 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams = $this->sessionCookieAttributesFactory->create()->getCookieParams($params, false);
I could help u with explain this

2022-12-19 09:12 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams = $this->sessionCookieAttributesFactory->create()->getCookieParams($params, false);
Thank you ! Please drop me a short call today after the daily meeting, once it is convince to You!

2022-12-19 09:37 UTC, poyuki commented on test/unit/session/Business/Service/SessionCookieServiceTest.php
> +            self::setGlobalFunctionExpectations('session_get_cookie_params', compact('lifetime', $lifetime));
compact function working expecting something like that if i'm not mistaken
```suggestion
            self::setGlobalFunctionExpectations('session_get_cookie_params', compact('lifetime'));
```

2022-12-19 09:39 UTC, poyuki commented on test/unit/session/Business/Service/SessionCookieServiceTest.php
> +            self::setGlobalFunctionExpectations('session_get_cookie_params', compact('httponly', true));
compact support array argument if it's contains names of variable in current context
```suggestion
            self::setGlobalFunctionExpectations('session_get_cookie_params',['path' => $this->createSessionCookieAttributeString()]);
            self::setGlobalFunctionExpectations('session_get_cookie_params', ['domain' => $this->getCookieDomain($domain)]);
            self::setGlobalFunctionExpectations('session_get_cookie_params',['secure'=> Request::isHttps()]);
            self::setGlobalFunctionExpectations('session_get_cookie_params', ['httponly'=> true]);
```

2022-12-19 12:12 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +                    'httponly' => true,
use value from `$cookieParams`
```suggestion
                    'httponly' => $cookieParams['httponly'],
```

2022-12-19 12:14 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams->add(new SessionCookieAttribute('lifetime', (string) $sessionParams['lifetime']));
should it be also in **`SessionCookieAttributeCollection`** constructor ?

2022-12-19 12:14 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
>          $isSecureFlag  = Request::isHttps();
```suggestion

```

2022-12-19 12:15 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams->add(new SessionCookieAttribute('lifetime', (string) $sessionParams['lifetime']));
Sergei told me above in review this is should be at this level not in the constructor

2022-12-19 12:16 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams->add(new SessionCookieAttribute('lifetime', (string) $sessionParams['lifetime']));
At least I understood this, this is why I not put into the constructor

2022-12-19 15:17 UTC, poyuki reviewed
good job for a moment have comments related to code style. also please address all previous comments https://github.com/oat-sa/tao-core/pull/3698/files#r1050457234

will try to validate localy is it working

2022-12-19 15:32 UTC, poyuki commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams = $this->sessionCookieAttributesFactory->create()->getCookieParams($sessionParams['lifetime']);
this place failed (type error)
<img width="536" alt="Screenshot 2022-12-19 at 16 26 44" src="https://user-images.githubusercontent.com/37804293/208461785-b32bf985-dd96-4ba9-a7c0-1ff1b214602a.png">
<img width="1063" alt="Screenshot 2022-12-19 at 16 26 32" src="https://user-images.githubusercontent.com/37804293/208461792-aeab91dc-8edb-4149-bd5c-eed2378beaf4.png">

2022-12-19 15:32 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +    public function getCookieParams(?string $lifetime): array
```suggestion
    }

    public function getCookieParams(?string $lifetime): array
```

2022-12-19 15:34 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams = $this->sessionCookieAttributesFactory->create()->getCookieParams($sessionParams['lifetime']);
Yes, I found it and did commit already a fix, don't know yet is it solve the issue or not.

2022-12-19 15:34 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +            $retVal[$attribute->name()] = $attribute->value();
`SessionCookieAttributeInterface` doesn't  declare name, value methods, and it fails in that place  because on of implementation also does't have it `SessionCookiePathAttribute`

2022-12-19 15:35 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams = $this->sessionCookieAttributesFactory->create()->getCookieParams($sessionParams['lifetime']);
still miss something, thank you

2022-12-19 16:07 UTC, africz commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +            $retVal[$attribute->name()] = $attribute->value();
My mistake I don't have good env need to copy changed filed I did accidentally overwritten the already modified file, thank you for point it out.

2022-12-19 16:08 UTC, africz commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +            $retVal[$attribute->name()] = $attribute->value();
public function name(): string
    {
        return $this->name;
    }
    public function value(): string
    {
        return $this->value;
    }
 This should exists

2022-12-19 16:11 UTC, africz commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +declare (strict_types = 1);
My phpstorm license expired, still not extended. I use VSCode and set PSR-2 compilant, once everything works well I will do.

2022-12-20 08:47 UTC, kilatib requested changes

2022-12-20 08:47 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookieAttribute.php
> +    }
```suggestion
    }
    
```

2022-12-20 08:47 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +    }
```suggestion
    }
    
```

2022-12-20 08:47 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +    public function getCookieParams(?string $lifetime): array
I think we could right out of this function and it could be removed

2022-12-20 08:47 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams = $this->sessionCookieAttributesFactory->create()->getCookieParams($lifeTime);
```suggestion
        $cookieParams = $this->sessionCookieAttributesFactory->create();
        $cookieParams->add(new SessionCookieAttribute('lifetime', $lifeTime));
```

2022-12-20 08:47 UTC, kilatib commented on test/unit/session/Business/Service/SessionCookieServiceTest.php
> +                //var_dump("==ACTUAL ARGUMENTS==:",$globalFunctionExpectation['actualArguments']);
```suggestion
          
```

2022-12-20 12:11 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $cookieParams = $this->sessionCookieAttributesFactory->create()->getCookieParams($lifeTime);
Problem is, create return back with collection and we need an array here as return, I kept create return value as collection to left compatible if called from somewhere else and use getCookieParams() to return an array from collection.

2022-12-20 12:13 UTC, africz commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +            $retVal[$attribute->name()] = $attribute->value();
fixed

2022-12-20 12:17 UTC, africz commented on test/unit/session/Business/Service/SessionCookieServiceTest.php
> +                //var_dump("==ACTUAL ARGUMENTS==:",$globalFunctionExpectation['actualArguments']);
I don't have yet valid PHPStorm license, once I have it I will make neccesary formating changes on the final code

2022-12-20 12:27 UTC, kilatib requested changes

2022-12-20 12:27 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookiePathAttribute.php
> +    private $name;
```suggestion
    private $name;
    
```

2022-12-20 12:27 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookiePathAttribute.php
> +    }
```suggestion
    }
    
```

2022-12-20 12:27 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +            $rawAttributes[] = (string) $attribute;
let's revert that change

2022-12-20 12:27 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +    }
I think now we don't need that method and it not used; Let's revert that change at all
```suggestion
```

2022-12-20 12:27 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookiePathAttribute.php
> +    }
```suggestion
```
If we remove `getParams()` we could remove that methods too

2022-12-20 13:29 UTC, africz commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +    }
interface SessionCookieAttributesFactoryInterface
{
    public function create(): SessionCookieAttributeCollection;
}
this is return back with an object

  $cookieParams = $this->sessionCookieAttributesFactory->create()->getCookieParams($lifeTime);

//session set_cookie_params accept an array
session_set_cookie_params($cookieParams);

getCookieParams make the object-> array conversion

2022-12-20 16:43 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +        }
```suggestion
    $sessionParams['lifetime'] = (int)$sessionParams['lifetime'];
```

2022-12-21 09:02 UTC, kilatib commented
all looks good, just add 2 changes 
1. Update doc
2. Add a test for that case

2022-12-21 09:51 UTC, wazelin requested changes

2022-12-22 21:00 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $lifeTime=(int)($sessionParams['lifetime']);
I made all changes based on above instruction, unit tests are not fixed yet, I will do when the fix is approved.

2022-12-23 08:37 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookieAttribute.php
> +
```suggestion
```

2022-12-23 08:37 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookieAttribute.php
> +}
```suggestion
}

```

2022-12-23 08:44 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +declare (strict_types = 1);
```suggestion
declare(strict_types=1);
```

2022-12-23 08:44 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +        : $sessionParams['domain'];
```suggestion
            ? UriHelper::getDomain(ROOT_URL)
            : $sessionParams['domain'];
```

2022-12-23 08:45 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookieAttribute.php
> +    public function getName()
could you please provide return types?

2022-12-23 08:49 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookiePathAttribute.php
> +    public function getName()
both of this classes (`SessionCookieAttribute`,`SessionCookiePathAttribute`) implementing interface https://github.com/oat-sa/tao-core/blob/6c1c3c6b35bbe2ba57d2ad48fe9f43b4157d3982/models/classes/session/Business/Contract/SessionCookieAttributeInterface.php
attribute collection also tried to rely on it https://github.com/oat-sa/tao-core/blob/12974d676ea679573580c71810ee64a37e1934ac/models/classes/session/Business/Domain/SessionCookieAttributeCollection.php#L33-L34

could you provided this new methods in interface in this case

2022-12-23 08:49 UTC, poyuki commented on models/classes/session/Business/Service/SessionCookieService.php
> +                $params['lifetime']=$params['lifetime'] + time();
```suggestion
                $params['lifetime'] = $params['lifetime'] + time();
```

2022-12-23 08:50 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +    public function toArray(): array
```suggestion
    }

    //iterator_to_array not formated properly as we need for cookie paramters
    //iterator to array make a simple array with objects
    public function toArray(): array
```

2022-12-23 08:59 UTC, africz commented on models/classes/session/Business/Domain/SessionCookieAttribute.php
> +    public function getName()
yes, good point, thank you!

2022-12-23 09:00 UTC, africz commented on models/classes/session/Business/Domain/SessionCookiePathAttribute.php
> +    public function getName()
Yes, I will try

2022-12-23 09:11 UTC, wazelin requested changes

2022-12-23 09:11 UTC, wazelin commented on models/classes/session/Business/Service/SessionCookieService.php
> +                    $params
This will still cause a problem unfortunately.

`lifetime` parameter must be replaced with `expires`, and calculated as `lifetime` + `time()`.

See https://www.php.net/manual/en/function.session-set-cookie-params.php and https://www.php.net/manual/en/function.setcookie.php for reference.

> ... may have any of the keys _expires_, path, domain, secure, httponly and samesite

2022-12-23 09:13 UTC, wazelin commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $lifeTime=(int)($sessionParams['lifetime']);
Lovely!

2022-12-23 09:18 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $params = $this->sessionCookieAttributesFactory->create()->toArray();
```suggestion
        $params = iterator_to_array($this->sessionCookieAttributesFactory->create());
```

2022-12-23 09:20 UTC, poyuki commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $params = $this->sessionCookieAttributesFactory->create()->toArray();
i guess @africz  provided explanation in comment https://oat-sa.atlassian.net/browse/TR-4949?focusedCommentId=210501

2022-12-23 09:28 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $params = $this->sessionCookieAttributesFactory->create()->toArray();
That's link to release steps

2022-12-23 09:30 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookieAttributeCollection.php
> +    public function toArray(): array
actually for collection toArray which return map is counterintuitive from my point of view.
Firs association for me was that method should return list of associative array.
`toArray` in some object which return map is ok, but collection is something else, so may be to reduce misunderstanding in this place we can rename it as `toMap` or `toDictionary`

2022-12-23 10:24 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $params = $this->sessionCookieAttributesFactory->create()->toArray();
Iterator_to_array makes wrong conversion, we need an array with key=>value pairs , not an array with objects.

2022-12-23 11:26 UTC, poyuki commented on models/classes/session/Business/Domain/SessionCookieAttribute.php
> +}
```suggestion
}

```
https://www.php-fig.org/psr/psr-12/#22-files

2022-12-23 11:47 UTC, poyuki commented on models/classes/session/Business/Service/SessionCookieService.php
> +        }
you already set it when found

2022-12-23 11:48 UTC, poyuki commented on models/classes/session/Business/Service/SessionCookieService.php
> +    public function toArray($params): array
in method you ignored everything going outside and always started from empty array

2022-12-23 12:10 UTC, poyuki commented
i create small draft here based on you PR to summarise some comments
https://github.com/oat-sa/tao-core/pull/3711

2022-12-23 12:13 UTC, kilatib requested changes

2022-12-23 12:13 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookieAttribute.php
> +    public function __construct(string $name, $value)
why did you remove typecasting here?

2022-12-23 12:13 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookieAttribute.php
> +
```suggestion
```

2022-12-23 12:13 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookieAttribute.php
> +    public function getValue()
```suggestion
    public function getValue(): string
```

2022-12-23 12:13 UTC, kilatib commented on models/classes/session/Business/Domain/SessionCookiePathAttribute.php
> +    public function getValue()
```suggestion
    public function getValue(): string
```

2022-12-23 12:13 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +        $expires = $params['lifetime'] + time();
I think we should validate is that params present in giving params at all. 

Also, should we get params outside could we get them internally?

2022-12-23 12:17 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +                    $params
required changes are done, lifetime replaced with expires

2022-12-23 17:19 UTC, kilatib requested changes

2022-12-23 17:19 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +        return $sessionCookieParams;
```suggestion
        $sessionCookieParams = [];
        if ($this->cookieParams['lifetime'] !== 0) {
            $sessionCookieParams = $this->getCookieParams();
            $sessionCookieParams['expires'] = $this->getCookieParams()['lifetime'] + time();
            unset($sessionCookieParams['lifetime']);
        }
        return $sessionCookieParams;
```

2022-12-23 17:19 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +    private $cookieParams = [];
```suggestion
```

2022-12-23 17:19 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +    private $attributes = [];
```suggestion
```

2022-12-23 17:40 UTC, africz commented on models/classes/session/Business/Service/SessionCookieService.php
> +        return $sessionCookieParams;
Nice, elegant, thank you!

2022-12-26 14:42 UTC, kilatib commented on models/classes/session/Business/Service/SessionCookieService.php
> +        //   $this->init();
```suggestion

```

2022-12-27 15:10 UTC, poyuki commented
close this PR in favor of https://github.com/oat-sa/tao-core/pull/3712

2022-12-27 15:10 UTC, closed without merging