feat: Script parsing seed file and searching for markers
oat-sa/tao-core pull request #3723
Opened 2023-01-16 11:59 UTC by Karol-Stelmaczonek

Script injects PHP code into config files using markers from seed.json file.
Marker in seed file:
![image](https://user-images.githubusercontent.com/118974926/212672158-616ad10b-d85a-42c8-b74e-be7be1676dff.png)
Script result:
![image](https://user-images.githubusercontent.com/118974926/212673006-cf79137a-d876-4f96-8282-5263fe81afab.png)
This way we can remove secret values from config files.

2023-01-17 09:56 UTC, bartlomiejmarszal requested changes
WHen type hinting we do not need to duplicate annotations with type hointing. Could you remove all places where you using it?
Is it possible to use DI in taSetup? We should always avoid creating directly new class that serves as service. Maybe we could use service manager instead?

2023-01-17 09:56 UTC, bartlomiejmarszal commented on install/utils/ConfigurationMarkers.php
> +     */
```suggestion
```

2023-01-17 09:56 UTC, bartlomiejmarszal commented on install/utils/ConfigurationMarkers.php
> +        $this->notice($message);
```suggestion
        $this->info($message);
```

2023-01-17 09:56 UTC, bartlomiejmarszal commented on install/utils/ConfigurationMarkers.php
> +     */
```suggestion
```

2023-01-17 09:56 UTC, bartlomiejmarszal commented on install/utils/ConfigurationMarkers.php
> +        $this->notice(sprintf('Converted config %s value to PHP Serializable.', $item));
```suggestion
        $this->info(sprintf('Converted config %s value to PHP Serializable.', $item));
```

2023-01-17 09:56 UTC, bartlomiejmarszal commented on install/utils/ConfigurationMarkers.php
> +     */
```suggestion
```

2023-01-17 09:56 UTC, bartlomiejmarszal commented on install/utils/ConfigurationMarkers.php
> +        if ($this->logger === null) {
We should always have some logger, no? Isn't it better to address logger using static methods?

2023-01-17 09:56 UTC, bartlomiejmarszal commented on install/utils/ConfigurationMarkers.php
> +    private function secretValueExist(string $key): bool
This method is an alias for `isset`. What's the point?

2023-01-17 12:11 UTC, Karol-Stelmaczonek commented on install/class.Setup.php
> +        $markers = new ConfigurationMarkers($parameters['configuration']);
Theres a service manager there so I can use it but need to check how to do it.

2023-01-17 12:34 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +    /** @var array */
Removed

2023-01-17 12:34 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +    /** @var ?LoggerInterface */
Removed

2023-01-17 12:36 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +        return $this;
I always add FS never know when they come handy

2023-01-17 12:37 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +    public function setLogger(LoggerInterface $logger): self
I dont want to couple this class with logger, also its not vital for logic to work.

2023-01-17 12:37 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +     */
Removed

2023-01-17 12:37 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +     */
Removed

2023-01-17 12:37 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +     */
Removed

2023-01-17 12:37 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +     */
Removed

2023-01-17 12:38 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +     */
Removed

2023-01-17 12:38 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +        $this->notice($message);
Thx I wanted to do after my test and forgot! Changed.

2023-01-17 12:38 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +        $this->notice(sprintf('Converted config %s value to PHP Serializable.', $item));
Changed

2023-01-17 12:38 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +     */
Removed

2023-01-17 12:41 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +        if ($this->logger === null) {
Its used inside object thats one, second I got it as object from taoSetup scope so thats it. Forcing user to always have logger its unnecessary from point of this class. For me its better to have and option than be forced to.

2023-01-17 12:42 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +    private function secretValueExist(string $key): bool
Yeah I wanted to use it in tests but I gave up on it. I removed function and put isset.

2023-01-17 15:18 UTC, andreluizmachado requested changes
Very Good Job @Karol-Stelmaczonek . I just left some comments to instigate discussion and code quality :).

2023-01-17 15:18 UTC, andreluizmachado commented on install/utils/ConfigurationMarkers.php
> +            if (isset($this->secretsStorage[$matches[1] ?? '']) === false) {
What if I have $_ENV['']='broken env var'?

2023-01-17 15:18 UTC, andreluizmachado commented on install/utils/ConfigurationMarkers.php
> +    private function printMatchNotification(array $match): void
```suggestion
    private function printMatchNotification(bool $isSecretDefined, string $secretName): void
    {
        if (empty($match)) { //I'd leave this conditional on walk, make more sense there from my perspective
            return;
        }

        $message = sprintf('Found seed file marker: %s', $secretName);
        /* if ($isSecretDefined) {
            $message .= sprintf(' and Secrets Storage value "%s"', ); //not sure if it's a good idea, we shouldn't log it for security reasons
        } */
        
        if(!$isSecretDefined) {
            $message .= ' but NO CORRESPONDING value in Secrets Storage!';
        }
        
        $this->info($message);
    }
```

2023-01-17 15:18 UTC, andreluizmachado commented on models/classes/EnvPhpSerializable.php
> +
declare(strict_types=1);

2023-01-17 15:18 UTC, andreluizmachado commented on models/classes/EnvPhpSerializable.php
> +
please check the other new files

2023-01-17 15:22 UTC, andreluizmachado commented on test/unit/models/classes/EnvPhpSerializableTest.php
> +    public function testIndexesAndValues()
Missing return type

2023-01-17 15:26 UTC, andreluizmachado commented on test/unit/install/utils/ConfigurationMarkersTest.php
> +    public function testReplacingMarkers(): void
did you test if the logger was called?

2023-01-17 15:26 UTC, andreluizmachado commented on test/unit/install/utils/ConfigurationMarkersTest.php
> +    public function testReplacingMarkers(): void
when there is no configuration?

2023-01-17 15:26 UTC, andreluizmachado commented on test/unit/install/utils/ConfigurationMarkersTest.php
> +    public function testReplacingMarkers(): void
when there is no match in the regex?

2023-01-18 08:17 UTC, Karol-Stelmaczonek commented on install/class.Setup.php
> +        $markers->setSecretsStorage($_ENV)
Yes $_ENV is populated during app bootstrap process and its available here.

2023-01-18 08:18 UTC, Karol-Stelmaczonek commented on install/class.Setup.php
> +        $parameters['configuration'] = $markers->replace();
Ive checked all other attributes and theres any secret data left only in persistence config. Ive posted it [here](https://oat-sa.atlassian.net/browse/AUT-2896?focusedCommentId=213018)

2023-01-18 08:20 UTC, Karol-Stelmaczonek commented on install/class.Setup.php
> +                            'The class : ' . $className . ' can not be set as a Configurable Service'
Ok Ive touch it so its mine ... changed ;)

2023-01-18 08:21 UTC, Karol-Stelmaczonek commented on install/class.Setup.php
> +                                        'Your config ' . $ext . '/' . $key . ' cannot be set'
@andreluizmachado theres more of it in taoSetup do you want me to change it all to use sprintf?

2023-01-18 08:30 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +    private function printMatchNotification(array $match): void
I've changed it to your suggestion and removed printing secret value. Is only for screen prompt but for sure its also stored somewhere on log file so better remove it, thanks!

2023-01-18 08:40 UTC, andreluizmachado commented on install/class.Setup.php
> +                                        'Your config ' . $ext . '/' . $key . ' cannot be set'
It is just a suggestion, not mandatory.

2023-01-18 09:09 UTC, bartlomiejmarszal commented on install/class.Setup.php
> +                                        'Your config ' . $ext . '/' . $key . ' cannot be set'
You touched it.

2023-01-18 09:12 UTC, bartlomiejmarszal commented on install/utils/ConfigurationMarkers.php
> +    public function setLogger(LoggerInterface $logger): self
IMO it should be in __construct only. It should be easy to implement by DI anyway. I see it as a service

2023-01-18 11:15 UTC, Karol-Stelmaczonek commented on test/unit/install/utils/ConfigurationMarkersTest.php
> +    public function testReplacingMarkers(): void
I've added test for all those cases

2023-01-18 11:17 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +            if (isset($this->secretsStorage[$matches[1] ?? '']) === false) {
Thanks for you comment, I've refactored this part of code and there's no comparison now so I'm good but thanks for the tip!

2023-01-18 11:20 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +            if (isset($this->secretsStorage[$matches[1] ?? '']) === false) {
Right now it just leave it as is, but probably need to remove all broken/mismatched markers from resulting config even if they are under correct config array index. I will change it and add test for it.

2023-01-18 11:20 UTC, Karol-Stelmaczonek commented on install/class.Setup.php
> +                                        'Your config ' . $ext . '/' . $key . ' cannot be set'
I've changed only marked.

2023-01-18 11:21 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +        if ($this->logger === null) {
Moved to __construct

2023-01-19 14:01 UTC, Karol-Stelmaczonek commented on install/class.Setup.php
> +        $markers = new ConfigurationMarkers($parameters['configuration']);
Ok so I've added ServiceProvider for my class and try to use it in taoSetup but failed, then asked Bart to help me and we try to use it and we failed :D Long story short we had to register my service in taoSetup script which is pointless because it require to spawn new instance of my class, store it in service manager and then use it from service manager. That's isn't optimal so we decided to leave it as is.

2023-01-19 14:43 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +            if (isset($this->secretsStorage[$matches[1] ?? '']) === false) {
I changed logic an now if theres no match the script removes markers from config file.

2023-01-20 12:38 UTC, andreluizmachado commented on install/class.Setup.php
> +        $parameters['configuration'] = $markers->replace();
I see but this can be different depending on the customer. Also, it can be very convenient, for example:
Given the following setup.json
```json
{
...
    "postInstall": [
    "InitializeQueue": {
      "class": "oat\\taoTaskQueue\\scripts\\tools\\InitializeQueue",
      "params": [
        "--broker=rds",
        "--persistence=default",
        "--receive=10"
      ]
    },
    ]
...
}
```
as you can see, setup.json gives us the ability to also run scripts. If we enable this feature to the file. we could do some things like:
```json
{
...
    "postInstall": [
    "PassEnvAsParameter": {
      "class": "oat\\taoTaskQueue\\scripts\\tools\\PassEnvAsParameter",
      "params": [
        "--DEBUG=$_ENV[DEBUG]",
      ]
    },
    ]
...
}
```

2023-01-20 12:38 UTC, andreluizmachado commented on install/utils/ConfigurationMarkers.php
> +                $item = '';
you can remove it as you already have the return

2023-01-20 12:38 UTC, andreluizmachado commented on install/utils/ConfigurationMarkers.php
> +        $this->serializableClass = $serializableClass;
This should be part of the constructor as well from my point of view

2023-01-20 12:38 UTC, andreluizmachado commented on install/utils/ConfigurationMarkers.php
> +        $item = new $this->serializableClass($match);
Can't you inject the object directly?

2023-01-20 12:38 UTC, andreluizmachado commented on install/utils/ConfigurationMarkers.php
> +        $this->secretsStorage = $secretsStorage;
same as me comment above

2023-01-20 12:38 UTC, andreluizmachado commented on install/utils/ConfigurationMarkers.php
> +        $this->configurationWithMarkers = $configurationWithMarkers;
This could be a parameter on the replace method

2023-01-20 12:38 UTC, andreluizmachado commented on install/utils/ConfigurationMarkers.php
> +    public function replace(): array
```suggestion
    public function replaceMarkers(array $configurationWithMarkers): array
```

2023-01-20 14:20 UTC, Karol-Stelmaczonek commented on install/class.Setup.php
> +        $parameters['configuration'] = $markers->replace();
Ok I changed it to traverse whole config array not only persistence part

2023-01-20 14:20 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +        $this->serializableClass = $serializableClass;
Changed

2023-01-20 14:21 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +        $item = new $this->serializableClass($match);
Changed it to look more like factory

2023-01-20 14:21 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +        $this->configurationWithMarkers = $configurationWithMarkers;
Changed

2023-01-20 14:21 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +    public function replace(): array
Changed

2023-01-20 14:39 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +                $item = '';
Its passed as reference so I will leave it.

2023-01-24 13:47 UTC, andreluizmachado commented on install/class.Setup.php
> +// @codingStandardsIgnoreStart
```suggestion
// phpcs:disable PSR1.Classes.ClassDeclaration.MissingNamespace, Squiz.Classes.ValidClassName.NotCamelCaps
```

2023-01-30 11:23 UTC, Karol-Stelmaczonek commented on install/utils/ConfigurationMarkers.php
> +        $this->secretsStorage = $secretsStorage;
Moved to constructor

2023-01-30 14:45 UTC, pnal approved these changes
Good job!
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2023-01-30 16:03 UTC, andreluizmachado approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2023-01-31 09:59 UTC, merged