Fix/aut 38/disable htmlencoding in feedback
oat-sa/tao-core pull request #3736
Opened 2023-02-08 13:49 UTC by bartlomiejmarszal

When a user uses special characters for classes and tries to illegally move resources to classes that contain special characters, a warning message is broken. 

How to reproduce:
1. Create a class that contains special characters: i.e: æøå
2. Restrict class for the user so he will have only read access
3. Login as a restricted user 
4. Move resources to a restricted class
5. You should see the correct message without broken characters.

2023-02-08 13:56 UTC, bziondik requested changes
please revert package-lock.json
And next time, no need to add js and css builds. It will done on release automatically
Only if you update scss you need to add css.

2023-02-08 14:58 UTC, Karol-Stelmaczonek approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2023-02-08 14:59 UTC, Karol-Stelmaczonek commented
Just one thing, do we need vendor changes here? Looks odd.

2023-02-09 06:51 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2023-02-09 11:21 UTC, merged