fix: jsonSerialize return type array
oat-sa/tao-core pull request #3738
Opened 2023-02-09 16:29 UTC by bartlomiejmarszal

Missing return type for jsonSerialise cause a massive amount of warnings in logs.

2023-02-13 08:25 UTC, kstelmaczonek commented
Its better now :) But still its 30+ files change so there's could be collateral damage done can we test all those changes?

2023-02-15 09:22 UTC, Karol-Stelmaczonek commented
Piece of good work @bartlomiejmarszal , but from experience I know something can blow up on those return types. Strange edge cases with nulls especially, also we need to check it with PHP8 in mind. Maybe we are covered IDK.

2023-02-15 09:23 UTC, Karol-Stelmaczonek approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2023-02-15 09:23 UTC, Karol-Stelmaczonek commented on models/classes/taskQueue/TaskLog/Entity/TaskLogEntity.php
> +            $rs['createdAtElapsed'] = (new \DateTime(
This formatted block doesn't look good. Below is almost the same and look normal :)

2023-02-15 14:08 UTC, andreluizmachado requested changes
Hey @bartlomiejmarszal,
This PR seems to contain breaking changes for me so I'd leave commits as bellow to follow semantic versioning:
```
fix!: ....
or
fix: xxxx
BREAKING CHANGE: yyy
```

2023-02-15 15:42 UTC, bartlomiejmarszal commented on models/classes/datatable/implementation/AbstractDatatablePayload.php
>          return $this->getPayload();
I will put the correct return types for all related methods.

2023-02-15 15:45 UTC, bartlomiejmarszal commented on models/classes/taskQueue/Task/CallbackTask.php
>          $callableClassOrArray = $this->getCallable();
But it is not callable that is returned. 
```
return parent::jsonSerialize();
```
And it is always array

2023-02-15 16:39 UTC, bartlomiejmarszal commented on models/classes/service/class.Parameter.php
> +    abstract public function jsonSerialize(): array;
I reverted this change

2023-02-28 08:09 UTC, andreluizmachado commented on models/classes/taskQueue/Task/CallbackTask.php
>          $callableClassOrArray = $this->getCallable();
can you please add return type here?
```
    /**
     * @return callable|string|object
     */
    public function getCallable()
    ```

2023-02-28 16:10 UTC, bartlomiejmarszal commented on models/classes/taskQueue/Task/CallbackTask.php
>          $callableClassOrArray = $this->getCallable();
There is many other return types missing. I want to fix only those that are causing errors this time.

2023-03-09 09:14 UTC, merged