fix: Create item or class from subclasses from search result items in left sidebar (Search by label) for TAO Enterprise INVALSI PHP 8.1
oat-sa/tao-core pull request #3746
Opened 2023-02-21 07:13 UTC by chinnu-focaloid

Related to https://oat-sa.atlassian.net/browse/LSI-1825
Fix 500 error when clicking on 'New class'/'New Item' on search result items if the item is under subclasses

2023-02-21 14:53 UTC, wazelin requested changes

2023-02-21 14:53 UTC, wazelin commented on models/classes/resources/ListResourceLookup.php
> +
```suggestion

```

2023-02-21 14:53 UTC, wazelin commented on models/classes/resources/ListResourceLookup.php
> +                    $this->getParentClass($resource)->getUri()
`getParentClass()` return type is nullable, and this expression can result in an null-pointer exception.

2023-02-24 08:11 UTC, wazelin approved these changes

2023-02-28 08:39 UTC, bartlomiejmarszal reviewed
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2023-02-28 08:40 UTC, bartlomiejmarszal approved these changes
Great work!

2023-02-28 09:47 UTC, merged