Feature/aut 2978/rdf import export scripts
oat-sa/tao-core pull request #3747
Opened 2023-02-23 08:24 UTC by pnal

2023-02-23 10:45 UTC, Karol-Stelmaczonek requested changes

2023-02-23 10:45 UTC, Karol-Stelmaczonek commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        return Report::createSuccess(sprintf('%s content saved to %s file', $parentClassUri, $path));
You dont check any output from export() method in L:66 or from file_put_contents from L:68 so assuming that everything went well here is wishful thinking.

2023-02-23 10:45 UTC, Karol-Stelmaczonek commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +    private function fetchContent($content, $targetClass): Report
maybe change name to prepareReport() or generateReport? At the end it's what it does.

2023-02-23 10:45 UTC, Karol-Stelmaczonek commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +class CustomizedRdfImporter extends tao_models_classes_import_RdfImporter
Again how customized? Name its to blurry for me.

2023-02-24 08:52 UTC, andreluizmachado commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        $rdf = $adapter->export($class);
Do we have sufficient memory to export everything into one shot?

2023-02-24 08:52 UTC, andreluizmachado commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        $rdf = $adapter->export($class);
is it a generator?

2023-02-24 09:43 UTC, pnal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        $rdf = $adapter->export($class);
On my local instance 2Gb memory was enough to perform it for over 100k items, I did not find an easy way to improve it.
As it is one time action we could increase a memory limit if it will be an issue.

2023-02-24 09:49 UTC, pnal commented on scripts/tools/export/RDF/CustomizedGenerisAdapterRdf.php
> +class CustomizedGenerisAdapterRdf extends tao_helpers_data_GenerisAdapterRdf
I can propose this name  but it's too long: `NotSkippingResourceRelatedFileLinksGenerisAdapterRdf`
I added comment describing a reason of extending the class instead.
It might be done better if I refactor a source class or do not re-use a code at all but decided to avoid touching legacy code to make the change safe and isolated for the CLI tool only needs.

2023-02-24 09:49 UTC, pnal commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +class CustomizedRdfImporter extends tao_models_classes_import_RdfImporter
I can propose something meaningful but it will be too long: `KeepingOriginalResourceIdentifiersForImportedResourcesRdfImporter`
Added a comment describing a reason of extending the class instead.

2023-02-24 09:50 UTC, pnal commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +    private function fetchContent($content, $targetClass): Report
It does the import itself, not just a helper that generates a report.
even so I renamed it

2023-02-24 10:35 UTC, andreluizmachado commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        $rdf = $adapter->export($class);
It should be enough for now. But I will take a note of this in case we want to enrich this command

2023-02-24 11:52 UTC, pnal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        $rdf = $adapter->export($class);
It is possible to improve if we create a fork and modify this lib: https://github.com/easyrdf/easyrdf/blob/main/lib/Serialiser/RdfXml.php#L233

2023-02-24 12:01 UTC, pnal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        return Report::createSuccess(sprintf('%s content saved to %s file', $parentClassUri, $path));
added try/catch for possible exception

2023-02-24 12:30 UTC, bartlomiejmarszal requested changes
It is a very good approach. I see it as valuable code that we could reuse in future. We should keep it clear and to high standards. I encourage you to keep all code in the correct namespace.

2023-02-24 12:30 UTC, bartlomiejmarszal commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +class CustomizedRdfImporter extends tao_models_classes_import_RdfImporter
Why is this in `oat\tao\scripts\tools\import\RDF` namespace instead of more generic `oat\tao\models\{import domain}`

2023-02-24 12:30 UTC, bartlomiejmarszal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        return Report::createSuccess(sprintf('%s content saved to %s file', $parentClassUri, $path));
and `file_put_contents` function could that be also in try-catch block?

2023-02-24 12:30 UTC, bartlomiejmarszal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        $class = new \core_kernel_classes_Class($parentClassUri);
```suggestion
use OntologyAwareTrait;
# (...)
        $class =         $this->getClass($parentClassUri);
```

2023-02-24 12:30 UTC, bartlomiejmarszal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        $adapter = new CustomizedGenerisAdapterRdf();
Can we use ServiceManager instead?

2023-02-24 12:30 UTC, bartlomiejmarszal commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +        $parser = new tao_models_classes_Parser($filePath, ['extension' => 'rdf']);
Could we register it as a container so we could have access to it through ServiceManager?

2023-02-24 12:30 UTC, bartlomiejmarszal commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +        $graph = new Graph();
This class should be register in ServiceProvider so we  can avoid using the new keywords and just inject required services and classes.

2023-02-24 15:08 UTC, pnal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        return Report::createSuccess(sprintf('%s content saved to %s file', $parentClassUri, $path));
done

2023-02-24 15:09 UTC, pnal commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +class CustomizedRdfImporter extends tao_models_classes_import_RdfImporter
@bartlomiejmarszal moved

2023-02-24 15:09 UTC, pnal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        $class = new \core_kernel_classes_Class($parentClassUri);
done

2023-02-24 15:09 UTC, pnal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +        $adapter = new CustomizedGenerisAdapterRdf();
done

2023-02-24 15:09 UTC, pnal commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +        $parser = new tao_models_classes_Parser($filePath, ['extension' => 'rdf']);
done

2023-02-24 15:28 UTC, pnal commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +        $graph = new Graph();
done

2023-02-24 15:44 UTC, Karol-Stelmaczonek commented on scripts/tools/export/RDF/CustomizedGenerisAdapterRdf.php
> +class CustomizedGenerisAdapterRdf extends tao_helpers_data_GenerisAdapterRdf
Discussed on meeting.

2023-02-24 15:44 UTC, Karol-Stelmaczonek commented on scripts/tools/import/RDF/CustomizedRdfImporter.php
> +class CustomizedRdfImporter extends tao_models_classes_import_RdfImporter
Discussed on meeting.

2023-02-24 15:47 UTC, Karol-Stelmaczonek approved these changes

2023-03-01 11:31 UTC, bartlomiejmarszal requested changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2023-03-01 11:31 UTC, bartlomiejmarszal commented on models/classes/export/CustomizedGenerisAdapterRdf.php
> +class CustomizedGenerisAdapterRdf extends tao_helpers_data_GenerisAdapterRdf
```suggestion
class CustomisedGenerisAdapterRdf extends tao_helpers_data_GenerisAdapterRdf
```

2023-03-01 11:31 UTC, bartlomiejmarszal commented on models/classes/import/CustomizedRdfImporter.php
> +        $parser = new tao_models_classes_Parser($filePath, ['extension' => 'rdf']);
Why is this not a service? Could you include this in service provider?

2023-03-01 11:31 UTC, bartlomiejmarszal commented on models/classes/import/CustomizedRdfImporter.php
> +        $data = $this->easyRdfGraph->serialise($format);
Could you merge this into one line and extract `php` into constant
```suggestion
        $data = $this->easyRdfGraph->serialise(Format::getFormat(self::Format));
```

2023-03-01 11:31 UTC, bartlomiejmarszal commented on models/classes/import/CustomizedRdfImporter.php
> +                $this->importProperties(new RdfResource($subjectUri), $propertiesValues, $map, $targetClass)
Can you use `$this->getResource($subjectUri)`

2023-03-01 11:31 UTC, bartlomiejmarszal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +/**
Could you describe this command a little?

2023-03-01 14:14 UTC, pnal commented on models/classes/import/CustomizedRdfImporter.php
> +        $parser = new tao_models_classes_Parser($filePath, ['extension' => 'rdf']);
Because it is not a service, it takes a path to a file as a constructor method. Until we do not refactor this to a service in order to include it as a service we may create a service with factory method but it will just move keyword `new` to another place. Do you think it is necessary?

2023-03-01 14:16 UTC, pnal commented on scripts/tools/export/RDF/ExportRdfStructure.php
> +/**
Is the description on line 63 below not enough?

2023-03-01 14:20 UTC, pnal commented on models/classes/import/CustomizedRdfImporter.php
> +        $data = $this->easyRdfGraph->serialise($format);
Done

2023-03-01 14:22 UTC, pnal commented on models/classes/import/CustomizedRdfImporter.php
> +                $this->importProperties(new RdfResource($subjectUri), $propertiesValues, $map, $targetClass)
Done

2023-03-01 14:22 UTC, pnal commented on models/classes/export/CustomizedGenerisAdapterRdf.php
> +class CustomizedGenerisAdapterRdf extends tao_helpers_data_GenerisAdapterRdf
Why?

2023-03-01 15:32 UTC, bartlomiejmarszal commented on models/classes/export/CustomizedGenerisAdapterRdf.php
> +class CustomizedGenerisAdapterRdf extends tao_helpers_data_GenerisAdapterRdf
Right. Both are correct.It is fine

2023-03-01 15:40 UTC, bartlomiejmarszal reviewed
It is more a feature than a fix, don't you think?

2023-03-01 16:10 UTC, bartlomiejmarszal approved these changes

2023-03-01 16:19 UTC, merged