fix: add retryTask for all exceptions
oat-sa/tao-core pull request #3752
Opened 2023-03-01 13:17 UTC by tikhanovichA

For some cases related to remote publications, webhook can be failed because delivery is not ready yet. 
We can manage all those retries using `retryMax` option in the webhookRegistry.conf.php if it will be needed.

2023-03-01 14:28 UTC, andreluizmachado commented
Hey, can we also fix PHP CS mentioned on [CIs](https://github.com/oat-sa/tao-core/actions/runs/4304532634/jobs/7505695016)?

2023-03-01 14:34 UTC, pnal requested changes
Please fix a CI CS warning

2023-03-01 14:34 UTC, pnal commented on models/classes/webhooks/WebhookTaskServiceInterface.php
>      /**
`public const SERVICE_ID = 'tao/webhookTaskService';`
on line 30

2023-04-18 15:25 UTC, wazelin requested changes
This looks alright-ish, but potentially dangerous.

Can a more specific exception be added instead to cover the case you're trying to here? If not, consider this approved once the CI is back to green again.

2024-08-07 07:54 UTC, closed without merging