fix: remove EnvironmentValueStorage
oat-sa/tao-core pull request #3783
Opened 2023-04-12 13:33 UTC by bartlomiejmarszal

# How to reproduce

When creating a new image using a container built with environment variables we will not pass container environment variables defined in the new container. 

# Solution

We will not use EnvironmentValueStorage container to store environment variables but instead, we will access them directly.

2023-04-18 07:48 UTC, andreluizmachado commented on models/classes/configurationMarkers/ConfigurationMarkers.php
> +        $isSecretDefined = $_ENV[$matches[1]] ?? false;
instead of accessing global vars directly here, can't we inject it as a dependency ???

2023-04-18 07:52 UTC, albertosgz approved these changes
I agree with Andre's comment

2023-04-18 08:12 UTC, gabrielfs7 commented on models/classes/configurationMarkers/ConfigurationMarkers.php
> +        $isSecretDefined = $_ENV[$matches[1]] ?? false;
Yes, I agree with @andreluizmachado . You can just do this:

```
public function __construct(
        SerializableSecretDtoFactory $serializableFactory,
        LoggerInterface $logger,
        array $envVars = null
    ) {
        $this->serializableFactory = $serializableFactory;
        $this->logger = $logger;
        $this->envVars = $envVars ?? $_ENV;
    }
```

And here 

```suggestion
        $isSecretDefined = $this->envVars[$matches[1]] ?? false;
```

2023-04-18 08:18 UTC, bartlomiejmarszal commented on models/classes/configurationMarkers/ConfigurationMarkers.php
> +        $isSecretDefined = $_ENV[$matches[1]] ?? false;
I'm a little confused here. The whole point of this change was to remove injecting env variables in __constructor. And now we want to inject it in a different place. 
What if I use `getenv` function instead of referring to a global variable?

2023-04-18 09:08 UTC, gabrielfs7 commented on models/classes/configurationMarkers/ConfigurationMarkers.php
> +        $isSecretDefined = $_ENV[$matches[1]] ?? false;
The point is to remove it from the container definition, otherwise it is not dynamic anymore, but static.

2023-04-19 08:36 UTC, pnal requested changes
agree with injecting env array as the class property

2023-04-19 15:36 UTC, gabrielfs7 commented on models/classes/configurationMarkers/ConfigurationMarkers.php
> +        $this->envVars = $_ENV;
We should still add it as constructor parameter to be able to mock it on tests and not couple it to this very class. Example: 

```
public function __construct(
        SerializableSecretDtoFactory $serializableFactory,
        LoggerInterface $logger,
        array $vars = null
    ) {
        $this->serializableFactory = $serializableFactory;
        $this->logger = $logger;
        $this->envVars = $vars ?? $_ENV;
```

P.s: You do not need to change anything in the Container provider ;)

2023-04-20 09:42 UTC, Karol-Stelmaczonek approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2023-04-20 12:17 UTC, andreluizmachado approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2023-04-20 13:37 UTC, gabrielfs7 approved these changes

2023-04-20 13:39 UTC, merged