Feature/adf 1424/front end permissions radio buttons
oat-sa/tao-core pull request #3784
Opened 2023-04-14 09:41 UTC by rgomeztao

coming from [https://oat-sa.atlassian.net/browse/ADF-1424](https://oat-sa.atlassian.net/browse/ADF-1424)

changes:
* adds radio buttons values to event handling

2023-04-18 07:40 UTC, jsconan requested changes
Wrong prettier applied, could you fix it first?

2023-04-18 07:40 UTC, jsconan commented on views/js/layout/actions/common.js
> +  "module",
**issue:** It looks like your IDE is misconfigured. It applied the wrong code style. Please check that Prettier is properly configured, with respect to `@oat-sa/prettier-config`

2023-04-18 10:32 UTC, rgomeztao commented on views/js/layout/actions/common.js
> +  "module",
I have updated my phpstorm configuration and re run prettier, let see if this fixes it, thanks!

2023-04-18 11:07 UTC, jsconan requested changes
The overall look okayish. However, did you try with `aclTransferMode = false`?

2023-04-18 11:07 UTC, jsconan commented on views/js/layout/actions/common.js
> +                    showACL: module.config().aclTransferMode !== undefined,
**issue:** same issue 😄

2023-04-18 11:07 UTC, jsconan commented on views/js/provider/resources.js
> +                        aclMode: aclTransferMode
**suggestion:** It would have been better to use a consistent name, and it then this would allow using object shorthand.
```suggestion
                        aclMode
```

2023-04-19 07:41 UTC, jsconan approved these changes
It works as expected, once the place is set up.
![image](https://user-images.githubusercontent.com/1500098/233001807-6800bfd6-1558-4a61-a3d4-9c7ca1924695.png)

I added a few suggestions, nothing blocking.

Regarding the PR description, it would have been nice to write the steps for testing the feature atomically. Like so:
- open the file `config/tao/client_lib_config_registry.conf.php`
- add these lines:
    ```php
        'layout/actions/common' => [
            'aclTransferMode' => 'acl.keep.original' // or 'acl.use.destination'
        ]
    ```
- from the TAO backoffice, copy items/tests/... and see the additional parameters

**Note:** The frontend dependency is not linked. Usually, we add the link in the package.json file, with the branch as a temporary link, and we mention it in the description. This will save time for the reviewers...

I had to manually set this line:
```
"@oat-sa/tao-core-ui": "https://github.com/oat-sa/tao-core-ui-fe.git#feature/adf-1424/acl-section-on-destination-selector",
```

2023-04-19 07:41 UTC, jsconan commented on views/js/provider/resources.js
> +                        aclMode
**suggestion:** As the code is reformatted, it could be the good time too to convert it to ES6, like object shorthand.
```suggestion
                        uri, destinationClassUri, signature, aclMode
```

2023-04-19 07:41 UTC, jsconan commented on views/js/provider/resources.js
> +            moveTo: function moveTo(ids, destinationClassUri, aclTransferMode) {
```suggestion
            moveTo: function moveTo(ids, destinationClassUri, aclMode) {
```

2023-04-19 11:02 UTC, merged