Feat/pisa25 364/ckeditor sourcedialog plugin
oat-sa/tao-core pull request #3822
Opened 2023-05-23 14:25 UTC by shaveko

related to https://oat-sa.atlassian.net/browse/PISA25-364

### Description

This PR enables the [sourcedialog](https://ckeditor.com/cke4/addon/sourcedialog) plugin based on environment configuration 

To enable sourceditor .env file in project root has to be updated withthe following string:

```
FEATURE_FLAG_CKEDITOR_SOURCEDIALOG=true
```

### How to test

Test with installed version of tao

2023-05-24 15:19 UTC, rgomeztao approved these changes
looks nice, pretty straightforward, i left a comment optional to review, nice work!

2023-05-25 08:50 UTC, jsconan requested changes
It works, but I'm not sure we need to add code for loading the env var.

Regarding the behavior, I think it is not correct. The source should be inline, not in a popup.
![image](https://github.com/oat-sa/tao-core/assets/1500098/47bc59c3-34ee-4dd8-899a-dfd60956e0bc)

2023-05-25 08:50 UTC, jsconan commented on models/classes/featureFlag/Repository/FeatureFlagRepository.php
> +        $output[FeatureFlagCheckerInterface::FEATURE_FLAG_CKEDITOR_SOURCEDIALOG] = $sourceDialogEnabledInEnv;
**thought:** Is it actually needed??? I'd expect this to be automated. Actually, it should: https://github.com/oat-sa/tao-core/pull/3822/files#diff-1fe008b3b60d47cd1fe865ec3202300e46008d2afabfcf4564bde407ec4e3b29R83-R87

2023-05-25 08:50 UTC, jsconan commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_CKEDITOR_SOURCEDIALOG = 'FEATURE_FLAG_CKEDITOR_SOURCEDIALOG';
**chore:** Please document the feature flag in the readme. See https://github.com/oat-sa/tao-core/tree/develop#environment-variables

2023-05-25 09:32 UTC, shaveko commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_CKEDITOR_SOURCEDIALOG = 'FEATURE_FLAG_CKEDITOR_SOURCEDIALOG';
Thanks, added the doc

2023-05-25 09:39 UTC, shaveko commented on models/classes/featureFlag/Repository/FeatureFlagRepository.php
> +        $sourceDialogEnabledInEnv = filter_var($_ENV['FEATURE_FLAG_CKEDITOR_SOURCEDIALOG'] ?? false, FILTER_VALIDATE_BOOLEAN) ?? false;
Removed the code, it works well without it

2023-05-25 09:39 UTC, shaveko commented on models/classes/featureFlag/Repository/FeatureFlagRepository.php
> +        $output[FeatureFlagCheckerInterface::FEATURE_FLAG_CKEDITOR_SOURCEDIALOG] = $sourceDialogEnabledInEnv;
Thanks, indeed, it works well without that code.

2023-05-25 10:34 UTC, jsconan approved these changes
All good!
As the ACs have been updated, the behavior is acceptable.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code respects code style rules
- [x] New code respects best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

2023-05-26 15:34 UTC, gabrielfs7 commented on models/classes/featureFlag/FeatureFlagCheckerInterface.php
> +    public const FEATURE_FLAG_CKEDITOR_SOURCEDIALOG = 'FEATURE_FLAG_CKEDITOR_SOURCEDIALOG';
Maybe we do not need to have it here as it is only used in the FE and already present in the README.md

2023-05-26 15:34 UTC, gabrielfs7 commented on views/package.json
> +        "@oat-sa/tao-core-shared-libs": "git+https://github.com/oat-sa/tao-core-shared-libs-fe#feat/PISA25-364/add-sourcedialog-plugin",
- [ ] Just a reminder to update it before merge

2023-05-31 11:34 UTC, gabrielfs7 approved these changes

2023-05-31 13:02 UTC, merged