[FEATURE][SOLAR-59] Portal authoring access
oat-sa/tao-core pull request #3840
Opened 2023-06-15 15:47 UTC by andreluizmachado

2023-06-16 08:44 UTC, Karol-Stelmaczonek commented on migrations/Version202306151107152234_tao.php
> +        return '';
Please add description.

2023-06-16 08:47 UTC, Karol-Stelmaczonek commented on models/classes/theme/ConfigurableTheme.php
> +                $template = Template::getTemplate('blocks/logout-button.tpl', 'tao');
its minor but case is `logout` and template name is `logout-button`, not consistent.

2023-06-16 08:47 UTC, Karol-Stelmaczonek commented on models/classes/theme/PortalTheme.php
> +                return Template::getTemplate('blocks/portal/back-button.tpl', 'tao');
same here, without name consistency

2023-06-16 08:49 UTC, Karol-Stelmaczonek commented on views/templates/blocks/logout-button.tpl
> +    <a id="logout" href="<?= get_data('logout') ?>" title="<?= __('Log Out') ?>">
Shouldn't it be 'Logout'?

2023-06-16 08:49 UTC, Karol-Stelmaczonek commented on views/templates/blocks/portal/logout-menu-settings.tpl
> +    <a id="logout" href="<?= get_data('logout') ?>" title="<?= __('Log Out') ?>">
Shouldn't it be 'Logout'?

2023-06-20 07:16 UTC, andreluizmachado commented on models/classes/theme/ConfigurableTheme.php
> +                $template = Template::getTemplate('blocks/logout-button.tpl', 'tao');
This is because we now 2 templates for logout. One is a button, the other is a link

2023-06-20 07:17 UTC, andreluizmachado commented on models/classes/theme/PortalTheme.php
> +                return Template::getTemplate('blocks/portal/back-button.tpl', 'tao');
On portal we do not render a logo on the header, but a button which goes back to portal

2023-06-20 07:20 UTC, andreluizmachado commented on views/templates/blocks/logout-button.tpl
> +    <a id="logout" href="<?= get_data('logout') ?>" title="<?= __('Log Out') ?>">
No, this is how it was done before. https://github.com/oat-sa/tao-core/blob/49ee2296470509e21c3cd5308f2552c906cbb019/views/templates/blocks/header-main-navi.tpl#L104

2023-06-20 07:20 UTC, andreluizmachado commented on views/templates/blocks/portal/logout-menu-settings.tpl
> +    <a id="logout" href="<?= get_data('logout') ?>" title="<?= __('Log Out') ?>">
https://github.com/oat-sa/tao-core/pull/3840#discussion_r1234842742

2023-06-20 08:02 UTC, pnal approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2023-06-20 12:08 UTC, bartlomiejmarszal commented on models/classes/mvc/DefaultUrlModule/TaoPortalResolver.php
> + *  Copyright (c) 2017 (original work) Open Assessment Technologies SA (under the project TAO-PRODUCT);
```suggestion
 *  Copyright (c) 2023 (original work) Open Assessment Technologies SA (under the project TAO-PRODUCT);
```

2023-06-20 12:09 UTC, bartlomiejmarszal commented on models/classes/mvc/DefaultUrlModule/TaoPortalResolver.php
> + */
```suggestion
```

2023-06-20 12:11 UTC, bartlomiejmarszal commented on models/classes/theme/PortalTheme.php
> + */
```suggestion
```

2023-06-20 12:13 UTC, bartlomiejmarszal commented on models/classes/theme/ThemeService.php
> +        if ($this->getFeatureFlagChecker()->isEnabled('FEATURE_FLAG_ENABLE_PORTAL_LAYOUT')) {
Can we use feature flag that is describing feature?

2023-06-20 12:14 UTC, bartlomiejmarszal commented on models/classes/theme/ThemeService.php
> +    public function getFeatureFlagChecker(): FeatureFlagCheckerInterface
Why don't we register this a container and define this service in service provider?

2023-06-20 12:14 UTC, bartlomiejmarszal commented on scripts/install/RegisterPortalLogoutActionResolver.php
> + * Copyright (c) 2020-2021 (original work) Open Assessment Technologies SA (under the project TAO-PRODUCT);
```suggestion
 * Copyright (c) 2023 (original work) Open Assessment Technologies SA (under the project TAO-PRODUCT);
```

2023-06-20 12:15 UTC, bartlomiejmarszal commented on scripts/install/RegisterPortalTheme.php
> +class RegisterPortalTheme extends InstallAction
We should use DI instead

2023-06-20 12:16 UTC, bartlomiejmarszal commented on views/package.json
> +    "@oat-sa/tao-core-ui": "https://github.com/oat-sa/tao-core-ui-fe#feature/SOLAR-59/back-button-icon",
Please make sure to fix this before we merge. Mabe we could use todo keyword?

2023-06-20 12:34 UTC, andreluizmachado commented on models/classes/theme/PortalTheme.php
> +                return Template::getTemplate('blocks/portal/logout-menu-settings.tpl', 'tao');
It is part of ACs. Please check SOLAR-59

2023-06-20 12:36 UTC, andreluizmachado commented on helpers/class.Icon.php
> +        return self::buildIcon(self::CLASS_BACK_BUTTON, $options);
As far as I know, UX provided it to us. Correct If  am wrong @viktar-dzmitryieu-tao

2023-06-20 12:39 UTC, andreluizmachado commented on models/classes/theme/ThemeService.php
> +        if ($this->getFeatureFlagChecker()->isEnabled('FEATURE_FLAG_ENABLE_PORTAL_LAYOUT')) {
not sure If I understood. Do you have a suggestion?

2023-06-20 12:39 UTC, andreluizmachado commented on scripts/install/RegisterPortalTheme.php
> +class RegisterPortalTheme extends InstallAction
As far as I know, we do not use DI for controllers, actions

2023-06-20 12:51 UTC, andreluizmachado commented on migrations/Version202306151107152234_tao.php
> +        $this->registerLogoutActionResolver();
RegisterPortalLogoutActionResolver is an action class. not sure if i can call it here directly.

2023-06-20 12:57 UTC, viktar-dzmitryieu-tao commented on helpers/class.Icon.php
> +        return self::buildIcon(self::CLASS_BACK_BUTTON, $options);
this icon was exported from Figma design.

2023-06-20 13:01 UTC, andreluizmachado commented on migrations/Version202306151107152234_tao.php
> +        $this->registerLogoutActionResolver();
Unless I do:
```
        $registerAction = new RegisterTaoLogoutActionResolver();
        $registerAction->setServiceLocator($this->getServiceLocator());
        $registerAction();
```
Let me know what you prefer.

2023-06-20 13:22 UTC, bartlomiejmarszal requested changes
Can we reconsider logout button

2023-06-20 13:22 UTC, bartlomiejmarszal commented on migrations/Version202306200857162234_tao.php
> +final class Version202306200857162234_tao extends AbstractMigration
Why don't we use one migration instead?

2023-06-20 13:22 UTC, bartlomiejmarszal commented on models/classes/mvc/DefaultUrlModule/TaoLogoutResolver.php
> +    use ServiceLocatorAwareTrait;
Do we need this?

2023-06-20 13:24 UTC, andreluizmachado commented on models/classes/mvc/DefaultUrlModule/TaoLogoutResolver.php
> +    use ServiceLocatorAwareTrait;
yes, RedirectResolveInterface extends ServiceLocatorAwareInterface which requires to implement two methods implemented by this trait.

2023-06-20 13:25 UTC, andreluizmachado commented on migrations/Version202306200857162234_tao.php
> +final class Version202306200857162234_tao extends AbstractMigration
too many responsibilities just for one migration. That's why I divided on this case.

2023-06-20 13:31 UTC, andreluizmachado commented on models/classes/theme/PortalTheme.php
> +                return Template::getTemplate('blocks/portal/logout-menu-settings.tpl', 'tao');
This was validate with PO already.

2023-06-23 09:14 UTC, Karol-Stelmaczonek approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2023-06-27 08:21 UTC, viktar-dzmitryieu-tao approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X]  New code is respecting code style rules
- [X]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [X]  Acceptance criteria are respected
- [X]  Pull request title and description are meaningful

2023-06-27 11:41 UTC, bartlomiejmarszal reviewed
**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2023-06-27 11:41 UTC, bartlomiejmarszal commented on models/classes/theme/PortalTemplateFinderTrait.php
> +     */
```suggestion
    /**
     * @thorws InvalidArgumentException
     */
```

2023-07-10 11:53 UTC, bartlomiejmarszal approved these changes

2023-07-10 11:53 UTC, merged