fix: Set literal range for UpdatedBy resource
oat-sa/tao-core pull request #3913
Opened 2023-10-19 15:38 UTC by yaraslau-kavaliou

Queries with `UpdatedBy` property produced the wrong query to neo4j because `UpdatedBy` range was set to `User` type.
E. g. - https://github.com/oat-sa/generis/blob/feat/REL-1198/list-neo4j/test/integration/model/persistence/starsql/ClassTest.php#L71
In order to fix rdf `UpdatedBy` range has been set to literal.

How to test:
1. Launch integration tests twice. No issue have to occur. (`php vendor/bin/phpunit -c phpunit.xml generis/test/integration/model/persistence/starsql/`)

2023-10-20 13:28 UTC, vbyndych requested changes
@yaraslau-kavaliou You will need a migration to sync RDFs from the file to the database. See https://github.com/oat-sa/tao-core/blob/master/migrations/Version202307101518342234_tao.php as an example.

2023-10-20 13:28 UTC, vbyndych commented on models/ontology/tao.rdf
> -      <rdfs:range rdf:resource="http://www.tao.lu/Ontologies/TAO.rdf#User"/>
This was not a mistake, it was intentional to make the `UpdatedBy` field a relationship, so it would go to the user resource who made a change. But we have an issue with either detection mechanics ([isRelationship method](https://github.com/oat-sa/generis/blob/eb99b9078aa9ef19f3d0cee98d6790a567e8966a/core/kernel/classes/class.Property.php#L399)) or creation logic (https://github.com/oat-sa/generis/blob/eb99b9078aa9ef19f3d0cee98d6790a567e8966a/core/kernel/persistence/starsql/class.Class.php#L215), which despite the relation type sets it as a plain property.

So I suggest fixing it there rather than changing RDF.

2023-10-23 15:55 UTC, yaraslau-kavaliou commented
> @yaraslau-kavaliou You will need a migration to sync RDFs from the file to the database. See https://github.com/oat-sa/tao-core/blob/master/migrations/Version202307101518342234_tao.php as an example.

Thanks, done

2023-10-23 16:52 UTC, vbyndych approved these changes

2023-10-25 08:03 UTC, merged