Feature/tr 5892 integrate google analytics
oat-sa/tao-core pull request #3948
Opened 2024-01-09 14:24 UTC by btamas

Related to https://oat-sa.atlassian.net/browse/TR-5892

Include Google analytics tag script.

Environment variables are already added: https://github.com/oat-sa/taocloud-k8s/blob/develop/construct/construct.libsonnet#L75

Test:
- set `GA_TAG` and `NODE_ENV` environment variable and check layout header.

2024-01-09 14:30 UTC, pribi commented on helpers/Layout.php
> +        $environment = getenv('NODE_ENV') === 'production' ? 'Production': 'Internal';
592 | ERROR | [x] Expected at least 1 space before ":"; 0 found

Can you please put one space character before the : ?
        $environment = getenv('NODE_ENV') === 'production' ? 'Production' : 'Internal';

2024-01-09 14:32 UTC, andreluizmachado commented on helpers/Layout.php
> +    public static function getAnalyticsCode()
```suggestion
    public static function getAnalyticsCode(): string
```

2024-01-09 14:33 UTC, bartlomiejmarszal requested changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2024-01-09 14:33 UTC, bartlomiejmarszal commented on helpers/Layout.php
> +    public static function getAnalyticsCode()
```suggestion
    /**
     * Returns the necessary analytics code
     */
    public static function getAnalyticsCode(): string
```

2024-01-09 14:33 UTC, bartlomiejmarszal commented on helpers/Layout.php
> +        $gaTag = getenv('GA_TAG');
Is this a feature flag? If so we should use [Feature flag implementation](https://github.com/oat-sa/tao-core/blob/master/models/classes/featureFlag/README.md)

2024-01-09 14:34 UTC, andreluizmachado commented on helpers/Layout.php
> +        $environment = getenv('NODE_ENV') === 'production' ? 'Production' : 'Internal';
Can it be `ucfirst(getenv('NODE_ENV'))`?

2024-01-09 14:34 UTC, Karol-Stelmaczonek approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2024-01-09 14:34 UTC, Karol-Stelmaczonek commented on helpers/Layout.php
> +    public static function getAnalyticsCode()
I think we can add return type here.

2024-01-09 14:34 UTC, Karol-Stelmaczonek commented on views/templates/blocks/analytics.tpl
> +</script>
Missing newline at the end of file.

2024-01-09 14:34 UTC, Karol-Stelmaczonek commented on helpers/Layout.php
> +use oat\tao\helpers\Template;
Its same namespace, you don't need import it.

2024-01-09 14:35 UTC, btamas commented on helpers/Layout.php
> +        $gaTag = getenv('GA_TAG');
This is a string that defines of the Google Tag identifier.

2024-01-09 14:35 UTC, andreluizmachado commented on helpers/Layout.php
> +        $gaTag = getenv('GA_TAG');
it seems to be a config

2024-01-09 14:36 UTC, pribi commented on helpers/Layout.php
> +        $gaTag = getenv('GA_TAG');
Is GA_TAG always defined in env? I mean if it is not defined by accident this can trigger an error.

2024-01-09 14:36 UTC, Karol-Stelmaczonek commented
It would be great to add some simple unittest to it under `test/unit/helpers/`

2024-01-09 14:41 UTC, andreluizmachado commented on views/templates/blocks/analytics.tpl
> +<script async src="https://www.googletagmanager.com/gtag/js?id=<?= get_data('gaTag') ?>"></script>
I remember a long time ago how easily you could break your application using Google Tag Manager as this allows users from gtm to dynamically add js code on the page. Do we plan to enable it to all the customers?

2024-01-10 07:06 UTC, btamas commented on helpers/Layout.php
> +        $environment = getenv('NODE_ENV') === 'production' ? 'Production' : 'Internal';
Not really. If it is defined and it is production, it is `Production`, but if it is not defined or anything else, it is `Internal`

2024-01-10 07:09 UTC, btamas commented on views/templates/blocks/analytics.tpl
> +<script async src="https://www.googletagmanager.com/gtag/js?id=<?= get_data('gaTag') ?>"></script>
I think yes, or at least for ignite clients. This was requested by marketing to be able to track the users.

2024-01-10 08:04 UTC, btamas commented
> It would be great to add some simple unittest to it under `test/unit/helpers/`

@Karol-Stelmaczonek Can you please help me, because I don't know how can I mock static functions.

2024-01-10 18:27 UTC, pribi requested changes
I checked in my local environment created with taoDockerize.
- I see the GA code is included in the source:
![Screenshot from 2024-01-10 19-22-52](https://github.com/oat-sa/tao-core/assets/8711268/719932f1-20c3-4a9d-82f5-2578f8556738)
- There are some errors in the console:
![Screenshot from 2024-01-10 19-26-02](https://github.com/oat-sa/tao-core/assets/8711268/c865b0bb-7af1-452c-9efa-4cb709f4e4db)
Maybe my test environment is not properly setup. Let's discuss how we can check the feature together.

2024-01-10 18:27 UTC, pribi commented on helpers/Layout.php
> +            return Template::inc('blocks/analytics.tpl', 'tao', ['gaTag' => $gaTag, 'environment' => $environment]);
As far as I can see Template:inc returns void, so it won't work with the expected return type: string.

2024-01-10 18:27 UTC, pribi commented on views/templates/layout.tpl
> +    <?= Layout::getAnalyticsCode() ?>
Expected value type is string, but we got string|void instead.

2024-01-12 09:09 UTC, pribi approved these changes
LGTM. Tested in local environment the feature is working properly. The PR contains my changes / fixes as well, so my code review is not very relevant. Because I cannot review my own code. Therefore we need additional code review from other people, @andreluizmachado, @bartlomiejmarszal what do you think?

2024-01-12 09:10 UTC, pribi commented
> I checked in my local environment created with taoDockerize.
> 
> * I see the GA code is included in the source:
>   ![Screenshot from 2024-01-10 19-22-52](https://private-user-images.githubusercontent.com/8711268/295668092-719932f1-20c3-4a9d-82f5-2578f8556738.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTA4NDIsIm5iZiI6MTcwNTA1MDU0MiwicGF0aCI6Ii84NzExMjY4LzI5NTY2ODA5Mi03MTk5MzJmMS0yMGMzLTRhOWQtODJmNS0yNTc4Zjg1NTY3MzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDkwOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWJjYTAyODQ0OTlmZDU5ZmIxNjcwYjMzM2MzNWYzZDZiNzc3N2RlOTgwMTc5ODgxMDc5YmNlNjczNGIyMGE5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NHbEBNjJeFUvvnXivCdnJlb-H5Sxb9ygG06UOP38wTg)
> * There are some errors in the console:
>   ![Screenshot from 2024-01-10 19-26-02](https://private-user-images.githubusercontent.com/8711268/295668250-c865b0bb-7af1-452c-9efa-4cb709f4e4db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTA4NDIsIm5iZiI6MTcwNTA1MDU0MiwicGF0aCI6Ii84NzExMjY4LzI5NTY2ODI1MC1jODY1YjBiYi03YWYxLTQ1MmMtOWVmYS00Y2I3MDlmNGU0ZGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMDkwOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGI1MDUwYmI3YTRiN2JjMjJmZjk2MzEzMmY3MTZhNGQ0NDZhZDRkZDIwMGZjYTRhMjQxNWY5Y2FmMjc1N2M5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Bv6TK0tGrzOuhT9Ban3ndMXKo-4TaomVcLB64jakFlQ)
>   Maybe my test environment is not properly setup. Let's discuss how we can check the feature together.

These issues are fixed by additional commits.

2024-01-12 15:29 UTC, btamas commented
Does anybody else plans to review it? It was tested, I have the 2 approvals, so if not, I will merge it. @bartlomiejmarszal @andreluizmachado

2024-01-12 16:13 UTC, bartlomiejmarszal approved these changes

2024-01-15 07:29 UTC, merged