AUT-3552 fix: do not duplicate read only labels (model 2)
oat-sa/tao-core pull request #3973
Opened 2024-03-08 08:51 UTC by pnal

This PR aims to avoid saving/duplicating system properties from UI

How to test:
- Install recent TAO release with test-centers extension
- Select Test-taker root class
- Submit edit from or submit schema (properties) form
- Create test-center
- See duplicates as described [in the ticket](https://oat-sa.atlassian.net/browse/AUT-3552)
- Switch tao-core to this PRs branch and run taoUpdate
- Ensure that the duplicate has gone
- Submit forms related Test-taker root class as before
- Check that the duplicates do not appear anymore
- Check that other properties (which form inputs are not disabled) still editable from UI

2024-03-12 07:57 UTC, tikhanovichA requested changes

2024-03-12 07:57 UTC, tikhanovichA commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        return $property->isWritable();
```suggestion
        return !$property->isWritable();
```
Maybe we should return false if it's writable as the method is `isBlockedForModification`. Because we should block for writing if a property is not writable

2024-03-12 10:10 UTC, pnal commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +        return $property->isWritable();
Good point, seems I forgot to change it while worked on unit tests

2024-03-12 10:27 UTC, tikhanovichA approved these changes
LGTM
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2024-03-22 11:23 UTC, bartlomiejmarszal requested changes
How is your migration fix duplicated label for test taker?

**Review Checklist**
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2024-03-22 11:23 UTC, bartlomiejmarszal commented on actions/form/class.EditClassLabel.php
> +                $readonly = \tao_helpers_form_FormFactory::getElement('', 'Readonly');
Could you put this in import block?
```suggestion
                $readonly = tao_helpers_form_FormFactory::getElement('', 'Readonly');
```

2024-03-22 11:23 UTC, bartlomiejmarszal commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +
Why not use Ontology trait?

2024-03-25 08:22 UTC, pnal commented on models/classes/dataBinding/class.GenerisInstanceDataBinder.php
> +
I was unable to test my changes with trait, finally I had to revert my changes but decided to leave the Ontology usage refactoring

2024-03-25 10:09 UTC, pnal commented on actions/form/class.EditClassLabel.php
> +                $readonly = \tao_helpers_form_FormFactory::getElement('', 'Readonly');
`How is your migration fix duplicated label for test taker?`
it removes a duplicate, other changes in controllers does not allow to create them back

2024-03-25 12:19 UTC, bartlomiejmarszal approved these changes

2024-03-25 12:20 UTC, merged