fix google tag rendering
oat-sa/tao-core pull request #3978
Opened 2024-03-12 16:59 UTC by poyuki

# [TR-6036](https://oat-sa.atlassian.net/browse/TR-6036)

## Summary
This PR aim to address issue with rendering of GA tag in some environments

## Development impact
- fixed usage of deprecated sort tag `<? ?>` (which at least on `uat.eu.premium.lab.taocloud.org` converted into html comment)
- used `$_ENV` instead of `getenv` (usage of which [discouraged](https://github.com/vlucas/phpdotenv?tab=readme-ov-file#putenv-and-getenv) by dotenv lib documentation )

2024-03-12 17:01 UTC, kilatib approved these changes
LGTM  now

2024-03-12 19:12 UTC, wazelin requested changes

2024-03-12 19:12 UTC, wazelin commented on helpers/Layout.php
> +        $environment = $_ENV['NODE_ENV'] === 'production' ? 'Production' : 'Internal';
We need to check if the keys are set in $_ENV now before accessing them to avoid undefined-key warnings.

2024-03-12 19:19 UTC, wazelin requested changes

2024-03-12 19:19 UTC, wazelin commented on views/templates/layout.tpl
> +<?= Layout::getAnalyticsCode(); ?>
This function returns `void`. 
Echoing its response out is pointless I believe.
```suggestion
<?php Layout::getAnalyticsCode(); ?>
```

2024-03-13 09:18 UTC, poyuki commented on helpers/Layout.php
> +        $environment = $_ENV['NODE_ENV'] === 'production' ? 'Production' : 'Internal';
actually `$_ENV['GA_TAG']` will be null if it not define as far as I can see

2024-03-13 09:19 UTC, poyuki commented on views/templates/layout.tpl
> +<?= Layout::getAnalyticsCode(); ?>
fair enough

2024-03-13 10:43 UTC, wazelin commented on helpers/Layout.php
> +        $environment = $_ENV['NODE_ENV'] === 'production' ? 'Production' : 'Internal';
Yes. But it will also raise a PHP warning :)

2024-03-13 14:23 UTC, wazelin approved these changes
Well done, @poyuki!

Let's merge and port to the March release:
1. On top of https://github.com/oat-sa/tao-core/releases/tag/v54.2.2
2. Then as part of TAO Community
3. Then include TAO Community to https://github.com/oat-sa/taocloud-ami-luoss/blob/release-2024.03.2/composer.json#L103

2024-03-13 15:50 UTC, merged