feat: replaced the TaoAsTool FF by Verifying TaoLtiSession
oat-sa/tao-core pull request #3983
Opened 2024-03-15 09:33 UTC by andreluizmachado

- Removed the Environment Variable `FEATURE_FLAG_TAO_AS_A_TOOL`
- Instead of using the enviornment variable, we will now check the session type `TaoLtiSession`

Refs: https://oat-sa.atlassian.net/browse/RFE-847
Refs: https://github.com/oat-sa/tao-portal/pull/720

2024-03-20 12:34 UTC, bartlomiejmarszal requested changes
Could we simplify this PR by just registering those services that are using configs with correct configurations by ServiceProvider?

2024-03-20 12:34 UTC, bartlomiejmarszal commented on models/classes/AuthoringAsTool/AuthoringAsToolEnvironmentVariableConfigProvider.php
> +class AuthoringAsToolEnvironmentVariableConfigProvider implements AuthoringAsToolConfigProviderInterface
What a name! Longer than an actual content ;)

2024-03-20 12:34 UTC, bartlomiejmarszal commented on models/classes/mvc/DefaultUrlService.php
> +     * @return string|null
```suggestion
```

2024-03-20 12:34 UTC, bartlomiejmarszal commented on models/classes/mvc/DefaultUrlService.php
> +     *
```suggestion
```

2024-03-20 12:34 UTC, bartlomiejmarszal commented on models/classes/theme/ThemeServiceAbstract.php
> +            ->isAuthoringAsToolEnabled();
Could we register it as a service instead?

2024-03-20 12:34 UTC, bartlomiejmarszal commented on models/classes/AuthoringAsTool/AuthoringAsToolConfigProviderInterface.php
> +interface AuthoringAsToolConfigProviderInterface
Why don't we put those configs directly on service that is using this configs?

2024-03-20 12:34 UTC, bartlomiejmarszal commented on models/classes/mvc/DefaultUrlService.php
> +     *
```suggestion
```

2024-03-20 12:34 UTC, bartlomiejmarszal commented on models/classes/mvc/DefaultUrlService.php
> +        ) ?? $this->getUrl('login', $params);
Could we register this service in ServiceProvider and inject those configs there?

2024-03-20 12:34 UTC, bartlomiejmarszal commented on models/classes/mvc/DefaultUrlService.php
> +     * @return string|null
```suggestion
```

2024-03-20 12:57 UTC, andreluizmachado commented on models/classes/theme/ThemeServiceAbstract.php
> +            ->isAuthoringAsToolEnabled();
It would effectively increase the effort of this task and the estimation as well given that these are old services which are not using Symfony DI

2024-03-20 13:01 UTC, andreluizmachado commented on models/classes/AuthoringAsTool/AuthoringAsToolConfigProviderInterface.php
> +interface AuthoringAsToolConfigProviderInterface
I did not want to add extra responsibility to that service given that it contains too much already. It was also very convenient like that for unit test proposals given that it is a totally new isolated service with only this responsability.

2024-03-20 13:03 UTC, Karol-Stelmaczonek approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2024-03-20 13:03 UTC, Karol-Stelmaczonek commented on models/classes/AuthoringAsTool/AuthoringAsToolServiceProvider.php
> + * Copyright (c) 2021 (original work) Open Assessment Technologies SA;
```suggestion
 * Copyright (c) 2024 (original work) Open Assessment Technologies SA;
```

2024-03-20 13:03 UTC, Karol-Stelmaczonek commented on models/classes/AuthoringAsTool/AuthoringAsToolServiceProvider.php
> +                            'default::'
nitpic: its better to use sprintf instead of string concat

2024-03-20 13:04 UTC, andreluizmachado commented on models/classes/AuthoringAsTool/AuthoringAsToolEnvironmentVariableConfigProvider.php
> +class AuthoringAsToolEnvironmentVariableConfigProvider implements AuthoringAsToolConfigProviderInterface
Any suggestion?

2024-03-20 13:08 UTC, andreluizmachado commented on models/classes/mvc/DefaultUrlService.php
> +        ) ?? $this->getUrl('login', $params);
I really wanted to do that but:

1. because of this: https://github.com/oat-sa/tao-core/pull/3983#discussion_r1532041385
2. this would be also a breaking change given that some customers replace this implementation using the old approach (via register method, not using symfony DI). So for these customers, we might break their apps because of it.

2024-03-20 13:14 UTC, andreluizmachado commented on models/classes/AuthoringAsTool/AuthoringAsToolServiceProvider.php
> +                            'default::'
given that it is only a service configuration, I would like to keep it simpler. is it ok? I mean, concatenation seems to be sufficient.

2024-03-25 13:25 UTC, pnal approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2024-03-25 17:28 UTC, bartlomiejmarszal requested changes
Instead this extra service that you register in ServiceProvider I would suggest to:
- Create new options in ConfigurableService 
- Make a single migration in taoLti that will introduce new options in [DefaultUrlService](https://github.com/oat-sa/tao-core/pull/3983/files#diff-9c6b5e9bdbef1895a3d9fef10742ad1296058e91facc6a73951ee4b7e4b00d62) or any other service that may require configurable urls

2024-03-25 17:28 UTC, bartlomiejmarszal commented on models/classes/mvc/DefaultUrlService.php
> +        ) ?? $this->getUrl('login', $params);
We could make a migration that will introduce this configs.  you can create const with new options that you want to introduce here. This would simplify your PR.

2024-03-26 09:55 UTC, andreluizmachado commented on models/classes/mvc/DefaultUrlService.php
> +        return null;
I want to avoid Configurable Options a the new implementations are not using this approach anymore.

2024-03-26 09:55 UTC, andreluizmachado commented on actions/class.Main.php
> +            $this->setData(
I want to avoid Configurable Options a the new implementations are not using this approach anymore.

2024-03-26 10:11 UTC, bartlomiejmarszal requested changes
I have concerns about introducing AuthoringAsTool awareness into the tao-core code. Instead, I recommend maintaining a more generalized approach here, rather than explicitly adding specific tool-related details.

2024-03-26 10:11 UTC, bartlomiejmarszal commented on models/classes/AuthoringAsTool/AuthoringAsToolConfigProviderInterface.php
> +    public function isAuthoringAsToolEnabled(): bool;
is this required in this interface? We could want to change config fallback from other reason than enabling `AuthoringAsTool`

2024-03-26 10:11 UTC, bartlomiejmarszal commented on models/classes/mvc/DefaultUrlService.php
> +        return null;
https://github.com/oat-sa/tao-core/pull/3983#discussion_r1538925921

2024-03-26 10:13 UTC, bartlomiejmarszal commented on actions/class.Main.php
> +            $this->setData(
But a point of this ticket is to add dynamic url definition fallback and it make sense using with a new service

2024-03-26 10:15 UTC, bartlomiejmarszal commented on actions/class.Main.php
> +            $this->setData(
Could we execute this `setData` on a condition that `getConfigByName` return a value?

2024-03-26 10:16 UTC, bartlomiejmarszal commented on actions/class.Main.php
> +        return $this->getServiceLocator()->getContainer()->get(AuthoringAsToolConfigProviderInterface::class);
```suggestion
        return $this->getServiceLocator()->getContainer()->get(DynamiConfigProvider::class);
```

2024-03-26 10:16 UTC, bartlomiejmarszal commented on actions/class.Main.php
> -        common_session_SessionManager::endSession();
Why do we remove this `endSession`?

2024-03-26 10:18 UTC, bartlomiejmarszal commented on actions/class.Main.php
> +        );
What is this used for?

2024-03-26 10:21 UTC, bartlomiejmarszal commented on actions/class.Main.php
> +                $this->redirect($this->getDefaultPageUrl());
Do we redirect user base on `count($sections) > 0`? Why?

2024-03-26 10:23 UTC, bartlomiejmarszal commented on models/classes/AuthoringAsTool/AuthoringAsToolEnvironmentVariableConfigProvider.php
> +    }
https://github.com/oat-sa/tao-core/pull/3983/files#r1538933041

2024-03-26 11:24 UTC, bartlomiejmarszal commented on models/classes/theme/ThemeServiceAbstract.php
> +            ->isAuthoringAsToolEnabled();
I'm want to recommend to remove method `isTaoAsToolEnabled`. 
`getCurrentThemeId` should use option `OPTION_CURRENT` as it was before.
`\oat\tao\model\theme\PortalTheme` should be moved to taoLti where we introduce integration with portal.
Migration should be created to change theme to PortalTheme

2024-03-26 12:34 UTC, andreluizmachado commented on models/classes/theme/ThemeServiceAbstract.php
> +            ->isAuthoringAsToolEnabled();
This changes would break tao-styles extension

2024-03-26 12:35 UTC, andreluizmachado commented on models/classes/mvc/DefaultUrlService.php
> +        ) ?? $this->getUrl('login', $params);
I will skip this approach as I will also skip solution using getOptions

2024-03-26 12:37 UTC, andreluizmachado commented on actions/class.Main.php
> +            $this->setData(
I will not do it man. Those methods are deprecated we should not even consider to reuse it.

2024-03-26 13:06 UTC, pnal commented on models/classes/theme/ThemeServiceAbstract.php
> +            ->hasConfig(DynamicConfigProviderInterface::PORTAL_URL_CONFIG_NAME);
```suggestion
            ->hasConfig(DynamicConfigProviderInterface::PLATFORM_URL_CONFIG_NAME);
```
to make name more generic

2024-03-26 13:46 UTC, bartlomiejmarszal commented on models/classes/DynamicConfig/DynamicConfigProviderInterface.php
> +    public const PORTAL_URL_CONFIG_NAME = 'portal-url';
```suggestion
    public const EXTERNAL_LMS_URL_CONFIG_NAME = 'external-lms-url';
```

2024-03-26 13:46 UTC, bartlomiejmarszal commented on models/classes/DynamicConfig/DynamicConfigProviderInterface.php
> +    public const LOGIN_URL_CONFIG_NAME = 'login';
```suggestion
    public const LOGIN_URL_CONFIG_NAME = 'login-url';
```

2024-03-26 13:48 UTC, bartlomiejmarszal commented on models/classes/DynamicConfig/EnvironmentVariableConfigProvider.php
> +    public const ENV_PORTAL_URL = 'PORTAL_URL';
```suggestion
    public const ENV_EXTERNAL_LMS_URL = 'EXTERNAL_LMS_URL';
```

2024-03-26 13:50 UTC, bartlomiejmarszal commented on models/classes/theme/ThemeServiceAbstract.php
>      protected function isTaoAsToolEnabled(): bool
Can we get rid of this method? Why it is protected?

2024-03-26 13:51 UTC, andreluizmachado commented on models/classes/theme/ThemeServiceAbstract.php
>      protected function isTaoAsToolEnabled(): bool
This would be a breaking change on another service. I believe in tao-style extension If I remember that well

2024-03-26 13:52 UTC, bartlomiejmarszal commented on models/classes/theme/ThemeServiceAbstract.php
> +            ->isAuthoringAsToolEnabled();
How is this braking tao-styles?

2024-03-26 13:52 UTC, bartlomiejmarszal commented on models/classes/DynamicConfig/DynamicConfigProviderInterface.php
> +    public const PORTAL_URL_CONFIG_NAME = 'portal-url';
```suggestion
    public const PLATFORM_URL_CONFIG_NAME = 'platform-url';
```

2024-03-26 13:54 UTC, bartlomiejmarszal commented on models/classes/theme/ThemeServiceAbstract.php
>      protected function isTaoAsToolEnabled(): bool
https://github.com/oat-sa/extension-tao-styles/blob/2add8c4262cad517b6ddec4b62e2962c4a508b7e/model/service/PersistenceThemeService.php#L337

This should be fixed together.

2024-03-26 14:02 UTC, andreluizmachado commented on models/classes/DynamicConfig/EnvironmentVariableConfigProvider.php
> +    public const ENV_PORTAL_URL = 'PORTAL_URL';
This is a breaking change.

2024-03-26 14:05 UTC, andreluizmachado commented on models/classes/theme/ThemeServiceAbstract.php
>      protected function isTaoAsToolEnabled(): bool
No I will not do it given that this increase the scope of this task.

2024-03-26 14:06 UTC, andreluizmachado commented on models/classes/DynamicConfig/DynamicConfigProviderInterface.php
> +    public const LOGIN_URL_CONFIG_NAME = 'login';
I will skip it for now given that this is the same string defined for DefaultUrlService and I do not want to create another mapping just for it. The Const name should be ok for now

2024-03-26 14:51 UTC, bartlomiejmarszal commented on models/classes/theme/ThemeServiceAbstract.php
>      protected function isTaoAsToolEnabled(): bool
This ticket should cover all changes that was introduced with previous feature flag approach

2024-03-26 14:53 UTC, bartlomiejmarszal commented on models/classes/DynamicConfig/EnvironmentVariableConfigProvider.php
> +    public const ENV_PORTAL_URL = 'PORTAL_URL';
```suggestion
    //deprecated
    public const ENV_PORTAL_URL = 'PORTAL_URL';
    public const ENV_EXTERNAL_LMS_URL = 'EXTERNAL_LMS_URL';
```

2024-03-26 14:55 UTC, bartlomiejmarszal commented on actions/class.Main.php
> +                $this->redirect($this->getDefaultPageUrl());
But why?

2024-03-26 15:01 UTC, andreluizmachado commented on models/classes/DynamicConfig/EnvironmentVariableConfigProvider.php
> +    public const ENV_PORTAL_URL = 'PORTAL_URL';
ok. Then I would leave that for the ticket: https://oat-sa.atlassian.net/browse/AUT-3578 to avoid break all the customers on deploying that on ignite

2024-03-26 15:02 UTC, andreluizmachado commented on models/classes/theme/ThemeServiceAbstract.php
>      protected function isTaoAsToolEnabled(): bool
no, please take a look at my ticket.

2024-03-27 09:15 UTC, bartlomiejmarszal commented on actions/class.Main.php
> +                $this->redirect($this->getDefaultPageUrl());
This line does not change anything for me

2024-03-27 10:41 UTC, bartlomiejmarszal commented on actions/class.Main.php
> +        );
This is used in `tao/tao/views/templates/blocks/header-main-navi.tpl:73`

2024-03-27 10:57 UTC, bartlomiejmarszal commented on models/classes/theme/ThemeServiceAbstract.php
>      protected function isTaoAsToolEnabled(): bool
We should remove this method and make modification in `\oat\tao\model\theme\ThemeService::getCurrentThemeId` to use your dynamic config instead.

2024-03-27 12:02 UTC, bartlomiejmarszal commented on models/classes/theme/ThemeServiceAbstract.php
>      protected function isTaoAsToolEnabled(): bool
> no, please take a look at my ticket.

> Switch Perspective on Authoring based on user login flow

Using correct theme is a part of your ticket.

2024-03-27 12:08 UTC, bartlomiejmarszal commented on models/classes/DynamicConfig/DynamicConfigProviderInterface.php
> +    ];
This should be defined in implementation. Why do we want to restrict this interface only to those configs?

2024-04-04 10:51 UTC, merged

2024-05-08 15:47 UTC, wazelin commented
I might be wrong, but I believe that before this change (or maybe some other recent one), Portal return URL was defined by the `return_url` property in LTI launch presentation. e.g.
```
"https://purl.imsglobal.org/spec/lti/claim/launch_presentation": {
    "locale": "",
    "return_url": "https://qa-client-ignite-qa.staging.gcp-eu.taocloud.org/sessions"
  }
```

This is no longer the case on OAT dev. @tikhanovichA, @bartlomiejmarszal, could you please check that regression?

Steps to reproduce:
1. Log in as an admin to Portal
2. Navigate to Sessions
3. Navigate to Content Bank
4. Click "back to portal"

Expected:
The user agent is returned to the Sessions page

Experienced:
The user agent is returned to the main Portal page

2024-05-08 15:53 UTC, wazelin commented
Forget what I said. I can see now that https://development.eu.premium.lab.taocloud.org/ is old.