feat: enable disabled actions by feature flags
oat-sa/tao-core pull request #4004
Opened 2024-04-23 12:31 UTC by pnal

This PR aims to add ability to enable disabled action by feature flag.

How to test:
```php
return new oat\tao\model\action\ActionBlackList(array(
    'disabledActions' => array(
        'action-name'
    ),
    'enabledActionsByFeatureFlagMap' => array(
       'action-name' => 'FEATURE_FLAG_THAT_ENABLES_ACTION_NAME'
    )
));
```
- Add some action id in a list of `disabledActions` in  `config/tao/ActionBlackList.conf.php` as above
- Validate that action button is **not visible** in TAO3.x UI (existing functionality)
- Add a map pair into `enabledActionsByFeatureFlagMap` in the same conf file
- Set the chosen environment variable to `true`; validate that action button is **visible**
- Set the chosen environment variable to `false`; validate that action button is **not visible**

2024-04-24 09:29 UTC, bartlomiejmarszal requested changes
Why don't you just ad your action to disabled actions

2024-04-24 09:29 UTC, bartlomiejmarszal commented on models/classes/action/ActionBlackList.php
> +    public const OPTION_ENABLED_ACTIONS_BY_FEATURE_FLAG_MAP = 'enabledActionsByFeatureFlagMap';
Why do you need this?

2024-04-24 12:17 UTC, Karol-Stelmaczonek approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2024-04-26 08:44 UTC, pnal commented on models/classes/action/ActionBlackList.php
> +    public const OPTION_ENABLED_ACTIONS_BY_FEATURE_FLAG_MAP = 'enabledActionsByFeatureFlagMap';
because it should be enabled by feature flag

2024-04-26 09:49 UTC, tikhanovichA approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2024-05-14 15:08 UTC, merged