AUT-3765: make translation with new prefix
oat-sa/tao-core pull request #4035
Opened 2024-06-04 09:37 UTC by SultanSagi

### Related to: https://oat-sa.atlassian.net/browse/AUT-3675

### Summary

It makes translations with new prefix

To create and update new local files:
```sh
// from Docker container

php  tao/scripts/taoTranslate.php -v -a=create -a=taoQtiItem -l=en-us```
### How to test

- Enable Feature flag

To create and update new local files:
```sh
// from Docker container

php  tao/scripts/taoTranslate.php -v -a=create -a=taoQtiItem -l=en-us```

2024-06-12 09:27 UTC, marpesia approved these changes
LGTM

Please, check PHP checks on GH actions

2024-06-12 12:34 UTC, bartlomiejmarszal requested changes
Hey, I'm missing unit test for your new business logic. 
Your comments should explain what method does and they should not contain type hinting.

2024-06-12 12:34 UTC, bartlomiejmarszal commented on actions/class.RdfController.php
> +        $this->setData('formTitle', __('Edit class %s', \tao_helpers_Display::htmlize($getLabel)));
```suggestion
        $this->setData('formTitle', __('Edit class %s', tao_helpers_Display::htmlize($getLabel)));
```

2024-06-12 12:34 UTC, bartlomiejmarszal commented on actions/form/class.Instance.php
> +     */
```suggestion
```

2024-06-12 12:34 UTC, bartlomiejmarszal commented on actions/form/class.Instance.php
> +    private function notContainPrefix(string $language): bool
```suggestion
    private function isContainPrefix(string $language): bool
```

2024-06-12 12:34 UTC, bartlomiejmarszal commented on actions/form/class.Instance.php
> +     */
```suggestion
```

2024-06-12 12:34 UTC, bartlomiejmarszal commented on actions/form/class.Instance.php
> +     */
```suggestion
```

2024-06-12 12:34 UTC, bartlomiejmarszal commented on actions/form/class.Instance.php
> +     */
WHat this method is suppose to be doing?

2024-06-12 12:34 UTC, bartlomiejmarszal commented on helpers/LayoutHelper.php
> +        return Layout::isSolarDesignEnabled();
This is some kind o proxy? I could not find this reference

2024-06-12 12:34 UTC, bartlomiejmarszal commented on helpers/LayoutHelper.php
> +    public function isSolarDesignEnabled(): bool
What is Solar doing here?

2024-06-12 12:34 UTC, bartlomiejmarszal commented on helpers/class.Display.php
> +    public static function mapClassesNames(string $className): string
What you are mapping here?

2024-06-12 12:34 UTC, bartlomiejmarszal commented on helpers/class.Display.php
> +            ];
This should be in const

2024-06-12 12:34 UTC, bartlomiejmarszal commented on helpers/class.I18n.php
> +     */
Please make more meaningful comments. Please do not provide type hinting

2024-06-12 12:35 UTC, bartlomiejmarszal requested changes
Why had you include those locales?

2024-06-12 12:48 UTC, marpesia commented on helpers/LayoutHelper.php
> +    public function isSolarDesignEnabled(): bool
This is part of the RFE to enable the new Solar theme. Related to https://github.com/oat-sa/tao-core/pull/4029

2024-06-12 12:52 UTC, marpesia commented
> Why had you include those locales?

This PR mixed some FE and BE changes.
We added a new language to add the new terminology, which can be applied only when the solar theme is enabled.
The language should be standard, like `en-US`, but we need to be distinct from the regular Theme, so we create a new language, copied from the regular one and with a different folder name to manage the language to load.

2024-06-12 12:56 UTC, marpesia commented on helpers/class.Display.php
> +    public static function mapClassesNames(string $className): string
We use this helper to add the translation function and change the key if needed. As you can see, `Media` and `Assets` have the same translation key.

2024-06-12 13:02 UTC, bartlomiejmarszal commented on helpers/class.Display.php
> +    public static function mapClassesNames(string $className): string
I'm still not sure what is purpose of this action. Why is it static?

2024-06-12 13:05 UTC, marpesia commented on helpers/class.Display.php
> +    public static function mapClassesNames(string $className): string
you can see together on this commit https://github.com/oat-sa/tao-core/pull/4035/commits/a04e9b12c2dff536c31b99caa023b59005b89d9d

2024-06-12 13:34 UTC, bartlomiejmarszal requested changes
I'm still confused about mapClassesNames method

2024-06-12 13:34 UTC, bartlomiejmarszal commented on models/classes/clientConfig/ClientConfigServiceProvider.php
> +                    service(LayoutHelper::class),
Is this working?

2024-06-12 13:34 UTC, bartlomiejmarszal commented on helpers/class.Display.php
> +    public static function mapClassesNames(string $className): string
Why it is in Display Helper not in independent service? Why this array is static?

2024-06-13 05:27 UTC, SultanSagi commented on helpers/LayoutHelper.php
> +        return Layout::isSolarDesignEnabled();
It was problematic to test a static method. So I wrapped it in the `LayoutHelper` class

2024-06-13 07:30 UTC, bartlomiejmarszal commented on helpers/LayoutHelper.php
> +        return Layout::isSolarDesignEnabled();
And it was less problematic when wrapped? Where have you test it?

2024-06-13 07:35 UTC, bartlomiejmarszal commented on models/classes/class.LanguageService.php
> +                    }
This may impact existing functionality. I recommend to extract this business logic into different service and unit service. I also recommend when replacing business logic here to use proxy approach maybe including Feature Flag to keep it safe

2024-06-13 07:36 UTC, bartlomiejmarszal commented on models/classes/clientConfig/ClientConfigStorage.php
> +        return $language;
Please extract this to exteranal service and unit test it.

2024-06-13 07:36 UTC, bartlomiejmarszal commented on scripts/class.TaoTranslate.php
> +            "Deleting language '" . $languageDir . "' for extension '"
Please use `sprintf` insetad

2024-06-13 07:37 UTC, bartlomiejmarszal commented on scripts/class.TaoTranslate.php
> +        if (!$this->isContainPrefix($language)) {
This is duplicated from `models/classes/clientConfig/ClientConfigStorage.php`?

2024-06-13 07:45 UTC, SultanSagi commented on helpers/LayoutHelper.php
> +        return Layout::isSolarDesignEnabled();
Yes, I didn't add new test, but it triggers here `ClientConfigStorageTest.php`

2024-06-13 08:12 UTC, marpesia commented
> I'm still confused about mapClassesNames method

Please, re-check again @bartlomiejmarszal

2024-06-13 08:18 UTC, SultanSagi commented on models/classes/class.LanguageService.php
> +                    }
to clarify what do you mean with Business logic? Only my added if condition or whole logic inside `foreach`?

2024-06-17 07:37 UTC, bartlomiejmarszal requested changes
Missing empty lines on the end of php files

2024-06-17 07:37 UTC, bartlomiejmarszal commented on helpers/translation/SolarThemeHelper.php
> +}
```suggestion
}

```

2024-06-17 07:44 UTC, bartlomiejmarszal commented on models/classes/class.LanguageService.php
> +                    }
Not sure I understand this answer. You are adding new business logic into existing service. This will impact other parts of the code that is using `models/classes/class.LanguageService.php`. You should make sure it will not brake anything and for this you need to isolate impact of your change. I would recommend to create new Sprout class with method `getLanguageFiles` overloaded.

2024-06-17 14:11 UTC, SultanSagi commented on models/classes/clientConfig/ClientConfigServiceProvider.php
> +                    service(LayoutHelper::class),
fixed

2024-06-18 06:49 UTC, bartlomiejmarszal commented on helpers/LayoutHelper.php
> +        return Layout::isSolarDesignEnabled();
as a Mock?

2024-06-21 09:52 UTC, SultanSagi commented on helpers/LayoutHelper.php
> +        return Layout::isSolarDesignEnabled();
Yes

2024-06-21 09:53 UTC, SultanSagi commented on models/classes/clientConfig/ClientConfigStorage.php
> +        return $language;
fixed

2024-06-21 09:53 UTC, SultanSagi commented on scripts/class.TaoTranslate.php
> +        if (!$this->isContainPrefix($language)) {
fixed

2024-06-21 10:22 UTC, pribi commented
Please resolve the merge conflicts.
![image](https://github.com/oat-sa/tao-core/assets/8711268/cd8288b4-a722-41fa-93f8-40d8bfebfb5f)

2024-06-21 10:40 UTC, marpesia commented
> Please resolve the merge conflicts. ![image](https://private-user-images.githubusercontent.com/8711268/341731544-cd8288b4-a722-41fa-93f8-40d8bfebfb5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjU3MDQsIm5iZiI6MTcxODk2NTQwNCwicGF0aCI6Ii84NzExMjY4LzM0MTczMTU0NC1jZDgyODhiNC1hNzIyLTQxZmEtOTNmOC00MGQ4YmZlYmZiNWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjFUMTAyMzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI0NzliNmFhZTE3MzRjOWYwOWU5NTVlY2E4NGMzZWNmYzQ0MjhlYzJkZmIzMjhhMzcyMWE2MzU2MTUwMjEwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5Dk9CQWvzeXMzDOtw0tMaLSQz335A2u9ircT75j3A-s)

Fixed @pribi

2024-06-21 11:02 UTC, bartlomiejmarszal commented on helpers/LayoutHelper.php
> +        return Layout::isSolarDesignEnabled();
How could you test a class by mocking it only?

2024-06-21 11:02 UTC, bartlomiejmarszal commented on helpers/translation/AbstractSolarThemeHelper.php
> +}
Empty line on the end of line

2024-06-21 11:05 UTC, marpesia commented on helpers/translation/AbstractSolarThemeHelper.php
> +}
fixed @bartlomiejmarszal

2024-06-21 11:06 UTC, bartlomiejmarszal commented on scripts/taoTranslate.php
This file change is not well readable. This is just reformatting? Could you skip reformatting for this?

2024-06-21 11:10 UTC, marpesia commented on scripts/taoTranslate.php
There are new code added at the bottom of the array, though. 
I can move the first square bracket to the line 29. Is that ok?

2024-06-21 11:11 UTC, bartlomiejmarszal commented on helpers/mapLabelNameService.php
> +        $mapName = $labelName;
What is the point of changing variable name?

2024-06-21 11:14 UTC, marpesia commented on helpers/mapLabelNameService.php
> +        $mapName = $labelName;
If you look closely, the Media and the Asset have the same name for the translation. This is the problem; we have changed the UI since this was done.

2024-06-21 11:18 UTC, bartlomiejmarszal commented on helpers/translation/AbstractSolarThemeHelper.php
> +    protected function addPrefix(string $language): string
You actually adding postfix

2024-06-21 11:21 UTC, bartlomiejmarszal commented on actions/class.RdfController.php
> +        $getLabel = MapLabelNameService::mapLabelName($class->getLabel());
Why don't you call it as you would call service?

2024-06-21 11:22 UTC, bartlomiejmarszal commented on helpers/translation/AbstractSolarThemeHelper.php
> +    }
```suggestion
    public function __construct(LayoutHelper $layoutHelper) {
        $this->layoutHelper = $layoutHelper;
    }
```

2024-06-21 11:23 UTC, bartlomiejmarszal commented on helpers/mapLabelNameService.php
> + class MapLabelNameService
I'm still not understand purpose of this class

2024-06-21 11:26 UTC, marpesia commented on helpers/mapLabelNameService.php
> + class MapLabelNameService
Several places in the UI take the Label name from the PHP code. To set the correct Label for the translation, I need to map the PHP names with the translation IDs.

2024-06-21 11:39 UTC, bartlomiejmarszal commented on scripts/class.TaoTranslate.php
> +    private ?AbstractSolarThemeHelper $solarThemeHelper;
How this could be null? It is defined in ServiceProvider.

2024-06-21 12:53 UTC, bartlomiejmarszal commented on helpers/mapLabelNameService.php
> + class MapLabelNameService
Could you point me the UI that will be impacted by your change?

2024-06-21 12:58 UTC, bartlomiejmarszal commented on helpers/mapLabelNameService.php
> + class MapLabelNameService
I was reviewing this with @pribi and I think I understand purpose of this. 
Looking into usage of `actions/class.RdfController.php` you will make a change translation for Items. 
![Screenshot 2024-06-21 at 14 56 00](https://github.com/oat-sa/tao-core/assets/16231681/c0020210-5963-4d35-9151-93fb02f04b60)
I understand that Items now should be renamed? WIll we rename root class Item? Do we want to apply this change everywhere? To each client and each instance?

2024-06-21 13:00 UTC, bartlomiejmarszal commented on helpers/class.I18n.php
> +        if (!self::isContainPrefix($language)) {
Should this be under feature flag?

2024-06-21 13:23 UTC, marpesia commented on helpers/mapLabelNameService.php
> + class MapLabelNameService
The problem is that the new name is ONLY when the SolarUI Theme is applied.
Shall we continue these comments on the new PRs?
Locales only -> https://github.com/oat-sa/tao-core/pull/4052
BE logic -> https://github.com/oat-sa/tao-core/pull/4053
BE to change FE -> https://github.com/oat-sa/tao-core/pull/4054
CSS FE fix -> https://github.com/oat-sa/tao-core/pull/4055

2024-06-21 14:31 UTC, closed without merging

2024-06-21 15:50 UTC, SultanSagi commented on helpers/class.I18n.php
> +    private static function checkPrefix(string $language): string
Because this class itself initiates statically. It's not using construct method

2024-06-21 15:52 UTC, SultanSagi commented on helpers/class.I18n.php
> +        if (!self::isContainPrefix($language)) {
Feature flag is called inside `isContainPrefix`

2024-06-21 17:12 UTC, SultanSagi commented on scripts/class.TaoTranslate.php
> +    private ?AbstractSolarThemeHelper $solarThemeHelper;
fixed

2024-06-23 19:06 UTC, SultanSagi commented on helpers/translation/AbstractSolarThemeHelper.php
> +    protected function addPrefix(string $language): string
fixed

2024-06-23 19:06 UTC, SultanSagi commented on helpers/translation/AbstractSolarThemeHelper.php
> +    }
fixed

2024-06-23 19:09 UTC, SultanSagi commented on helpers/class.I18n.php
> +     * Check and Add prefix for Solar design translations
In the ticket there is a condition to check for a new translation, if there is no new translation then use a normal translation. That's why I check via `is_dir`. If the comment doesn't fit, is there any suggestion on how to change it?