fix: User cannot move resource to class wherte resource is
oat-sa/tao-core pull request #4049
Opened 2024-06-17 13:06 UTC by bartlomiejmarszal

User cannot move resource to this same class. 

1. Select resource and click `Move To`
2. Select Class where item is located
3. Observe error message `Unable to move the resources`

https://github.com/oat-sa/tao-core/assets/16231681/0b8cebf8-081f-411f-972e-cd8a18e22410

2024-06-17 14:51 UTC, pnal commented on actions/class.RdfController.php
> +                $this->validateDestinationClass($destinationClassUri, $this->getResourceParentClass($id));
the methods called below throws some InvalidArgumentException but not catched here
```
$this->validateUri($id);
$this->validateInstanceRoot($id);
$this->validateMoveRequest();
```
Furthermore some of them validates params that you used above
for example:
```
protected function validateMoveRequest()
    {
        if (!$this->isRequestPost()) {
            throw new common_exception_MethodNotAllowed('Only POST method is allowed to move instances.');
        }

        if (!$this->hasRequestParameter('destinationClassUri')) {
            throw new InvalidArgumentException('Destination class must be specified');
        }

        $destinationClass = new core_kernel_classes_Class($this->getRequestParameter('destinationClassUri'));
        if (!$destinationClass->isClass()) {
            throw new InvalidArgumentException('Destination class must be a valid class');
        }
```

2024-06-18 13:22 UTC, bartlomiejmarszal commented on actions/class.RdfController.php
> +                $this->validateDestinationClass($destinationClassUri, $this->getResourceParentClass($id));
But I catch this exception at most granular way.

2024-06-19 11:30 UTC, Karol-Stelmaczonek commented on actions/class.RestResource.php
> +                        $this->getExcludedClasses()
Can we mimic logic which is used for other parameters? In L:134 for example? Handle $this->hasGetParameter('exclude') outside you new function, and here just pass variable with return value from ` getExcludedClasses()` ?

2024-06-19 11:30 UTC, Karol-Stelmaczonek commented on actions/class.RestResource.php
> +            if (!$selectedResourceToExclude->exists()) {
```suggestion
            if ($selectedResourceToExclude && !$selectedResourceToExclude->exists()) {
```

2024-06-19 11:30 UTC, Karol-Stelmaczonek commented on actions/class.RestResource.php
> +            if (!$resourceParentClass->isClass()) {
```suggestion
            if ($resourceParentClass && !$resourceParentClass->isClass()) {
```

2024-06-19 11:30 UTC, Karol-Stelmaczonek commented on models/classes/GenerisTreeFactory.php
> +            if (!in_array($child['attributes']['data-uri'], $this->excludedClasses)) {
```suggestion
            if (isset($child['attributes']['data-uri']) && !in_array($child['attributes']['data-uri'], $this->excludedClasses)) {
```

2024-06-19 11:30 UTC, Karol-Stelmaczonek commented on actions/class.RdfController.php
> +        if (!$type->isClass()) {
```suggestion
        if ($type && !$type->isClass()) {
```

2024-06-25 07:32 UTC, Karol-Stelmaczonek commented on actions/class.RestResource.php
> +                $excludedClasses = $this->getExcludedClasses();
```suggestion
                $excludedClasses = $this->hasGetParameter('exclude') ? $this->getExcludedClasses() : '';
```
And then remove if with `$this->hasGetParameter('exclude')` from `getExcludedClasses()`

2024-06-26 14:01 UTC, bartlomiejmarszal commented on actions/class.RestResource.php
> +                $excludedClasses = $this->getExcludedClasses();
I'm not sure if this is more clean version.

2024-06-26 15:04 UTC, tikhanovichA commented
The current implementation blocks moving ticket to child classes from the current class. For example if my resource now in class_1 then I will not able to move it into class_1_1.
Because of that, let's just show the error message for now
![image](https://github.com/oat-sa/tao-core/assets/1053022/c673ee84-8e2b-4905-a067-f2e8176550a5)

2024-06-26 15:40 UTC, pnal requested changes
It seems that fully BE solution will not work here

2024-06-27 09:01 UTC, tikhanovichA approved these changes
I think that we are ok with that BE solution with the error message
<img width="1113" alt="image" src="https://github.com/oat-sa/tao-core/assets/1053022/a4ceef68-578e-4e74-88cc-2bc433cd7e1d">

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code respects code style rules
- [x] New code respects best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

2024-06-27 09:42 UTC, pnal approved these changes

2024-07-04 07:34 UTC, merged