Feat/aut 3675/add support to solar UI locales
oat-sa/tao-core pull request #4053
Opened 2024-06-21 12:24 UTC by marpesia

### Related to: https://oat-sa.atlassian.net/browse/AUT-3675

### Summary

It makes translations with new prefix

To create and update new local files:
```sh
// from Docker container

php  tao/scripts/taoTranslate.php -v -a=create -e=taoQtiItem -l=en-us```

2024-06-22 16:55 UTC, pribi requested changes

2024-06-22 16:55 UTC, pribi commented on helpers/ServiceProvider/HelperServiceProvider.php
> +                    service(LayoutHelper::class)
```suggestion
                    LayoutHelper::class
```

2024-06-22 18:17 UTC, pribi requested changes

2024-06-22 18:17 UTC, pribi commented on helpers/ServiceProvider/HelperServiceProvider.php
```suggestion
use function Symfony\Component\DependencyInjection\Loader\Configurator\service;
```

2024-07-10 21:18 UTC, pribi approved these changes
LGTM.

Tested by installing tao-community, success.
```
composer require -W "oat-sa/tao-core":"dev-feat/AUT-3675/add-support-to-SolarUI-locales as 54.10.4.3"
```
![image](https://github.com/oat-sa/tao-core/assets/8711268/0d13f592-5989-4a69-8fb8-681c107fdc9d)

![image](https://github.com/oat-sa/tao-core/assets/8711268/3b1c77b9-7390-42c8-a6df-3ba174a3a58f)

2024-07-11 08:11 UTC, bartlomiejmarszal requested changes
Great. I have few more comments to your recent changes. 
I'm still testing it on my local machine. 

Please provide in PR description a way how to test this PR

2024-07-11 08:11 UTC, bartlomiejmarszal commented on scripts/class.TaoTranslate.php
> +            : $this->options['language'];
This looks weird for me. Why can't we instantiate solarThemeHelper one way or another and assign language always from `checkPostfix` method?

2024-07-11 08:11 UTC, bartlomiejmarszal commented on scripts/class.TaoTranslate.php
> +            : $this->options['language'];
This looks weird for me. Why can't we instantiate solarThemeHelper one way or another and assign language always from checkPostfix method?

Especialy that you repeat this logic

2024-07-11 08:11 UTC, bartlomiejmarszal commented on scripts/class.TaoTranslate.php
> +            : $this->options['language'];
3x times is a charm:

At this point I recommend to instantiate solarThemeHelper one way or another and assign language always from `checkPostfix` method?

2024-07-11 08:31 UTC, bartlomiejmarszal commented on scripts/class.TaoTranslate.php
> +    public const LANG_PREFIX = '-S';
Where do you use it?

2024-07-11 08:36 UTC, bartlomiejmarszal commented on helpers/translation/AbstractSolarThemeHelper.php
> +        $this->layoutHelper = $layoutHelper;
Why don't you just use static method instead? This is unnecessary complication.

2024-07-11 08:37 UTC, bartlomiejmarszal commented on helpers/LayoutHelper.php
> +}
Why don't you just use static method instead? This is unnecessary complication.

2024-07-11 08:37 UTC, bartlomiejmarszal commented on scripts/taoTranslate.php
> +    new SolarThemeHelper(new LayoutHelper())
Why don't you just use static method instead? This is unnecessary complication.
```suggestion
    new SolarThemeHelper()
```

2024-07-11 08:45 UTC, Karol-Stelmaczonek requested changes

2024-07-11 08:45 UTC, Karol-Stelmaczonek commented on actions/form/class.Instance.php
> +        $pattern = '/' . self::LANG_POSTFIX . '$/';
Can we use `sprintf` here? 
```suggestion
       $pattern = sprintf('/%s$/', self::LANG_POSTFIX);
```

2024-07-11 08:45 UTC, Karol-Stelmaczonek commented on actions/form/class.Instance.php
> +        return !Layout::isSolarDesignEnabled() || preg_match($pattern, $language, $matches);
```suggestion
        return !Layout::isSolarDesignEnabled() || preg_match($pattern, $language);
```
We don't need $matches as we don't use it

2024-07-11 08:45 UTC, Karol-Stelmaczonek commented on actions/form/class.Instance.php
> +        return $language;
We can simplify it a little, wdyt?
```suggestion
        if ($this->isContainPostfix($language)) {
            return $language;
        }
        $localesDir = 'views/locales';
        $dir = sprintf('%s/../../%s/%s', dirname(__FILE__), $localesDir, $this->addPostfix($language));
        if (is_dir($dir)) {
                return $this->addPostfix($language);
        }
        return $language;
```

2024-07-11 08:45 UTC, Karol-Stelmaczonek commented on actions/form/class.Instance.php
> +        return !Layout::isSolarDesignEnabled() || preg_match($pattern, $language, $matches);
Also I think that `preg_match($pattern, $language)` return integers/bool not bool only and it can fail as you function has bool return type only. Probably we need to change it to `preg_match($pattern, $language) === 1`

2024-07-11 08:45 UTC, Karol-Stelmaczonek commented on helpers/LocaleFilesHelper.php
> +        return null !== $pattern && preg_match($pattern, $localeDir, $matches);
Here also we can skip `$matches` and check `preg_match($pattern, $localeDir, $matches) === 1;`

2024-07-11 08:45 UTC, Karol-Stelmaczonek commented on helpers/class.I18n.php
> +    private static function isContainPostfix(string $language): bool
Ok I don't like this code duplication, can we extract those functions? I think we can. I'm talking about this one and ` addPostfix()` , `checkPostfix()` here and in `actions/form/class.Instance.php`. If its impossible please at least fix same problems I mentioned earlier

2024-07-11 11:09 UTC, SultanSagi commented on helpers/LayoutHelper.php
> +}
The reason I'm calling these methods is that PHPunit fails to check in the static method: `Layout::isSolarDesignEnabled()`

2024-07-11 14:57 UTC, pnal commented on test/unit/helpers/SolarThemeHelperTest.php
> +        $this->assertTrue($solarThemeHelper->isContainPostfix('de-DE'));
what is a point of asserting that mocked method returns mocked value?

2024-07-11 14:57 UTC, pnal commented on test/unit/helpers/SolarThemeHelperTest.php
> +<?php
missing copyright

2024-07-11 14:57 UTC, pnal commented on test/unit/helpers/SolarThemeHelperTest.php
> +        $this->assertEquals($locale, $solarThemeHelper->checkPostfix($locale));
same question

2024-07-11 14:57 UTC, pnal commented on test/unit/helpers/LocaleFilesHelperTest.php
> +<?php
missing copyright

2024-07-12 05:48 UTC, SultanSagi commented on scripts/taoTranslate.php
> +    new SolarThemeHelper(new LayoutHelper())
fixed

2024-07-12 11:46 UTC, bartlomiejmarszal requested changes
I'm just having issue with empty abstract class. Maybe you could change it into interface instead?

2024-07-12 11:46 UTC, bartlomiejmarszal commented on helpers/translation/AbstractSolarThemeHelper.php
> +abstract class AbstractSolarThemeHelper
Abstract class without some implementation is useless. You may want to create interface instead

2024-07-12 12:05 UTC, bartlomiejmarszal approved these changes

2024-07-12 12:30 UTC, Karol-Stelmaczonek commented on models/classes/class.LanguageService.php
> +    }
```suggestion
    private function isDirectory(string $path, array $localeDir): bool
{
    if (!isset($localeDir[0])) {
        return false;
    }

    if ($localeDir[0] == '.') {
        return false;
    }

    if (!is_dir($path)) {
        return false;
    }

    return true;
}
```

2024-07-12 12:35 UTC, Karol-Stelmaczonek approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2024-07-16 12:58 UTC, pribi approved these changes

2024-08-02 06:25 UTC, merged