Feature/aut 3624/add translation to fe labels
oat-sa/tao-core pull request #4054
Opened 2024-06-21 12:33 UTC by marpesia

**Related to:** AUT-[3624](https://oat-sa.atlassian.net/browse/AUT-3624)

**Description:**
Add new terms on a new locale language on the new SolarUi theme enabled

**Changes:**

- Check Google Sheet with new terms

**How to check:**

- Enable FeatureFlag https://oat-sa.atlassian.net/wiki/spaces/OAT/pages/2406350936/RFE-1147+Implementation+documentation
- Run Translation scripts on Docker php container
````
php  tao/scripts/taoTranslate.php -v -a=compile -a=tao -l=en-US-S
````

2024-06-21 13:10 UTC, pribi requested changes

2024-06-21 13:10 UTC, pribi commented on helpers/mapLabelNameService.php
> +    }
We can add the is solar design enabled as a parameter, so there is no need to have the hidden dependency Layout::isSolarDesignEnabled() it can be injected from outside => easier to test, easier to mock in tests.

```suggestion
    public static function mapLabelName(string $labelName, bool $isSolarDesignEnabled): string
    {
        if ($isSolarDesignEnabled && array_key_exists($labelName, self::$mapLabelNames)) {
            return self::$mapLabelNames[$labelName];
        }

        return $labelName;
    }
```

2024-06-21 13:10 UTC, pribi commented on actions/class.RdfController.php
> +        $getLabel = MapLabelNameService::mapLabelName($class->getLabel());
```suggestion
        $getLabel = MapLabelNameService::mapLabelName($class->getLabel(), Layout::isSolarDesignEnabled());

```

2024-06-21 13:10 UTC, pribi commented on helpers/mapLabelNameService.php
> +<?php
Please rename the file to MapLabelNameService.php. The current name starts with lowercase m.

2024-06-21 13:10 UTC, pribi commented on views/templates/blocks/sections.tpl
> +                                    $className = MapLabelNameService::mapLabelName($tree->get('className'));
```suggestion
                                    $className = MapLabelNameService::mapLabelName($tree->get('className'), Layout::isSolarDesignEnabled());
```

2024-06-21 13:10 UTC, pribi commented on views/templates/blocks/sections.tpl
> +use oat\tao\helpers\MapLabelNameService;
```suggestion
use oat\tao\helpers\MapLabelNameService;
use oat\tao\helpers\Layout;
```

2024-06-21 13:15 UTC, bartlomiejmarszal commented on helpers/mapLabelNameService.php
> +}
```suggestion
}

```

2024-06-21 13:16 UTC, bartlomiejmarszal commented on helpers/class.Display.php
> +
```suggestion
```

2024-06-21 13:36 UTC, marpesia commented on actions/class.RdfController.php
> +        $getLabel = MapLabelNameService::mapLabelName($class->getLabel());
Should I add `use oat\tao\helpers\Layout;` here as well?

2024-06-26 06:34 UTC, jsconan approved these changes
Quick code review only.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code respects code style rules
- [ ] New code respects best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

2024-07-16 13:51 UTC, merged