feat: advanced search support
oat-sa/tao-core pull request #4117
Opened 2024-10-10 11:15 UTC by shpran

# [ADF-1794](https://oat-sa.atlassian.net/browse/ADF-1794)

## Changes
* Added new property to set translated languages
* Added event + listener to cover all translated resources
* 3 translation actions modified to trigger this new event:
  * Create translation
  * Delete translation
  * Sync translations

2024-10-11 15:56 UTC, gabrielfs7 commented on models/classes/Translation/Form/Modifier/TranslationFormModifier.php
> +            TaoOntology::PROPERTY_TRANSLATION_TYPE,
- [ ] We probably need to fix the tests

2024-10-11 15:58 UTC, gabrielfs7 commented on models/classes/Translation/Listener/ResourceTranslationChangedEventListener.php
> +class ResourceTranslationChangedEventListener
- [ ] Lets add the tests before merge, please. Thanks!

2024-10-11 15:58 UTC, gabrielfs7 commented on migrations/Version202410100711422234_tao.php
> +        $eventManager->attach(
- [ ] We also need to setup the event in fresh install

2024-10-11 16:00 UTC, gabrielfs7 commented on models/classes/Translation/Event/ResourceTranslationChangedEvent.php
> +class ResourceTranslationChangedEvent implements Event
- [ ] Unit test missing, please

2024-11-13 11:13 UTC, gabrielfs7 commented on models/classes/Translation/Listener/TranslationActionEventListener.php
> +    public function populateTranslatedIntoLanguagesProperty(TranslationActionEvent $event): void
**Brainstorm**. Maybe we can listen to all `ItemCreated/Updated/Deleted` and `Resource/Updated/Created/Deleted` here and use existing events for that. 🤔

2024-11-13 11:17 UTC, gabrielfs7 requested changes
Thanks @shpran, amazing work! 

It is working as expected and we have some minor things to address and I can approve the PR: 

Issues related to adv search.

- [x] We need to make uniqueId available as criteria
- [x] Translation Type must not be displayed as criteria
- [x] Translation Progress must not be displayed as criteria
- [x] Original resource must not be displayed as criteria

2024-11-15 07:05 UTC, shpran commented on views/package.json
> +        "@oat-sa/tao-core-ui": "github:oat-sa/tao-core-ui-fe#feat/ADF-1811/group-conditions-logic",
- [ ] Change to release tag before merge

2024-11-15 08:43 UTC, gabrielfs7 commented on models/ontology/tao.rdf
> +  <rdf:Description rdf:about="http://www.tao.lu/Ontologies/TAO.rdf#TranslatedIntoLanguages">
@shpran Can you please confirm that translation properties do not appear as filter in case the `FEATURE_FLAG_TRANSLATION_ENABLED` is disabled?

2024-11-15 08:48 UTC, gabrielfs7 approved these changes
Thanks for this, @shpran. Looks great! 

- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

## TODO 

There is a small thing missing, but I am pre-approving as it is an improvement

- [ ] Do not show translation filters or columns if the translation feature flag is not enabled
- [ ] Do not show UniqueId filter o column if the feature flag is not enabled

2024-11-22 11:49 UTC, shpran commented on models/ontology/tao.rdf
> +  <rdf:Description rdf:about="http://www.tao.lu/Ontologies/TAO.rdf#TranslatedIntoLanguages">
Yes

2024-11-22 11:54 UTC, merged